### ISSUE TITLE
Encoding issue with lambda symbol in files created with DrRacket

### ISSUE THREAD

**Issue by jarcane** [greghendershott/racket-mode#108]
I've run into a bit of an issue with the encoding when opening up old files from DrRacket in racket-mode/emacs. The lambda symbol winds up being gibberish, for some reason.

You can actually see it in this gist here: https://gist.github.com/jarcane/930466b881c100dea60a

That's the text pasted from a DrR window, from an Emacs window, and the file uploaded directly at the bottom. As you can see, where the lambda symbol is there, there's gibberish instead, and the odd thing is that the gibberish still evaluates correctly in the REPL.

I'm not sure if this is an issue with racket-mode, with Emacs (24.4), or with the font I'm using (Envy Code R), but it does rather mangle some of the old source files where I've used it.

**Comment by greghendershott** [comment]
Thanks for the report!

I think it's about encoding not fonts. But a few questions:

(a) How was the lambda character in original-fact.rkt created in the first place? Using DrRacket's _Insert Lambda_ command? Or some other way?

When I use DrRacket 6.1.1.6 and its the _Insert Lambda_ command to create the following tiny file:

```
#lang racket
λ
```

And I open that in Emacs racket-mode, I get the `λ` displaying correctly.  How about you? (I realize you created the problem files with an older DrR; I'm just curious how a newer version works on your system.)

(b) When you open the file in Emacs racket-mode, what is the leftmost character in the mode line for that buffer?  Do you see a `U`, or something else?

(c) FWIW here on GitHub when I [click the Raw button for original-fact.rkt](https://gist.githubusercontent.com/jarcane/930466b881c100dea60a/raw/b171a5a6399bfeadbd0fad1071957d6c776ebd0e/original-fact.rkt), it shows `Î»` not `λ`.

**Comment by jarcane** [comment]
Hmm, I went and tried the same test as you did. I opened a blank file in DrRacket on Windows, did Insert Lambda, and then saved the result. 

When I open the file in Emacs, I do indeed get the `Î»` result. The mode line is `l(Unix)`, and mousing over indicates that it's reading the file as iso-latin-1-unix encoding.

My guess then, is my Emacs is not opening or detecting Racket files properly as utf8?

**Comment by greghendershott** [comment]
OK. So try <kbd>M-x describe-coding-system</kbd> and hit <kbd>RET</kbd>.  I have:

```
Priority order for recognizing coding systems when reading files:
  1. utf-8 (alias: mule-utf-8)
  2. iso-2022-7bit 
  3. iso-latin-1 (alias: iso-8859-1 latin-1)
  4. iso-2022-7bit-lock (alias: iso-2022-int-1)
  5. iso-2022-8bit-ss2 
  6. emacs-mule 
  7. raw-text 
  8. iso-2022-jp (alias: junet)
  9. in-is13194-devanagari (alias: devanagari)
  10. chinese-iso-8bit (alias: cn-gb-2312 euc-china euc-cn cn-gb gb2312)
  11. utf-8-auto 
  12. utf-8-with-signature 
  13. utf-16 
  14. utf-16be-with-signature (alias: utf-16-be)
  15. utf-16le-with-signature (alias: utf-16-le)
  16. utf-16be 
  17. utf-16le 
  18. japanese-shift-jis (alias: shift_jis sjis)
  19. chinese-big5 (alias: big5 cn-big5 cp950)
  20. undecided 
```
I'm guessing `utf-8` is not at the top of the list for you?

I don't recall doing anything to change that. Don't see anything in my Emacs init file in that regard.

You could change that with <kbd>M-x prefer-coding-system</kbd> and type <kbd>utf-8</kbd>. I'm not sure if that would be undesirable for you. Instead:

I also notice there is an association list of file extensions to coding systems. Perhaps I should be adding `.rkt` (and so on) to that list with `utf-8` as the value. I'll do some research on that.

Meanwhile, you could try that:

```
     (modify-coding-system-alist 'file "\\.rkt\\'" 'utf-8)
```

**Comment by jarcane** [comment]
You are correct. My priority list looks like:

```
Coding system for saving this buffer:
  Not set locally, use the default.
Default coding system (for new files):
  1 -- iso-latin-1-dos (alias: iso-8859-1-dos latin-1-dos)

Coding system for keyboard input:
  1 -- iso-latin-1-unix (alias: iso-8859-1-unix latin-1-unix)

Coding system for terminal output:
  * -- cp1252 (alias of windows-1252)

Coding system for inter-client cut and paste:
  U -- utf-16le-dos

Defaults for subprocess I/O:
  decoding: - -- undecided-dos (alias: dos)

  encoding: - -- undecided-unix (alias: unix)


Priority order for recognizing coding systems when reading files:
  1. iso-latin-1 (alias: iso-8859-1 latin-1)
  2. utf-8 (alias: mule-utf-8)
  3. iso-2022-7bit 
  4. iso-2022-7bit-lock (alias: iso-2022-int-1)
  5. iso-2022-8bit-ss2 
  6. emacs-mule 
  7. raw-text 
  8. iso-2022-jp (alias: junet)
  9. in-is13194-devanagari (alias: devanagari)
  10. chinese-iso-8bit (alias: cn-gb-2312 euc-china euc-cn cn-gb gb2312)
  11. utf-8-auto 
  12. utf-8-with-signature 
  13. utf-16 
  14. utf-16be-with-signature (alias: utf-16-be)
  15. utf-16le-with-signature (alias: utf-16-le)
  16. utf-16be 
  17. utf-16le 
  18. japanese-shift-jis (alias: shift_jis sjis)
  19. chinese-big5 (alias: big5 cn-big5 cp950)
  20. undecided 
```

Setting `prefer-coding-system` to `utf-8` fixes the problem: I get normal lambda symbols on the original fact.rkt once more. 

It might be a good idea though to add some hinting to racket-mode to expect utf-8 if that's possible, since I think that's the standard anyhow.

**Comment by greghendershott** [comment]
> It might be a good idea though to add some hinting to racket-mode to expect utf-8 if that's possible, since I think that's the standard anyhow.

I agree. And I see there's a precedent for Emacs Elisp files doing this. I just pushed a commit for this.
