### ISSUE TITLE
paren-face mode does not work

### ISSUE THREAD

**Issue by gour** [greghendershott/racket-mode#120]
Hello,

I'm doing my 1st steps with Racket and according to docs installed few modes along with racket-mode. I've added racket-mode to *paren-face-modes*:

   ` ("racket-mode" lisp-mode emacs-lisp-mode lisp-interaction-mode ielm-mode scheme-mode inferior-scheme-mode clojure-mode cider-repl-mode nrepl-mode arc-mode inferior-arc-mode)`

but it does not work with some snippet of Racket mode which I tried, although it works with my Elisp configuration files for Emacs.

Is it known issue or I'm doing something wrong?

**Comment by greghendershott** [comment]
racket-mode defines and uses [`racket-paren-face`](https://github.com/greghendershott/racket-mode/blob/master/Reference.md#racket-paren-face).

If you're referring to the `paren-face` package on MELPA, I wasn't aware of that until I looked it up just now. I can take a look at how to cooperate with that package. Meanwhile if you don't mind you could set `racket-paren-face` using in your Emacs init file or using Customize.

**Comment by gour** [comment]
>  I can take a look at how to cooperate with that package. 

Thank you.

> Meanwhile if you don't mind you could set racket-paren-face in your Emacs init file or using Customize.

Well, I'm doing my first baby steps with Racket and paren-face's feature to dim parentheses in Racket code seems interesting to me...

**Comment by greghendershott** [comment]
Just to make sure the "work-around" is clear:

In a sense, racket-mode has always had a paren-face-mode feature built in. It can already do this.

racket-mode already draws `( ) [ ] { }` using the face [`racket-paren-face`](https://github.com/greghendershott/racket-mode/blob/master/Reference.md#racket-paren-face).

Therefore you can use Customize or your init file to change the `racket-paren-face` color to (say) `"grey60"` and those characters will appear "dim".

(I even defaulted racket-mode to use dim parens, until https://github.com/greghendershott/racket-mode/pull/6 a very long time ago.)

---

I will still look into detecting paren-face-mode and deferring to it if active.  However if that is likely to cause confusion, or require even more customization than the above, I will probably mark this "wontfix" and close it.

**Comment by gour** [comment]
> Therefore you can use Customize or your init file to change the racket-paren-face color to (say) "grey60" and those characters will appear "dim".

Don't know why, but neither attempt to change it within init file nor via Customize it's possible to change the value?

> I will still look into detecting paren-face-mode and deferring to it if active. However if that is likely to cause confusion, or require even more customization than the above, I will probably mark this "wontfix" and close it.

That's understandable and it customizing via racket-paren-face does work, then there is probably no need for it.

**Comment by greghendershott** [comment]
@gour I'm not sure why that wouldn't work for you.

My init.el has a giant `custom-set-faces` form. Pruned to the racket-mode stuff:

```
(custom-set-faces
 ;; racket-mode
 '(racket-keyword-argument-face ((t (:foreground "IndianRed3"))))
 '(racket-selfeval-face ((((background dark)) (:foreground "SeaGreen3"))
                         (((background light)) (:foreground "SeaGreen4"))))
 '(racket-paren-face ((((background dark)) (:foreground "HoneyDew4"))
                      (((background light)) (:foreground "grey60")))))
```

Does that work for you?

**Comment by gour** [comment]
> Does that work for you?

It does -- my mistake -- I was not properly setting colors. :-(

Still I wonder how one can do it within Customize?

**Comment by greghendershott** [comment]
> Still I wonder how one can do it within Customize?

<kbd>M-x customize</kbd>, `Programming`, `Languages`, `Racket`, `Racket Faces`.

Then move point to a face value and hit <kbd>RET</kbd> and... wait, what?!  it says, `You can't edit this part of the Custom buffer`. Try clicking with mouse on the value: Nothing happens, not even a message. Invoke M-x widget-button-press: `Text is read-only: "Attempt to change text outside editable field"`.

It's not just racket-mode faces. Any face I try in Customize. Although it's been months (years?) since I customized a face this way, I could have sworn it used to work. What the heck?

Is that what you're seeing, too?  Sorry I misunderstood this before, I had no idea it would not work.

**Comment by greghendershott** [comment]
Oh right. You need to click that triangle to expand the face item, and you get a bunch of face properties underneath.

**Comment by gour** [comment]
> Oh right. You need to click that right pointing triangle (Show) to expand the face item, and you get a bunch of face properties underneath.

Thank you!

To me (aka uninitiated) it looked just as fancy item bullet. :-)

**Comment by greghendershott** [comment]
This is a really old issue, but:

`(add-to-list 'paren-face-modes 'racket-mode)` works for me: paren-face-mode overrides the `racket-paren-face` applied racket-mode's font-lock.

As a result I'm going to close this issue.

---

I _think_ maybe your original problem was simply that you were doing `(add-to-list 'paren-face-modes "racket-mode")` -- adding `"racket-mode"` the string not `'racket-mode` the symbol?  At least that's what it looks like in your original report:

> `("racket-mode" lisp-mode emacs-lisp-mode lisp-interaction-mode ielm-mode scheme-mode inferior-scheme-mode clojure-mode cider-repl-mode nrepl-mode arc-mode inferior-arc-mode)`

I wish I'd noticed that sooner.

---

Optional: You might also want `(setq paren-face-regexp (rx (any "()[]{}")))` to have paren-face work on square brackets and curly braces, too.
