### ISSUE TITLE
Prompt isn't preceeded by newline

### ISSUE THREAD

**Issue by mromyers** [greghendershott/racket-mode#122]
scratch.rkt﻿> (display 'x)
    xscratch.rkt﻿> 
This might be the desired behavior, but it's difficult to work around something like

    scratch.rkt> (:print-type 0)
    Zeroscratch.rkt> 
since :print-type only works on the top-level.

**Comment by greghendershott** [comment]
I agree, this has annoyed me, too.

Probably I can use `port-count-lines!` on the output port to determine the column and issue a newline if needed.
