### ISSUE TITLE
Commands timeout while program is running in the REPL

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/racket-mode#132]
From issue #126, @samertm reports:

> Also, if something is running in `*Racket REPL*`, racket-mode will just constantly stall. So if you call racket-run in a buffer with this:

> ```
> #lang racket
> (require web-server/servlet web-server/servlet-env)
> (define (start req) (response/xexpr "test"))
> 
> (serve/servlet start)
> ```
>
> Without closing the server, if you start writing "(define " (or anything else), racket-mode will stall. Not sure if these two bugs are related. What function is being called when you type "(some-chars " (with the space)?

(This is with eldoc-mode enabled.)

My explanation:

> Basically, the communication mechanism is that the edit buffer "types things for you" into the REPL buffer. At the REPL prompt, if you type `,help` you will many of these "commands". For example you could type `,sig foo` and see the function signature (if available) for `foo`. When the eldoc code needs a sig, basically that is what's happening behind the scenes.

> As a result, unless the REPL is "ready" at a prompt, the commands can't be sent. (You can <kbd>C-c C-c</kbd> in the REPL to break the running Racket program. I mean that the edit buffer can't send the "hidden commands".)

> Generally this works well and is very reliable (there are no thread synchronization issues for example). Except in the use case you described: Keeping something like a server running a long time in the REPL while continuing to edit.

> Probably I should redesign this to use a socket and work out how to synchronize things and efficiently handle programs that emit a huge amount to stdout, etc. etc.

**Comment by greghendershott** [comment]
Working on this in the [`command-socket`](https://github.com/greghendershott/racket-mode/tree/command-socket) branch.

**Comment by tbrooke** [comment]
Just a thumbs up on this running into the same problem using web-server - the work around
seem to be to kill the repl before returning to editing

**Comment by greghendershott** [comment]
Unfortunately I won't be able to change this in the foreseeable future.

One work-around I can suggest is to use a `thread`.

For example replace `(serve/servlet start)` with `(thread (λ _ (serve/servlet start)))` or equivalent `(thread (thunk (serve/servlet start)))`.

Although the web server banner output may appear after the prompt...

```
foo.rkt﻿> Your Web application is running at http://localhost:8000/servlets/standalone.rkt.
Stop this program at any time to terminate the Web Server.
```

...you do have control. You can e.g. type `42` and press <kbd>ENTER</kbd>. It will evaluate and print `42`, and give you another prompt.

**Comment by greghendershott** [comment]
By the way: The next `racket-run` will delete this extra thread. racket-mode uses a custodian for all the resources created for/by the REPL. All are released/freed.
