### ISSUE TITLE
Handle `scheme/gui/base` and `racket/gui/dynamic`

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/racket-mode#133]
Originally reported by @UberLambda as a comment on issue #26:

---

Hi, it seems like the issue wasn't fixed on my setup.

I'm currently trying to run this snippet (via <kbd>C-c C-k</kbd>):
```racket
#lang planet neil/sicp

(* 3 4 5)
```
But when I do run it a second time, this appears on the `Racket-REPL` buffer:
```racket
; cannot instantiate `racket/gui/base' a second time in the same process
; Context:
;  /home/paolo/.racket/planet/300/6.1.1/cache/soegaard/sicp.plt/2/1/primitives.rkt:1:1 [traversing imports]
;  /home/paolo/.racket/planet/300/6.1.1/cache/soegaard/sicp.plt/2/1/painters.rkt:1:1 [traversing imports]
;  /home/paolo/.racket/planet/300/6.1.1/cache/soegaard/sicp.plt/2/1/sicp.rkt:1:1 [traversing imports]
;  /home/paolo/.racket/planet/300/6.1.1/cache/neil/sicp.plt/1/17/main.rkt:1:1 [traversing imports]
;  /home/paolo/sicp/sicp.rkt:1:1 [traversing imports]
```
Was this error intentional? (The previous comments talk about a "graceful error", but it doesn't seem to be this one; sorry if it indeed was)

**Comment by greghendershott** [comment]
Currently racket-mode is using a module name resolver to detect use of `racket/gui/base`. I thought `scheme/gui/base` was simply an alias for `racket/gui/base`, these days, so it would be covered. Apparently I'm wrong and it's not that simple.

**Comment by greghendershott** [comment]
I pushed a commit that fixes a simple test case:

```
#lang scheme
(require scheme/gui/base)
```

Confession: I did not actually install the neil/sicp Planet package, because I don't have time now, and honestly I'm reluctant to gunk up a fresh laptop with lots of old Planet dependencies. As a result, there's some chance it might not actually fix the problem for you, @UberLambda. If so, please let me know and I'll take more time to recreate the full scenario you reported.

If you installed racket-mode from MELPA, the update should flow through there within an hour or two.

If you have any questions or problems please let me know.

**Comment by UberLambda** [comment]
Thanks! I'll try to update as soon as I can when MELPA sources the new commit.

**Comment by UberLambda** [comment]
It does not appear to be working... :(

**Comment by greghendershott** [comment]
I just got a chance to install `neil/sicp`. I see the issue is that it requires `racket/gui/dynamic`. So I need to add that to the list. About to push a commit.

**Comment by greghendershott** [comment]
@UberLambda This commit fixed it for me. If not, for you, please feel free to re-open. Thanks again for reporting this.

**Comment by UberLambda** [comment]
@greghendershott It didn't, but there is no sense in you wasting time for this - since Planet is deprecated I just need to find another lang package :)

**Comment by greghendershott** [comment]
One reason it might not have worked for you: After updating from MELPA, you would need to restart the Racket REPL for the change to take effect. (At its prompt type `,exit`. Then run again with <kbd>C-c C-k</kbd>.)

**Comment by greghendershott** [comment]
> there is no sense in you wasting time for this - since Planet is deprecated I just need to find another lang package

Thanks for saying that. I hate it when things mysteriously don't work. And I don't think it's the "Planet-ness" that's the problem. I think if it were a `#lang sicp` from the new package system, it would work (or, _not_ work) the same.  However admittedly I don't have any other ideas now why it would work for me but not you.

**Comment by UberLambda** [comment]
It does not seem like this is the problem...

```racket
Welcome to Racket v6.1.1.
﻿> 
60
playc.rkt﻿> 
; cannot instantiate `racket/gui/base' a second time in the same process
; Context:
;  /home/paolo/.racket/planet/300/6.1.1/cache/soegaard/sicp.plt/2/1/primitives.rkt:1:1 [traversing imports]
;  /home/paolo/.racket/planet/300/6.1.1/cache/soegaard/sicp.plt/2/1/painters.rkt:1:1 [traversing imports]
;  /home/paolo/.racket/planet/300/6.1.1/cache/soegaard/sicp.plt/2/1/sicp.rkt:1:1 [traversing imports]
;  /home/paolo/.racket/planet/300/6.1.1/cache/neil/sicp.plt/1/17/main.rkt:1:1 [traversing imports]
;  /hdd/Informatica/sicp-impl/playc.rkt:1:1 [traversing imports]

﻿> ,exit

Process Racket REPL finished
Welcome to Racket v6.1.1.
﻿> 
60
playc.rkt﻿> 
; cannot instantiate `racket/gui/base' a second time in the same process
; Context:
;  /home/paolo/.racket/planet/300/6.1.1/cache/soegaard/sicp.plt/2/1/primitives.rkt:1:1 [traversing imports]
;  /home/paolo/.racket/planet/300/6.1.1/cache/soegaard/sicp.plt/2/1/painters.rkt:1:1 [traversing imports]
;  /home/paolo/.racket/planet/300/6.1.1/cache/soegaard/sicp.plt/2/1/sicp.rkt:1:1 [traversing imports]
;  /home/paolo/.racket/planet/300/6.1.1/cache/neil/sicp.plt/1/17/main.rkt:1:1 [traversing imports]
;  /hdd/Informatica/sicp-impl/playc.rkt:1:1 [traversing imports]

﻿> 
```
