### ISSUE TITLE
electric-pair-skip-self not work

### ISSUE THREAD

**Issue by an0** [greghendershott/racket-mode#140]
electric-pair-skip-self is non-nil but inserting a closing paren character results
in "())" rather than "()".

It works in list-mode and scheme-mode.

**Comment by greghendershott** [comment]
In lisp-mode and scheme-mode <kbd>)</kbd> is bound to plain-old `self-insert-command`, which is compatible with `electric-pair-mode`.

In racket-mode, <kbd>)</kbd> is bound to `racket-insert-closing-paren`. The `racket-insert-closing-xxx` commands use the shape of the matching opening delimiter.  For example you can just keep hitting <kbd>)</kbd> or the unshifted <kbd>]</kbd> and it will insert the correct shape. This isn't compatible with `electric-pair-mode`.

In your Emacs init file, please try binding the <kbd>)</kbd>, <kbd>]</kbd> and <kbd>}</kbd> keys in `racket-mode-map` to `self-insert-command`?  (You may want to do the same for `racket-repl-mode-map`.

**Comment by greghendershott** [comment]
Did that help?

I'm going to go ahead and tag this "question" and close it. However if you disagree and think it's a bug, or if you simply need more help, please feel free to comment here and re-open it.

**Comment by x-ji** [comment]
This worked. Thanks.
