### ISSUE TITLE
racket-test support for test-suites

### ISSUE THREAD

**Issue by aidalgol** [greghendershott/racket-mode#142]
`racket-test` (`C-c C-t`) is great for test submodules and I would really like to be able to use it to run (and parse the output of) my system `test-suite`s.  I have a separate `tests.rkt` file that is a stand-alone Racket program of the form...

```racket
#lang racket/base

(require rackunit
         rackunit/text-ui
         ...)

(define some-tests
  (test-suite
   "Some tests"

   (test-case
    "A test"
    ... )

   (test-case
    "Another test"
    ...)))

(define some-more-tests
  (test-suite
   "Some more tests"
   ...)

   ...)

(run-tests some-tests)
(run-tests some-more-tests)
```

What would be involved in changing adding support for this?  The `run-tests` output is similar but the fields are in a different order, but the _key_ difference is the format of the "location" line (FILE:LINE:COLUMN).

**Comment by greghendershott** [comment]
First glance, it seems there are two parts:

1. Running the tests.

    - Would you mind wrapping the tests in a `(module+ test ....)` form? That way `racket-test` will find and run them.

    - Otherwise, I can look at making `racket-test` behave more like `raco test` -- which I believe is (a) if there's a test submodule, run that, otherwise (b) run the file normally. That seems simple enough (?).

2. Parsing the output. This should simply entail adding a regexp to `compilation-error-regexp-alist` in `racket-repl.el`. It's unfortunate that `test-suite` doesn't print the full path, but I _think_ it will be OK if the current directory is set there.

**Comment by greghendershott** [comment]
p.s. Maybe I'm over-thinking 1. If you're fine doing a normal `racket-run` (instead of `racket-test`) on a file dedicated to tests, maybe only 2 matters to you?

**Comment by greghendershott** [comment]
I pushed a commit that only addresses 2 -- making compilation-mode recognize test-suite failure locations. I _think_ that closes the issue, but let me know if you disagree.

**Comment by aidalgol** [comment]
Yup, that's working for me.  Thanks!

**Comment by greghendershott** [comment]
You're welcome! Glad to hear it's working for you.
