### ISSUE TITLE
The DrRacket IDE doesn't work after using racket-mode

### ISSUE THREAD

**Issue by weizhao0** [greghendershott/racket-mode#143]
I was using the DrRacket IDE (GUI). To use racket-mode in emacs, I installed the brew version racket, and also "raco pkg install drracket". Here is the error message when I open the DrRacket IDE:
![screen shot 2015-06-27 at 11 58 13 pm](https://cloud.githubusercontent.com/assets/13036251/8395344/64f772fa-1d28-11e5-85ad-ea5039acd90e.png)

**Comment by greghendershott** [comment]
To make sure I understand, it sounds like:

1. You already had Racket installed (how/from where?), and were using DrRacket successfully.

2. You couldn't get racket-mode to work with Racket. As a result, you felt you needed to install Racket again, this time from Homebrew.

Is that correct?

If so, it sounds to me like you have 2 conflicting versions of Racket are conflicting, and you should remove one?

---

racket-mode does _not_ require the Homebrew distribution of Racket. It works with the regular distribution you download from http://download.racket-lang.org.  On OS X, the only catch is that it won't be automatically added to your PATH; you need to add it to your `.profile` or `~/.bashrc` or whatever, yourself. Furthermore, by default Emacs on OS X doesn't know the PATH. This is [described here in the README](http://docs.mathjax.org/en/latest/start.html).

**Comment by weizhao0** [comment]
Yes, what you said is exactly what I did and what I thought. Now I would like to fully remove the homebrew version Racket and anything installed from ""raco pkg install drracket". What should I do?

**Comment by weizhao0** [comment]
Yes, what you said is exactly what I did.
Issue fixed.

**Comment by greghendershott** [comment]
Cool, I'm happy to hear it's working.
