### ISSUE TITLE
Keymap problems in terminal

### ISSUE THREAD

**Issue by mromyers** [greghendershott/racket-mode#148]
When using non-graphical emacs (as from emacs -nw, etc), once racket-mode is enabled, many keys & combinations stop working. So far I've noticed F5, F10, and the all important M-x, but there are probably more. Before racket-mode is enabled, they work fine. When racket-mode is turned off, the effect persists, but does it does not effect any buffers where it has not yet been activated.

I tested this with a fresh .emacs containing nothing but the most recent racket-mode (no other options or packages), and it still persists.

Occasionally I get the message:
"call-interactively: Wrong type argument: characterp, nil [3 times]"
when pressing one of those keys in this situation, but I can't reproduce this message predictably.

This is on GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5), from debian stable.

**Comment by greghendershott** [comment]
That is ... weird.

I can't reproduce this, at least not with `"GNU Emacs 25.0.50.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8)"` built from source.

In case it's related to a minor mode you're using, I'd ask you to `M-x racket-bug-report` and paste the info here. But if you can't use <kbd>M-x</kbd> ...?  Hmm. Can you <kbd>M-:</kbd> to get the `Eval:` prompt and enter `(racket-bug-report)`?

**Comment by greghendershott** [comment]
Although you said a clean `.emacs`, so maybe `racket-bug-report` unlikely to say much. Instead I should try a clean `.emacs`....

**Comment by greghendershott** [comment]
I still couldn't reproduce it with this `.emacs`:

```
(require 'use-package)

(use-package racket-mode
  :load-path "~/src/elisp/racket"
  :config (setq racket-racket-program "/usr/racket/bin/racket"
                racket-raco-program   "/usr/racket/bin/raco"))
```

Although I can't right now I guess I should try Emacs 24.4.1, too.

**Comment by mromyers** [comment]
When I said, 'a clean .emacs', I actually meant a clean .emacs.d with the following init.el

```
(load-library "package")
(add-to-list 'package-archives
  '("gnu" . "http://elpa.gnu.org/packages/") t)
(add-to-list 'package-archives
  '("melpa" . "http://melpa.milkbox.net/packages/") t)
(package-initialize)
```

with racket mode then installed from melpa. I'm not sure how the use-package thing works.

The steps I followed are:
1. mv .emacs.d .old.emacs.d
2. add the above init.el
3. install racket-mode through the package menu
4. emacs -nw
5. enter racket mode, either by M-x racket-mode, or C-x C-f ~/prog/rkt/scratch.rkt

If I M-x racket-mode in the scratch buffer, it reliably gives the error message I first reported. If I open a .rkt file, it simply fails to load. Neither M-x nor M-: work. Most recently, when I tried M-:, it ended up freezing and using all available cpu until I killed it.

**Comment by mromyers** [comment]
Ok, M-x and M-: seem to be working fine now in both cases, I have no idea what changed. 
When I do M-x racket-mode in the scratch buffer, F5 and F10 still fail with
```
call-interactively: Wrong type argument: characterp, nil
```
When I load a .rkt file instead, pressing them immediately causes emacs to freeze and use as much cpu as possible.

Neither of these happen when run graphically.

**Comment by mromyers** [comment]
Oh, racket bug-report gives:

Please copy and paste this into your bug report at:

  https://github.com/greghendershott/racket-mode/issues/new

```
((emacs-version "24.4.1")
 (emacs-uptime "4 minutes, 4 seconds")
 (system-type gnu/linux)
 (major-mode racket-mode)
 (racket--source-dir "/home/mrm/.emacs.d/elpa/racket-mode-20150715.1103/")
 (racket-racket-program "racket")
 (racket-raco-program "raco")
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-use-company-mode t))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-font-lock-mode)
 (hs-minor-mode)
 (line-number-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-mark-mode))
(disabled-minor-modes
 (abbrev-mode)
 (auto-fill-function)
 (blink-cursor-mode)
 (buffer-read-only)
 (column-number-mode)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (defining-kbd-macro)
 (display-time-mode)
 (electric-layout-mode)
 (global-prettify-symbols-mode)
 (global-visual-line-mode)
 (ido-everywhere)
 (isearch-mode)
 (jit-lock-debug-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-check-syntax-mode)
 (size-indication-mode)
 (temp-buffer-resize-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode))
```

**Comment by greghendershott** [comment]
In a misbehaving racket-mode buffer, what happens if you do <kbd>M-:</kbd> `(local-unset-key (kbd "M-["))`? And/or `(global-unset-key (kbd "M-["))`?

Why I ask:

After reading lots of Elisp docs about keymaps and translations, I noticed this:

```
21.14.1 Interaction with normal keymaps

The end of a key sequence is detected when that key sequence either is
bound to a command, or when Emacs determines that no additional event
can lead to a sequence that is bound to a command.

   This means that, while ‘input-decode-map’ and ‘key-translation-map’
apply regardless of whether the original key sequence would have a
binding, the presence of such a binding can still prevent translation
from taking place.  For example, let us return to our VT100 example
above and add a binding for ‘C-c <ESC>’ to the global map; now when the
user hits ‘C-c <PF1>’ Emacs will fail to decode ‘C-c <ESC> O P’ into
‘C-c <PF1>’ because it will stop reading keys right after ‘C-x <ESC>’,
leaving ‘O P’ for later.  This is in case the user really hit ‘C-c
<ESC>’, in which case Emacs should not sit there waiting for the next
key to decide whether the user really pressed ‘<ESC>’ or ‘<PF1>’.

   For that reason, it is better to avoid binding commands to key
sequences where the end of the key sequence is a prefix of a key
translation.  The main such problematic suffixes/prefixes are ‘<ESC>’,
‘M-O’ (which is really ‘<ESC> O’) and ‘M-[’ (which is really ‘<ESC> [’).
```

Theory: About 4 weeks ago in commit c980131 I added a binding of <kbd>M-[</kbd> to `racket-align` -- perhaps that's the cause?

(By default <kbd>M-[</kbd> is bound to the built-in `align` command. I don't yet understand why my binding would fubar things when that does not.)

**Comment by mromyers** [comment]
I just tried this, and it prevents the weird behavior. Maybe add a customize option to change or disable that binding for now?

**Comment by greghendershott** [comment]
Good!

It turns out `emacs -nw` is smart enough not to bind <kbd>M-[</kbd> to `align` at all, according to <kbd>C-h k</kbd>.

I want to follow its example. But so far I can't find it. Not in `align.el` or `bindings.el`. Still searching....

**Comment by greghendershott** [comment]
I found this interesting comment in simple.el confirming the basic issue:

```cl
(defvar visual-line-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map [remap kill-line] 'kill-visual-line)
    (define-key map [remap move-beginning-of-line] 'beginning-of-visual-line)
    (define-key map [remap move-end-of-line]  'end-of-visual-line)
    ;; These keybindings interfere with xterm function keys.  Are
    ;; there any other suitable bindings?
    ;; (define-key map "\M-[" 'previous-logical-line)
    ;; (define-key map "\M-]" 'next-logical-line)
    map))
```

Still searching for how the binding is done conditionally for align....

**Comment by greghendershott** [comment]
Gah. I am an idiot. Emacs doesn't bind it. I'd done so in my own init file so long ago that I forgot. _\*sigh\*_

I'll change (or maybe simply remove) the default binding for racket-mode, and push a commit.
