### ISSUE TITLE
Blocked threads hang REPL

### ISSUE THREAD

**Issue by florence** [greghendershott/racket-mode#154]
To Reproduce:

Enter the program:

```
#lang racket
(define t (thread (sync never-evt)))
```

then run `racket-run`

The racket repl starts, but the prompt is ever available.

Expect behavior:

The prompt should appear, and `(thread-running? t)` should be true.

**Comment by greghendershott** [comment]
I think you intended the following instead?

    #lang racket
    (define t (thread (λ () (sync never-evt))))

Or equivalently:

    (define t (thread (thunk (sync never-evt))))
    (define t (thread (curry sync never-evt)))

---

Whereas to evaluate

    #lang racket
    (define t (thread (sync never-evt)))

Racket first has to evaluate (eagerly) `(sync never-evt)`. As a result the module evaluation never finishes. It's effectively the same as:

    #lang racket
    (sync never-evt)

Which never reaches the prompt, and I think is as-expected.

**Comment by florence** [comment]
Oops. This was an attempt at simplifying a larger program. I'll get back to
you on this tomorrow.
