### ISSUE TITLE
RET adds an extra \n

### ISSUE THREAD

**Issue by andmkent** [greghendershott/racket-mode#156]
Sometimes pressing RET will add an extra '\n' in addition to indenting.

Consider this small file:

```racket
#lang racket

(+ (+ 1 2) (+ 3 4))
```

If I place my cursor directly after the sexp ``` (+ 1 2) ``` (so it is "touching" the closing paren) and press RET the result is what you would expect:

```racket
#lang racket

(+ (+ 1 2)
   (+ 3 4))
```

However, if I instead place the cursor one character further, so it is "touching" the next opening paren for the sexp ``` (+ 3 4)``` an extra \n is inserted and my cursor is correctly indented on the new empty line I did not want:

```racket
#lang racket

(+ (+ 1 2)
              ;; <-- cursor on this line, correctly indented
   (+ 3 4))

```

This does not happen in Dr. Racket or in lisp buffers in emacs, and obviously it leads to a lot of deleting of the unwanted newlines (this gets old fast).

Commenting out the following line in racket-mode.el seemed to fix the issue for me (although I have done minimal testing):

```racket
  ("RET"         newline-and-indent)
```

My (extremely naive) guess is the behavior we want (nice indenting after the newline insertion) is *already* inherited from lisp-mode-shared-map, and the line above is giving us `double feeds' in some circumstances.

**Comment by greghendershott** [comment]
If you're using Emacs 24.4 or newer, you probably have `electric-pair-mode` enabled, and in your init.el you can `(unbind-key (kbd "RET") racket-mode-map)`.

Probably I should remove this keybinding, and users of 24.3 (the oldest version supported by racket-mode) could add it or an electric-pair sort of mode, themselves.
