### ISSUE TITLE
Functions calling `racket--self-insert` should consider declaring a delete-selection property

### ISSUE THREAD

**Issue by cpitclaudel** [greghendershott/racket-mode#159]
From the docs of `delete-selection-mode`:

> Commands which will delete the selection need a 'delete-selection property on their symbols; commands which insert text but don't have this property won't delete the selection.

For example:
```
(put 'racket-smart-open-bracket 'delete-selection t)
```

Adding these properties would prevent racket-mode from negatively interfering with `delete-selection-mode`.

Cheers and thanks for `racket-mode`!

**Comment by greghendershott** [comment]
Thank you for the report and advice! I'm always learning something new about Emacs.

It sounds like I ought to review some other racket-mode commands that insert text, too. Including for example the `racket--xxx-requires` commands.

**Comment by greghendershott** [comment]
Although the `racket-xxx-requires` commands don't need this, the `racket-insert-closing-xxx` commands do (in addition to `racket-smart-open-bracket` as you'd reported).

Thanks again.
