### ISSUE TITLE
racket/gui process can outlive *Racket REPL* session (and even the emacs process)

### ISSUE THREAD

**Issue by florence** [greghendershott/racket-mode#165]
I'm on OSX.

When I launch a slideshow program from `racket-mode` I get a Dock icon for the gui process (this is typical for racket gui programs). However if I kill the REPL, or close Emacs the gui process does not go away. (And relaunching the REPL generates another gui process).

I would expect the gui process to die when the REPL does.

**Comment by greghendershott** [comment]
I don't use slideshow, can you give me a simple example program that exhibits the problem for you?

Meanwhile I tried using `plot`. I don't see the problem you describe with: 

```
#lang racket

(require plot)

(plot-new-window? #t) ;show in a GUI window instead of printing graphic in REPL

(plot (function sin (- pi) pi))
```

1. Run this. Window is created with plot. Also, I get the process icon on the OSX dock.

2. Run some other file, or type `,top` in the REPL. Window is automatically deleted. Process icon remains on dock (as expected).

3. Type `,exit` to exit the Racket REPL. Racket process exits. The icon is gone from the dock, for me.

This with Emacs 24.3, OS X 10.7.5, and Racket 6.1.1.8 (yeah I haven't used OSX much lately and some versions are old).

How about the above, for you?

**Comment by greghendershott** [comment]
OK, I RTFd the M. I tried:

```
#lang slideshow

(slide
 #:title "How to Say Hello"
 (t "Hello World!"))
```

1. Run it. Slideshow appears full screen. <kbd>ESC</kbd>. Yes I want to quit.
2. In REPL, type `,top`.  The "exec" item remains in dock (as expected).
3. In REPL, type `,exit`. The Racket process exits. The "exec" icon is _gone_ from the dock, for me.

So, I can't repro it with slideshow, either.

I'm guessing the Emacs version is N/A, but the OSX and/or Racket versions might be A.  You have newer of both, I bet.

Or maybe there's some other step. Could you try the above, exactly, and let me know what happens?

**Comment by florence** [comment]
Ahah.

The gui process does quit when I use `,exit`, but not if I kill the buffer via `M-x k` or if I just close emacs outright.

**Comment by greghendershott** [comment]
OK. In that case I wonder if you're actually experiencing #158, fixed about 10 days ago. Can you make sure you have a version since that was fixed? A MELPA version newer than "20150922xxx"?

(Also, just updating the package from MELPA wouldn't be enough; you'd need to restart the racket REPL to be using the updated code.)

**Comment by florence** [comment]
Aha! My racket-mode was out of date (I forgot I have a clone of it, instead of installing it from MELPA, so it wasn't getting updated). Everything works fine now!
