### ISSUE TITLE
what is (require 's) in the racket-util.el ?

### ISSUE THREAD

**Issue by xieyuheng** [greghendershott/racket-mode#167]

**Comment by greghendershott** [comment]
The `(require 's)` requires the `s` "feature" provided by [the `s` package](http://melpa.org/#/s).

The `s` package is declared as a dependency for the `racket-mode` package [in `racket-mode.el`](https://github.com/greghendershott/racket-mode/blob/master/racket-mode.el#L6):

    ;; Package-Requires: ((emacs "24.3") (faceup "0.0.2") (s "1.9.0"))
