### ISSUE TITLE
Repeated printing of - : Any in REPL when using Typed Racket

### ISSUE THREAD

**Issue by david-christiansen** [greghendershott/racket-mode#172]
When working on a Typed Racket module, the REPL keeps spitting out the following:
```
tt.rkt﻿> - : Any
tt.rkt﻿> - : Any
tt.rkt﻿> - : Any
tt.rkt﻿> - : Any
tt.rkt﻿> - : Any
```

My guess is that something behind the scenes is causing evaluation to occur and not trapping the type output.

**Comment by greghendershott** [comment]
Thank you for the report. I can reproduce.

**Comment by greghendershott** [comment]
A simpler (from my point of view) example of this is to use a REPL command like `,pwd`. It should:

1. print the current directory on one line as a comment
2. _not_ print `- : Any` on its own line
3. give another prompt

This used to work correctly. I recall that it was as simple as making sure that REPL commands returned `void`, for which Typed Racket prints no type. They still do AFACIT so it's not obvious to me what's wrong.

Unfortunately I haven't been using Typed Racket hands-on for awhile, so I didn't notice immediately how/when this regressed. Will investigate....

**Comment by greghendershott** [comment]
Fixed. If you're installing from MELPA, it might take awhile (from 1 to 24 hours?) for it to refresh and supply this.

Thanks again for pointing this out!

**Comment by david-christiansen** [comment]
Thanks for the quick turnaround! I appreciate it!

I'm liking racket-mode quite a lot.
