### ISSUE TITLE
path-replace-suffix: removing suffix makes path element empty

### ISSUE THREAD

**Issue by mastokley** [greghendershott/racket-mode#175]
Hello,

I am receiving the following error when I use the 'run-racket-and-switch-to-repl' command:

; path-replace-suffix: removing suffix makes path element empty
;   given path: #<path:.rkt>

Racket-mode is working - I can evaluate (+ 1 3) inside emacs, for example. My PATH and my emacs init file are configured.

So the problem is - racket-mode will not take my code from my racket editing buffer and feed it into the repl buffer.

**Comment by mastokley** [comment]
Ah, it's because I was using the emacs 'junk' file, which has no filename.

I confirmed the command works with regular files.

Closing!

**Comment by greghendershott** [comment]
> Ah, it's because I was using the emacs 'junk' file, which has no filename.

That's interesting. I've never heard of that before. I searched and found the `open-junk-file` package. Is that what you mean, you use that?

racket-mode does require an actual file; it doesn't work from a buffer per se. Although I've considered changing, it hasn't seemed like an important thing (so far), and requiring an actual file simplifies many things.

**Comment by mastokley** [comment]
Yup, open-junk-file.
