### ISSUE TITLE
Recent font-lock changes are too slow?

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/racket-mode#178]
I was adding a new test at the end of markdown/test.rkt, and unhappy how slow it was. I'm afraid that this is due to recent font-lock changes, that find the start of a module-level form.

If I can't make this significantly faster, I may need to revert some of those enhancements.

**Comment by greghendershott** [comment]
The bulk of this is due to calling `syntax-ppss` too much. Although it has a cache, it's flushed after the buffer is changed. Ergo this is reparsing the entire buffer after every change.

The call to `syntax-ppss` is part of an effort to escape a string or comment. I think the answer is to move that out of `racket--module-level-form`, and use it only in `racket--beginning-of-defun-function`.

**Comment by david-christiansen** [comment]
I can confirm that `font-lock` is running very slowly on a recent MELPA checkout of `racket-mode`. When I edit a fairly short file (about 850 lines), it is unusably slow when `font-lock` is enabled. Disabling font-lock makes editing speedy again.

**Comment by greghendershott** [comment]
I hope to push a commit, today.

On the bright side (and to explain why I didn't notice this at first), it's not so much the file size -- it's the size of the top-level sexp you're in, such as a function definition.  However in Racket that could be a `module` form that is hundreds of lines -- that's where it's particularly painful right now.

**Comment by greghendershott** [comment]
Update:

I got side-tracked by Travis CI failures that turned out to be a bug in Emacs snapshot's package.el.

In the process of researching that, I discovered [flycheck/emacs-travis](https://github.com/flycheck/emacs-travis), decided it's superior to what I'm doing, and got side-tracked into adopting that.

I'm almost ready to "pop the stack" a couple times and resume finishing this item....

**Comment by greghendershott** [comment]
Commit merged. Whenever you have a chance to try, please let me know if the experience is now good again. (Although I've dog-fooded this the last couple days, and it's been great for me, it's possible there's some corner case I didn't exercise.)

**Comment by greghendershott** [comment]
@david-christiansen I just caught up with Twitter and learned about your [tt-playground](https://github.com/david-christiansen/tt-playground). Cool!  I cloned it and did some no-meaning edits, especially near the end of the long-ish `tt.rkt` file. The performance seemed OK to me.

**Comment by david-christiansen** [comment]
Thanks so much! I'll update from MELPA tomorrow and give it a whirl.

I really do need to get tt.rkt split up into meaningful modules --- that'll
be a good way to learn Racket modules.

2015-11-23 18:06 GMT+01:00 Greg Hendershott <notifications@github.com>:

**Comment by timjervis** [comment]
Dear Greg,

So far, so good. Racket-mode with font-lock appears to be back to its usual “instantaneous” speed on my Mac OS X 10.11.1 / Racket 6.2 / Aquamacs 3.3dev (Emacs 25.0.50.4) system.

Many thanks,

Tim

> On 23 Nov 2015, at 16:47, Greg Hendershott <notifications@github.com> wrote:
> 
> Commit merged. Whenever you have a chance to try, please let me know if the experience is now good again. (Although I've dog-fooded this the last couple days, and it's been great for me, it's possible there's some corner case I didn't exercise.)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/greghendershott/racket-mode/issues/178#issuecomment-158992466>.
> 


Tim Jervis

http://timjervis.com/ <http://timjervis.com/>

**Comment by david-christiansen** [comment]
I can confirm that racket-mode editing performance is once again great. Thanks!

**Comment by greghendershott** [comment]
@timjervis @david-christiansen Thank you for the feedback. I'm sorry this performance issue arose in the first place.
