### ISSUE TITLE
disable eldoc

### ISSUE THREAD

**Issue by deyaaeldeen** [greghendershott/racket-mode#181]
I use racket-mode 0.4
I am not sure if this is the intended behavior, but it looks like eldoc tries to call some repl functions while I am editing or moving in a racket code buffer. I have not experienced this behavior before upgrading to emacs 25.1 (dev version). If this is intended, how can I disable it?

Error:
Debugger entered--Lisp error: (error "Racket did not respond in time")
  signal(error ("Racket did not respond in time"))
  error("Racket did not respond in time")
  racket--repl-cmd/buffer(",type r" nil)
  racket--repl-cmd/string(",type r" nil)
  racket--repl-cmd/sexpr(",type r")
  racket-get-type("r")
  racket-eldoc-function()
  eldoc-print-current-symbol-info()
  #[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2]()
  apply(#[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2] nil)
  timer-event-handler([t 0 0 500000 nil #[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2] nil idle 0])

**Comment by deyaaeldeen** [comment]
ok, i figured it out, i should call (global-eldoc-mode 0) after loading racket mode.

**Comment by greghendershott** [comment]
Ah, that's right -- Emacs 25 enables eldoc by default. Not sure I agree that's a good default, but that's the reality now.

I'll think about how racket-mode could deal with this more gracefully. Maybe it shouldn't try to start the Racket REPL automatically for eldoc, instead maybe it should `message` to let you know it won't work until you start the REPL manually.
