### ISSUE TITLE
error-display-handler

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/racket-mode#183]
From @samth on `#racket`:

```
7:04 PM <samth> 2. repl expressions that call (error-display-handler) multiple times
7:04 PM <samth> (it only seems to print the first one
7:04 PM <samth> )
7:06 PM <samth> greghendershott: note that xrepl also does poorly on the second, though drracket does well
```

**Comment by greghendershott** [comment]
@samth I'm not sure what to be trying, here. Can you give me a simple example of what you were doing, and what you hoped/expected racket-mode to do instead?

**Comment by samth** [comment]
Oh, this seems to be working better than I saw before. We can close this; I don't know what the issue was.

**Comment by greghendershott** [comment]
OK I'll close it for now.
