### ISSUE TITLE
Better UX when racket segfaults

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/racket-mode#184]
From @samth on `#racket`:

```
#lang racket

(require ffi/unsafe)

(define-cstruct _scheme_thread_set
  ([typetag _short]
   [key _int]
   [parent _scheme]))

(define ctg (cast (current-thread-group) _scheme _scheme_thread_set-pointer))

(define (crash) (scheme_thread_set-parent ctg))
```

In REPL, enter `(crash)`.

Result: The Racket process and REPL become unresponsive. Need to kill with <kbd>C-c C-\\</kbd>.

@samth would prefer this to be detected, a message printed, and the racket process to continue or at least to be automatically killed.

Note: I'm not sure exactly what "this" is -- what condition should be detected. It seems this code is changing the parent of the REPL's thread, so ....?  Need to think/understand more.

**Comment by greghendershott** [comment]
With plain racket (no XREPL loaded), typing these expressions in its REPL:

```
$ racket
Welcome to Racket v6.2.
> (require ffi/unsafe)
> (define-cstruct _scheme_thread_set
  ([typetag _short]
   [key _int]
   [parent _scheme]))
> (define ctg (cast (current-thread-group) _scheme _scheme_thread_set-pointer))
> (define (crash) (scheme_thread_set-parent ctg))
> (crash)
$ 
```

Notice that racket terminates without displaying any message about the segfault.

So if I understand correctly, that's what's happening in the racket-mode REPL, too.  And so this issue amounts to, "racket-mode should detect when the racket process has terminated, and when that happens, display a message even when racket failed to do so".  Does that sound right @samth?

**Comment by greghendershott** [comment]
No that's not right. I added an Emacs process sentinel. It's not called when I enter `(crash)`, only after I manually terminate with <kbd>C-c C-\\</kbd>.

For some reason when `(crash)` is evaluated, the racket process continues to run. It "hangs indefinitely" rather than terminating.

I am confuse.

**Comment by greghendershott** [comment]
Doing some issue weeding, I'm going to close this. Seems both:
- a to-do for racket not racket-mode
- rare for most users (e.g. for me racket segfaults approximately never, although I appreciate it depends how much you're using FFI directly or indirectly)

**Comment by samth** [comment]
Just for posterity, I don't think it's right that the Racket process hangs here, since the shell prompt comes back. Or at least, the shell detects that something has happened, even if Emacs doesn't.
