### ISSUE TITLE
Inline images don't work on Windows

### ISSUE THREAD

**Issue by interplinternet** [greghendershott/racket-mode#188]
I've tried googling and going through the source myself, but haven't found any solution. Emacs on Windows can support images fine, and I can display them in the scratchpad using what seems to be the same function used in racket-repl.el: `(insert-image (create-image [filename]))`. I've also checked my temp dir, and there is in fact an image there with the racket-generated filename. However, M-x `racket-view-last-image` gives me the message that "There aren't 1 images". Using M-: to eval `racket-image-cache-dir` gives a result of nil. I'm not sure if that's the desired output, but maybe it'll be helpful. The image is also listed in the repl as `#<Image: C:\\Users\\user\\AppData\\Local\\Temp\\racket-image-14501363761450136376317.png>`, so I thought it might be a problem relating to the escaped backslashes, but using that file's location as the target for the above insert-image+create-image function (including backslashes) still displays the image. Here's the result of `racket-bug-report`.

```
((emacs-version "24.5.1")
 (emacs-uptime "5 minutes, 25 seconds")
 (system-type windows-nt)
 (major-mode racket-repl-mode)
 (racket--source-dir "c:/Users/argos/.emacs.d/elpa/racket-mode-20151207.1952/")
 (racket-racket-program "c:\\Program Files\\Racket\\Racket.exe")
 (racket-raco-program "c:\\Program Files\\Racket\\raco.exe")
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (blink-cursor-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-font-lock-mode)
 (line-number-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-mark-mode))
(disabled-minor-modes
 (abbrev-mode)
 (auto-fill-function)
 (buffer-read-only)
 (column-number-mode)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (defining-kbd-macro)
 (display-time-mode)
 (electric-layout-mode)
 (global-prettify-symbols-mode)
 (global-visual-line-mode)
 (hs-minor-mode)
 (ido-everywhere)
 (isearch-mode)
 (jit-lock-debug-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-check-syntax-mode)
 (sh-electric-here-document-mode)
 (size-indication-mode)
 (temp-buffer-resize-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode))
```

**Comment by greghendershott** [comment]
Thank you for the report. It sounds like you investigated the obvious things, which I appreciate. Although I want racket-mode to work well on Windows, and do try it from time to time, unfortunately it might be a week or two before I'll have the chance to try it on Windows first-hand. As a result, if you or anyone else is able to figure it out and submit a PR before I can get to it, I'd be grateful.
