### ISSUE TITLE
`racket-smart-open-bracket` doesn't know about `new`

### ISSUE THREAD

**Issue by david-christiansen** [greghendershott/racket-mode#189]
I like that I can type `[` to get the correct kind of opening paren in `racket-mode`, but it doesn't seem to know about `new`.

I would expect that if I wrote `(new bitmap-dc% I)` and had the cursor at the I, pressing `[` inserts square brackets, but it inserts parens instead.

**Comment by greghendershott** [comment]
That makes sense. IIUC it's of the same pattern as `case`, `match`, `syntax-parse`, etc. I'll add `new` to that pattern.

(While looking at [that doc page](http://docs.racket-lang.org/reference/objcreation.html#%28form._%28%28lib._racket%2Fprivate%2Fclass-internal..rkt%29._new%29%29), I wondered about some forms like `instantiate`. However I tried and DrRacket doesn't treat them specially. And I don't use those OO forms enough in Racket to have a strong opinion if they should be handled specially. So I won't.)
