### ISSUE TITLE
Highlight untested functions when code is run

### ISSUE THREAD

**Issue by aviralg** [greghendershott/racket-mode#195]
Hi,

DrRacket highlights untested code when run button is pressed. I don't know how it does that but its surely useful to have (especially for students like me whose assignments require 100% test coverage!).
You think this could be added to racket-mode?

Thanks,
Aviral Goel

**Comment by greghendershott** [comment]
It already does! Try giving a prefix to [`racket-test`](https://github.com/greghendershott/racket-mode/blob/master/Reference.md#racket-test).

In other words:
- <kbd>C-c C-t</kbd> runs tests.
- <kbd>C-u C-c C-t</kbd> runs tests and also highlights expressions uncovered by tests.
