### ISSUE TITLE
wildcard not allowed as an expression

### ISSUE THREAD

**Issue by xificurC** [greghendershott/racket-mode#207]
Hi,

running this in DrRacket's REPL works just fine

```racket
(match 1 [_ 1])
```

In Emacs Racket REPL I get this behavior instead

```racket
﻿> (match 1 [_ 1])
; stdin::9831: _: wildcard not allowed as an expression
;   in: (_ 1)
```

Here is the output of `M-x racket-bug-report`

```
((emacs-version "24.5.1")
 (emacs-uptime "5 hours, 58 minutes, 41 seconds")
 (system-type windows-nt)
 (major-mode racket-repl-mode)
 (racket--source-dir "c:/home/.emacs.d/elpa/racket-mode-20160213.904/")
 (racket-racket-program "Racket.exe")
 (racket-raco-program "Raco.exe")
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil))
(enabled-minor-modes
 (Info-breadcrumbs-in-mode-line-mode)
 (anzu-mode)
 (async-bytecomp-package-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (clean-aindent-mode)
 (column-number-mode)
 (company-mode)
 (diff-auto-refine-mode)
 (electric-indent-mode)
 (eval-sexp-fu-flash-mode)
 (evil-escape-mode)
 (evil-local-mode)
 (evil-mode)
 (evil-search-highlight-persist)
 (evil-surround-mode)
 (fci-mode)
 (file-name-shadow-mode)
 (flx-ido-mode)
 (flycheck-pos-tip-mode)
 (font-lock-mode)
 (global-anzu-mode)
 (global-auto-revert-mode)
 (global-company-mode)
 (global-evil-search-highlight-persist)
 (global-evil-surround-mode)
 (global-flycheck-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-git-gutter+-mode)
 (global-hl-line-mode)
 (global-page-break-lines-mode)
 (global-spacemacs-default-map-override-mode)
 (global-spacemacs-leader-override-mode)
 (global-undo-tree-mode)
 (global-vi-tilde-fringe-mode)
 (helm-descbinds-mode)
 (helm-flx-mode)
 (helm-mode)
 (hybrid-mode)
 (ido-vertical-mode)
 (line-number-mode)
 (mouse-wheel-mode)
 (override-global-mode)
 (persp-mode)
 (popwin-mode)
 (projectile-global-mode)
 (projectile-mode)
 (recentf-mode)
 (savehist-mode)
 (shell-dirtrack-mode)
 (show-smartparens-global-mode)
 (show-smartparens-mode)
 (smartparens-mode)
 (smartparens-strict-mode)
 (spaceline-helm-mode)
 (spaceline-info-mode)
 (spacemacs-default-map-override-mode)
 (spacemacs-leader-override-mode)
 (transient-mark-mode)
 (undo-tree-mode)
 (vi-tilde-fringe-mode)
 (volatile-highlights-mode)
 (which-key-mode)
 (window-numbering-mode)
 (winner-mode)
 (xterm-mouse-mode)
 (yas-global-mode))
(disabled-minor-modes
 (2C-mode)
 (abbrev-mode)
 (adaptive-wrap-prefix-mode)
 (auto-fill-function)
 (auto-highlight-symbol-mode)
 (auto-image-file-mode)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (blink-cursor-mode)
 (buffer-read-only)
 (bug-reference-mode)
 (bug-reference-prog-mode)
 (company-search-mode)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (defining-kbd-macro)
 (diff-hl-dir-mode)
 (diff-hl-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (dired-isearch-filenames-mode)
 (dired-omit-mode)
 (display-time-mode)
 (edebug-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (flycheck-mode)
 (git-commit-mode)
 (git-gutter+-mode)
 (global-auto-highlight-symbol-mode)
 (global-diff-hl-mode)
 (global-highlight-parentheses-mode)
 (global-hl-todo-mode)
 (global-prettify-symbols-mode)
 (global-visual-line-mode)
 (goto-address-mode)
 (goto-address-prog-mode)
 (helm--minor-mode)
 (helm--remap-mouse-mode)
 (helm-adaptive-mode)
 (helm-autoresize-mode)
 (helm-migemo-mode)
 (helm-popup-tip-mode)
 (hidden-mode-line-mode)
 (highlight-numbers-mode)
 (highlight-parentheses-mode)
 (hl-line-mode)
 (hl-todo-mode)
 (hs-minor-mode)
 (ibuffer-auto-mode)
 (ido-everywhere)
 (isearch-mode)
 (jit-lock-debug-mode)
 (mail-abbrevs-mode)
 (menu-bar-mode)
 (mml-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (package-build-minor-mode)
 (page-break-lines-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-check-syntax-mode)
 (rainbow-delimiters-mode)
 (rectangle-mark-mode)
 (server-buffer-clients)
 (server-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (size-indication-mode)
 (smartparens-global-mode)
 (smartparens-global-strict-mode)
 (smooth-scrolling-mode)
 (spacemacs-centered-buffer-mode)
 (temp-buffer-resize-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (use-hard-newlines)
 (vc-parent-buffer)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (with-editor-mode)
 (yas-minor-mode))
```

**Comment by xificurC** [comment]
`(require racket/match)` solves this so I will close this issue.

How can I check what language is run in the REPL? Is there a way to set the REPL to launch a specific `#lang`? Like `racket` or `racket/base` or `typed/racket`

**Comment by greghendershott** [comment]
Thanks for the report!

The short answer is: Put `#lang desired-lang` in a `.rkt` file, and `racket-run` from that.

> I will open a new issue for this if you want me to

I think #110 already covers the feature request.

The main use case for the REPL is with a `.rkt` file buffer, from which you `racket-run`. The REPL runs in the namespace of a module (or submodule) of that file. The language is automatically what's on the `#lang` line (or lang position of a `module` form) in the file.

Although you _can_ use the REPL stand-alone, and it generally does work, that's not really intended or enthusiastically supported by me. Which is why #110 is still open. I've started to do it a couple times, but think, meh, someone could just put `#lang foo` in a `.rkt`. Adding this seems like low ROI. Maybe even negative ROI if it leads to bugs or follow-on FRs for something outside the main use case.

**Comment by xificurC** [comment]
> The main use case for the REPL is with a .rkt file buffer, from which you racket-run. The REPL runs in the namespace of a module (or submodule) of that file. The language is automatically what's on the #lang line (or lang position of a module form) in the file.

Ah, OK. I would recommend getting this reflected in the docstring, do you think that's a reasonable request? If yes I can throw up a PR or you can add it yourself, I'll let you decide.

**Comment by xificurC** [comment]
Hm, trying out the `#lang` way doesn't work here. Don't have much time today, will try to get more info on this today/tomorrow.

**Comment by xificurC** [comment]
I'm reopening as I'm unable to get this working. 
- I started a clean emacs with `emacs -q`,
- did only `(package-initialize)` and `(require 'racket-mode)`, 
- after that opened a clean file `test.rkt`, 
- typed in `#lang racket`, 
- ran `C-c C-z`,
- tried to use `match`, e.g. `(match 1 [1 1])`,
- got `match: undefined` and `cannot reference undefined identifier`

Copy-paste of `racket-bug-report`
```elisp
((emacs-version "24.5.1")
 (emacs-uptime "1 hour, 14 minutes, 52 seconds")
 (system-type gnu/linux)
 (major-mode racket-repl-mode)
 (racket--source-dir "/home/bubo/.emacs.d/elpa/racket-mode-20160213.904/")
 (racket-racket-program "racket")
 (racket-raco-program "raco")
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (blink-cursor-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-font-lock-mode)
 (line-number-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-mark-mode))
(disabled-minor-modes
 (abbrev-mode)
 (auto-fill-function)
 (buffer-read-only)
 (column-number-mode)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (defining-kbd-macro)
 (display-time-mode)
 (electric-layout-mode)
 (global-prettify-symbols-mode)
 (global-visual-line-mode)
 (hs-minor-mode)
 (ido-everywhere)
 (isearch-mode)
 (jit-lock-debug-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-check-syntax-mode)
 (sh-electric-here-document-mode)
 (size-indication-mode)
 (temp-buffer-resize-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode))
```

**Comment by greghendershott** [comment]
Instead of <kbd>C-c C-z</kbd>, type <kbd>C-c C-k</kbd> i.e.`M-x racket-run`.

If you do that from a `foo.rkt` buffer, you will see the REPL prompt change from just `>` (no particular file/module) to `file.rkt>`.  Now it will work.

<kbd>C-c C-z</kbd> is just a convenience for switching between a file buffer and a REPL.

---

> Ah, OK. I would recommend getting this reflected in the docstring, do you think that's a reasonable request? If yes I can throw up a PR or you can add it yourself, I'll let you decide.

I _think_ it's fairly clear from the README.md. But maybe not. And not everyone may see that (e.g. if they just install from MELPA). So I'll look at updating the doc string. To be clear, do you mean the one for the `racket-repl` command?

**Comment by xificurC** [comment]
Seems I can't even read anymore, you wrote `racket-run` before and I didn't notice. Sorry.

Re documentation - I actually couldn't find much about running the REPL. Maybe I'm just blind again though :) I see `racket-run` being mentioned in the completions section, key bindings and documentation but not really about running a buffer-dedicated REPL. For noobs like me it would be beneficial to add a short section or note in the `README`, such as

# REPL
To start the repl use <kbd>C-c C-k</kbd> which runs `racket-run`. This will start a REPL for your current buffer. To start a REPL without a dedicated buffer you can run `racket-repl`. Note that this will automatically start it in `#lang racket/base`. If you want to use a different `#lang` create a new buffer, put the `#lang` in and run `racket-run` from there (<kbd>C-c C-k</kbd>).


A note in the end of `racket-repl`'s docstring would be nice too (e.g. "If you want to run the REPL for you current buffer use `racket-run` instead.").

Thank you for your time and patience with me. I'll go code now ;) If you'd like me to open a PR for some of these suggestions just let me know. And if you don't like the suggestions feel free to disregard them, you're the boss :)
