### ISSUE TITLE
Feature request: fallback to scheme-indent-function 

### ISSUE THREAD

**Issue by tonyg** [greghendershott/racket-mode#219]
At the moment, `racket-indent-function` works just fine. However, I have a ton of `scheme-indent-function` definitions in various local variable sections stretching across a lot of old code. Would it be possible to use `racket-indent-function` first, if it's there, and fall back to `scheme-indent-function` if no `racket-indent-function` is defined for a symbol?

**Comment by greghendershott** [comment]
It is already supposed to do that -- see #60. Were you asking proactively, or, because you already tried but it's not in fact working for you?

**Comment by greghendershott** [comment]
Scratch that. Looking more carefully, I see that was removed later, in commit a2459f7. From the commit message, it seems I was trying to handle all `with-*` forms automatically in the same way as `def*` forms -- without the need to tediously specify each one. And, to handle them indented with `'defun` style not `1`. However the legacy `scheme-indent-function` kept insisting on `1`. So I removed support for that.

Maybe not the best rationale and decision.

Maybe I could have tried harder to preserve it. I can take another look at that now, I think.

**Comment by tonyg** [comment]
Ah, thank you, I didn't see #60.

Commit a2459f7 is interesting. I wonder if the fallback cascade could be `racket-indent-function` -> special cases -> `scheme-indent-function`, rather than `racket-indent-function` -> `scheme-indent-function` -> special cases, and whether that would address the problem?

Something like this, perhaps: https://github.com/greghendershott/racket-mode/commit/02c776e63efb58f5ae063fb6c5ad0144593ce6b5 (Apologies for the crudeness of it; I don't know elisp well)

**Comment by greghendershott** [comment]
Thanks for the suggestion!

My only concern is that the `cond` statement is already more complicated than I'd like.

Another idea would be to focus on the exact problem I had -- the half-dozen `with-*` indents introduced by `scheme-mode` itself. Ignore exactly those. Allow all else.

**Comment by greghendershott** [comment]
I think I'd like to go with that approach. I pushed a commit to a topic branch, `issue-219-scheme-indent`.

Although it passes my existing indentation tests, I don't have any tests (or time to add any) now for using `scheme-indent-function` values.

So I'll wait before merging to `master`, in case you'd like to try it first.

**Comment by tonyg** [comment]
I've tried it out, and it works perfectly for my old `scheme-indent-function` definitions. Thanks, Greg!
