### ISSUE TITLE
Completion in REPL uses symbols from first edited buffer

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/racket-mode#225]
As reported by @CSRaghunandan in #224 but I'm making a distinct issue for this, which is a bug.

> I seem to have a problem with completions in REPL again.

> Whenever i open a racket file and load it for the first time, the completions work fine in `racket-repl`, but if I open another file and run <kbd>C-c C-k</kbd> to load that file in `racket-repl`, there are no completions for the definitions of the second file. And it's the same if I open a third file and so on. I get completions only for the first file that I loaded.  Looks like`racket-repl` fails to update the symbols list after another file is loaded.

> Also, if I press <kbd>C-M-i</kbd> on any of the definitions of second file, it says `no matches`

**Comment by greghendershott** [comment]
I can reproduce this. I'm surprised I haven't noticed this. (I guess I mainly use completion in `racket-mode` (edit) buffers. When I use completion in `racket-repl-mode` I suppose it's for standard Racket identifiers that the files all happen to share.) I'm glad you noticed this!

In the `racket-mode` (edit not REPL) buffers, completion works as-expected for me. In fact, each buffer has its own cache of the completion symbols, in an Emacs buffer-local var. `racket-run` invalidates the current buffer's cache.

I think what is happening is that `racket-repl-mode` also has its own buffer-local copy of this var, and, `racket-run` is _not_ invalidating _that_ one. But I'll need to confirm, and, think about the best solution.

**Comment by greghendershott** [comment]
Update: I didn't have time to work on this for a few days. Then I did, but realized there's a similar issue for a `racket-mode` buffer that hasn't been `M-x racket-run` yet. So I'm taking some more time to think about this and try to solve it as thoroughly as I can.

**Comment by greghendershott** [comment]
Merged a commit to `master`. If you install from MELPA, keep in mind it may take the usual N hours before it refreshes there.

**Comment by CSRaghunandan** [comment]
The issue seems to be fixed now. The completions in REPL are working as expected. 
Thank you 👍
