### ISSUE TITLE
Emacs Port - Repl not interactive

### ISSUE THREAD

**Issue by tbrooke** [greghendershott/racket-mode#227]
I'm using Spacemacs - I upgraded to emacs 25.1 and had trouble with my fonts so I tried https://github.com/railwaycat/homebrew-emacsmacport and it looks beautiful except the repl in Racket mode doesn't work -- It evaluates the buffer but you can not interact with the repl within in the buffer

I'll post an issue with railwaycat also since it may be more relevant to his build of emacs -

**Comment by greghendershott** [comment]
That sounds... interesting.

1. Are you saying it worked fine for you in "vanilla/official" builds of 24.x and also in 25.1 -- but not in the railwaycat build of 25.1?

2. Can you please give me a super simple recipe of steps for "it"?  The actual commands or keys you're using?

3. Can you please `M-x racket-bug-report` and paste into a comment here?  (Details about settings and active minor modes might turn out to matter.)

---

p.s. Caveat: Unfortunately lately I've barely had time to keep up with maintaining racket-mode on plain Emacs -- much less testing with things I don't personally use such as spacemacs, and, alternative builds of Emacs. However if someone on the spacemacs and/or railwaycat side can help narrow it down for me, of course I'll take a look.

**Comment by tbrooke** [comment]
Sorry for being premature - I got it - I tested with homebrew emacs-plus - which is basically vanilla Emacs with some options and it works. Then I tested it on the railwaycat build of 25.1 which from my understanding was from a "carbon" port of Emacs. The railwaycat build has a much better interface on my Retina Mac. The fonts are crisp and the powerline stuff looks better - All my tests were with Spacemacs using hybrid mode which means I can use either evil mode or emacs mode 

The repl buffer does behave differently with railwaycat in that if you back space you can delete the prompt etc - which may have confused me since I didn't realize that it was still a buffer -  but new stuff will evaluate.

I do get the following error messages in the text buffer which is fixed with racket-run - I never got this previously

     Company: An error occurred in auto-begin

     Company: backend company-capf error "Completions not available until you ‘racket-run’ this buffer" with args (candidates define) 

So looks like Racket mode is good to go on all of the above - thanks for the good work

**Comment by greghendershott** [comment]
Glad to hear it's resolved.

> I do get the following error messages in the text buffer which is fixed with racket-run - I never got this previously ....

That's very recent, from fixing #225. It does explain the situation -- but a little aggressively.

With the vanilla Emacs completion, you wouldn't see this until you pressed a key like <kbd>TAB</kbd> to invoke completion -- and it would be presented in the echo area more like an advisory message.

Whereas with company-mode, it's going to happen when you simply pause typing -- and it's presented as "OMG error!". The presentation/UX is not ideal.
