### ISSUE TITLE
send buffer to repl broken after package upgrade?

### ISSUE THREAD

**Issue by jgarvin** [greghendershott/racket-mode#229]
When I try to send I get this:

```
Debugger entered--Lisp error: (invalid-function with-racket-repl-buffer)
  with-racket-repl-buffer(nil)
  racket--invalidate-completion-cache()
  racket--do-run(medium)
  racket-run(nil)
  call-interactively(racket-run nil nil)
  command-execute(racket-run)
```

Strangely using describe-function on with-racket-repl-buffer still gives the accurate description as expected.

Also just running racket-repl works.

**Comment by greghendershott** [comment]
Hmm. If it's not too inconvenient for you to try restarting Emacs, does that help?

`with-racket-repl-buffer` is a macro that is defined in `racket-repl.el`, added in commit 2dbceb0. In addition to working for me locally, [a full byte-compile succeeds](https://travis-ci.org/greghendershott/racket-mode/builds/162252136).

I wonder if the package update process did not result in a full re-eval and/or re-compile and you are running with stale state?

**Comment by jgarvin** [comment]
sorry for the false alarm, this ended up being one of 1000 problems I ran into after upgrading ;) after deleting all my packages and reinstalling it went away
