### ISSUE TITLE
racket-mode (version 20160923.851) Error starting racket REPL: make-vector: contract violation

### ISSUE THREAD

**Issue by cassc** [greghendershott/racket-mode#231]
With the sample code on racket site in emacs, 
```racket
#lang racket
;; Finds Racket sources in all subdirs
(for ([path (in-directory)])
  (printf "source file: ~a\n" path))
````
When I execute 'C-c C-k` or `racket-run`, I get the following error:

```
Welcome to Racket v6.1.
﻿> 
; make-vector: contract violation
;   expected: exact-nonnegative-integer?
;   given: -1175042080
```

**Comment by greghendershott** [comment]
That seems to be unique to Racket 6.0 and 6.1. I encountered [a similar error](https://travis-ci.org/greghendershott/racket-mode/jobs/165090912#L1351) recently, and have [a commit to fix it on a branch for an upcoming other feature](https://github.com/greghendershott/racket-mode/commit/a6b40c5c6be22f298187d0f3ebadb47c2d9923e0). I thought the error was related to other changes on that branch, and didn't realize anyone was experiencing it on `master`. (Maybe few people are using Racket 6.0 or 6.1.)

If you can easily upgrade to Racket 6.2 or newer, you should be all set. The commit will be there for everyone when I merge that branch to `master`, probably within a few days.

However if you can't easily upgrade to Racket 6.2 or newer, please let me know and I'll try to get that commit to `master` sooner?

**Comment by greghendershott** [comment]
Actually I'll cherry-pick that commit and make another change. Pushed to `issue-231` branch. Assuming tests pass on Travis CI, I'll merge to `master`.
