### ISSUE TITLE
racket-run should run main submodule

### ISSUE THREAD

**Issue by vkz** [greghendershott/racket-mode#232]
`main` and `test` submodules are special and **racket-mode** does a fantastic job handling `test`. Would be wonderful to also handle `main` as both **racket** executable and **DrRacket** do it. Example:

```racket
#lang racket

(module main racket
  (println "hi there"))

;; <F5> or C-c C-k to racket-run expect to print
;; "hi there"
```

Running this with `racket-run` should probably execute the body of `main` submodule. Atm one needs to explicitly `(require 'main)` to run it. IIUC this isn't a required behavior but a convenient convention that both **racket** and **DrRacket** provide as for instance [mentioned in the Guide](http://docs.racket-lang.org/guide/Module_Syntax.html#%28part._main-and-test%29). Something we can totally live without but it is on occasion useful to keep modules in one file as you develop.

(emacs-version "25.1.1")
running `racket-mode` built from commit `b6a7db7`

**Comment by greghendershott** [comment]
Unless I'm misunderstanding, it already does.

Awhile ago in commit 51d89c0 I changed `racket-run` to run whatever (sub)module point is within. And "enter" its namespace: You'll notice the REPL prompt change to reflect that.

As of that change, `racket-test` <kbd>C-c C-t</kbd> became not much more than a shortcut for the special case of `test` submodules.

**Comment by greghendershott** [comment]
If you're too lazy to move point within the `main` submodule and want a keystroke like the one for `test`? :grin:

You could try writing a tiny Elisp command -- probably `(racket--do-run racket-context-level (cons (buffer-file-name) 'main)` -- and bind key(s) to that.

Although I have the engine all over the garage floor for [this upcoming milestone](https://github.com/greghendershott/racket-mode/milestone/1) your command is likely to survive that change just fine. (The `racket--` double-hyphen prefix commands are "private", following the Elisp convention, and subject to change. But `racket--do-run` is not likely to change.)

**Comment by vkz** [comment]
Oh wow. Ok. Take it back. We have everything we need :)
