### ISSUE TITLE
with-racket-repl-buffer

### ISSUE THREAD

**Issue by acarrico** [greghendershott/racket-mode#236]
From irc:

(01:07:49 PM) acarrico: I'll try latest melpa on another machine to see if I just have a wacked env. or something...
(01:12:18 PM) acarrico: Installing 20161029.1105 ... yep. the file #lang racket\n"hello" gives me: Invalid function: with-racket-repl-buffer even on a different machine.

**Comment by greghendershott** [comment]
Can you please try to uninstall / exit Emacs / reinstall as described [here](https://github.com/greghendershott/racket-mode/issues/230#issuecomment-251122013)?

**Comment by acarrico** [comment]
Works for me. :) Weird. Stale macro expansion. I also deleted a bunch of old racket-mode's at the same time, so that was probably good. Sorry I didn't notice the existing issue.

**Comment by greghendershott** [comment]
Glad it's working. No worries. I just pushed commit 12399116a to hopefully alert more people up-front. Or at least give me a handy [link](https://github.com/greghendershott/racket-mode#update) to reuse. ;)
