### ISSUE TITLE
Can't load test submodule on latest master

### ISSUE THREAD

**Issue by david-christiansen** [greghendershott/racket-mode#238]
In the latest `racket-mode`, when I put the following in a buffer that's saved to a file called `new-test.rkt`:
```
#lang racket

(module+ test
  (define x 54))
```
and then `C-c C-t`, I get the following in my `*Racket REPL*` buffer:
```
; module-declared?: contract violation
;   expected: (or/c module-path? module-path-index? resolved-module-path?)
;   given: '(submod (submod #<path:new-test.rkt> test) configure-runtime)
```
Previously, it would put the REPL in the context of the test submodule.

**Comment by david-christiansen** [comment]
`M-x emacs-version RET` gives:
```
GNU Emacs 26.0.50.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.2) of 2016-10-30, unofficial emacs-snapshot build: http://emacs.secretsauce.net
```

**Comment by greghendershott** [comment]
Ugh, sorry; I'd tested this after making the command socket changes.

This seems to be from the tip commit 7b0b818 from #234.

```diff
modified   run.rkt
@@ -137,28 +137,28 @@
 (define (maybe-load-language-info path)
   ;; Load language-info (if any) and do configure-runtime.
   ;; Important for langs like Typed Racket.
   (define info (module->language-info path #t))
   (when info
     (define get-info ((dynamic-require (vector-ref info 0)
                                        (vector-ref info 1))
                       (vector-ref info 2)))
     (define configs (get-info 'configure-runtime '()))
     (for ([config (in-list configs)])
       ((dynamic-require (vector-ref config 0)
                         (vector-ref config 1))
-       (vector-ref config 2)))
-    (define cr-submod `(submod ,path configure-runtime))
-    (when (module-declared? cr-submod)
-      (dynamic-require cr-submod #f))))
+       (vector-ref config 2))))
+  (define cr-submod `(submod ,path configure-runtime))
+  (when (module-declared? cr-submod)
+    (dynamic-require cr-submod #f)))
```

@willghatch do you have any suggestions here?  One simple thing that occurs to me is to guard this in `(unless (list? path) ....)` (on the assumption that submodules will never have `configure-runtime` submodules?).  If you're unsure or unable to respond soon, I'll revert that commit for now.

**Comment by willghatch** [comment]
Sorry about that! I just made a new PR that fixes it. I was in a hurry to make it before my laptop battery died (which it now has). It works fine for submodules of submodules now, but I think the second match pattern is bad I realize after my rushed PR -- I think it should always make valid module paths, but they will just be the wrong path. I can fix that PR in a while once I can plug my laptop in.

On November 1, 2016 9:20:18 AM MDT, Greg Hendershott <notifications@github.com> wrote:
>Ugh, sorry; I'd tested this after making the command socket changes.
>
>This seems to be from the tip commit 7b0b818 from #234.
>
>```diff
>modified   run.rkt
>@@ -137,28 +137,28 @@
> (define (maybe-load-language-info path)
>   ;; Load language-info (if any) and do configure-runtime.
>   ;; Important for langs like Typed Racket.
>   (define info (module->language-info path #t))
>   (when info
>     (define get-info ((dynamic-require (vector-ref info 0)
>                                        (vector-ref info 1))
>                       (vector-ref info 2)))
>     (define configs (get-info 'configure-runtime '()))
>     (for ([config (in-list configs)])
>       ((dynamic-require (vector-ref config 0)
>                         (vector-ref config 1))
>-       (vector-ref config 2)))
>-    (define cr-submod `(submod ,path configure-runtime))
>-    (when (module-declared? cr-submod)
>-      (dynamic-require cr-submod #f))))
>+       (vector-ref config 2))))
>+  (define cr-submod `(submod ,path configure-runtime))
>+  (when (module-declared? cr-submod)
>+    (dynamic-require cr-submod #f)))
>```
>
>@willghatch do you have any suggestions here?  One simple thing that
>occurs to me is to guard this in `(unless (list? path) ....)` (on the
>assumption that submodules will never have `configure-runtime`
>submodules?).  If you're unsure or unable to respond soon, I'll revert
>that commit for now.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/greghendershott/racket-mode/issues/238#issuecomment-257594828

-- 
Sent from my pocket computer.  Please excuse the lint.

**Comment by david-christiansen** [comment]
I'll give the next MELPA build a shot. Thanks!

**Comment by greghendershott** [comment]
Note that for the fix to take effect, you'll need to restart the Racket REPL.  e.g. type `,exit` at the prompt, then `racket-run` again.

**Comment by david-christiansen** [comment]
I tend to restart Emacs after installing new MELPA stuff anyway :-)

**Comment by david-christiansen** [comment]
This is indeed fixed in the latest MELPA version.

**Comment by greghendershott** [comment]
Thanks again to @willghatch for helping out so quickly!
