### ISSUE TITLE
Alternate class indentation style

### ISSUE THREAD

**Issue by winny-** [greghendershott/racket-mode#240]
Is it possible to configure the alignment of `new` and `send`'s arguments, so they align with  actual arguments, not with the class or instance?

For example this is what happens when I type a snippet in racket-mode:

```racket
(new frame% [label "test"]
     [stretchable-width #f]
     [stretchable-height #f])
```

But I want this (without manual indentation):

```racket
(new frame% [label "test"]
            [stretchable-width #f]
            [stretchable-height #f])
```

**Comment by greghendershott** [comment]
No, but you could [set an Emacs property on `'new` and `'send` for `racket-indent-function` to use](https://github.com/greghendershott/racket-mode/blob/master/Reference.md#racket-indent-line), with a value of `1`, which would get you this:

```racket
(new a
  b
  c
  d)

(new a b
  c
  d)
```

By the way, the tradition AFAICT is that custom indentation is only for syntax (macros) -- not for plain functions. Both `new` and `send` _are_ syntax. But they're not syntax you created. So it _might_ be better to defer to how other people indent them.

**Comment by winny-** [comment]
The [documentation for Racket GUI](https://docs.racket-lang.org/gui/windowing-overview.html) uses this style extensively in code listings. The style used in Racket Reference is mixed, mostly with `send+` and `send*` examples with their actual arguments aligned (as opposed to aligned to the class or method).

Personally I believe it leads to cleaner code when using Racket's class system.

I did try the suggestion of `(puts 'new 'racket-indent-function 1)` and that appears to yield the same result as using the default indentation style.

Is there a way to configure this? If not, I could attempt to add this feature and make a PR, but no promises :)

**Comment by greghendershott** [comment]
Try `'defun`. (I'd edited my comment to fix that; sorry.)

I'd tried DrRacket quickly and didn't see it do special indent for these. I rarely use racket/class. It's possible I'm wrong about the idiom. I'll research more.

**Comment by winny-** [comment]
You're right about Dr Racket -- it doesn't appear to have a setting for this either. I see the `'defun` does the two-space indent. Good to know, though not exactly what I'm looking for. I'll look into this more as well. Thanks for the discussion!
