### ISSUE TITLE
prevent editing the prompt in racket-repl-mode

### ISSUE THREAD

**Issue by rntz** [greghendershott/racket-mode#245]
In `racket-repl-mode`, the prompt can be edited and moved into, which leads to some occasionally curious behavior. In Python's repl mode (for example), this doesn't happen. I think, but am not sure, that the reason why has to do with the `inhibit-line-move-field-capture` text property (and maybe some other related properties): http://emacs.stackexchange.com/questions/13592/how-does-comint-mode-override-beginning-of-line-behavior-i-want-same-functional

In any case, it would be nice if the prompt were uneditable and couldn't be moved into, at least not by accident. For example, `M-b` (`backward-word`) at the prompt moves the cursor backward into the prompt.

**Comment by greghendershott** [comment]
Making the prompt **read-only** is (IMHO) too strong. In a long running REPL session, I sometimes like to excise some of what's accumulated. It's nice to be able to mark part of the buffer and `kill-region`. But setting the prompt read-only makes this impossible: You get an error like `"kill-region: Text is read-only: #<buffer *the-repl-buffer-for-some-langs*>"`. (For instance I find this (mildly) annoying with CIDER's REPL for Clojure. At most I can <kbd>C-c C-o</kbd> items one by one.)

However I like the idea of merely **inhibiting motion** into the prompt text. That would avoid accidental editing. But it would still allow (I think) `kill-region` to kill the _entire_ prompt and other text.

**Comment by rntz** [comment]
That seems like a good distinction to me. I just don't want to be changing the prompt by accident when what I really wanted was to change the stuff I'm entering into it.

**Comment by greghendershott** [comment]
What I said about making the prompt read-only, isn't quite right. `comint-mode` supplies a `comint-kill-region` that lets you delete prompts.

So I think the simple/right thing to do is make the prompt read-only. I just want to figure out #115, first.

**Comment by greghendershott** [comment]
Reopened due to problem described in #259.

**Comment by jaseemabid** [comment]
@greghendershott Just in case you are working on the REPL, I'd like to point out that 'ENTER' wont work if there is trailing space in the command typed. This is slightly annoying, so I'll try to get a patch if I can figure out how to make it work.  :crossed_fingers:

**Comment by greghendershott** [comment]
@jaseemabid Thanks for pointing this out! See #313.
