### ISSUE TITLE
Auto-select command port

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/racket-mode#249]
As suggested by `rntz` and @zenspider on `#racket`, re problem that `specing` was having.

This would allow users to run more than one Racket REPL at a time (at least using two different instances of Emacs) and also allow me to `make test` without needing to exit a running REPL (to avoid a port conflict).

---

To do so:

We could flip things around to where Emacs accepts connections from the Racket process. (This works; [I'd actually experimented with both ways](https://github.com/greghendershott/racket-mode/commits/old-command-socket). I think I'd settled on Racket accepting just because it seemed more natural, it's the "server".)

We could use `make-network-process` with `t` for the port, then [`process-contact`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Process-Information.html#Process-Information) to learn the actual port, and pass that to the Racket process as command-line arg for it to use when `connect`-ing.

This would make the `racket-command-port` `defcustom` obsolete. Or maybe it now also allows a `t` value, meaning "any avail", and that's the default. (User could still specify a port number).

**Comment by greghendershott** [comment]
Will leave this open. Not planning to do anytime soon.

- The problem that "specing" was having resulted from them running two instances of Emacs. If that were a real/frequent use case, they could set `racket-command-port` to different values in each instance. Furthermore, subsequent convo in `#irc` suggested they don't really need/want this changed (just griping).

- I have other open issues on various projects that do seem to matter. To the extent I have time these days I should work on those, first.

**Comment by specing** [comment]
The real use-case here is "working" on multiple projects simultaneously. In my case that would be multiple independent homeworks for a computer science class.

**Comment by greghendershott** [comment]
Weeding some old open issues. This was done back in February 2020, as part of [changing how I/O is done with the back end](https://www.greghendershott.com/2020/02/the-big-switcheroo.html). Now command I/O is stdin/stdout with the back end process. The back end creates an "ephemeral" TCP listener (server) and reports that port number to the front end. The front end makes a connection for each REPL (supporting multiple REPLs).
