### ISSUE TITLE
`racket--in-repl-or-its-file-p' malfunctions on Windows

### ISSUE THREAD

**Issue by lsdsjy** [greghendershott/racket-mode#256]
I still got the error message `"Completion not available until you 'racket-run' this buffer"` after <kbd>C-c C-k</kbd>.

Checked the source file of racket-mode and found problem in `racket--in-repl-or-its-file-p`. 
At [racket-repl.el#L236](https://github.com/greghendershott/racket-mode/blob/3cd7ef6ad55a8968eada46fc8398dfc1e2ad8867/racket-repl.el#L236), `(buffer-file-name)` obtain path in the format of `"d:/path/to/file.rkt"` while `(racket-repl-file-name)` obtain `"d:\\path\\to\\file.rkt"`, which fails the predicate `racket--in-repl-or-its-file-p`, thus caused the error.

**Comment by greghendershott** [comment]
I don't have easy access to Windows at the moment.

I'm surprised Windows Emacs' `buffer-file-name` returns a Unix style path.

---

A possible fix would be for racket-mode's internal `path` command to return a Unix-style path, always.

This patch _might_ work:

```patch
modified   cmds.rkt
@@ -159,7 +159,7 @@
       [(info)            (info)]
       ;; These remaining commands are intended to be used by
       ;; racket-mode, only.
-      [(path)            (elisp-println path)]
+      [(path)            (elisp-println (unix-path-string path))]
       [(prompt)          (elisp-println (and (at-prompt?) (or path 'top)))]
       [(syms)            (syms)]
       [(def)             (def-loc (read))]
@@ -198,6 +198,10 @@
        ,cd <path>
        ,log <opts> ...}))
 
+(define (unix-path-string p)
+  (path->string
+   (apply build-path/convention-type (list* 'unix (explode-path p)))))
+
 ;;; run, top, info
 
 ;; Parameter-like interface, but we don't want thread-local. We do
```

Maybe someone could try this, before I'll have a chance to try it.

---

I suppose another approach would be for racket-mode's internal `path` command to continue returning the true pathname -- but do a slash-style-independent compare in Emacs Lisp.

**Comment by lsdsjy** [comment]
@greghendershott The first approach somehow doesn't work but the second approach does.

At `racket-repl.el` Line 231, I added an additional function call to `subst-char-in-string`, say
```(subst-char-in-string` ?\\ ?/ (racket--repl-command "path"))``` 
and that worked.

**Comment by greghendershott** [comment]
@lsdsjy Thank you for trying that. Is that work-around OK for you, for now? If so, I'd like wait until I can try myself, on Windows, before settling on how to fix this and pushing a commit.

**Comment by lsdsjy** [comment]
It’s OK for me. I appreciate your help and look forward to your fix.

**Comment by greghendershott** [comment]
@lsdsjy I was finally able to try on Windows, and pushed a commit to fix.

**Comment by lsdsjy** [comment]
@greghendershott Sincerely appreciate your work!
