### ISSUE TITLE
Text displayed after read-only prompt is wrongly read-only

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/racket-mode#259]
Given a file:

```racket
#lang racket/base
(log-fatal "foo")
```

<kbd>C-c C-k</kbd> it.  The REPL shows:

```
foo.rkt﻿> ; [fatal] foo
|
```

Where `|` represents point.

Normally you should be able to type e.g. `42` and hit <kbd>RET</kbd>. But attempting to type something displays `"Text is read-only"` in the echo area.

Same with:

```rkt
#lang racket/base
(thread (λ () (displayln "hi")))
```

In other words the issue arises when Racket writes the prompt, then writes more output on the same line as the prompt.

---

This seems to be due to `comint-mode` placing a `read-only` property with the value `'fence` on the newline before point.

---

This was introduced by commit cdf6583 to close #245. I might need to revert that commit, until/unless I can't figure out why `comint-mode` does this and how to avoid it.

**Comment by enjelbeteu** [comment]
`
#lang racket
(define n (read))
`
also read-only

**Comment by greghendershott** [comment]
@enjelbeteu Maybe I'm misunderstanding what you're describing -- the following interaction in the REPL works fine for me:

```
foo.rkt﻿> (define n (read))
12
foo.rkt﻿> n
12
foo.rkt﻿> 
```

What are you doing, that causes a read-only message?

**Comment by enjelbeteu** [comment]
@greghendershott
Given a file:
`#lang racket

(define n (read))
`
also cause read-only

**Comment by greghendershott** [comment]
I went down the `comint` rabbit hole for awhile but couldn't figure out how to work around its `'readonly` `'fence` thing.

I don't think I can spend more time on this now, so, I'm going to revert commit cdf6583 and reopen #245.
