### ISSUE TITLE
Support programs that import `racket/gui/base`

### ISSUE THREAD

**Issue by florence** [greghendershott/racket-mode#26]
If a program requires 'racket/gui/base' `racket-run' will fail if used multiple times, with the error: 

```
 ; cannot instantiate `racket/gui/base' a second time in the same process
```

Sometimes this even happens:

```
 ; cannot instantiate `racket/gui/base' a second time in the same process

> 
Process Racket REPL segmentation fault: 11
```

Although I can't quite nail down whats causing the segfault. It seems to only happen with (require redex).

**Comment by UberLambda** [comment]
Hi, it seems like the issue wasn't fixed on my setup.
I'm currently trying to run this snippet (via <kbd>C-C</kbd><kbd>C-K</kbd>):
```lang:racket
#lang planet neil/sicp

(* 3 4 5)
```

But when I do run it, this appears on the console:
```
; cannot instantiate `racket/gui/base' a second time in the same process
; Context:
;  /home/paolo/.racket/planet/300/6.1.1/cache/soegaard/sicp.plt/2/1/primitives.rkt:1:1 [traversing imports]
;  /home/paolo/.racket/planet/300/6.1.1/cache/soegaard/sicp.plt/2/1/painters.rkt:1:1 [traversing imports]
;  /home/paolo/.racket/planet/300/6.1.1/cache/soegaard/sicp.plt/2/1/sicp.rkt:1:1 [traversing imports]
;  /home/paolo/.racket/planet/300/6.1.1/cache/neil/sicp.plt/1/17/main.rkt:1:1 [traversing imports]
;  /home/paolo/sicp/sicp.rkt:1:1 [traversing imports]
```
Was this error intentional? It doesn't seem like so judging the previous commit messages.

**Comment by greghendershott** [comment]
I'm handling `racket/gui/base`, but not `scheme/gui/base` (these are very old Planet packages, which use the latter).

I thought `scheme/gui/base` was simply an alias for `racket/gui/base` these days, so it would be covered. Apparently I'm wrong and it's not that simple.

I think I'll open a fresh issue for that, as the comment thread on this issue is already very long,

**Comment by UberLambda** [comment]
Thanks!

**Comment by greghendershott** [comment]
@UberLambda I pushed a commit. (Mentioning here in case the @ mention on issue #133 didn't notify you.)
