### ISSUE TITLE
Don't need to provide both Racket and raco programs.

### ISSUE THREAD

**Issue by LeifAndersen** [greghendershott/racket-mode#263]
In your readme you say:

* racket-raco-program is the name or pathname of the Raco executable. This defaults to Raco.exe on Windows else raco.

I should point out that once you have the racket executable, you don't need to find the path to the raco executable. The command: `racket -l raco` is equivalent to just running `raco` directly.

**Comment by greghendershott** [comment]
Great point; I didn't realize that back then.

We can mark `racket-raco-program` as deprecated.

Also, maybe we can just entirely ignore its value, without confusing people -- on the assumption that no one is going to have set `racket-racket-program` to a different directory and/or different OS executable name style?

**Comment by LeifAndersen** [comment]
Either of those work.

Another thing you could do is (and I have no idea how hard this would be to do in elisp), is if `racket-raco-program` is not defined, then just get it from the `racket-racket-program`, otherwise get the one given to by the user.

Also, it might make sense to change the name to just `racket-program`, or `racket-executable`, and  leave the existing settings for backwards compatibility?
