### ISSUE TITLE
infinite loop when presented with an unmatched |#

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/racket-mode#280]
Mitchell Wand via Twitter https://twitter.com/mwand/status/909960172273127424

> @greghendershott #racketmode elpa/racket-mode-20170902.924/racket-mode.elc goes into an infinite loop when presented with an unmatched |#

**Comment by greghendershott** [comment]
Hmm actually I can't repro this with say:

```racket
#lang racket/base

|#
```

It doesn't hang while typing that, or, after visiting the file.

If I <kbd>C-c C-c</kbd> a.k.a. `M-x racket-run`, then the `*Racket REPL*` buffer says:

```
; /tmp/foo.rkt:3:0: read: unbalanced `|'
; Context:
;  /Applications/Racket_v6.10/collects/syntax/module-reader.rkt:186:17 body
;  /Applications/Racket_v6.10/collects/syntax/module-reader.rkt:183:2 wrap-internal
;  /Applications/Racket_v6.10/collects/racket/../syntax/module-reader.rkt:65:9 lang:read-syntax
; [Due to errors, REPL is just racket/base]
foo.rkt﻿> 
```

And the REPL is still alive.

---

Can you give me a hint how to repo?

**Comment by mwand** [comment]
Try it with the attached file.

I just ran it under Windows 10, with GNU Emacs 24.4.1 (i686-pc-mingw32) of
2014-10-24 on LEG570 .  It also failed on my other machine, which I think
is running Emacs 25.2 (also W10).

On Tue, Sep 19, 2017 at 12:21 PM, Greg Hendershott <notifications@github.com

**Comment by mwand** [comment]
Forgot to mention: all I had to do was visit this file, and emacs hung
completely-- I had to kill it from task manager.

**Comment by greghendershott** [comment]
> Try it with the attached file.

I don't see any file? I don't think the GitHub email interface accepts attachments. The GitHub web site does; could you use that (or Gist or whatever else you prefer)?

**Comment by mwand** [comment]
Here's a dropbox link.

https://www.dropbox.com/s/smu7vf9hw5m8yne/buggy.rkt?dl=0

**Comment by greghendershott** [comment]
Thanks! When I open that file

```racket
(define (foo x) x)

|#
```

in `GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2016-08-21` on macOS 10.11 everything is fine; no hang.

When I have a bit more time I'll try on Emacs 24.4 on macOS. (If I still can't repro it, then when I have a bigger block of time I'll try again 24.4 on Windows 10).

**Comment by mwand** [comment]
I get the same behavior with
GNU Emacs 25.2.1 (i686-w64-mingw32) of 2017-04-24

**Comment by greghendershott** [comment]
Hmm. Could you please `M-x racket-bug-report` and give me the `<details> .... </details>` portion?

**Comment by mwand** [comment]
Here you go:

<details>
```
((emacs-version "25.2.1")
 (emacs-uptime "44 seconds")
 (system-type windows-nt)
 (major-mode racket-mode)
 (racket--source-dir
"c:/Users/wand/AppData/Roaming/.emacs.d/elpa/racket-mode-20170902.924/")
 (racket-program "Racket.exe")
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-function)
 (auto-fill-mode)
 (auto-save-mode)
 (blink-cursor-mode)
 (column-number-mode)
 (display-time-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (hs-minor-mode)
 (line-number-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (save-place-mode)
 (show-paren-mode)
 (tooltip-mode)
 (transient-mark-mode))
(disabled-minor-modes
 (abbrev-mode)
 (buffer-read-only)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (defining-kbd-macro)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (global-prettify-symbols-mode)
 (global-visual-line-mode)
 (horizontal-scroll-bar-mode)
 (ido-everywhere)
 (isearch-mode)
 (jit-lock-debug-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-check-syntax-mode)
 (sh-electric-here-document-mode)
 (size-indication-mode)
 (temp-buffer-resize-mode)
 (tool-bar-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode))
```

**Comment by greghendershott** [comment]
For future reference the file at https://www.dropbox.com/s/smu7vf9hw5m8yne/buggy.rkt?dl=0 is:

```
(define (foo x) x)

|#

```

**Comment by greghendershott** [comment]
I'm doing "spring cleaning" and noticed this old open issue.

I was never able to reproduce this. I tried again, and still can't. :disappointed: 

I'm not sure what to do with it. Should I just close it? Do you still experience this? Are you even still using Racket Mode, all these years later?

**Comment by mwand** [comment]
Naw...   I've been teaching Software Engineering in Typescript since 2019
and haven't written any Racket since then (alas!).

Feel free to close it; I'll let you know if I run across it again.

Good luck with your Spring cleaning!

--Mitch

**Comment by greghendershott** [comment]
Thank you for the feedback; I hope eventually you're able to do more Racketeering!
