### ISSUE TITLE
Clarify differences with Geiser

### ISSUE THREAD

**Issue by thblt** [greghendershott/racket-mode#283]
This sentence:

> If you've used other Lisps and Schemes before, you might prefer Geiser, which is very sophisticated.

Has been on the README since the very beginning.  Is it still relevant, and if yes, could you please clarify the differences between the two, and why a user would choose one or the other?    

Thanks!

**Comment by greghendershott** [comment]
I recently simplified the README in commit 06edbb1. Now it simply mentions Geiser and Quack under "alternatives" (a section I've seen in other READMEs).

I don't think I ought to compare or recommend. Not even the self-deprecating comment in the README, before. It's understandable you'd read that and ask to hear more. I solved that by deleting it. :smile:

For awhile now I've provided [Reference.md](https://github.com/greghendershott/racket-mode/blob/master/Reference.md) as a way to see all the features and caveats (without needing to install racket-mode and <kbd>C-h f</kbd> to see doc strings one at a time).  I think that's enough from me, and I'll leave it to other people to do more.
