### ISSUE TITLE
paredit mode behaves differently in the racket repl concerning delimiters

### ISSUE THREAD

**Issue by jjackaman** [greghendershott/racket-mode#289]
Paredit doesn't behave as expected when using it from a racket repl, from paredit.el:

> ( inserts `()', leaving the point in the middle;
> ) moves the point over the next closing delimiter;

When typing ) In a racket repl, paredit inserts a new ) in addition of moving the point over to the next closing ).

For example, if you type:

`(define (foo))`

you end with:

`(define (foo)))`

**Comment by greghendershott** [comment]
I don't see that happen. Maybe it's related to something else you're using -- if you [do this](https://github.com/greghendershott/racket-mode/blob/master/CONTRIBUTING.md#reporting-bugs) I could take a look?

**Comment by jjackaman** [comment]
evil-mode was causing the behavior, disabling it for the repl allows paredit.el to work as expected.
