### ISSUE TITLE
racket-describe for place-channel-put

### ISSUE THREAD

**Issue by pmatos** [greghendershott/racket-mode#297]
I am slightly surprised that for some reason `C-c C-.` does not work for `place-channel-put`. What's special about it so that it doesn't work for this function? I tried for a few others including `make-parameter` and `struct` and had no problems obtaining the requested information.

**Comment by greghendershott** [comment]
Probably you need to `racket-run` the file at least once, first -- to make sure that `place-channel-put` becomes a known identifier (unlike say `struct` it is not provided by `racket/base`).

It works me in this simple example:

```
#lang racket
place-channel-put
```

When I:

1. `racket-run` <kbd>C-c C-c</kbd>
2. `racket-describe` <kbd>C-c C-.</kbd>

I do get a `*Racket Describe*` buffer:

```
procedure Provided from: racket/place, racket | Package: base

 (place-channel-put pch v) → void  
   pch : place-channel?  
   v : place-message-allowed?  
Sends a message v on channel pch. Since place channels are asynchronous,
place-channel-put calls are non-blocking.

See place-message-allowed? form information on automatic coercions in v, such as
converting a mutable string to an immutable string.

Definition   Documentation in Browser          [q]uit
```

**Comment by pmatos** [comment]
@greghendershott That's correct. In that case it does work. The downside of that is that you need a syntactically correct buffer, otherwise the repl will fail to load the buffer and the information is still not available.

**Comment by greghendershott** [comment]
That's why in August I added commit 2f13e68 to close issue #272. Commit message:

> Try to eval "skeleton" of file with error
> 
> The resulting REPL has a namespace with bindings from module
> languages, requires, and definitions. That way things like completion
> and racket-describe are more likely to work while you are editing the
> file to fix the error.
> 
> Closes #272.

---

With that, then this...

```
#lang racket
(+ x 1)
place-channel-put
```

...will display this...

```
; /tmp/foo.rkt:2:3: x: unbound identifier in module
;   in: x
; [Due to errors, REPL is just module language, requires, and stub definitions]
```

...and for many identifiers in the file, various things work:

- completion
- `racket-visit-definition`
- `racket-describe`

**Comment by greghendershott** [comment]
Not impressed? :smile:

I don't see a clear to-do, so I'm going to close, but you're welcome to reopen.

**Comment by pmatos** [comment]
Sorry @greghendershott . I am not very active during the weekends. I am certainly impressed and happy with the solution although I did notice that when it's the case of a missing parens, the REPL always defaults to `racket/base`:
```
#lang racket
(define foo hello
```

shows:
```
; /home/pmatos/tmp/test.rkt:3:0: read: expected a `)' to close `('
; Context:
;  /home/pmatos/installs/racket-6.12/collects/syntax/module-reader.rkt:186:17 body
;  /home/pmatos/installs/racket-6.12/collects/syntax/module-reader.rkt:183:2 wrap-internal
;  /home/pmatos/installs/racket-6.12/collects/racket/../syntax/module-reader.rkt:65:9 lang:read-syntax
; [Due to errors, REPL is just racket/base]
```

**Comment by greghendershott** [comment]
Ah. Yes, that's interesting. (I hadn't noticed, because paredit.)

So there could be a third attempt -- where it at least uses the textually apparent `#lang`. That would be useful.

(It could even try to gather textually apparent `require` statements... but I think that's probably going too far.)

**Comment by pmatos** [comment]
That would certainly be interesting. I don't think it's too far trying to use texturally apparent `(require racket/...)`, given that the racket style guide recommends starting with `#lang racket/base` as much as possible.

**Comment by greghendershott** [comment]
If the missing paren is among the `require` forms, then "apparent" could be complicated due to `require` sub-forms like `prefix-in`, `multi-in`, and so on.

That's why I'm not sure how far to take this -- is it maybe too much work and corner cases for a benefit that maybe isn't too big? (But I might take a PR attempting this -- if the contributor would stick around indefinitely to help fix any follow-on issues.)

**Comment by pmatos** [comment]
I could try to help if necessary. However, not sure how you would go about this. How do you read the file in emacs to know which lang it is in and find each require? Is this a simple textual search (I guess it has to be given the racket might be ill-formed)?
