### ISSUE TITLE
Pipes in strings confuse syntax highlighting

### ISSUE THREAD

**Issue by MichaelBurge** [greghendershott/racket-mode#298]
The following program prints the symbol |.

```scheme
#lang racket

(define x (begin "|" '\|))

(println x)
```

However, racket-mode highlights everything after the first | as if it were in a string.

**Comment by greghendershott** [comment]
You're right. It's probably a consequence of racket-mode supporting Racket pipe-delimited identifiers and symbols, such as:

```racket
(define |identifier with spaces| '|symbol with spaces|)
|identifier with spaces|
```

[Looks like GitHub's new syntax highlighter doesn't support this. The old one based on Pygments did.]

I'll try to untangle this when I have some time.

**Comment by vkz** [comment]
As a workaround you could replace "|" in your Racket code with "\x7c" and it works. Hat tip @AlexKnauth
