### ISSUE TITLE
Function for sending string to repl

### ISSUE THREAD

**Issue by EliasCarl** [greghendershott/racket-mode#300]
Hi, first of all thanks for a great package.

As a complete beginner to elisp (and racket) I was trying to extend the following function in lispy-mode https://github.com/abo-abo/lispy/blob/58a3f21a1946768bb6d20a6694d37d749cb136ce/lispy.el#L6429. I could get it to work by copying racket--send-region-to-repl and modify it to take a string instead and give that function to lispy--eval. Just wondering if there's already such a "send-string-to-repl" function to use instead of my ugly copy & paste solution.

**Comment by greghendershott** [comment]
Hi! I glanced at this when you submitted, saw it didn't seem to be an urgent bug, and... forgot to loop back and make some reply. Sorry!

The copy/paste is the least-worst available solution.

You could almost just do `(comint-send-string (racket--get-repl-buffer-process) "(+ 1 1)\n")` -- the `\n` is important -- if you don't care about details like checking for a REPL and starting one if necessary.

**Comment by xuchunyang** [comment]
> I could get it to work by copying racket--send-region-to-repl and modify it to take a string instead and give that function to lispy--eval.

That's not enough, you still need to find a way to capture the return value, which is required by lispy--eval, but not provided by racket--send-region-to-repl.

**Comment by greghendershott** [comment]
Ah, OK. I don't use lispy myself and unfortunately currently don't have time to learn about it.

I did take a very quick look at its repo. I notice that its support for e.g. geiser uses some "private" functions: `geiser--`_name_.[^1] This seems non-ideal.

So, if anyone wanted to make a PR to lispy to add racket-mode support, I do have a suggestion: First make a PR here to add a `racket-lispy-eval` public "API" function, and have lispy use _that_. 

(Of course the implementation of `racket-lispy-eval` may use whatever private racket-mode functions it needs.)

---

[^1]: Emacs Lisp doesn't have modules or namespaces, so, `mode--`_name_ is a convention meaning "private" as opposed to `mode-`_name_ meaning "public". Two vs. one hyphen.

**Comment by xuchunyang** [comment]
I don't use lispy either. But I am interested because I would like racket-mode's `C-x C-e` to be able to show the result in echo area, just like `C-x C-e` in emacs-lisp-mode.

BTW, for python, there is a `python-shell-send-string-no-output`

```
(python-shell-send-string-no-output "2**10\n")
;; => "1024"
```

**Comment by greghendershott** [comment]
I see.

The status quo <kbd>C-x C-e</kbd> is bound to `racket-send-last-sexp`, which essentially just "types the expression into the REPL for you", and, relies on the REPL's printing of values. [I like having a REPL buffer visible, and it's similar to DrRacket, so of course I like the status quo just fine. :smile:.]

To do what you'd prefer:

We could add a `racket-eval-last-sexp`, which prints the value(s) in the echo area. (Values plural. Unlike Elisp, Racket functions can return multiple values.)

I imagine we should add an `eval` command in `cmds.rkt`. It should use `call-with-values` to pack the values into a `list`. Something like:

```racket
(call-with-values (λ ()
                    (eval (read (open-input-string user-input))
                          repl-namespace))
                  list)
```

That eval command could be used by the Elisp `racket-eval-last-sexp` via `racket--repl-command` (via the TCP command channel) to get the `list` of values. Then unpack the values to the echo area.  When multiple values, probably each one on its own line, much like the REPL does?

Note: If the evaluated expression has side effects like `display`-ing to stdout, should that appear in the REPL (by default it will) or go nowhere?

**Comment by xuchunyang** [comment]
I wrote [`racket-shell-send-string-no-output`](https://github.com/xuchunyang/emacs.d/blob/46d9803339d8fc403027c5770d0b9dd957391b27/lisp/racket-ext.el#L39), it simply captures the output to the REPL

```elisp
(racket-shell-send-string-no-output
 "(begin (displayln (version)) (values 1 2))\n")

;; =>

"6.12
1
2"


(racket-shell-send-string-no-output "(define x 42)\n")
;; => ""
```
it seems unlike Emacs Lisp, not every sexp in Racket returns value.
