### ISSUE TITLE
Invoking a function beginning with "lambda" highlights it as a keyword

### ISSUE THREAD

**Issue by MichaelBurge** [greghendershott/racket-mode#304]
In the below example

```scheme
#lang racket

(define (lambda-num-arguments x) 5)
(lambda-num-arguments #f)
```
, the application of `lambda-num-arguments` has the "lambda" portion highlighted as a keyword.

The expected behavior is that no portion of `lambda-num-arguments` is highlighted.

**Comment by greghendershott** [comment]
Thanks for the report! I was able to repro. Commit 48f0cb9 fixes it for me.
