### ISSUE TITLE
#lang datalog doesn't work in racket-repl-mode buffer

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/racket-mode#305]
On `#racket` IRC @odanoburu reports that `#lang datalog` works fine in DrRacket, a DrRacket interactions REPL, and in racket-mode buffer --- but _not_ in racket-repl-mode.

When I try, entering something like `path(X, Y)?`, after I hit <kbd>enter</kbd>, racket-repl-mode just sits there -- as when a complete s-expr hasn't been entered yet, which of course it's not, it's datalog.

Possibly also related to [this repl-submit business for DrRacket](https://github.com/racket/datalog/blob/master/lang/reader.rkt#L14-L15)??

---

Even after fixing that, there still might be a problem. Because: When I try in plain command-line `racket`, <kbd>ENTER</kbd> does get a result but it's an error.

```
#lang datalog

edge(a, b). edge(b, c). edge(c, d). edge(d, a).
path(X, Y) :- edge(X, Y).
path(X, Y) :- edge(X, Z), path(Z, Y).

path(X, Y)?
```

```
$ racket -qit datalog.rkt
Welcome to Racket v6.10.
path(a, a).
path(a, d).
path(a, c).
path(a, b).
path(b, a).
path(b, d).
path(b, c).
path(b, b).
path(c, a).
path(c, d).
path(c, c).
path(c, b).
path(d, b).
path(d, c).
path(d, d).
path(d, a).
> path(X, Y)?
path: undefined;
 cannot reference undefined identifier
  context...:
   /Applications/Racket_v6.10/collects/racket/private/misc.rkt:88:7
> stdin::7: unquote: not in quasiquote
  in: (unquote Y)
  context...:
   /Applications/Racket_v6.10/collects/racket/private/misc.rkt:88:7
> ?: undefined;
 cannot reference undefined identifier
  context...:
   /Applications/Racket_v6.10/collects/racket/private/misc.rkt:88:7
```

Possibly this is related to a problem with `#%top-interaction`?? Or [not](https://github.com/racket/datalog/issues/9)?

**Comment by odanoburu** [comment]
using s-expression datalog (i.e., `#lang racket` and `(require datalog)`) is a possible workaround.

**Comment by greghendershott** [comment]
To expand on the first sub-issue -- hitting <kbd>ENTER</kbd> does nothing and "hangs the REPL": 

Currently racket-repl-mode binds <kbd>RET</kbd> to `racket-repl-eval-or-newline-and-indent`. This tries to be "smart" and until there's a complete sexpr, don't `comint-send-input` yet, just `newline-and-indent`.

Obviously that's not going to work with a non-sexpr lang.

Options:

1. Disable it completely.

2. Make it an Emacs variable, `t`/on by default. People could toggle it off when using a non-sexpr lang. (They could even use file-local variables to toggle it per-file.)

3. "Ideally" use the [`repl-submit` interface that DrRacket supplies](https://docs.racket-lang.org/tools/drracket_modes.html). But. This is one of those `#lang` features that works for any IDE so long as the IDE is DrRacket; it assumes DrRacket GUI is running. The contract is `repl-submit : (-> (is-a?/c drracket:rep:text%) number? boolean?)`. For some reason Emacs doesn't use a `drracket:rep:text%` interactions editor -- silly rabit. Is there some Rube Goldberg way for the racket-mode backend Racket code to simulate one from the Emacs buffer text... probably... eek?

**Comment by greghendershott** [comment]
Re the second sub-issue -- `#lang datalog` doesn't work in a plain command-line `racket` REPL -- [it looks like this is just not supported currently by `#lang datalog`](https://github.com/racket/datalog/issues/9#issuecomment-398369738).

As a result, although I'll leave this issue open, it looks like I won't be able to fix it fully.

---

I suppose I _could_ fix the portion about <kbd>ENTER</kbd> not working for non-s-expressions. But I'd prefer to handle that on-demand -- if/when someone has a specific non-sexpr `#lang` that does work in plain command-line `racket` -- so fixing the bug would actually someone and the fix would get exercised in the real world.

**Comment by greghendershott** [comment]
Before I wrote:

> "Ideally" use the [`repl-submit` interface that DrRacket supplies](https://docs.racket-lang.org/tools/drracket_modes.html). But. This is one of those `#lang` features that works for any IDE so long as the IDE is DrRacket; it assumes DrRacket GUI is running. The contract is `repl-submit : (-> (is-a?/c drracket:rep:text%) number? boolean?)`. For some reason Emacs doesn't use a `drracket:rep:text%` interactions editor -- silly rabbit. Is there some Rube Goldberg way for the racket-mode backend Racket code to simulate one from the Emacs buffer text... probably... eek?

Actually that seems to be the wrong documentation. The [`'drracket:submit-predicate`](https://docs.racket-lang.org/tools/lang-languages-customization.html#(part._.R.E.P.L_.Submit_.Predicate)) -- supplied by the `get-info` function obtained via `module->language-info` or `read-language` -- works with a simple `input-port?`

That would be non-crazy to attempt.

**Comment by greghendershott** [comment]
Re-testing I can no longer reproduce this, as a result of commit 2522488 from a few months ago, which  redesigns REPL I/O. It works regardless of whether the edit buffer associated with the REPL uses `racket-mode` or the new `racket-hash-lang-mode`.
