### ISSUE TITLE
The racket-command process outputs Emacs Lisp code?

### ISSUE THREAD

**Issue by xuchunyang** [greghendershott/racket-mode#315]
Otherwise, this is very weird:

https://github.com/greghendershott/racket-mode/blob/0f75097771a8ad9b9356c915ba877353aff1e7f6/racket-repl.el#L286

Maybe you intend to use only `read`? If you can make sure the data passed to Emacs can recognized the Emacs Lisp reader. Otherwise, one way to exchange data between two languages is JSON.

**Comment by greghendershott** [comment]
The back-end sends command responses [as Emacs Lisp s-expressions](https://github.com/greghendershott/racket-mode/blob/3e8ff8e24b61fdd975d41d0ebc043b88332985e1/cmds.rkt#L384-L405).

By default Racket prints things like `(list 1)` as `'(1)` -- which Elisp `read`s as `(quote (1))`. The Elisp front-end uses `eval` to "consume the quote".

[Instead? Probably the Racket back-end could `parameterize` `print-as-expression` to `#f`, and the Elisp side not use `eval`.]

**Comment by xuchunyang** [comment]
> parameterize print-as-expression to #f

Or use `write`.
