### ISSUE TITLE
melpa racket-mode causes emacs to become unresponsive with 100% CPU

### ISSUE THREAD

**Issue by bhrgunatha** [greghendershott/racket-mode#318]
`emacs`: 26.1
`racket-mode`: from melpa - installed to `racket-mode-20180805.227` from commit  2549a697044235c860a11d124d7755bf2aeb2e05  

I don't think it's related to #280 - I don't use multi-line comments. When this first started I could reliably cause the hang by simply typing into a new file:
```
#lang racket/base 
(de|)
```
I couldn't even get to the "f" in `define` - I'm using `paredit` so the closing paren is automatic. Now though after re-installing `racket-mode` and restarting `emacs` (a few times), it's less predictable, but still seems to be inevitable.

`racket-bug-report` output:
 
<details><pre>
((emacs-version "26.1")
 (emacs-uptime "32 seconds")
 (system-type gnu/linux)
 (major-mode racket-mode)
 (racket--source-dir "/home/bhrgunatha/.emacs.d/.cask/26.1/elpa/racket-mode-20180805.227/")
 (racket-program "racket")
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (company-mode)
 (display-line-numbers-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (flx-ido-mode)
 (font-lock-mode)
 (global-company-mode)
 (global-display-line-numbers-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (global-hl-line-mode)
 (global-visual-line-mode)
 (hs-minor-mode)
 (ido-everywhere)
 (ido-vertical-mode)
 (line-number-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (paredit-mode)
 (pcre-mode)
 (rainbow-delimiters-mode)
 (show-paren-mode)
 (tooltip-mode)
 (transient-mark-mode)
 (visual-line-mode)
 (yas-global-mode)
 (yas-minor-mode))
(disabled-minor-modes
 (abbrev-mode)
 (auto-fill-function)
 (auto-save-visited-mode)
 (blink-cursor-mode)
 (buffer-read-only)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (company-search-mode)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (defining-kbd-macro)
 (display-time-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-pair-mode)
 (electric-quote-mode)
 (global-prettify-symbols-mode)
 (hl-line-mode)
 (horizontal-scroll-bar-mode)
 (isearch-mode)
 (jit-lock-debug-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (package-build-minor-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-check-syntax-mode)
 (rxt--read-pcre-mode)
 (rxt-global-mode)
 (rxt-mode)
 (server-mode)
 (sh-electric-here-document-mode)
 (size-indication-mode)
 (temp-buffer-resize-mode)
 (tool-bar-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (window-divider-mode)
 (xref-etags-mode))
</pre></details>

**Comment by bhrgunatha** [comment]
Well that's a good starting point, thanks. 

I can't find a definite way to trigger the problem though, so I'll try a manual `git bisect` to see if I can narrow it down.

**Comment by bhrgunatha** [comment]
It does seem to be completions that are causing the hang. 
I haven't tried to automate this, but I managed to do some manual testing and on my machine the bug first appears with commit  b44e008c9b4389a9370a58ead3b197077c9e8766 

Steps to reproduce:  
1. `killall emacs`  
1. `git checkout b44e008`   
1. `make clean && make compile`   
1. `cp *.{rkt,el,elc} /home/bhrgunatha/.emacs.d/.cask/26.1/elpa/racket-mode-20180805.227/`    
1. Rename the attached file tesseract.txt  to tesseract.rkt and visit it.  
1. `C-c C-c` to load it in the REPL - faile due to an error  
1. Go to the 2nd line and try to type `(define rotated-chars (make-hash))`  

Hangs after typing `(de` 

The commit before that seems to be fine with showing and using completions and the REPL always seems to have completions working. 

I understand this is not a clean test - that manual copy of the files is suspect but I need to keep the `racket-mode-pkg.el` and it **does** overwrite all the existing files and it was good enough to replicate the error. 


[tesseract.txt](https://github.com/greghendershott/racket-mode/files/2278183/tesseract.txt)

**Comment by greghendershott** [comment]
Thank you for the detailed report. I just got back from a week away from a real computer, so, I should be able to look at this soon.

**Comment by greghendershott** [comment]
I followed your recipe using commit 2549a69 which you got from MELPA. (It's still my most-recent commit locally.)

I used `GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-30`.

Unfortunately I can't reproduce the problem. So let's investigate more please:

1. With the `tesseract.rkt` as the current buffer, please <kbd>C-h v</kbd>, type `eldoc-documentation-function` and press <kbd>RET</kbd>.  Is the value `nil`?

2. As a new step 6.5, what happens if you <kbd>M-x company-mode</kbd> to disable it, then do step 7?
  - If it doesn't hang and you can type <kbd>f</kbd>:  What happens if you then type <kbd>C-M-i</kbd> for the plain old non-company completion?  Does _that_ hang, or, do you see completion candidates in a `*Completions*` buffer?  (Or does something else happen?)

(I tried both with company-mode enabled and disabled, no problem either way. But if it behaves differently one way, for you, maybe that's a helpful clue for me.)

Thanks!

**Comment by lockie** [comment]
Got same problem here, Emacs with racket-mode (spacemacs to be precise) occasionally randomly hangs when typing in .rkt buffer. I was able to catch it when profiling, here's profiler report: https://pastebin.com/NUnFutKn (I've let it to be stuck for about 20 minutes).

**Comment by lockie** [comment]
Also here's my `racket-bug-report`: https://pastebin.com/4kzLbB4d

**Comment by greghendershott** [comment]
@lockie Thanks! The profile report shows it stuck at `racket--cmd/await`, which is:

```elisp
(defun racket--cmd/await (command-sexpr)
  "Send COMMAND-SEXPR. Await and return an 'ok response value, or raise `error'."
  (let* ((awaiting 'RACKET-REPL-AWAITING)
         (response awaiting))
    (racket--cmd/async-raw command-sexpr
                           (lambda (v) (setq response v)))
    (with-timeout (racket-command-timeout
                   (error "racket-command process timeout"))
      (while (eq response awaiting)
        (sit-for 0.1))
      (pcase response
        (`(ok ,v)    v)
        (`(error ,m) (error "%s" m))
        (v           (error "Unknown command response: %S" v))))))
```

I'm confused how it could be stuck for 20 minutes (!) -- the default value of `racket-command-timeout` is just 10 seconds. After which, it should `error` all the way out of the call chain from company-mode.

Of course, it shouldn't take even 10 seconds. I'm just startled and wondering what else is wrong about my mental model of what's happening here.

**Comment by lockie** [comment]
@greghendershott Yeah, I've also tracked the problem to this point and wasn't sure where to go next. Could it be some problem in `racket--cmd/async-raw` implementation?..

**Comment by greghendershott** [comment]
@lockie I won't rule out any cause, yet. The async command approach is only about a month old. Although I've used it heavily myself, reliably, it's possible my usage pattern and/or config don't intersect some edge case.

Could I ask you to try the same things I asked @bhrgunatha [above](https://github.com/greghendershott/racket-mode/issues/318#issuecomment-412136550)? (Check the value of `eldoc-documentation-function`, and, try with company-mode disabled at least in the racket buffer?)

**Comment by bhrgunatha** [comment]
After resetting to commit 2549a69 : 
I can't trigger it reliably any more but it's there (and in the REPL too)

`eldoc-documentation-function : nil` 

I set `company-mode` minimum prefix to 2 chars and it **is** consistently hanging after trying to type a 3rd character. That part has **always** been consistent and makes me think it *is* related. 
My `company-mode` settings:

    company-idle-delay 0.1
    company-minimum-prefix-length 2
    company-tooltip-align-annotations t
    company-show-numbers t
    company-require-match nil
  
I've turned `company-mode` off for all `racket-mode` buffers for the time being and I'll see how that goes.

**Comment by greghendershott** [comment]
Good news: I got the problem to happen while using company-mode! Eventually after a lot of <kbd>C-g</kbd> I regained control.

Bad news: I didn't have debug-on-quit enabled to see a trace. Since enabling it, I haven't been able to make it happen again. I love Heisenbugs.

@bhrgunatha Thanks for those company-mode settings! I'll try them now.

**Comment by greghendershott** [comment]
(I have a guess that (at least part of) the problem is `racket--cmd/await` using `sit-for` when instead it ought to use `accept-process-output`. But I don't have a crisp explanation why that hasn't mattered for me using standard completion with no freezes for the last month, but would matter for company-mode. So, I definitely want to get some recipe to repro this consistently.)

**Comment by greghendershott** [comment]
@bhrgunatha Using your settings (thanks again!!) for me it is not 100% reliable to get the problem.

However I got a freeze to occur pretty quickly, using a buffer that is simply `#lang racket/base` and nothing else -- and, not even any <kbd>C-c C-c</kbd> `racket-run` first.

I typed "with-handlers" blah something blah, quickly, hit backspace quickly a few times, and boom -- frozen.

Numerous <kbd>C-g</kbd>s didn't seem to help. Until I mindlessly started doing some <kbd>C-b</kbd>s to back up --  _then_ it unfroze. The debug-on-quit handler never kicked in (?!).

Looking in the `*Messages*` buffer, I saw the line `Error in post-command-hook (company-post-command): (quit)` and then `Quit`.

Trying again in the same buffer, company-mode acted like it was disabled.  But if I re-visit the file, clean slate, company-mode works again and I can reproduce the steps and results above.

---

So. I _think_ I can conclude:

1. This actually has nothing to do with `racket--cmd/await` (with command requests and responses between Emacs and the Racket back end).  When the buffer hasn't been `racket-run` yet, the completion candidates are taken from font-lock keywords.

2. I should probably zero in on the completion-at-point function racket-mode supplies.

**Comment by bhrgunatha** [comment]
I can't get _anything_ to trigger it reliably, it's very transient.  
 I'm in awe of your `C-g` mashing skills too - I couldn't reel it back in even with `ESC ESC ESC`

**Comment by greghendershott** [comment]
OK, when I wrote

> 1. This actually has nothing to do with `racket--cmd/await` (with command requests and responses between Emacs and the Racket back end). When the buffer hasn't been `racket-run` yet, the completion candidates are taken from font-lock keywords.

I was wrong. In this scenario, there _is_ a command sent using `racket--cmd/await`. It is to get the name of the file that the REPL is running:

```elisp
  (unless racket--namespace-symbols
    (when (racket--in-repl-or-its-file-p) ;; <-- this issues a command
      (setq racket--namespace-symbols
            (list (racket--cmd/await '(syms))))))
```

So when I wrote this:

> (I have a guess that (at least part of) the problem is `racket--cmd/await` using `sit-for` when instead it ought to use `accept-process-output`. But I don't have a crisp explanation why that hasn't mattered for me using standard completion with no freezes for the last month, but would matter for company-mode. So, I definitely want to get some recipe to repro this consistently.)

It was correct. Thanks to you @bhrgunatha I have a reliable recipe. I've confirmed that using `sit-for` elicits the freeze but using `accept-process-output` does not.

```diff
 (defun racket--cmd/await (command-sexpr)
   "Send COMMAND-SEXPR. Await and return an 'ok response value, or raise `error'."
   (let* ((awaiting 'RACKET-REPL-AWAITING)
          (response awaiting))
     (racket--cmd/async-raw command-sexpr
                            (lambda (v) (setq response v)))
     (with-timeout (racket-command-timeout
                    (error "racket-command process timeout"))
       (while (eq response awaiting)
-        (sit-for 0.1))
+        (accept-process-output nil 0.1))
       (pcase response
         (`(ok ,v)    v)
         (`(error ,m) (error "%s" m))
         (v           (error "Unknown command response: %S" v))))))

```

---

I could rush to push a commit, but if it's OK with you I'd like to ponder a bit and make sure I understand why, consider whether that means I should review other code, etc.

If anyone would like to try this fix locally, it's pretty easy to hack this live in Emacs:

1. `M-x find-function` and enter `racket--cmd/await`.
2. Replace `(sit-for 0.1)` with `(accept-process-output nil 0.1)` (just like in the diff above).
3. With point still on that line, press <kbd>C-M-x</kbd> to redefine the function with that change.

@bhrgunatha and @lockie in particular if you'd like to try this and let me know if it works, that would be great.

**Comment by bhrgunatha** [comment]
We have a fix that we can apply locally; **you're** the best one to make decisions about _how_ to release it. 

I applied the diff and byte compiled it - `C-u 0 M-x byte-recompile-directory` to update the `.elc` file. I'll report back if it re-appears.

Thank you for taking time out of your weekend to look at this and a bigger thanks for all your hard work on `racket-mode`.

**Comment by greghendershott** [comment]
Thank you for working so hard on the bug report and experiments and follow-ups. Seriously -- it's a huge help!

After thinking about it more, I feel I do understand why the change fixes the problem that I was able to reproduce. So I will probably go ahead and merge that to master/MELPA soon.

Of course, I can't be 100.0% sure I fixed the exact same issue that you were experiencing. So if the problem happens again, despite the patch, please do let me know. Thanks again!

**Comment by lockie** [comment]
I've updated the package from melpa and just had two loveliest hour-long racket coding sessions with no hangs whatsoever. Thanks for your hard work @greghendershott !

**Comment by greghendershott** [comment]
@lockie I'm happy and relieved to hear that. Thanks for your help with the extra details like the profiler report!
