### ISSUE TITLE
In else clauses of match expressions, else highlights as a keyword

### ISSUE THREAD

**Issue by jasonhemann** [greghendershott/racket-mode#320]
At least using racket-mode v. 20180805.227 from MELPA in `#lang racket`, `else` in an`else` clause of a `match` expression highlights as though it's a keyword.

**Comment by greghendershott** [comment]
Thanks for the report.

This is actually working as-intended, for the foreseeable future. To make sure font-lock (Emacs' jargon for syntax highlighting) is fast enough, "keywords" and "builtins" are identified textually via regular expressions. The list and the rationale is [described here](https://github.com/greghendershott/racket-mode/blob/master/keywords.rkt#L5-L36).

Looking forward:

- Over time, racket-mode font-lock has grown a bit beyond that static list. For example, identifiers in `let`-like bindings dynamically get `font-lock-variable-name-face` (and named `let` names get `font-lock-function-name-face`). I suppose similar could be done for `match` patterns -- including "else", which as you point out is just another identifier not a special keyword. 

- Also, someday I could see doing basic font-lock for racket-mode buffers that are merely visting files -- and later, if/when the buffer is `racket-run` and there is a live namespace, use that to font-lock imported bindings specially. Which ultimately is the only way to handle Racket as a programming-language programming language. (I believe something like this is done for Clojure: `clojure-mode` only knows about .clj* files and does basic formatting; after a `cider-jack-in`, `cider-mode` uses that live environment to do fancier formatting.)

**Comment by jasonhemann** [comment]
Ah. Aye aye. Closing then.
