### ISSUE TITLE
Weird issue with CPU jumping to 100% in modules with gui / frame

### ISSUE THREAD

**Issue by cwebber** [greghendershott/racket-mode#323]
For whatever reason this happens in racket-mode but not in DrRacket or at a repl started from the command line for me.  I also don't know when it started.  This is on GuixSD, but I don't think it's anything Guix-specific that's causing this... I intentionally tried it with grafts, which are the only thing I could think of that would be Guix-specific, turned off.

Here's the example program:

``` racket
#lang racket

(require racket/gui)
(define f (new frame% [label "test"]))
```

Hit C-c C-c in that file and open htop.  For me, the cpu jumps to 100%.

Now here's the weird thing... even with the same REPL session open, I can open up another buffer that does *not* have any GUI things happening in it, hit C-c C-c again, and the CPU stops being at 100%!

Would be interested if anyone else can reproduce this at all :)

**Comment by greghendershott** [comment]
p.s. On a vastly less important note: Opening code blocks with

    ```racket

is better than using `scheme`.

For one thing, GitHub's Scheme lexer highlights square brackets as errors. (That's not correct even for Scheme, but, a couple years ago GitHub decided to stop using Pygments and instead try to use Atom lexers. In my experience, that was a pretty bad change.)

**Comment by cwebber** [comment]
Thanks for the fix, and for letting me know that racket was a lexer option on GH!  I didn't know! :)
