### ISSUE TITLE
Racket-logger-mode does not show any GC logging.

### ISSUE THREAD

**Issue by PLu55** [greghendershott/racket-mode#325]
I do not get any logging from GC in racket-logger-mode.

Racket-mode 20180824.1410, Racket 6.9, Kubuntu 17.10, kernel 4.13.0-46-lowlatancy

**Comment by greghendershott** [comment]
I don't either, using this minimal `example.rkt`:

```racket
#lang racket/base
(for ([i 3]) (collect-garbage))
```

Command-line Racket works -- provided you set the level for GC to debug using the `-W` flag:

```
$ racket -W debug@GC example.rkt 
GC: 0:min @ 1,483K(+100K)[+216K]; free 1,110K(-5,206K) 2ms @ 31
GC: 0:min @ 1,631K(+4,048K)[+232K]; free 701K(-701K) 2ms @ 39
GC: 0:min @ 2,159K(+3,520K)[+244K]; free 585K(-1,881K) 2ms @ 47
GC: 0:min @ 4,493K(+3,266K)[+252K]; free 1,542K(-1,542K) 3ms @ 60
GC: 0:min @ 5,153K(+2,606K)[+264K]; free 1,060K(-6,452K) 4ms @ 76
GC: 0:min @ 7,586K(+5,565K)[+340K]; free 1,731K(-3,027K) 7ms @ 99
GC: 0:MAJ @ 7,124K(+7,323K)[+484K]; free 2,263K(-2,263K) 8ms @ 118
GC: 0:MAJ @ 4,861K(+9,586K)[+484K]; free 0K(+2,255K) 10ms @ 126
GC: 0:MAJ @ 4,878K(+7,329K)[+488K]; free 18K(-18K) 6ms @ 136
GC: 0:atexit peak 7,586K; alloc 13,880K; major 3; minor 6; 44ms
```

However in racket-mode, if I:
- `M-x racket-run` the file
- `M-x racket-logger` to open a `*Racket Logger*` buffer
- In the logger buffer, <kbd>l</kbd> then choose `GC` then choose `debug`.
- `M-x racket-run` the file again.

There is no output after the logger config:

```
racket-logger-config:
((cm-accomplice . warning)
 (GC . debug)
 (module-prefetch . warning)
 (optimizer . info)
 (racket/contract . error)
 (sequence-specialization . info)
 (* . fatal))
```

Output for other loggers and levels does work (for me).

This is... strange. I need more coffee.

**Comment by greghendershott** [comment]
Also, to clarify: [On StackOverflow you shared a program](https://stackoverflow.com/questions/52021540/gc-logging-when-running-racket-as-emacs-repl) where you're making your own log receiver and it should just print the first result it gets:

```racket
(define my-logger (make-log-receiver (current-logger) 'debug 'GC))
(collect-garbage)
(sync/timeout 1 my-logger)
```

When `racket-run`, this _ought_ to print to stdout and show up in the `*Racket REPL*` buffer, just like any other output. It doesn't under racket-mode, and that's a bug.

---

So, the interesting thing here is that racket-mode is not only failing to show debug output for the `GC` logger in `*Racket Logger*` -- also it's preventing user programs from making a receiver and showing this in normal output. And, this only affects the `GC` logger -- not others.

This is a really interesting bug!  My first wild guess is that it's something related to using a custodian -- perhaps how racket-mode uses `custodian-limit-memory`?

Alas I need to be AFK for the next 12+ hours so I can't dig into this for awhile.

**Comment by greghendershott** [comment]
This turned out to be a result of creating a new logger:

    (define global-logger (make-logger))
      (current-logger global-logger)

rather than just using the existing one:

    (define global-logger (current-logger))

The existing logger is special, as [the Racket documentation for loggers](https://docs.racket-lang.org/reference/logging.html) explains:

> On start-up, Racket creates an initial logger that is used to record events from the core run-time system. For example, an `'debug` event is reported for each garbage collection (see [Garbage Collection](https://docs.racket-lang.org/reference/eval-model.html#%28part._gc-model%29)).

Commit ec35502 which fixes this is merged to master. https://melpa.org/#/racket-mode hasn't refreshed yet; I forget the schedule, but maybe within an hour or two?

Thanks again for reporting this1
