### ISSUE TITLE
GUIs involving plots have black screen with racket-mode on GNU/Linux

### ISSUE THREAD

**Issue by cwebber** [greghendershott/racket-mode#326]
Or at least it seems to here.  Not critical for my needs but strange/annoying.  Sample program, taken from the [plot tutorial](https://docs.racket-lang.org/plot/intro.html):

``` racket
(require plot)
(plot-new-window? #t)
(plot (function sin (- pi) pi #:label "y = sin(x)"))
```

This is fine in DrRacket but when I run in racket-mode's repl I get a black window which has weird artifacts when resized.  I wonder what's different?

**Comment by greghendershott** [comment]
I can repro on macOS. It's a normal frame with a white background, but blank, no plot content. Furthermore, the close button doesn't work. I suspect this is a variation on #323 -- it smells like the GUI's current-interaction-port isn't being used, and that means the racket/gui event loop is getting starved. I'm guessing.

[I'm glad you're using racket/gui things with racket-mode! That's not within the scope of how I dogfood racket-mode these days. Generally the racket/gui aspect has been stable and worked fine for some years now -- but the recent changes I've made have poked jello and it's still quivering.]

**Comment by greghendershott** [comment]
OK I think I have a fix -- and understand what to keep in mind going forward.

Also I will try to smoke-test `racket/gui` more often. Although I hardly ever use the whole GUI framework in real life, `plot` _is_ something I do use for real (just happened not to very recently).
