### ISSUE TITLE
how should I extend racket-unicode-input-method

### ISSUE THREAD

**Issue by capfredf** [greghendershott/racket-mode#330]
Hi Greg, I want to use several symbols like · (middle dot), ⊢ (turnstile), arrows (like ⇒), but I'm not sure everyone wants it so I don't send a pull request about it. 

Is there a way that I can non-invasively extend the input method without modifications to racket-unicode-input-method.el?

**Comment by greghendershott** [comment]
Good question. My honest answer is that I cargo cult-ed this from haskell-mode. It uses something called `quail`. It looks like [this approach](https://emacs.stackexchange.com/questions/3104/how-can-i-add-characters-to-an-input-method) would work, substituting `"racket-unicode"` for `"TeX"` as the quail package name?

**Comment by greghendershott** [comment]
@capfredf Did that work?

**Comment by capfredf** [comment]
@greghendershott Greg, thanks for the tip. I haven't tried it yet. I will get back to you later in this week when I have some free time.

**Comment by greghendershott** [comment]
I'm weeding open issues. I'm going to close this because there's nothing actionable for me, now.

However feel free to comment more (I'm happy to try to help when I have time), or reopen the issue, or submit a PR to improve the docs, or whatever you think makes sense.
