### ISSUE TITLE
how to debug in racket-mode

### ISSUE THREAD

**Issue by chaomaer** [greghendershott/racket-mode#340]
I am new to emacs and racket-mode. I want to know how to debug and how to set breakpoint like DrRacket.
Thank you.

**Comment by greghendershott** [comment]
Have you seen [this `racket-debug-mode` documentation](https://github.com/greghendershott/racket-mode/blob/master/Reference.md#racket-debug-mode)?

Please let me know if that helps or not.

**Comment by greghendershott** [comment]
Please let me know if the documentation was helpful for you?

If yes: That's good to know.

If not: I can listen to you and we can improve the documentation.

**Comment by chaomaer** [comment]
@greghendershott  I am sorry to rely slowly. I will tell you immediately when I read over the document. Thank you again.

**Comment by greghendershott** [comment]
I didn't mean to rush you. If you decide not to try using the debugger, at all, no worries. But if someday you do take time to try it, I'd be grateful to know your feedback -- at your convenience. Thank you.
