### ISSUE TITLE
Request: native way to enter! modules

### ISSUE THREAD

**Issue by Bogdanp** [greghendershott/racket-mode#343]
First off, thank you for racket-mode!

I would like to be able to `enter!` arbitrary modules during a single REPL session so I can make changes to my code while it's running. I've come up with this function that gets me about 95% of the way there:

```elisp
  (defun bp-racket-enter ()
    (interactive)
    (let* ((source-file (buffer-file-name))
           (source-directory (expand-file-name (file-name-directory source-file)))
           (package-root (expand-file-name (locate-dominating-file source-file "info.rkt")))
           (module (file-relative-name source-file package-root)))
      (switch-to-buffer-other-window racket--repl-buffer-name)
      (end-of-buffer)
      (insert "(require racket/enter)")
      (racket-repl-submit)
      (insert (concat "(current-load-relative-directory \"" package-root "\")"))
      (racket-repl-submit)
      (insert (concat "(enter! \"" module "\")"))
      (racket-repl-submit)
      (insert (concat "(current-load-relative-directory \"" source-directory "\")"))
      (racket-repl-submit)))
```

There are two issues with this approach as far as I can see:

1. it breaks down if the repl is initially run on any module that doesn't live in the package root
2. it doesn't update the prompt

Is there a better way I can do this myself? Would you consider adding something like this to racket-mode?

**Comment by greghendershott** [comment]
racket-mode's `racket-run` command does the equivalent of `enter!` -- including using `module->namespace` to give the REPL a namespace that is "inside" the module.

But it also does more. Like DrRacket, it effectively reloads everything from your source file -- and all the source files it transitively requires. If I understand correctly, this is the aspect you don't want (or don't always want).

Unfortunately it's not an aspect I have time to change -- or feel super motivated to change even if I had time. [It's fun to mutate running code, but, for my own sanity I really believe in having a single source of truth -- source files, preferably under version control.]

---

As for 1, I think it should work if you simply give the full absolute path to the file, to `current-load-relative-directory`?  e.g. If the buffer is `/path/to/file.rkt` then `(parameterize ([current-load-relative-directory "/path/to"]) (enter! "file.rkt"))` should work?

But yes, as for 2 -- the prompt and other racket-mode features like completion and find-definition won't know that you're in the file that you `enter!`.  So this would be just a little halfway hack.

**Comment by Bogdanp** [comment]
> If I understand correctly, this is the aspect you don't want (or don't always want).

Yup. My use case is a somewhat large web app where reloading it on every change ends up taking a lot of time so this kind of workflow is much faster when working with things like that (and especially `include-template` because I can just re-evaluate the code that uses my templates after I change them rather than restart my whole server), but I understand why you would want to keep it this way.

I'll live w/o the prompt for now. I also noticed that geiser works with racket-mode pretty well so I could just use it as my REPL when I'm doing this sort of work.

Anyway, thanks a ton for replying and for all your work on racket-mode!

**Comment by greghendershott** [comment]
Sometimes it's feasible for an app to make explicit that certain parts are reloadable.

Being explicit can be seen as an inconvenience or as an advantage, depending on the application and on your point of view.

Although you may already know about them a couple potentially interesting links are:

- [How do I use templates “dynamically"?](https://docs.racket-lang.org/web-server/faq.html#(part._.How_do_.I_use_templates__dynamically__))
- [racket-reloadable](https://github.com/tonyg/racket-reloadable)
