### ISSUE TITLE
read-line from the program is wrong

### ISSUE THREAD

**Issue by sorawee** [greghendershott/racket-mode#353]
Consider:

```
#lang racket

(read-line)
```

When running and prompted for an input, type `1` and enter. I would expect `"1"` to be the result, but nothing seems to happen. Now, type `2` and enter. The result is:

```
"2"
1
```

so it seems somehow `1` is sent to the REPL instead of the running program.

Note that the bad interaction between the Racket REPL and `read-line` is well-known: https://groups.google.com/forum/#!topic/racket-users/0TTsA9-3HDs. Not sure if it's the cause of this bug.

This issue originally came up in https://stackoverflow.com/questions/54384304/writing-y-or-n-p-in-racket

**Comment by greghendershott** [comment]
Yes, I think it's basically the issue that Matthew mentioned.

Partially related: I've been trying to take steps to make racket-mode friendly to non-sexpr `#lang`s -- including using the "submit? predicate" that a lang can supply.

**Comment by greghendershott** [comment]
See also #311 #313.

**Comment by greghendershott** [comment]
Actually I can't reproduce this. I get the expected behavior.

If you <kbd>C-h v</kbd> and enter `racket--el-source-dir`, what is the value?

**Comment by sorawee** [comment]
It's `~/.emacs.d/elpa/26.1/develop/racket-mode-20181206.329/`.

Note that for this bug is triggered whenever I saw the following message in the minibuffer:

> Starting racket to run ~/.emacs.d/elpa/26.1/develop/racket-mode-20181206.329/racket/run.rkt ...
> Connected to racket-command process on port 55555 after 5 attempt(s)

But sometimes this message doesn't appear, and I couldn't reproduce it in those cases.

**Comment by sorawee** [comment]
Here's a GIF demonstrating the bug:

![racket](https://user-images.githubusercontent.com/9099577/52253503-1a7f6f80-28bd-11e9-9b97-7fa73af7d69f.gif)

**Comment by greghendershott** [comment]
Thanks!

1. When the REPL is _not_ already live with a Racket process, I _can_ reproduce this, always (so far).

2. When the REPL is already running -- even for some other file -- then I _can't_ repro this, ever (so far).

So, I'll need to untangle the startup sequence. From past experience, that's an area where it is easy to create new bugs while fixing old ones. As a result, it may take me awhile to fix this, confidently.

---

Meanwhile a work-around is to start the REPL by running any "normal" file (without a file module level `read-line` expression).

You can also put the side-effecting stuff like this in a `(module+ main ___)` submodule. Or one named `example`, or whatever you like.

I find this useful so I can run/error-check a file, without actually running the side-effecting part. Then, when I do want to run it, I can move point inside the submodule and <kbd>C-c C-c</kbd> again to enter and run the submodule. In other words, this can be handy even when not working-around a bug.
