### ISSUE TITLE
`racket--buffer-file-name`  and `racket-repl-file-name` not equal.

### ISSUE THREAD

**Issue by AitorATuin** [greghendershott/racket-mode#357]
Yesterday i found a strange behavior when editing a simple racket file.
When requiring `net/url` in the racket buffer and after running `racket-run` the symbols defined in such module were not present when autocomplete, in the REPL buffer the symbols were properly detected though. After doing some debug (using what i found [here](https://github.com/greghendershott/racket-mode/blob/master/Reference.md#racket-debug-mode)) i realized that the problem was [here](https://github.com/greghendershott/racket-mode/blob/master/racket-repl.el#L483).
Somehow the value of `racket-repl-file-name` contains an extra slash at the beginning, for instance:

 - `racket--buffer-file-name`  is /home/user/some/path/file.rtk
 - `racket-repl-file-name` is //home/user/some/path/file.rtk

Since the problem seems to be in this racket [function]( https://github.com/greghendershott/racket-mode/blob/master/racket/mod.rkt#L110) and I don't really know how to debug it i made an ugly workaround trimming the extra slash in elisp code 
``` elisp
(string-equal (racket--buffer-file-name)
                           (replace-regexp-in-string
                            "/+" "/" (racket-repl-file-name)))
```

I'm new in emacs/elisp and racket but i remember this working properly one month ago or so.
Any idea what could be happening? 
Do you have any tips for debugging the racket code so I can debug it (and learn in the process)?.

**Comment by greghendershott** [comment]
I am impressed you tried to use racket-mode's debugger to debug some of racket-mode's Racket code. :smile:

My quick guess is to suspect recent commit 7140f611 to fix #346. This fixed some path handling on Windows. I verified it still worked with Unix style path names on macOS. But maybe I did something knuckle-headed.

If you wanted to look at that commit's code, and see if you can spot the problem, that would be fantastic. Otherwise I will try to take a look soon.

**Comment by greghendershott** [comment]
> Do you have any tips for debugging the racket code so I can debug it (and learn in the process)?.

That's a great question.  I'm not sure I have a great answer, but:

- Maybe [read this blog post](https://www.greghendershott.com/2018/10/racket-mode.html).

- `command-server.rkt` is where the commands from Emacs Lisp get received and dispatched in a big `match` expression. You can open the file with a definition -- e.g. "Oh, it looks like `describe` is defined in `command/describe.rkt` -- `racket-run` it. Then do the usual REPL things, try calling the function, see what it returns for various outputs, etc. Tip: Remember that the REPL itself is still running the _old_ code. To see a change you made to racket-mode, you'll need to <kbd>C-c C-l</kbd> and <kbd>C-c C-c</kbd> to restart the Racket process and run the code you just changed.

- As much as I like the experimental full-on debugger, honestly it's often easiest to do the time-honored thing of "instrumenting" the code maually. Also known as, temporarily adding a simple `println` or two.

- Check the commit history and suspect recent changes.

**Comment by AitorATuin** [comment]
> If you wanted to look at that commit's code, and see if you can spot the problem, that would be fantastic

Sure, I can take a look to see if I'm able to spot something :D 
Thanks for the quickly response

**Comment by AitorATuin** [comment]
Well ....
```
racketchat.rkt> (path->string/emacs "/uno/dos")
"//uno/dos"
```
:)

**Comment by greghendershott** [comment]
Wow that is pretty bad. I've been using racket-mode heavily (many hours per day) mostly on macOS for the few weeks since that commit. I thought I'd fetched through that commit and was using it. Apparently not. 😞

**Comment by greghendershott** [comment]
I'm embarrassed enough I'm going to go ahead and fix this myself.

**Comment by AitorATuin** [comment]
thanks :D
