### ISSUE TITLE
use racket-mode's font-lock(syntax highlighting) in geiser

### ISSUE THREAD

**Issue by yanyingwang** [greghendershott/racket-mode#365]
`racket-mode` has a better color scheme to render racket code. So I want to use it in Geiser. it already took me a long time trying to enable `racket-mode`'s font-lock in Geiser, but I can't figure it out. Here is what I've tried:

1. I tried to get values of `racket-font-lock-keywords` with `describe-variable`  in my Emacs.
2. And then use the value for the `geiser-custom-font-lock-keywords`, but it failed with raising errors.

 Do I have a way to export `racket-mode`'s font-lock and import it to Geiser? Or is there an easy way to do this?

**Comment by greghendershott** [comment]
IIUC geiser is a minor mode that enhances the scheme-mode major mode -- where you do your editing. So is scheme-mode really where you want to use the font-lock?  (I mean, what you care about, mostly. Maybe you'd also like to change font-lock in the Geiser REPL. But. One step at a time.)

The code used to set `font-lock-defaults` is [here](https://github.com/greghendershott/racket-mode/blob/master/racket-common.el#L200-L216). Maybe you could add a `scheme-mode-hook` and in your hook proc do the same (to replace scheme-mode's original value)??

I have no idea if that would work well, or at all. But that would be where I'd start if I had the time or inclination to do this. Good luck!

**Comment by yanyingwang** [comment]
@greghendershott  thanks for the fast replay and sorry for my bad issue description. The thing happens actually like this:

I was formerly playing around with another scheme dialect chez scheme in the Geiser REPL, recently I changed to using Racket. And then I find out there is a better emacs mode `racket-mode` which hold a better syntax highlight and `racket-repl` as well, and maybe more than that which I haven't explored out.
 
But I also notice something I didn't adapt myself with. Which comes first is, `racket-repl` seems only has the function `racket-repl-eval-or-newline-and-indent` and Geiser has the function `Geiser-repl--maybe-send`, if I may point out the difference between them is: when you input nothing in the line and press the `enter` key, in geiser the cursor will go to a new line prompt  just like things happens in a UNIX shell terminal, while `racket-repl` just inputs a `return` character without I guess.

I guess maybe there are some reasons `racket-repl` was designed like this. But all in all, I suppose the easier way to resolve this for me is trying to use the `racket-mode`'s syntax highlight in the `geiser-racket-repl`. And also, as my google search, emacs call syntax highlight as `font-lock` in some sense.

**Comment by greghendershott** [comment]
Oh. I think it's probably easier to change `racket-repl-mode`'s handling of empty input, than it would be transplant font-lock.

You could try this change yourself in `racket-repl-mode.el`:

```diff
 (defun racket-repl-submit (&optional prefix)
   "Submit your input to the Racket REPL.
 
 If the REPL is running a Racket lang whose language-info has a
 'drracket:submit-predicate, that is first called to see if the
 input is valid to be submitted.
 
 With a prefix: After sending your input and a newline, also calls
 `process-send-eof' -- because some langs require EOF to mark the
 end of an interactive expression/statement."
   (interactive "P")
   (let* ((proc (get-buffer-process (current-buffer)))
          (_    (unless proc (user-error "Current buffer has no process")))
          (text (substring-no-properties (funcall comint-get-old-input))))
     (cl-case (if racket-use-repl-submit-predicate
                  (racket--cmd/await `(repl-submit? ,text t))
                'default)
       ((nil)
        (user-error "Not a complete expression, according to the current lang's submit-predicate."))
       ((t default)
-       (comint-send-input)
-       (remove-text-properties comint-last-input-start
-                               comint-last-input-end
-                               '(font-lock-face comint-highlight-input))
-       ;; Hack for datalog/lang
-       (when prefix (process-send-eof proc))))))
+       (unless (equal "" (comint-get-old-input-default))
+         (comint-send-input)
+         (remove-text-properties comint-last-input-start
+                                 comint-last-input-end
+                                 '(font-lock-face comint-highlight-input))
+         ;; Hack for datalog/lang
+         (when prefix (process-send-eof proc)))))))
```

Now, when you hit <kbd>ENTER</kbd>, it will do nothing at all -- not insert a new line, and not show you a new prompt.

---

If instead you _really_ want it issue another prompt, like a shell would?  For that:

```diff
 (defun racket-repl-submit (&optional prefix)
   "Submit your input to the Racket REPL.
 
 If the REPL is running a Racket lang whose language-info has a
 'drracket:submit-predicate, that is first called to see if the
 input is valid to be submitted.
 
 With a prefix: After sending your input and a newline, also calls
 `process-send-eof' -- because some langs require EOF to mark the
 end of an interactive expression/statement."
   (interactive "P")
   (let* ((proc (get-buffer-process (current-buffer)))
          (_    (unless proc (user-error "Current buffer has no process")))
          (text (substring-no-properties (funcall comint-get-old-input))))
     (cl-case (if racket-use-repl-submit-predicate
                  (racket--cmd/await `(repl-submit? ,text t))
                'default)
       ((nil)
        (user-error "Not a complete expression, according to the current lang's submit-predicate."))
       ((t default)
+       (when (equal "" (comint-get-old-input-default))
+         (comint-send-string proc "(void)"))
        (comint-send-input)
        (remove-text-properties comint-last-input-start
                                comint-last-input-end
                                '(font-lock-face comint-highlight-input))
        ;; Hack for datalog/lang
        (when prefix (process-send-eof proc))))))
```
This works by invisibly typing `(void)` for you. The `print`ed form of that is... nothing. So Racket prints nothing, then you get another prompt.

**Comment by greghendershott** [comment]
p.s. To me, the first approach feels more correct: If there is nothing to do, then do nothing. :smile:

The second approach feels hacky -- sending an invisible `(void)`. However, it produces the exact result you prefer. And it's a slightly simpler change. :man_shrugging:

**Comment by greghendershott** [comment]
:roll_eyes:
