### ISSUE TITLE
begin0 where first form is a single "prefix" char indents second form as continuation of first

### ISSUE THREAD

**Issue by sorawee** [greghendershott/racket-mode#371]
Consider:

```
(begin0 a
  b)
```

This is indented correctly.

Now, change it to:

```
(begin0 @ 
    b)
```

Somehow, it no longer indents correctly.

```
((emacs-version "26.1")
 (emacs-uptime "16 days, 14 hours, 58 minutes, 30 seconds")
 (system-type darwin)
 (major-mode racket-mode)
 (racket--el-source-dir "/Users/sorawee/.emacs.d/elpa/26.1/develop/racket-mode-20181030.1345/")
 (racket--rkt-source-dir "/Users/sorawee/.emacs.d/elpa/26.1/develop/racket-mode-20181030.1345/racket/")
 (racket-program "racket")
 (racket-command-port 55555)
 (racket-command-timeout 10)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-retry-as-skeleton t)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-use-repl-submit-predicate nil)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))))
```

(Note: I take minor mode data out)

**Comment by greghendershott** [comment]
Playing around with this for a few seconds, it looks like this happens with e.g. `'` as well as `@` -- but _not_ with e.g. `a` or `+`.

Using <kbd>C-u C-x =</kbd> with point on those various chars, to see their properties, shows that the problematic examples have in common:

```
               syntax: ' 	which means: prefix
```

In your example it seems to believe `@\nb` is all one symbol, and thinks it's the first form. Indent for `begin0` intentionally gives extra indent when the first form is on a line following the `begin0`. For instance these are intentionally correct:

```
(begin0
    result)

(begin0
    result
  for-effect-0
  for-effect-1)
```

Probably some regular expression needs to be adjusted not to match on white space like `\n`. Then it will see `@\nb` as the two forms `@` and `b` and the indent will behave as expected.

**Comment by greghendershott** [comment]
Oh. Wait. Racket allows white space between a prefix and other characters in an identifier.

This is a valid program:

```
'
a
```

It evaluates to `'a`.

So I think this is behaving as expected. `¯\_(ツ)_/¯`

If there's a bug, arguably, it would be more along the lines that `@` shouldn't have "prefix" char syntax. But I think the motivation for that was at-expressions?

I don't know. Is this actually impeding you from wanting to use `@` as a variable name in a non at-exp program?  If so, I'll spend more time on this. Otherwise, if you're just sharing an interesting little corner case you noticed, I'd prefer to close it or leave it open with a `help-wanted` tag. Please let me know what you think.

**Comment by sorawee** [comment]
Is it possible to adjust the regex by `#lang` then? In regular `#lang racket`, `@` should not be a prefix.

And in any case, note that this doesn't work:

```
#lang at-exp racket
(define a 1)
@
a 
;; unexpected whitespace after @
```

while this does work

```
#lang at-exp racket
(define a 1)
@a ; 1
```

So perhaps `@` should not be a prefix regardless of any `#lang` we are in.

**Comment by greghendershott** [comment]
> So perhaps @ should not be a prefix regardless of any #lang we are in.

Yes, I still think that's probably right. Modulo what else might break. I'd need a block of time to think about this.

So again:

>> I don't know. Is this actually impeding you from wanting to use `@` as a variable name in a non at-exp program? If so, I'll spend more time on this. Otherwise, if you're just sharing an interesting little corner case you noticed, I'd prefer to close it or leave it open with a `help-wanted` tag. Please let me know what you think.

?

**Comment by sorawee** [comment]
> Is this actually impeding you from wanting to use @ as a variable name in a non at-exp program?

Yes, unfortunately.

**Comment by greghendershott** [comment]
Result of some more thinking, and reading through git history from 4 or 5 years ago:

The motivation for `@` having Emacs "prefix" char-syntax is for Racket splicing -- `,@xs` and `#,@xs`.

This means e.g. navigation commands like `backward-sexp` or `paredit-backward` will work as expected and move point all the way to the start. There may be other consequences I can't remember without sucking more code into my brain's L1 cache.

I _think_ the way to change this would be:

1. Remove the [`(modify-syntax-entry ?@  "'   " st)`](https://github.com/greghendershott/racket-mode/blob/master/racket-common.el#L77).
2. Add some code to [`racket-syntax-propertize-function`](https://github.com/greghendershott/racket-mode/blob/master/racket-common.el#L89-L144) to give prefix syntax to the char sequences `,@` and `#,@`. (That function is how to assign syntax to certain sequences of chars.)
3. If "it works", update [`racket/indent.rkt`](https://github.com/greghendershott/racket-mode/blob/master/racket/example/indent.rkt) with `begin0` examples. As the comments at the start of this file explain...
4. Regenerate `racket/indent.faceup`.
5. `make compile && make test-elisp` to make sure the tests pass.
6. Wait to see what else this change breaks, if anything.

---

I don't have time to do this now. If it's urgent for you, you're welcome to try. Note: You could just do the first couple steps as a private hack, without going on to do the rest and prepare a PR.

I'll tag this issue as `help-wanted` in case you or someone else does someday want to do this. (Also maybe later I would if I have time.)
