### ISSUE TITLE
Empty identifier (||) breaks when there's another  | on the same line

### ISSUE THREAD

**Issue by sorawee** [greghendershott/racket-mode#376]
This is directly related to #261.

```
(define || (|list|))
```

results in 

<img width="181" alt="Screen Shot 2019-05-18 at 03 56 25" src="https://user-images.githubusercontent.com/9099577/57966521-fb16ca80-7920-11e9-91c6-16cb53cbe005.png">

**Comment by greghendershott** [comment]
Thanks for reporting. Possibly the fix is as simple as changing a one-or-more to zero-or-more, e.g.

```diff
modified   racket-common.el
@@ -137,7 +137,7 @@
     ;; Treat |identifier with spaces| -- but not #|comment|# -- as
     ;; word syntax
     ((rx (not (any ?#))
-         (group ?| (+? (not (any "|\"\r\n"))) ?|)
+         (group ?| (*? (not (any "|\"\r\n"))) ?|)
          (not (any ?#)))
      (1 "w")))
    (point)
```

**Comment by sorawee** [comment]
Thanks!
