### ISSUE TITLE
Info file racket does not exist

### ISSUE THREAD

**Issue by betamint** [greghendershott/racket-mode#377]
I installed racket-mode from MELPA and started Info to view its documentation, but got the following in `*Message*` after hitting `RET` on `Racket Mode` in the `*info*` buffer:

```
user-error: Info file racket does not exist
```

In my `/home/qkuic/.emacs.d/elpa/racket-mode-20190521.159/` there is a `racket-mode.info`. After creating a symlink named `racket.info` under this directory to `racket-mode.info`, I can browse Info documentation for racket mode.

Seems like a naming issue.

<details>

```
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
                 (20190521 159)
                 "Major mode for Racket language."
                 ((emacs
                   (24 3))
                  (faceup
                   (0 0 2)))
                 nil nil "/home/user/.emacs.d/elpa/racket-mode-20190521.159"
                 ((:url . "https://github.com/greghendershott/racket-mode")
                  (:maintainer "Greg Hendershott")
                  (:authors
                   ("Greg Hendershott")))
                 nil))
((emacs-version "26.1")
 (emacs-uptime "15 seconds")
 (system-type gnu/linux)
 (major-mode racket-repl-mode)
 (racket--el-source-dir "/home/user/.emacs.d/elpa/racket-mode-20190521.159/")
 (racket--rkt-source-dir "/home/user/.emacs.d/elpa/racket-mode-20190521.159/racket/")
 (racket-program "racket")
 (racket-command-port 55555)
 (racket-command-startup nil)
 (racket-command-timeout 10)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-retry-as-skeleton t)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-use-repl-submit-predicate nil)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal))))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (column-number-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (global-undo-tree-mode)
 (hs-minor-mode)
 (line-number-mode)
 (minibuffer-depth-indicate-mode)
 (mouse-wheel-mode)
 (show-paren-mode)
 (tooltip-mode)
 (transient-mark-mode)
 (undo-tree-mode)
 (winner-mode))
(disabled-minor-modes
 (abbrev-mode)
 (auto-fill-function)
 (auto-save-visited-mode)
 (blink-cursor-mode)
 (buffer-read-only)
 (cl-old-struct-compat-mode)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (defining-kbd-macro)
 (delete-selection-mode)
 (display-time-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-pair-mode)
 (electric-quote-mode)
 (global-prettify-symbols-mode)
 (global-visual-line-mode)
 (horizontal-scroll-bar-mode)
 (ido-everywhere)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (menu-bar-mode)
 (modalka-global-mode)
 (modalka-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (paredit-mode)
 (prettify-symbols-mode)
 (sh-electric-here-document-mode)
 (size-indication-mode)
 (temp-buffer-resize-mode)
 (tool-bar-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode))
```

</details>

<details>
<summary>Irrelevant Details</summary>

By the way, the generated text in `*racket-mode bug report*` should have a blank line between `<details>` and <code>```</code> for the content below it to by styled as code. In others words,

<pre>
&ltdetails&gt
```
((alist-get 'racket-mode package-alist)
......
</pre>

could be changed to

<pre>
&ltdetails&gt

```
((alist-get 'racket-mode package-alist)
......
</pre>

Hope it helps.

</details>

**Comment by greghendershott** [comment]
You tried this too soon! :smile:

Seriously, I'm glad you tried it, and, thank you very much for the report!

Until yesterday, when I merged to master commit 350f9f6, Racket Mode didn't even generate an Info file. It takes a little while for MELPA to refresh, so I hadn't yet checked whether `racket-mode.texi` would be delivered successfully -- much less installed as `racket-mode.info` successfully.

As to why it is looking for `racket.info` instead of `racket-mode.info`, I'll figure that out. Thanks again for reporting the problem.

(Meanwhile the HTML equivalent is generated to https://www.racket-mode.com.)

**Comment by greghendershott** [comment]
I pushed a commit that IIUC will fix this.

If you don't mind trying again, from MELPA, to confirm, that would be great. (You'll need to wait at least a couple hours, until the MELPA version is greater than `20190521.159` -- probably something like `20190522.x`.)

Thank you again for reporting this!

**Comment by betamint** [comment]
Glad to be the first one to visit the documentation in Info!

Can confirm it works on version `20190522.1323`.

(I have already checked https://www.racket-mode.com. It looks great. Clean, and great.)

Thanks for your work!

**Comment by greghendershott** [comment]
Congratulations! I'm sorry I don't have any grand-opening door-prize to give you. :smile:

Thanks again for the report.
