### ISSUE TITLE
phase X (X > 0) is executed more than once

### ISSUE THREAD

**Issue by sorawee** [greghendershott/racket-mode#379]
```
#lang racket

(begin-for-syntax
  (println 1))
```

results in 

```
1
1
```

in the Racket mode's Racket REPL. However, if we run this in `racket`, only one `1` appears.

<details><pre><code>
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
                 (20190505 1519)
                 "Major mode for Racket language."
                 ((emacs
                   (24 3))
                  (faceup
                   (0 0 2))
                  (s
                   (1 9 0)))
                 nil nil "/Users/sorawee/.emacs.d/elpa/26.2/develop/racket-mode-20190505.1519"
                 ((:url . "https://github.com/greghendershott/racket-mode")
                  (:maintainer "Greg Hendershott")
                  (:authors
                   ("Greg Hendershott")))
                 nil))
((emacs-version "26.2")
 (emacs-uptime "9 hours, 29 minutes, 59 seconds")
 (system-type darwin)
 (major-mode racket-mode)
 (racket--el-source-dir "/Users/sorawee/.emacs.d/elpa/26.2/develop/racket-mode-20190505.1519/")
 (racket--rkt-source-dir "/Users/sorawee/.emacs.d/elpa/26.2/develop/racket-mode-20190505.1519/racket/")
 (racket-program "racket")
 (racket-command-port 55555)
 (racket-command-startup nil)
 (racket-command-timeout 10)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-retry-as-skeleton t)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-use-repl-submit-predicate nil)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))))
</code></pre></details>

**Comment by greghendershott** [comment]
Put that code:

```racket
#lang racket

(begin-for-syntax
  (println 1))
```

in a file `issue-379.rkt`.

1. As you report:

```sh
$ racket issue-379.rkt
1
```
2. As you report, <kbd>C-c C-c</kbd> in Racket Mode:

```racket
Welcome to Racket v7.3.
1
1
issue-379.rkt> 
```

3. But wait. There's more. Pressing <kbd>F5</kbd> in DrRacket:

```
Welcome to DrRacket, version 7.3 [3m].
Language: racket, with debugging; memory limit: 128 MB.
1
1
1
> 
```

---

Conclusion: Racket Mode is the warm bowl of porridge, which means it is best. Q.E.D. Issue closed.

Seriously, what do you think is happening here?
