### ISSUE TITLE
port-write-handler is not reset after a run

### ISSUE THREAD

**Issue by sorawee** [greghendershott/racket-mode#381]
Paste the following code in a buffer and run it.

```
#lang racket/base

(let ([write-handler (port-write-handler (current-output-port))])
  (port-write-handler (current-output-port)
                      (λ (val port)
                        (write-handler "a" port))))

(write 1)
```

This prints `"a"` as expected. Now, paste the following code and then run it.

```
#lang racket/base

(write 1)
```

It still prints `"a"`!

-----------

<details>
```
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
                 (20190612 1928)
                 "Major mode for Racket language."
                 ((emacs
                   (24 3))
                  (faceup
                   (0 0 2)))
                 nil nil "/Users/sorawee/.emacs.d/elpa/26.2/develop/racket-mode-20190612.1928"
                 ((:url . "https://www.racket-mode.com/")
                  (:maintainer "Greg Hendershott")
                  (:authors
                   ("Greg Hendershott")))
                 nil))
((emacs-version "26.2")
 (emacs-uptime "5 days, 6 hours, 44 minutes, 24 seconds")
 (system-type darwin)
 (major-mode racket-mode)
 (racket--el-source-dir "/Users/sorawee/.emacs.d/elpa/26.2/develop/racket-mode-20190612.1928/")
 (racket--rkt-source-dir "/Users/sorawee/.emacs.d/elpa/26.2/develop/racket-mode-20190612.1928/racket/")
 (racket-program "racket")
 (racket-command-port 55555)
 (racket-command-startup nil)
 (racket-command-timeout 10)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-retry-as-skeleton t)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-use-repl-submit-predicate nil)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))))
```
</details>

**Comment by greghendershott** [comment]
Each `racket-run` gets a fresh custodian including a fresh dedicated thread for the REPL. As a result, parameters are reset. Therefore you expect `port-write-handler` to be reset. But it is not.

Is that correct?

I'm not very familiar with it, but I notice that the [documentation for `port-write-handler` and friends](https://docs.racket-lang.org/reference/Writing.html#(def._((quote._~23~25kernel)._port-write-handler))) doesn't actually use the word "parameter". Is it possible that it's a function that has a parameter-like signature, but is not actually a parameter?  Many "handlers" in Racket are parameters; maybe this isn't?

Maybe you could research this (e.g. ask on Slack or mailing list) and report back?

**Comment by greghendershott** [comment]
For that recipe Dr Racket prints `1` not `"a"`.

I don't know whether Dr Racket explicitly resets this handler. Instead it might be recreating the _port_, which is something special for the GUI REPL. Whereas Racket Mode is reusing stdout a.k.a. `current-output-port` here -- so if you stick some handler on that port, it remains in effect because it's still the same port.

**Comment by greghendershott** [comment]
Like [some](#371) [other](#376) [bugs](#379) [you've](#380) [filed](#362) recently, this seems to be an interesting edge case that seemingly no one else has encountered -- or at least reported -- in five years. As a result, although I guess I appreciate knowing about it, I'm not sure what action to take beyond the time already spent discussing this, because I'm not sure what is the cost:benefit ratio here.

**Comment by greghendershott** [comment]
Well this stuck in my brain overnight. I pushed a commit to address this.

I'm still not sure this is a great use of time, and, it's possible fixing this will cause some other, worse bug. But I pushed a commit to a topic branch. Maybe I will slow-roll actually merging it to master.
