### ISSUE TITLE
Keyboard Macros act up when racket-unicode-input-method is enabled

### ISSUE THREAD

**Issue by capfredf** [greghendershott/racket-mode#390]
Hi Greg, 

I've run into a problem when I tried to use Emacs' keyboard macros to edit racket code.

Reproduce steps:
1. start racket-mode with racket-unicode-input-method enabled
2. start defining a keyboard macro
3. type and stop defining the macro
4. replay the macro or edit the macro you just defined and you would see the bug

here is a gif showing the problem
![bug-report](https://user-images.githubusercontent.com/512906/60982157-97e45b80-a305-11e9-8654-6566b43c8d2e.gif)

I also recorded a gif with racket-unicode-input-method disabled
![no-ime](https://user-images.githubusercontent.com/512906/60982377-01646a00-a306-11e9-906a-8fd0b847a3f3.gif)

<details>
```
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
		 (20190710 46)
		 "Major mode for Racket language."
		 ((emacs
		   (24 3))
		  (faceup
		   (0 0 2)))
		 nil nil "/Users/capfredf/.emacs.d/elpa/racket-mode-20190710.46"
		 ((:url . "https://www.racket-mode.com/")
		  (:maintainer "Greg Hendershott")
		  (:authors
		   ("Greg Hendershott")))
		 nil))
((emacs-version "26.2")
 (emacs-uptime "10 minutes, 49 seconds")
 (system-type darwin)
 (major-mode racket-mode)
 (racket--el-source-dir "/Users/capfredf/.emacs.d/elpa/racket-mode-20190710.46/")
 (racket--rkt-source-dir "/Users/capfredf/.emacs.d/elpa/racket-mode-20190710.46/racket/")
 (racket-program "racket")
 (racket-command-port 55555)
 (racket-command-startup nil)
 (racket-command-timeout 10)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-retry-as-skeleton t)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-use-repl-submit-predicate nil)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal))))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (blink-cursor-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (hs-minor-mode)
 (line-number-mode)
 (mac-mouse-wheel-mode)
 (menu-bar-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-mark-mode))
(disabled-minor-modes
 (abbrev-mode)
 (auto-fill-function)
 (auto-save-visited-mode)
 (buffer-read-only)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (defining-kbd-macro)
 (display-time-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-pair-mode)
 (electric-quote-mode)
 (global-prettify-symbols-mode)
 (global-visual-line-mode)
 (horizontal-scroll-bar-mode)
 (ido-everywhere)
 (isearch-mode)
 (jit-lock-debug-mode)
 (mac-auto-ascii-mode)
 (mac-auto-operator-composition-mode)
 (mac-font-panel-mode)
 (mouse-wheel-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-check-syntax-mode)
 (sh-electric-here-document-mode)
 (size-indication-mode)
 (temp-buffer-resize-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode))
```
</details>

**Comment by greghendershott** [comment]
Hmm. I rarely use either Emacs keyboard macros or `racket-unicode-input-method`, much less both together. So, thank you for reporting this! And, I'll need to learn more.

Experimenting, it seems the problem is on the macro _recording_ side. If I <kbd>C-\\</kbd> to disable the method and record the macro, then <kbd>C-\\</kbd> to enable the method, then the macro plays fine. OTOH if I record the macro with the input method enabled, the macro is borked, and plays back with the weird result regardless of whether the input method is enabled or disabled during playback.

`racket-unicode-input-method` was, frankly, mostly cargo-culted from Haskell Mode. It uses `quail`. I will read up to try to understand any issues related to using quail with keyboard macros.

Using <kbd>C-\\</kbd> to toggle the input method off during macro recording is a work-around -- maybe not a great one -- in the meantime.

**Comment by capfredf** [comment]
> Experimenting, it seems the problem is on the macro recording side
Yes, I agree with you.

Here is the commands and keys that was recorded in the first gif
```elisp
C-e			;; move-end-of-line
-hhe			;; self-insert-command * 4
5*l			;; self-insert-command
olo			;; self-insert-command * 3
C-a			;; move-beginning-of-line
o			;; self-insert-command
C-a			;; move-beginning-of-line
C-SPC			;; set-mark-command
C-e			;; move-end-of-line
M-(			;; insert-parentheses
```
I will try to use macros in haskell or agda mode, which encourages extensive usage of unicode, and see if I can reproduce the same problem

**Comment by greghendershott** [comment]
I did some searches for "bug", "emacs keyboard macro" and "input-method" and didn't find anything. I also started to look at some Elisp source for quail and mule. Nothing jumped out at me and I ran out of time, for today.

I'm not shocked that keyboard macros and input-methods might have some issue cooperating at intercepting input. OTOH it seems like it ought to be possible for it to work.

If you learn something let me know, otherwise I'll try to loop back to this within the next few days (maybe busy due to RacketCon this weekend).

**Comment by greghendershott** [comment]
Had a few more minutes.

FWIW, it looks like quail uses a `'post-command-hook`.

There is a similar issue for Haskell mode.

Given a `foo.hs` file:

```hs
foo
bar
```

<kbd>M-x turn-on-haskell-unicode-input-method RET</kbd>

Press <kbd>F3</kbd>.

<kbd>C-A-f</kbd> to move to end of "foo". Type "-hello".

Press <kbd>F4</kbd>.

Move point before the "bar" and press <kbd>F4</kbd> to play. Result:

```hs
foo-hello
bar--hhelhllllolo
--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo--hhelhllllolo
```
And error message: `After 0 kbd macro iterations: quail-translate-key: Variable binding depth exceeds max-specpdl-size`.

So it's "even worse", but, essentially the same problem it seems.

**Comment by greghendershott** [comment]
Although I haven't forgotten about this I haven't had time to research more; I probably won't until a week or two from now.

**Comment by capfredf** [comment]
Just FYI: it looks like this was a bug in quail, which seems to have been fixed in Emacs. 
https://github.com/emacs-mirror/emacs/blob/03e3440dbbfea40b449a9f6f23a3630664275d11/lisp/international/quail.el

I don't have an Emacs 27 on my machines, so I will double check this issue when Emacs 27 comes out

**Comment by greghendershott** [comment]
Thanks for the update to let me know.

Hmm, super quick glance, it looks like this entailed changing a C source file, so I don't see any way to "backport" this or do a "polyfill" for older versions of Emacs. (Either for you to do that, or, for Racket Mode to do so -- not that it would probably be within scope for it to do so.)

**Comment by capfredf** [comment]
Ah, I should close this issue, since it has nothing to do with Racket-mode itself
