### ISSUE TITLE
lispy mode indentation

### ISSUE THREAD

**Issue by bestlem** [greghendershott/racket-mode#391]
To help me help you, please:

1. Open any racket-mode or racket-repl-mode buffer.

2. <kbd>M-x</kbd> `racket-bug-report` <kbd>ENTER</kbd>.

3. Copy and paste that, here.

**Comment by bestlem** [comment]
I am using lispy mode on top of racket-mode and for the small bits of lispy I use it seems to work. 
However we came across a bug https://github.com/abo-abo/lispy/issues/430
"  (defun (test?   x) x)" when reindented does not remove all the spaces.

The author of lispy says it is a racket-mode bug https://github.com/abo-abo/lispy/issues/430#issuecomment-507786855 He says indent-sexp should not remove the space at the begining of the line in this case.

I can understand why you might disagree as you do the same as Drracket  but in this case indent-sexp does not condends the multiple spaces between ? and x down to one as lispy does (but DrRacket does not)

**Comment by greghendershott** [comment]
It seems to me from its documentation and name, that `indent-sexp` should correctly indent the start of the current sexp. That seems like a feature, and it would instead be a bug if it did not do so?

I suppose it's possible that "all other Lisp modes" (?) behave differently. If that's true, I'd be interested to learn why.

In my experience, changing things related to indentation can be slow to do carefully -- including the time to find and fix any bugs that arise as a result of the change. So I'm not eager to mess with this, and I can't promise when I'll have a big enough block of free time to look at it. But I will try to, eventually.
