### ISSUE TITLE
Quotes in the documentation

### ISSUE THREAD

**Issue by soegaard** [greghendershott/racket-mode#392]
To help me help you, please:

Copy-paste from the documentation at racket-mode.com into an elisp file
doesn't work. An example from the documentation:

    (add-hook ‘racket-repl-mode-hook #’racket-unicode-input-method-enable)

Note that the apostrophe is the wrong one.

**Comment by greghendershott** [comment]
The HTML page seems correct -- plain old straight quotes `'`:

```html
<pre class="lisp">
(add-hook 'racket-mode-hook      #'racket-unicode-input-method-enable)
(add-hook 'racket-repl-mode-hook #'racket-unicode-input-method-enable)
</pre>
```

So it seems this must be happening when you yank a.k.a. paste?

I don't see this now with Emacs 25.2.2. IIRC you just started using 26.2. I wonder whether there is some new "pretty quote" option, there, that is doing this??

**Comment by soegaard** [comment]
It's futher down on the page.

racket-unicode-input-method-enable
M-x racket-unicode-input-method-enable RET

Set input method to racket-unicode.

The racket-unicode input method lets you easily type various Unicode symbols that might be useful when writing Racket code.


```
To automatically enable the racket-unicode input method in racket-mode buffers use ‘M-x customize-variable <RET> racket-mode-hook‘ or put the following code in your Emacs init file:

(add-hook ‘racket-mode-hook #’racket-unicode-input-method-enable)

Likewise for racket-repl-mode buffers:

(add-hook ‘racket-repl-mode-hook #’racket-unicode-input-method-enable)
```

**Comment by greghendershott** [comment]
Oh OK, yes, at https://www.racket-mode.com/#racket_002dunicode_002dinput_002dmethod_002denable.

This comes from the doc string for that command. The original text has a plain quote. Emacs is "helpfully" making it "fancy". I have passes to adjust various things in doc strings; I can add one to "undo" "fancy quotes". Or, see if there is some var I can set to prevent "fancy quotes" in the first place.

**Comment by greghendershott** [comment]
Still investigating. Narrowed it down to when `org-texinfo-export-to-texinfo` generates the `racket-mode.texinfo` file. Both the Info and HTML files are generated from that. Both share the problem where the quote is changed to a backquote. Trying to understand why and how to avoid that....
