### ISSUE TITLE
Document that racket-visit-definition can prompt for name

### ISSUE THREAD

**Issue by soegaard** [greghendershott/racket-mode#394]
The documentation for `racket-visit-definition` mentions what happens when point is in a name.
Mention that outside a name, the user is prompted for a name.

**Comment by greghendershott** [comment]
Thanks! Yes, <kbd>C-u M-.</kbd> to prompt is a convention in things like `lisp-mode` and `clojure-mode` but I shouldn't assume people would already know that.

**Comment by greghendershott** [comment]
Also: Same for `racket-visit-module`.

Also: The doc str talks about "symbol" but I think "identifier" would be more Racket-correct.
