### ISSUE TITLE
Use racket--indent-for as default for all "for/" forms (with a few exceptions)

### ISSUE THREAD

**Issue by soegaard** [greghendershott/racket-mode#396]
Hi Greg,

The comment in `racket--indent-for` says:

> "Indent function for all for/ and for*/ forms EXCEPT for/fold and for*/fold.

However in practise only the `for/` forms listed in `racket--set-indentation`
are indented using `racket--indent-for`.

Suggestion:  Use `racket--indent-for` for forms that start with `for/` unless 
they are listed in racket--set-indentation`.

**Comment by greghendershott** [comment]
Sorry to be slow to comment on this.

To make sure I understand:

- Currently, anything starting with `begin` or `def` is automatically indented a certain way -- unless there's a specific exception in `racket--set-indentation` (example: `begin0`).

- Similarly, you are proposing that anything starting with `for `, `for* `, `for/`, or `for*/` automatically be indented using `racket--indent-for` -- but specifically excepting for the `/fold` flavors.

Is that correct?

---

If so: That seems reasonable. It would:

- delete a couple dozen lines of repetitive code.
- automatically indent any user-defined `for` macros as (probably) desired.

On the one hand, I feel like the "ideal" solution is for Racket to support macros specifying their own indent, even if they aren't supplied by a `#lang`, and for racket-mode to use such a facility.

On the other hand, that seems unlikely to happen to in the near future; the proposal seems like an improvement meanwhile.

**Comment by soegaard** [comment]
Hi Greg,

No worries. Yes, that's correct. I defined a few `for/` macros of my own and
missed the indentation.

A module for `indentation-time` is a great idea, but a large project.
