### ISSUE TITLE
code works in non-debug mode but doesn't in debug mode

### ISSUE THREAD

**Issue by andreyorst** [greghendershott/racket-mode#400]
Hello. I really appreciate the debug mode, but I got strange error while toying with it and Sierpinski example:

```racket
#lang racket
(require 2htdp/image)

(define (sierpinski n size color)
  (define (sierpinski-iter n t)
    (if (= n 0)
        t
        (sierpinski-iter (- n 1) (scale 0.5 (above t (beside t t))))))
  (sierpinski-iter n (triangle size 'solid color)))
```

When calling it in non-debug mode it prints the image in the REPL:
![image](https://user-images.githubusercontent.com/19470159/64067217-a11ae600-cc2d-11e9-96ce-e7dd77037b78.png)

When I start debug session by `racket-run-with-debug` I get the error when trying to pass the image to `beside` function call:

![image](https://user-images.githubusercontent.com/19470159/64067226-e3dcbe00-cc2d-11e9-844d-66fd443fac56.png)

We can see that the result of `(triangle size 'solid color)` is `(values #(struct:object:image% ...))`. And it's being passed to the `sierpinski-iter` fucntion:

![image](https://user-images.githubusercontent.com/19470159/64067243-28685980-cc2e-11e9-99db-6a05fe20b11b.png)

The next step will be the last for the program, because we try to pass `'#(struct:object:image% ...)` into `beside` and it expects and image:

```racket
[fractals.rkt:182]> 
; beside: expects an image as first argument, given '#(struct:object:image% ...)
; Context:
;  /home/andreyorst/.racket/7.0/pkgs/htdp-lib/htdp/error.rkt:25:0 check-arg
;  /home/andreyorst/.racket/7.0/pkgs/htdp-lib/2htdp/private/img-err.rkt:97:0 check/normalize
;  /home/andreyorst/.racket/7.0/pkgs/htdp-lib/2htdp/private/img-err.rkt:89:11 beside
;  /home/andreyorst/Notes/Programming/LISP/Racket/fractals.rkt:5:2 sierpinski-iter
;  /usr/share/racket/collects/racket/repl.rkt:11:26
```

I'm not sure if this is the problem in the debug mode of this package or with debugging of Racket in general, but as I saw in the [blog post](http://www.greghendershott.com/2018/10/racket-mode.html), you [suggest to report](https://www.racket-mode.com/#racket_002ddebug_002dmode) all issues with debugging.

<details>
```
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
                 (20190803 1820)
                 "Major mode for Racket language."
                 ((emacs
                   (24 3))
                  (faceup
                   (0 0 2)))
                 nil nil "/home/andreyorst/.emacs.d/elpa/racket-mode-20190803.1820"
                 ((:url . "https://www.racket-mode.com/")
                  (:maintainer "Greg Hendershott")
                  (:authors
                   ("Greg Hendershott")))
                 nil))
((emacs-version "26.2")
 (emacs-uptime "4 minutes, 50 seconds")
 (system-type gnu/linux)
 (major-mode racket-mode)
 (racket--el-source-dir "/home/andreyorst/.emacs.d/elpa/racket-mode-20190803.1820/")
 (racket--rkt-source-dir "/home/andreyorst/.emacs.d/elpa/racket-mode-20190803.1820/racket/")
 (racket-program "racket")
 (racket-command-port 55555)
 (racket-command-startup nil)
 (racket-command-timeout 10)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-retry-as-skeleton t)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-use-repl-submit-predicate nil)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal))))
(enabled-minor-modes
 (async-bytecomp-package-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-revert-mode)
 (auto-save-mode)
 (blink-cursor-mode)
 (centaur-tabs-mode)
 (company-flx-mode)
 (company-mode)
 (diff-auto-refine-mode)
 (diff-hl-flydiff-mode)
 (diff-hl-mode)
 (display-line-numbers-mode)
 (doom-modeline-mode)
 (electric-indent-mode)
 (electric-pair-mode)
 (eyebrowse-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (gcmh-mode)
 (global-company-mode)
 (global-diff-hl-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-magit-file-mode)
 (global-undo-tree-mode)
 (hs-minor-mode)
 (ivy-mode)
 (magit-auto-revert-mode)
 (magit-file-mode)
 (minions-mode)
 (mouse-wheel-mode)
 (override-global-mode)
 (parinfer-mode)
 (recentf-mode)
 (savehist-mode)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (solaire-global-mode)
 (solaire-mode)
 (transient-mark-mode)
 (treemacs-filewatch-mode)
 (treemacs-follow-mode)
 (treemacs-fringe-indicator-mode)
 (treemacs-git-mode)
 (undo-tree-mode)
 (window-divider-mode))
(disabled-minor-modes
 (abbrev-mode)
 (ace-window-display-mode)
 (ace-window-mode)
 (auto-fill-function)
 (auto-image-file-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (avy-linum-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (centaur-tabs-local-mode)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (company-search-mode)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (counsel-mode)
 (defining-kbd-macro)
 (delete-selection-mode)
 (diff-hl-dir-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (display-time-mode)
 (doc-view-minor-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (flymake-mode)
 (flyspell-mode)
 (git-commit-mode)
 (global-auto-revert-mode)
 (global-display-line-numbers-mode)
 (global-hl-line-mode)
 (global-prettify-symbols-mode)
 (global-visual-line-mode)
 (gnus-dead-summary-mode)
 (gnus-undo-mode)
 (hl-line-mode)
 (horizontal-scroll-bar-mode)
 (ido-everywhere)
 (image-minor-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (line-number-mode)
 (magit-blame-mode)
 (magit-blame-read-only-mode)
 (magit-blob-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (magit-wip-initial-backup-mode)
 (magit-wip-mode)
 (mail-abbrevs-mode)
 (menu-bar-mode)
 (mml-mode)
 (next-error-follow-minor-mode)
 (org-cdlatex-mode)
 (org-src-mode)
 (orgstruct-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (parinfer-region-mode)
 (prettify-symbols-mode)
 (racket-check-syntax-mode)
 (racket-debug-mode)
 (server-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (size-indication-mode)
 (smerge-mode)
 (table-fixed-width-mode)
 (table-mode-indicator)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-resume-mode)
 (treemacs-tag-follow-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-parent-buffer)
 (vdiff-3way-mode)
 (vdiff-mode)
 (vdiff-scroll-lock-mode)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (which-function-mode)
 (with-editor-mode)
 (xref-etags-mode))
```
</details>

**Comment by greghendershott** [comment]
Thanks for reporting this. To set realistic expectations, the step debugger is labelled "EXPERIMENTAL" and I don't think I'll be able to spend time on it in the foreseeable future.

As a quick (maybe wrong) guess, the underlying issue here might be that the step debugger supports substituting values when stepping. This means the values need to be something that can be serialized from Racket to Emacs and back again. In general `struct`s can't be serialized unless they are `#:prefab`.

Maybe there could be a refinement where, when a value couldn't be serialized, it just doesn't let you substitute a new value for that step, but the debugger continues (no pun intended) to work otherwise.

**Comment by andreyorst** [comment]
> To set realistic expectations, the step debugger is labelled "EXPERIMENTAL" and I don't think I'll be able to spend time on it in the foreseeable future.

Visual step debugging is great instrument for learning how language works. I'm currently working through SICP in is some edge cases I use debugger to understand the flow of the described code, so I really appreciate the existence of `racket-run-with-debug` and will be sad to see if it will be removed.

If there's any existing documentation on how debugging works, both on Racket side and on Racket Mode side, you can point me to it, so I could see if I can help with anything on this feature.

**Comment by greghendershott** [comment]
- I don't have any plans to remove it. I just probably won't have time to do any non-trivial fixes or changes, in the near-future -- blame the Racket Mode Corporation's CFO. :smile:

- Dr Racket has a GUI step debugger. It probably does not have this specific bug, because it does not need to marshal values to/from a non-Racket process.

- I agree a step debugger can be great for learning. And when I wrote C/C++ code for many years, I liked to step through new code (as opposed to just running it). However in a language with a REPL, I find I just write smaller chunks of code (i.e. functions) and exercise them for the first time in the REPL. (Some of those example exercises, I end up copying into `test` sub-modules.)

- Also there are various `print`-flavored techniques:

    - `println` itself, ad hoc.
    - `racket/trace` can be handy, slightly less ad hoc.
    - logger functions like `log-debug`, `log-info`, `log-warning`, `log-error` are useful in production code. You can tweak the verbosity externally with env vars or command-line flags; also Racket Mode has a `racket-logger-mode`. So these are "print"s that you'd more likely leave in code, then "turn on or off" as needed.

**Comment by greghendershott** [comment]
Oh. I don't think I answered the question you were actually asking:

> If there's any existing documentation on how debugging works, both on Racket side and on Racket Mode side, you can point me to it, so I could see if I can help with anything on this feature.

AFIK there is no documentation; you look at the source code for the Dr Racket debugger.

There are a few cases like debugging and `errortrace` for profiling or test coverage where, essentially, you take the program and "instrument" (rewrite) it to be a different, "annotated" program.

So essentially it takes the program, and rewrites it to be a step-debug-able version of the program -- insert new code before and after every original expression, to allow features like pausing and substituting values. That part is [here](https://github.com/greghendershott/racket-mode/blob/master/racket/debug-annotator.rkt).

The rest of it is the Racket Mode "back end" sending an "event" message to the Emacs front end whenever a break happens; see [here](https://github.com/greghendershott/racket-mode/blob/master/racket/debug.rkt). That enables a [`racket-debug-mode`](https://github.com/greghendershott/racket-mode/blob/master/racket-debug.el) Emacs minor mode on the buffer, with commands to resume in various ways.  The specific bug on this issue is (probably) related to being unable to hurl the image struct values over this wall and back again.

**Comment by andreyorst** [comment]
> * I don't have any plans to remove it. I just probably won't have time to do any non-trivial fixes or changes, in the near-future -- blame the Racket Mode Corporation's CFO. :smile:

phew! :smile: 

> * Dr Racket has a GUI step debugger. It probably does not have this specific bug, because it does not need to marshal values to/from a non-Racket process.

Dr Racket has some interesting features, but I do not like it in general. Emacs is more comfortable environment for me.

> * I agree a step debugger can be great for learning. And when I wrote C/C++ code for many years, I liked to step through new code (as opposed to just running it). However in a language with a REPL, I find I just write smaller chunks of code (i.e. functions) and exercise them for the first time in the REPL. (Some of those example exercises, I end up copying into test sub-modules.)

I have quite the opposite situation! I'm writing a lot of bare metal C code at work for SoC, and we do not have debuggers or ability to debug with remote debugger, so all our debugging is restricted to printing and inspecting assembly. So for me, having a step debugger with immediate visual feedback is something magical :smile:. Going to look on `racket/trace` though.

> AFAIK there is no documentation; you look at the source code for the Dr Racket debugger.

That's unfortunate. 

> There are a few cases like debugging and `errortrace` for profiling or test coverage where, essentially, you take the program and "instrument" (rewrite) it to be a different, "annotated" program.
> 
> So essentially it takes the program, and rewrites it to be a step-debug-able version of the program -- insert new code before and after every original expression, to allow features like pausing and substituting values. That part is [here](https://github.com/greghendershott/racket-mode/blob/master/racket/debug-annotator.rkt).
> 
> The rest of it is the Racket Mode "back end" sending an "event" message to the Emacs front end whenever a break happens; see [here](https://github.com/greghendershott/racket-mode/blob/master/racket/debug.rkt). That enables a [`racket-debug-mode`](https://github.com/greghendershott/racket-mode/blob/master/racket-debug.el) Emacs minor mode on the buffer, with commands to resume in various ways. The specific bug on this issue is (probably) related to being unable to hurl the image struct values over this wall and back again.

OK, I'm gonna dig into the sources and see if I could fix this issue and contribute back the changes. Thanks for the links!

**Comment by greghendershott** [comment]
I think commit 832c6c5 is a reasonable way to fix this.

I haven't yet merged to master because I've been traveling and only able to look at this in little snatches of time.
