### ISSUE TITLE
How to bind #'racket-smart-open-bracket to "[" key when paredit enabled?

### ISSUE THREAD

**Issue by anton0xf** [greghendershott/racket-mode#401]
Hello. I am trying something like this:
```elisp
(defun my-racket-mode-hook ()
  (define-key racket-mode-map (kbd "[") #'racket-smart-open-bracket))
(add-hook 'racket-mode-hook #'my-racket-mode-hook)
(add-hook 'racket-mode-hook #'enable-paredit-mode)
```
and many other variations. But every time I see (`C-h m` window) that my keybinding is shadowed by paredit
> [               racket-smart-open-bracket
>  (that binding is currently shadowed by another mode)

And pressing "[" key inserts "[]", but not "()".

### Versions: 
racket-mode: 20190901.2121 (melpa)
paredit: 20171127.205 (melpa)
Emacs: 25.2.2

**Comment by greghendershott** [comment]
I'm traveling today so hard to check in detail and maybe a bad suggestion, but: What if you instead do a `paredit-mode-hook`, and change the binding in `paredit-mode-map`??  (There might be details like, maybe your hook function wants to check if `major-mode` is either `racket-mode` or `racket-repl-mode`. I'm not sure.)

**Comment by anton0xf** [comment]
Thank you for quick answer! It works. Just like `global-set-key`. But then `racket-smart-open-bracket` will be bound to `[` in other major modes with which I use **paredit**, e.g. clojure-mode, where I sometimes need to enter `[`as is.

**Comment by anton0xf** [comment]
I found tricky solution here: https://stackoverflow.com/a/13102821/1438643
```elisp
(defun my-racket-mode-hook ()
  (let ((oldmap (cdr (assoc 'paredit-mode minor-mode-map-alist)))
        (newmap (make-sparse-keymap)))
    (set-keymap-parent newmap oldmap)
    (define-key newmap (kbd "[") #'racket-smart-open-bracket)
    (make-local-variable 'minor-mode-overriding-map-alist)
    (push `(paredit-mode . ,newmap) minor-mode-overriding-map-alist)))
(add-hook 'racket-mode-hook #'my-racket-mode-hook)
(add-hook 'racket-mode-hook #'enable-paredit-mode)
```
It solves my issue, but makes me suffer because of its complexity

**Comment by greghendershott** [comment]
Thanks for researching this.

Probably I should update the documentation for `racket-smart-open-bracket` to include this example configuration code.

**Comment by greghendershott** [comment]
To follow up: I was thinking about this more. I think that making this into a new minor mode, would help. If you simply enable `racket-smart-open-bracket-mode`, it would take care of the <kbd>[</kbd> key binding. Furthermore, if you simply enable it _after_ enabling `paredit-mode`, then that map's binding should take priority as desired. (Even if not, tweaking the simpler `minor-mode-map-alist` variable should suffice.)

I have some code already. Most of the work is adjusting documentation as well as testing the various permutations of this with `electric-pair-mode`, `paredit-mode`, etc.

**Comment by greghendershott** [comment]
Looks like I botched the auto-close phrase in the commit message. This was merged to master about a week ago. Closing manually.
