### ISSUE TITLE
Issues rendering lists of less than 4 images

### ISSUE THREAD

**Issue by sturgman** [greghendershott/racket-mode#402]
Again, please ignore this if too trivial to worry about. I encounter these by going through the racket docs intro so it is not unthinkable that some Racket rookies find similar things but never bother to report.

Bug: lists of images with 2 or 3 elements are not render properly.

To replicate, setup as follows:
```
#lang slideshow

(define (square n)
  ; Renders a black square
  (filled-rectangle n n))

(define (rainbow p n)
  (map (lambda (color)
         (colorize p color))
       (take (list "blue" "purple" "yellow" "red" "green" "white" "cyan" "violet" "pink" ) n) ))
```
Now, if I do `(rainbow (square 15) 5)` in DrRacket.. I get:
![image](https://user-images.githubusercontent.com/4121024/65535796-1ba6f080-ded0-11e9-8d80-f999dde8f9dc.png)
In racket-mode I get:
![image](https://user-images.githubusercontent.com/4121024/65535979-7dfff100-ded0-11e9-8ca2-1f42fc066a5e.png)
I am not really worried about the difference in newlines since that is fairly trivial. However, if I do `(rainbow (square 15) 2)`, DrRacket gives:
![image](https://user-images.githubusercontent.com/4121024/65536053-9ff97380-ded0-11e9-8506-dd034428e715.png)
While racket-mode yields:
![image](https://user-images.githubusercontent.com/4121024/65536101-b30c4380-ded0-11e9-856f-b1b67ed47607.png)
Similar thing with `(rainbow (square 15) 3)`. However, `(rainbow (square 15) 1)` works:
![image](https://user-images.githubusercontent.com/4121024/65536190-ebac1d00-ded0-11e9-8df8-01df0f46cbfa.png)
And `(rainbow (square 15) 4)` works as well:
![image](https://user-images.githubusercontent.com/4121024/65536218-fbc3fc80-ded0-11e9-9459-c272313fbbad.png)
If I disable inline image rendering I get the following for the broken case `(rainbow (square 15) 2)`:
![image](https://user-images.githubusercontent.com/4121024/65536430-64ab7480-ded1-11e9-9eff-0da4e653f3c1.png)
So it only displays one image.
I have somewhat tracked this down to the file `print.rkt`, the following snippet:
```
(define (make-pretty-print-size-hook)
  (let ([orig (pretty-print-size-hook)]
        [width (floor (/ (pretty-print-columns) 4))]) ;magic number? yep.
    (λ (value display? port)
      (cond [(convert-image? value) width]
            [else                   (orig value display? port)]))))
```
By track this down I mean that if I change the magic number to 1... the issue disappears:
![image](https://user-images.githubusercontent.com/4121024/65536619-cb309280-ded1-11e9-8059-fdccf5c3fde5.png)

<details>
```
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
		 (20190924 1405)
		 "Major mode for Racket language."
		 ((emacs
		   (24 3))
		  (faceup
		   (0 0 2)))
		 nil nil "c:/Users/sturgmancohen/.emacs.d/elpa/racket-mode-20190924.1405"
		 ((:url . "https://www.racket-mode.com/")
		  (:maintainer "Greg Hendershott")
		  (:authors
		   ("Greg Hendershott")))
		 nil))
((emacs-version "26.1")
 (emacs-uptime "3 minutes, 16 seconds")
 (system-type windows-nt)
 (major-mode racket-repl-mode)
 (racket--el-source-dir "c:/Users/sturgmancohen/.emacs.d/elpa/racket-mode-20190924.1405/")
 (racket--rkt-source-dir "c:/Users/sturgmancohen/.emacs.d/elpa/racket-mode-20190924.1405/racket/")
 (racket-program "Racket.exe")
 (racket-command-port 55555)
 (racket-command-startup nil)
 (racket-command-timeout 10)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-retry-as-skeleton t)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-use-repl-submit-predicate nil)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal))))
(enabled-minor-modes
 (TeX-PDF-mode)
 (TeX-source-correlate-mode)
 (async-bytecomp-package-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-insert-mode)
 (auto-save-mode)
 (blink-cursor-mode)
 (desktop-save-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-eldoc-mode)
 (global-flycheck-mode)
 (global-font-lock-mode)
 (helm-mode)
 (line-number-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (override-global-mode)
 (paredit-mode)
 (persistent-scratch-autosave-mode)
 (recentf-mode)
 (shell-dirtrack-mode)
 (tooltip-mode)
 (transient-mark-mode)
 (yas-global-mode)
 (yas-minor-mode))
(disabled-minor-modes
 (LaTeX-math-mode)
 (TeX-Omega-mode)
 (TeX-interactive-mode)
 (abbrev-mode)
 (auto-fill-function)
 (auto-save-visited-mode)
 (buffer-read-only)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (company-mode)
 (company-search-mode)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (conda-env-autoactivate-mode)
 (defining-kbd-macro)
 (display-time-mode)
 (edebug-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-pair-mode)
 (electric-quote-mode)
 (flycheck-mode)
 (flymake-mode)
 (flyspell-mode)
 (global-company-mode)
 (global-prettify-symbols-mode)
 (global-visual-line-mode)
 (helm--minor-mode)
 (helm--remap-mouse-mode)
 (helm-autoresize-mode)
 (helm-ff--delete-async-modeline-mode)
 (helm-migemo-mode)
 (helm-popup-tip-mode)
 (horizontal-scroll-bar-mode)
 (hs-minor-mode)
 (ido-everywhere)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (next-error-follow-minor-mode)
 (org-bullets-mode)
 (org-cdlatex-mode)
 (org-src-mode)
 (orgstruct-mode)
 (outline-minor-mode)
 (outorg-edit-minor-mode)
 (outshine-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-check-syntax-mode)
 (sensitive-mode)
 (server-mode)
 (sh-electric-here-document-mode)
 (size-indication-mode)
 (temp-buffer-resize-mode)
 (tool-bar-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode)
 (winner-mode))
```
</details>

**Comment by greghendershott** [comment]
Thank you for reporting this.

Short answer: I think your change is the correct thing to do -- simply return `(pretty-print-columns)` as the "width".  That means a list of images will always be split across multiple lines, one image per line. And that will be OK.

---

I originally did this many years ago, so I don't recall the rationale exactly. I think the first thing that surprised me is that, unless you supply a `pretty-print-size-hook` that returns an integer, then your `pretty-print-hook` will be ignored -- it won't be used, at all.

In the case of displaying things in Emacs, we really don't have anything useful to say about the GUI width of the image or `pretty-print-columns` as it relates to Emacs buffer width. Forced to say _something_, I think I intended to say "assume we can fit about 4 images per line, because that seems to be true of most examples in the docs". Which is obviously a siilly assumption, but was the least-worst thing I could think of, then.

And I recall back then "it worked": Short lists of images would fit on one line, as in your DrRacket example.

But it doesn't work now, and there's the "empty square" bug you reported.

I don't understand why. Rather than try to figure it out, I'm inclined to make it stop trying (and failing) to be so clever. Instead: A list of images will print one per line, even if they might be small enough to print all on one line.

**Comment by greghendershott** [comment]
So I think the change I'll make is something like this:

```diff
@@ -22,8 +22,7 @@
 
 (define (make-pretty-print-size-hook)
-  (let ([orig (pretty-print-size-hook)]
-        [width (floor (/ (pretty-print-columns) 4))]) ;magic number? yep.
+  (let ([orig (pretty-print-size-hook)])
     (λ (value display? port)
-      (cond [(convert-image? value) width]
+      (cond [(convert-image? value) (pretty-print-columns)]
             [else                   (orig value display? port)]))))
 ```

**Comment by greghendershott** [comment]
Well, also adding this comment to help future-me: :smile:

```racket
;; We have nothing valuable to say about (a) pretty-print-columns as
;; it relates to Emacs window width or (b) the width in "characters"
;; of any particular image. Even so, we must say something. We must
;; supply a pretty-print-size-hook that returns _some_ integer width
;; -- else our pretty-print-hook won't be called. So simply return
;; pretty-print-columns. This means that e.g. a list of images will be
;; printed on multiple lines even if they could fit on one line.
;; That's less-worse than trying to be "clever"; see issue #402.
```
