### ISSUE TITLE
company-quickhelp opens *Racket Describe* buffer

### ISSUE THREAD

**Issue by andreyorst** [greghendershott/racket-mode#404]
Hello. This issue was described in this comment: https://github.com/greghendershott/racket-mode/issues/224#issuecomment-246083834, but the original issue was not about this particular problem:

>  racket-describe is invoked automatically for each of the company candidates. How do I disable this? I've company-quickhelp and it does the same, and racket-describe on every completion candidate SLOWS things down a lot.

I'm using [company-quickhelp](https://github.com/expez/company-quickhelp) package, and find it very helpful when I interact with new functions, and since I'm actively learn Racket, everything is new for me. 

The issue described in that comment, is half true for me, since I don't experience much of a slowdown because of this, but this behavior is a bit annoying.

This is how it looks on my setup:
![Screenshot from 2019-10-20 11-14-45](https://user-images.githubusercontent.com/19470159/67156711-fb315100-f32a-11e9-8590-1f93082c291f.png)

So I want to use `company-quickhelp` to read documentation while I write code, but I don't want a separate buffer to pop up every time. This doesn't happen when I use [geiser](https://www.nongnu.org/geiser/) for example:

![Screenshot from 2019-10-20 11-22-55](https://user-images.githubusercontent.com/19470159/67156817-020c9380-f32c-11e9-88ae-5302d2a59ad3.png)

I don't use Geiser for Racket, because your mode is superior to it, but this also doesn't happen in other `company-quickhelp` supported modes, like Emacs Lisp. So I believe, this issue is related to racket mode only.

<details>
```
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
                 (20191016 1311)
                 "Major mode for Racket language."
                 ((emacs
                   (24 3))
                  (faceup
                   (0 0 2)))
                 nil nil "/home/andreyorst/.emacs.d/elpa/racket-mode-20191016.1311"
                 ((:url . "https://www.racket-mode.com/")
                  (:maintainer "Greg Hendershott")
                  (:authors
                   ("Greg Hendershott")))
                 nil))
((emacs-version "27.0.50")
 (emacs-uptime "9 minutes, 15 seconds")
 (system-type gnu/linux)
 (major-mode racket-mode)
 (racket--el-source-dir "/home/andreyorst/.emacs.d/elpa/racket-mode-20191016.1311/")
 (racket--rkt-source-dir "/home/andreyorst/.emacs.d/elpa/racket-mode-20191016.1311/racket/")
 (racket-program "racket")
 (racket-command-port 55555)
 (racket-command-startup nil)
 (racket-command-timeout 10)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-retry-as-skeleton t)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-use-repl-submit-predicate nil)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal))))
(enabled-minor-modes
 (async-bytecomp-package-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-revert-mode)
 (auto-save-mode)
 (blink-cursor-mode)
 (company-flx-mode)
 (company-mode)
 (company-quickhelp-local-mode)
 (company-quickhelp-mode)
 (display-line-numbers-mode)
 (doom-modeline-mode)
 (electric-indent-mode)
 (eyebrowse-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (gcmh-mode)
 (global-company-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-magit-file-mode)
 (global-tab-line-mode)
 (global-undo-tree-mode)
 (hl-line-mode)
 (hs-minor-mode)
 (ivy-mode)
 (magit-auto-revert-mode)
 (magit-file-mode)
 (minions-mode)
 (mouse-wheel-mode)
 (override-global-mode)
 (parinfer-mode)
 (recentf-mode)
 (savehist-mode)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (solaire-global-mode)
 (solaire-mode)
 (transient-mark-mode)
 (treemacs-filewatch-mode)
 (treemacs-follow-mode)
 (treemacs-fringe-indicator-mode)
 (treemacs-git-mode)
 (undo-tree-mode)
 (window-divider-mode)
 (yas-minor-mode))
(disabled-minor-modes
 (abbrev-mode)
 (ace-window-display-mode)
 (ace-window-mode)
 (auto-fill-function)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (avy-linum-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (company-search-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (counsel-mode)
 (defining-kbd-macro)
 (delete-selection-mode)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (display-time-mode)
 (doc-view-minor-mode)
 (doc-view-presentation-mode)
 (eldoc-box-hover-at-point-mode)
 (eldoc-box-hover-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-pair-mode)
 (electric-quote-mode)
 (flymake-mode)
 (flyspell-mode)
 (git-commit-mode)
 (global-auto-revert-mode)
 (global-display-line-numbers-mode)
 (global-hl-line-mode)
 (global-prettify-symbols-mode)
 (global-visual-line-mode)
 (horizontal-scroll-bar-mode)
 (ido-everywhere)
 (image-minor-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (line-number-mode)
 (magit-blame-mode)
 (magit-blame-read-only-mode)
 (magit-blob-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (magit-wip-initial-backup-mode)
 (magit-wip-mode)
 (mail-abbrevs-mode)
 (menu-bar-mode)
 (mml-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (parinfer-region-mode)
 (prettify-symbols-mode)
 (racket-check-syntax-mode)
 (server-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (size-indication-mode)
 (smerge-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-resume-mode)
 (treemacs-tag-follow-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (which-function-mode)
 (with-editor-mode)
 (xref-etags-mode)
 (yas-global-mode))
```
</details>

**Comment by greghendershott** [comment]
Only just have a moment to look at this, now. To make sure I understand:

You are seeing both a "popup" from `company-quickhelp` as well as a `*Racket Describe*` buffer appear. You only want the former to appear. Is that correct?

It's been awhile so I don't remember the details without diving into the code, but maybe there is some parameter that Racket Mode is ignoring, about whether to show a buffer or simply return the text to display. (Is my first, quick guess.)

---

By the way, I notice the formatting in the popup is not quite as "nice" or "correct" as that in the `*Racket Describe*` buffer. That's probably the least of your worries, now ... but, it might be your next bug report after the main problem is fixed :smile: so I will try to look at both problems at once.

**Comment by andreyorst** [comment]
> You are seeing both a "popup" from company-quickhelp as well as a *Racket Describe* buffer appear. You only want the former to appear. Is that correct?

Correct. I have two windows side by side, one with Racket buffer, and one with Racket REPL. When I'm typing something, a popup appears, and the other window is switching to the `*Racket Describe*` buffer. If I close it, after popup appears again it is created.

Actually I've noticed that I was wrong at one thing. In case of Emacs Lisp the `*Help*` buffer **is** created, but not selected to display. So maybe that's the only part needed to be changed.

> By the way, I notice the formatting in the popup is not quite as "nice" or "correct" as that in the *Racket Describe* buffer. That's probably the least of your worries, now ... but, it might be your next bug report after the main problem is fixed smile so I will try to look at both problems at once.

That's a good point! But actually I didn't noticed that :smile: so maybe I would never do. FYI `company-quickhelp` has this setting `company-quickhelp-use-propertized-text`, which I set to `t`:

> Documentation:
> Allow the text to have properties like color, font size, etc.

Maybe you can take advantage of it. But I never seen it working so it's not a big deal.

**Comment by greghendershott** [comment]
The main problem turned out to be very simple to fix. Racket Mode was calling `display-buffer` when it didn't need to. Vanilla company calls it, so it was an unnoticed and harmless redundancy.

The formatting... I started to look into it, but it wasn't immediately clear. I decided to merge the fix for this main issue. If you or someone else wants to open a new issue about the formatting -- essentially there seems to be a "missing newline" -- I'm not discouraging you. If it bothers you, please do! But I won't proactively work on it until/unless it matters enough to someone.
