### ISSUE TITLE
If there's a way to set breakpoint in debug mode?

### ISSUE THREAD

**Issue by Loutine** [greghendershott/racket-mode#409]
Thanks for this excellent tool it's really convenient , it's fantastic to write Racket program on emacs by using this :smile:  
But I wonder if there's a way to set breakpoint like in drracket (pause at this point) to debug. I only find a way to debug step by step, haven't found a way to set the points in doc :cry: that really confused me. 
Have this function removed?

**Comment by greghendershott** [comment]
Try <kbd>h</kbd> a.k.a. `M-x racket-debug-run-to-here`.

In other words, what's exposed in the UI today is a single breakpoint. Move point somewhere, press <kbd>h</kbd>, a one-shot breakpoint is put there, and you resume until/unless you land there.

---

(At one point I had multiple arbitrary breakpoints. In fact a lot of code for that lurks in the background. (I even experimented with watchpoints a.k.a. _conditional_ breakpoints.) But I focused this down to just "run to  here" in the UI -- and in the Emacs front-end <=> Racket back-end command protocol -- in an effort to release something slightly less "EXPERIMENTAL!" and more usable.)

**Comment by Loutine** [comment]
thanks for your reply and patience. that's enough for my work now :smile:

**Comment by Loutine** [comment]
really useful especially for students like me.
