### ISSUE TITLE
There is no racket-switch-to-repl

### ISSUE THREAD

**Issue by xuchunyang** [greghendershott/racket-mode#412]
C-h f racket-run-and-switch-to-repl mentions

    This is `racket-run' followed by `racket-switch-to-repl'.

however, unlike `racket-run`, there is no function `racket-switch-to-repl`.

**Comment by greghendershott** [comment]
Thanks for pointing this out. The doc string did not get updated after some things changed.

It should say:

    This is `racket-run' followed by `racket-repl'.
