### ISSUE TITLE
Completion for local variables in let

### ISSUE THREAD

**Issue by xuchunyang** [greghendershott/racket-mode#413]
For example, `foo` should complete to `foobar` or `foobaz`, however, there is no completions for now in Racket Mode.

```racket
#lang racket

(let ([foobar 12]
      [foobaz 34])
  (+ foo))
```

the following are Emacs Lisp's

![Screen Shot 2020-01-15 at 22 39 19](https://user-images.githubusercontent.com/4550353/72442678-e8260400-37e7-11ea-9b1b-b96322c6671b.png)

Geiser with Scheme (such as Guile) supports simple case like above as well if I remember correctly, though Racket seems are much more complex than Emacs Lisp and Scheme.

**Comment by greghendershott** [comment]
As it happens, for the last week I've been working on changing `racket-check-syntax-mode` from a read-only thing, into one which you can have enabled even while you edit the buffer. And one aspect of that is that it can contribute local definitions as completion candidates.

Those commits are currently on a [`check-syntax` branch](https://github.com/greghendershott/racket-mode/tree/check-syntax). There has been a fair amount to figure out, and to refine (as a result of me actually using it a.k.a. dog-fooding it for a few days). I'm not sure when I'd feel good about merging it to `master`. I hope in a matter of days or weeks, not months.

**Comment by greghendershott** [comment]
This now works when the new [`racket-xp-mode`](https://www.racket-mode.com/#racket_002dxp_002dmode) is enabled, which is now merged to `master`, so I'm closing this.
