### ISSUE TITLE
How to sort completion candidates by length?

### ISSUE THREAD

**Issue by xuchunyang** [greghendershott/racket-mode#419]
I type `exn:fail` and find `exn:fail?` is in the very end, even it is only one character away, it should be the second candidate

![Screen Shot 2020-01-21 at 06 54 22](https://user-images.githubusercontent.com/4550353/72762526-e068c400-3c1a-11ea-8c84-a015929c62ef.png)

I understand it's due to the candidate list is in lexicographic order, It seems it makes more sense to sort by length (if the two lengths are equals then sort by alphabetical).

I've tried changed the order of symbols returned by the racket command server, but both the builtin `C-M-i` (`complete-symbol`) and Company Mode doesn't care at all, I don't know what's going on, and Emacs's Programmed Completion is complex and very difficult to understand.

```diff
diff --git a/racket/command-server.rkt b/racket/command-server.rkt
index 8bbf028..745f0f2 100644
--- a/racket/command-server.rkt
+++ b/racket/command-server.rkt
@@ -211,7 +211,10 @@
 
 (define (syms)
   (sort (map symbol->string (namespace-mapped-symbols))
-        string<?))
+        (lambda (s1 s2)
+          (if (= (string-length s1) (string-length s2))
+              (string<? s1 s1)
+              (< (string-length s1) (string-length s2))))))
 
 ;;; eval-commmand
 
```

**Comment by greghendershott** [comment]
>  I don't know what's going on, and Emacs's Programmed Completion is complex and very difficult to understand.

Yes it is pretty complicated. For example `completion-at-point-functions` is plural: There can be multiple sources of completions. So it makes sense that sorting would (or could) happen where the sources are combined into one list.

For company-mode it looks like you can supply your own sorting function in the customization variable [`company-transformers`](https://github.com/company-mode/company-mode/blob/d5053561cb166e03051c60e5c1e05a8a926dfee5/company.el#L489)?

---

I found that by [searching for issues that mention "sort"](https://github.com/company-mode/company-mode/issues?page=2&q=is%3Aissue+sort&utf8=%E2%9C%93), and paging through until I noticed ["Sort uppercase completions to the bottom #511"](https://github.com/company-mode/company-mode/issues/511) which had [this comment](https://github.com/company-mode/company-mode/issues/511#issuecomment-219016047).

**Comment by xuchunyang** [comment]
`company-transformers` is likely the solution for Company Mode, but it applies to all company completions, and alphabetical order seems to be a good default choice, I have been using company  for a long time happily, for this particular case is that mainly because Racket prefers `?` but `?` is larger than `-` and `:`. I decide to not worry about this issue for now, just enter `?` by myself.
