### ISSUE TITLE
complete require's module-path

### ISSUE THREAD

**Issue by xuchunyang** [greghendershott/racket-mode#420]
For example `(require net/)` should suggest

```
net/url
net/head
net/http-client
...
```

**Comment by greghendershott** [comment]
Yes, this is a great idea. Likewise for relative paths like "file.rkt", "../file.rkt", "path/to/file.rkt".

I've been meaning to get to this for awhile. I think I will try to tackle it when I get a breather from my deep dive the last few weeks into check-syntax mode.

**Comment by greghendershott** [comment]
Re the relative requires: It's probably possible to configure some "file system" candidates back-end for company-mode. However it would be nice if that did not contribute candidates everywhere, just while point is inside a require form. And it would be nice if it "just worked" as part of the default completion provided by Racket Mode.
