### ISSUE TITLE
Function signature hinting

### ISSUE THREAD

**Issue by Inc0ns1st3nt** [greghendershott/racket-mode#429]
For my lisp setup, Emacs would show the signature of the current function under the cursor, under the status-bar.
For example, for a function 'list-length' was defined `(define (list-length lst) ...)`, so it would hint `(list-length lst)`.
This would save me from looking up the function online.

**Comment by greghendershott** [comment]
That's `eldoc-mode` and it doesn't work as well for some languages, including Racket: [Explanation](https://www.racket-mode.com/#eldoc). TL;DR I recommend trying <kbd>C-c C-.</kbd> a.k.a. `racket-describe`.

There is an upcoming improvement in commit 3baf9e but that's on a `check-syntax` branch that's not yet merged to `master`. Also, that is limited to functions where someone has written Racket documentation, and it often will not fit in a single echo area line as with classic eldoc.
