### ISSUE TITLE
racket--font-lock-sexp-comments does not match racket behavior

### ISSUE THREAD

**Issue by tgbugs** [greghendershott/racket-mode#432]
Paste the following block into a racket-mode buffer.
```racket
#; ; this comments out the second sexp
   ; the racket reader skips over the intervening comment
   ; because it is a comment (I think)
#; ; this comments out the first sepx
(first sexp to be commented out)
(second sexp to be commented out is not highlighted)
```
If you run the code you will not get the error you would expect based on fontification.
The second sexp is not highlighted despite the fact that racket does not execute it.
I encountered this while writing tests to try and replicate racket-mode's fontification for a common lisp reader macro that does the same thing.

This is a fontification edge case.
The smallest repro is
```racket
#; #; 'one 'two 'three
```

<details>
```
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
                 (20200115 2148)
                 "Major mode for Racket language."
                 ((emacs
                   (24 3))
                  (faceup
                   (0 0 2)))
                 nil nil "/home/tom/.emacs.d/elpa/racket-mode-20200115.2148"
                 ((:url . "https://www.racket-mode.com/")
                  (:maintainer "Greg Hendershott")
                  (:authors
                   ("Greg Hendershott")))
                 nil)
 #s(package-desc racket-mode
                 (20191204 205)
                 "Major mode for Racket language."
                 ((emacs
                   (24 3))
                  (faceup
                   (0 0 2)))
                 nil nil "/home/tom/.emacs.d/elpa/racket-mode-20191204.205"
                 ((:url . "https://www.racket-mode.com/")
                  (:maintainer "Greg Hendershott")
                  (:authors
                   ("Greg Hendershott")))
                 nil))
((emacs-version "26.3")
 (emacs-uptime "19 hours, 20 minutes, 38 seconds")
 (system-type gnu/linux)
 (major-mode racket-mode)
 (racket--el-source-dir "/home/tom/.emacs.d/elpa/racket-mode-20200115.2148/")
 (racket--rkt-source-dir "/home/tom/.emacs.d/elpa/racket-mode-20200115.2148/racket/")
 (racket-program "racket")
 (racket-command-port 55555)
 (racket-command-startup nil)
 (racket-command-timeout 10)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-retry-as-skeleton t)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-use-repl-submit-predicate nil)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal))))
(enabled-minor-modes
 (async-bytecomp-package-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (csv-field-index-mode)
 (diff-auto-refine-mode)
 (display-line-numbers-mode)
 (electric-indent-mode)
 (electric-pair-mode)
 (evil-local-mode)
 (evil-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-display-line-numbers-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-magit-file-mode)
 (global-undo-tree-mode)
 (global-visual-line-mode)
 (hs-minor-mode)
 (line-number-mode)
 (magit-auto-revert-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (org-src-mode)
 (override-global-mode)
 (rainbow-delimiters-mode)
 (savehist-mode)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (tooltip-mode)
 (transient-mark-mode)
 (undo-tree-mode)
 (url-handler-mode)
 (visual-line-mode)
 (which-function-mode))
(disabled-minor-modes
 (abbrev-mode)
 (archive-subfile-mode)
 (auto-complete-mode)
 (auto-fill-function)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (bibtex-completion-notes-global-mode)
 (bibtex-completion-notes-mode)
 (blink-cursor-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (bug-reference-mode)
 (bug-reference-prog-mode)
 (cider--debug-mode)
 (cider-auto-test-mode)
 (cider-enlighten-mode)
 (cider-mode)
 (cider-popup-buffer-mode)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (csv-align-mode)
 (cua-mode)
 (cursor-intangible-mode)
 (cursor-sensor-mode)
 (defining-kbd-macro)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (display-time-mode)
 (doc-view-minor-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (elpy-django)
 (elpy-mode)
 (ess-debug-minor-mode)
 (ess-r-package-mode)
 (ess-roxy-mode)
 (eval-sexp-fu-flash-mode)
 (evil-leader-mode)
 (evil-magit-toggle-text-minor-mode)
 (evil-org-mode)
 (evil-paredit-mode)
 (flycheck-mode)
 (flymake-mode)
 (flyspell-mode)
 (git-commit-mode)
 (global-auto-complete-mode)
 (global-auto-revert-mode)
 (global-evil-leader-mode)
 (global-flycheck-mode)
 (global-hl-line-mode)
 (global-prettify-symbols-mode)
 (global-reveal-mode)
 (gnuplot-context-sensitive-mode)
 (gnus-dead-summary-mode)
 (gnus-undo-mode)
 (goto-address-mode)
 (goto-address-prog-mode)
 (helm--minor-mode)
 (helm--remap-mouse-mode)
 (helm-autoresize-mode)
 (helm-display-line-numbers-mode)
 (helm-migemo-mode)
 (helm-popup-tip-mode)
 (highlight-numbers-mode)
 (hl-line-mode)
 (horizontal-scroll-bar-mode)
 (html-autoview-mode)
 (ido-everywhere)
 (image-minor-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (js2-highlight-unused-variables-mode)
 (js2-minor-mode)
 (macrostep-mode)
 (magit-blame-mode)
 (magit-blame-read-only-mode)
 (magit-blob-mode)
 (magit-file-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (magit-wip-initial-backup-mode)
 (magit-wip-mode)
 (mail-abbrevs-mode)
 (markdown-live-preview-mode)
 (mml-mode)
 (next-error-follow-minor-mode)
 (ob-ipython-mode)
 (org-cdlatex-mode)
 (org-table-follow-field-mode)
 (orgtbl-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (paredit-mode)
 (prettify-symbols-mode)
 (pyvenv-mode)
 (pyvenv-tracking-mode)
 (racket-check-syntax-mode)
 (recentf-mode)
 (rectangle-mark-mode)
 (reftex-mode)
 (reveal-mode)
 (server-mode)
 (sgml-electric-tag-pair-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (size-indication-mode)
 (slime-autodoc-mode)
 (slime-edit-value-mode)
 (slime-editing-mode)
 (slime-fuzzy-target-buffer-completions-mode)
 (slime-macroexpansion-minor-mode)
 (slime-mode)
 (slime-popup-buffer-mode)
 (slime-repl-map-mode)
 (slime-repl-read-mode)
 (slime-trace-dialog-autofollow-mode)
 (slime-trace-dialog-hide-details-mode)
 (slime-trace-dialog-minor-mode)
 (smerge-mode)
 (table-fixed-width-mode)
 (table-mode-indicator)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (transient-resume-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (use-hard-newlines)
 (vc-parent-buffer)
 (vdiff-3way-mode)
 (vdiff-mode)
 (vdiff-scroll-lock-mode)
 (view-mode)
 (visible-mode)
 (window-divider-mode)
 (with-editor-mode)
 (xref-etags-mode))
```
</details>

**Comment by tgbugs** [comment]
Having looked around a bit more, I have a suspicion that this might be because of the decision to treat the comment as if it were a quote for the purposes of syntax.
https://github.com/greghendershott/racket-mode/blob/7a1414f83981aa174feba28f3d83e95574c7f075/racket-common.el#L117
This means that what emacs sees is actually `(quote (quote 'one)) 'two 'three`.

**Comment by greghendershott** [comment]
Thanks for reporting this. I think the short/honest answer is that I didn't even imagine the case of successive `#;`s -- a sexp comment where the next sexp is another sexp comment. (I think that's because it's a (very?) uncommon case in the wild, and, you could argue this bug should be triaged pretty low on the priority list. But it is good to know about!) So it's not even attempting to handle that.

Sexp comments are interesting because they mix font-lock, indentation, and reader macros that expand into parenthesized expressions.

My quick guess is the last element is what's contributing to the problem here. Possibly similar problems (if not this exact bug) lurk with other reader macros that expand into `quote`, `quasiquote`, `syntax`, `quasisyntax`, and so on. 

I'm not immediately sure how to handle this in a principled way without some reader-macro-expansion pass that is probably impractical for plain `racket-mode` and "normal" Emacs techniques. Maybe it is something that could be handled by the upcoming `racket-xp-mode` on the `check-syntax` branch. In that case maybe `racket-mode` would no longer attempt to handle sexp-comments at all. Or, maybe it would do status quo as a baseline, and `racket-xp-mode` (if enabled) would replace/enhance that with the full/correct way.

Disclaimer: The above is me just thinking/typing out loud on a Sunday morning needing another cup of coffee.

**Comment by tgbugs** [comment]
Quite a low priority, but wanted to get it logged.
Indeed, the absence of reader macros in emacs makes this decidedly non-trivial to implement.

One other place that implements something similar to your proposed racket-xp-mode solution is slime's handling of feature expressions [0]. [`slime-activate-font-lock-magic`](https://github.com/slime/slime/blob/cd8cc3c95c3391b1f1cffa9e100336250a4509a7/contrib/slime-fontifying-fu.el#L186) and [`slime-forward-reader-conditional`](https://github.com/slime/slime/blob/cd8cc3c95c3391b1f1cffa9e100336250a4509a7/slime.el#L7401) are the combination that seems to produced the correct behavior most of the time, but even there I find some edge cases when new lines are involved. Examples below.

```lisp
#+() #+() 'one 'two 'three

#+()
#+()
'one
'two
'three

#+()
#+()
'one
'two 'three

#+()
#+()
'one
'two
'three

#+()
#+()
'one
'two
'three

#+() #+() 'one 'two 'three

#+()
(this is suppressed ; this is a comment)
      this is suppressed)
```


0. Sort of note to self. One difference is that slime does actually have to evaluate the feature expressions to know whether they are on or off, in principle racket doesn't have to do that, they are always off, so in principle [this line](https://github.com/slime/slime/blob/cd8cc3c95c3391b1f1cffa9e100336250a4509a7/contrib/slime-fontifying-fu.el#L53) and [this result](https://github.com/slime/slime/blob/cd8cc3c95c3391b1f1cffa9e100336250a4509a7/slime.el#L7406-L7410) could simply be set to false. I don't think this affects indentation or other editing behavior.

**Comment by tgbugs** [comment]
I have mostly gotten this to work on my end (with slime's help skipping over cruft I think). The implementation is in [datum-comments.el](https://github.com/tgbugs/datum-comments/blob/master/datum-comments.el). I change ` (0 "'")` to ` (0 "_")` and modify [`slime-forward-cruft`](https://github.com/tgbugs/datum-comments/blob/31f13809e62675f24547b18c229ed819bc1f4937/datum-comments.el#L115) to know about datum comments. Then [`slime-forward-sexp`](https://github.com/slime/slime/blob/cd8cc3c95c3391b1f1cffa9e100336250a4509a7/slime.el#L7389) takes care of the rest during [fontification](https://github.com/slime/slime/blob/cd8cc3c95c3391b1f1cffa9e100336250a4509a7/contrib/slime-fontifying-fu.el#L64).

Translated into racket mode, I think this means the addition of a `racket-forward-sexp` that is used for fontification, and possibly also to avoid sending commented code to the repl.
