### ISSUE TITLE
next-error (M-g n) rebound to racket-xp-next-reror

### ISSUE THREAD

**Issue by Bogdanp** [greghendershott/racket-mode#438]
<details>
<pre>
((alist-get 'racket-mode package-alist))
((emacs-version "26.3")
 (emacs-uptime "18 hours, 42 minutes, 44 seconds")
 (system-type darwin)
 (major-mode racket-mode)
 (racket--el-source-dir "/Users/bogdan/.emacs.d/vendor/racket-mode/")
 (racket--rkt-source-dir "/Users/bogdan/.emacs.d/vendor/racket-mode/racket/")
 (racket-program "racket")
 (racket-command-port 55555)
 (racket-command-timeout 10)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-use-repl-submit-predicate nil)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal))))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (column-number-mode)
 (company-mode)
 (cursor-sensor-mode)
 (diff-auto-refine-mode)
 (dired-omit-mode)
 (dumb-jump-mode)
 (electric-indent-mode)
 (evil-local-mode)
 (evil-mode)
 (file-name-shadow-mode)
 (flx-ido-mode)
 (flycheck-mode)
 (font-lock-mode)
 (global-auto-revert-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-hl-line-mode)
 (global-magit-file-mode)
 (global-undo-tree-mode)
 (hs-minor-mode)
 (ido-everywhere)
 (ido-ubiquitous-mode)
 (ido-vertical-mode)
 (line-number-mode)
 (mac-mouse-wheel-mode)
 (magit-file-mode)
 (menu-bar-mode)
 (override-global-mode)
 (paredit-mode)
 (projectile-mode)
 (racket-xp-mode)
 (rainbow-delimiters-mode)
 (recentf-mode)
 (save-place-mode)
 (savehist-mode)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (transient-mark-mode)
 (undo-tree-mode))
(disabled-minor-modes
 (abbrev-mode)
 (auto-fill-function)
 (auto-image-file-mode)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (blink-cursor-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (bug-reference-mode)
 (bug-reference-prog-mode)
 (cl-old-struct-compat-mode)
 (company-search-mode)
 (compilation-in-progress)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (cua-mode)
 (cursor-intangible-mode)
 (defining-kbd-macro)
 (desktop-save-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (dired-isearch-filenames-mode)
 (diredp-breadcrumbs-in-header-line-mode)
 (display-time-mode)
 (doc-view-minor-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-pair-mode)
 (electric-quote-mode)
 (flyspell-mode)
 (git-commit-mode)
 (global-company-mode)
 (global-dired-hide-details-mode)
 (global-flycheck-mode)
 (global-prettify-symbols-mode)
 (global-reveal-mode)
 (global-visual-line-mode)
 (gnus-dead-summary-mode)
 (gnus-undo-mode)
 (hl-line-mode)
 (horizontal-scroll-bar-mode)
 (html-autoview-mode)
 (ibuffer-auto-mode)
 (ido-cr+-debug-mode)
 (image-dired-minor-mode)
 (image-minor-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (mac-auto-ascii-mode)
 (mac-auto-operator-composition-mode)
 (mac-font-panel-mode)
 (magit-auto-revert-mode)
 (magit-blame-mode)
 (magit-blame-read-only-mode)
 (magit-blob-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (magit-wip-initial-backup-mode)
 (magit-wip-mode)
 (mail-abbrevs-mode)
 (minibuffer-electric-default-mode)
 (mml-mode)
 (mouse-wheel-mode)
 (next-error-follow-minor-mode)
 (org-cdlatex-mode)
 (org-src-mode)
 (orgstruct-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (pyvenv-mode)
 (pyvenv-tracking-mode)
 (racket-smart-open-bracket-mode)
 (rectangle-mark-mode)
 (reveal-mode)
 (server-mode)
 (sgml-electric-tag-pair-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (size-indication-mode)
 (smerge-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-resume-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-parent-buffer)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (which-function-mode)
 (window-divider-mode)
 (with-editor-mode)
 (xref-etags-mode))
</pre>
</details>

I frequently use `compile` and run project-wide `ag`s to search for keywords then cycle through the search results using `next-error`, which is normally bound to `M-g n`. I noticed this broke for me inside Racket buffers a while ago, but didn't dig into it until today and I see now that it's because `racket-xp-mode` rebinds `M-g n` to `racket-xp-next-error`. The effect, for me, is that I'll run a search from a Racket buffer, see a new compile buffer pop up with all the search results and hit `M-g n` to go to the first one and I'll get a message saying "No more errors yet", which isn't what I would have expected. 

I think either `racket-xp-mode` should avoid rebinding the built-in keybinding or fall back to `next-error` when there are no Racket errors. While the latter would work, it might not be the right thing to do because the expectation with `next-error` is that it cycles through errors based on the output of a compilation command, I think. From `next-error`'s docstring:

```

M-x next-error normally uses the most recently started
compilation, grep, or occur buffer.  It can also operate on any
buffer with output from the M-x compile, M-x grep commands, or,
more generally, on any buffer in Compilation mode or with
Compilation Minor mode enabled, or any buffer in which
‘next-error-function’ is bound to an appropriate function.
To specify use of a particular buffer for error messages, type
M-x next-error in that buffer when it is the only one displayed
in the current frame.

```

In the mean time I think I can solve the problem for myself by binding `M-g n` to `next-error` in the `racket-xp-mode-map` so this isn't a big issue, but it is something that could disrupt someone's normal workflow, like it did mine -- I was just too lazy to look into it until now.

**Comment by greghendershott** [comment]
Thanks for the report! I agree with you in principle. In fact, I did spend what felt like a lot of time, trying to make `racket-xp-mode` work with the `next-error-function` approach. The problem I had, IIRC, was that if a compilation or REPL buffer existed and had a window (i.e. was on screen), even if it was not selected, it would _always_ be chosen.

So for example, if you were in a`racket-xp-mode` buffer, it had a syntax error, you choose next-error -- it would report "No errors" because next-error chooses the other, non-selected buffer as the source of errors. This sucked.

I wasn't able to figure out how to make `next-error-find-buffer` choose the `racket-xp-mode` buffer when it did in fact have errors, else some other buffer. Which I think is the desired behavior.

Although I felt like I spent enough time on this, before, to justify taking the decision I made, then, I think it's worth spending more time, now, so I'll look at this again.

**Comment by greghendershott** [comment]
I looked at this again. When there are no check-syntax, errors, I was trying to delegate to the default thing. But I think I had too-specific an idea of the default thing. I was calling `compilation-next-error-function` in the REPL buffer. Although that covers runtime errors, in the REPL, that would ignore `copmilation-mode` buffers.

Instead I think I should delegate by calling `next-error`. In my quick experiment, that seems to handle both cases, REPL and `compilation-mode`. Maybe it's that simple. I'm not yet sure if that really works, or if it just makes the bump in the carpet pop up somewhere else....

**Comment by greghendershott** [comment]
@Bogdanp Maybe you could try the change in commit 9090e73 and see if that handles your scenario(s)? If so, I'll think about it a bit more and possibly merge to `master`.

**Comment by Bogdanp** [comment]
@greghendershott thanks! That works in most cases for me. One thing I do often is I'll rename a function that's being used in a module (but defined elsewhere) then search for other usages and update them across a project. The way 9090e73 works, once I rename the function at the use site, it'll become a Racket error so I won't be able to jump through the search results. So it seems like compilation output should take precedence over racket errors. That said, I understand that that might be too specific to my own workflow or too complicated to be worth doing. 

Either way, 9090e73 is an improvement and it's easy to go back to the old behavior by rebinding `M-g {M,}-{p,n}` to `{previous,next}-error`.

**Comment by greghendershott** [comment]
Interesting. I felt like `racket-xp-mode` should take priority, when it has an error, because a syntax error is sometimes non-specific i.e. the start of the file. If you want to see the message, the only way is to go there. (I experimented with always showing syntax errors, but, that gets really noisy/distracting while actively editing. Plus Typed Racket can elicit > 1 error.) So that was the justification.

It's too bad `next-error` doesn't have a more flexible "protocol" for deciding, when there are multiple buffers that could provide errors, which one to use as the source. At least not that I could see.

I 100% hear this still isn't ideal for you so I will still think about ways to improve it.

**Comment by greghendershott** [comment]
Maybe in the meantime I will still merge that commit, but change it from "fixes #438" to "mitigates #438" or whatever -- that is, it helps but doesn't fully close this issue.

**Comment by greghendershott** [comment]
I thought more and I agree with your other suggestion: Don't rebind the `{next previous}-error` keys.

Needing to type `C-# N` for `racket-xp-next-error` isn't really any worse than typing `` C-x ` `` or `M-g n`, and there's no ambiguity, and anyway a user can rebind any of these as they like.

I pushed a commit (not yet merged to `master`) doing that -- in addition to the commit I'd already pushed implementing your other suggestion. TL;DR I will end up doing all of what you suggested in the first place. :smile:

**Comment by greghendershott** [comment]
Originally I thought using those keys made sense, because they're already overloaded to mean "next/previous interesting thing" for compilation, grep, and occur. However, those work via having a dedicated _major_ mode buffer like `*compilation-mode*` or `*grep*`, for the errors/results. It's not really set up to work well and as-intended, unless I were to add a "racket syntax errors" buffer dedicated just to this -- but that feels like overkill.
