### ISSUE TITLE
Feature request: show logger-based DrRacket tooltips in racket-xp-mode

### ISSUE THREAD

**Issue by david-christiansen** [greghendershott/racket-mode#451]
Thanks for `racket-xp-mode` - it's great!

In DrRacket, macros can add tooltips to the source code using syntax properties or loggers. This is used in Typed Racket and in Pie to show the types of subexpressions, and it's quite useful. Would it be possible to expose this information in `racket-xp-mode` as well? I believe that `racket-check-syntax-mode` showed this info, based on #241 :-)

Thanks!

**Comment by greghendershott** [comment]
Interesting, AFAIK it is showing all `syncheck:add-mouse-over-status` annotations that `drracket/check-syntax` produces. (Except it filters those with bogus position information; maybe that's it?) Anyway, glad to take a look and fix!

To give me a head-start, could you please show me an example of a simple `#lang typed/racket` program that you would see annotated in DrRacket, and tell me where it would show a tooltip (what expression)?

**Comment by greghendershott** [comment]
@david-christiansen I tried writing some simple Typed Racket programs that use (what I believe to be) "subexpressions" -- but I'm not seeing any interesting tooltips in DrRacket.

For instance, in this little program:

```racket
#lang typed/racket/base

(define x 42)
(define y (+ x 12))
x
y
```

I think `(+ x 12)`, `x`, and `12` are all subexpressions? But hovering over every character of that, one by one, in DrRacket all I see for textual tooltips is that `+` is "imported from typed/racket/base" (plus the arrows for `+` and `x`).

Probably I'm being dense. If you can give me some such example, that would help me figure out how/why Racket Mode's use of `drracket/check-syntax` is not showing these things that DrRacket does show.

**Comment by david-christiansen** [comment]
Sorry for the slow answer here!

Here's one example:
```
#lang typed/racket

42
```
When I mouse over `42` in DrRacket, I get a tooltip that says "Positive-Byte", which is the inferred type for that expression. I get the same result in `typed/racket/base`, interestingly. In Emacs in `racket-xp-mode`, I don't get this tooltip. However, if I replace `42` with `car`, I get a tooltip in Emacs that says it's imported from the language.

Similarly, Pie programs have no type tooltips for me in Emacs. In this program, I get a tooltip over `5` in DrRacket that says it's a `Nat`:
```
#lang pie

5
```
but I don't get it in `racket-xp-mode`.

Interestingly enough, the following works:
```
#lang racket

(define-syntax (tooltip stx)
  (syntax-case stx ()
    [(_ e) (syntax-property #'e 'mouse-over-tooltips (vector stx (sub1 (syntax-position stx)) (sub1 (+ (syntax-position stx) (syntax-span stx))) "tooltip!"))]))

(tooltip 42)
```

The `tooltip` form gets a tooltip in Emacs that says `tooltip!`, just as in DrRacket.

I think that the issue is that both Pie and Typed Racket use a logger to create the tooltips, rather than a syntax property. This lets them attach type info to a file that doesn't completely expand, e.g. due to a type error. Here's a minimal example of that technique, which indeed works for me in DrRacket but not Emacs:
```
#lang racket

(begin-for-syntax
  (define-logger online-check-syntax)
  (define (tooltip! stx)
    (log-message online-check-syntax-logger 'info "Ignored" (list (syntax-property #'ignored 'mouse-over-tooltips (vector stx (sub1 (syntax-position stx)) (sub1 (+ (syntax-position stx) (syntax-span stx))) "tooltip!"))))))

(define-syntax (tooltip stx)
  (syntax-case stx ()
    [(_ e) (tooltip! stx) #'e]))

(tooltip 42)
```
I suspect that the `check-syntax` server for `racket-xp-mode` needs to listen for log messages if this feature should work.

Thanks again!

**Comment by greghendershott** [comment]
Thanks!

1. I just realized that I'd had _automatic background_ check-syntax disabled in DrRacket. What you describe only works with that enabled (not pressing the Check Syntax button manually). Enabling it, now I see what you mean.

2. Even so, I'm glad I asked because you probably saved me a fair amount of time -- I wouldn't have immediately guessed this would be implemented via a logger!  Although the rationale makes sense.

**Comment by david-christiansen** [comment]
As always, thank you for making such a nice program!

**Comment by greghendershott** [comment]
I think it probably won't be entirely satisfactory until I also resolve #465. But that's a distinct thing. Also possibly you'll have other feedback for me, once you try it -- which is easiest for you to do if I go ahead and merge it. So I did.

(Plus it seemed harmless to merge... did I just jinx myself yes probably. :slightly_smiling_face:)

**Comment by greghendershott** [comment]
I merged to `master` another commit to make sure the logger-based annotations are shown when expansion fails. Also to close #465, so logger-based annotations are combined with those produced by check-syntax. As a result, I think this is finished -- modulo any more bugs/omissions/misunderstandings.
