### ISSUE TITLE
Hacking on Racket Mode: what is the typical development setup?

### ISSUE THREAD

**Issue by scolobb** [greghendershott/racket-mode#454]
Hello everyone,

I would like to add a function `racket-xp-helpdesk` which would correspond to "Search in Help Desk" menu item in DrRacket [0].  I've been trying to point my Emacs to the clone of this repository for some time now, and I'm trying heavier and heavier solutions (from my subjective perspective).  I'll eventually figure out how to do it, but I wonder what is your typical setup for hacking on Racket Mode.

Do you add the directory of the Git repository to `load-path` and then do a bunch of requires?  Is it actually enough?  Is there an easier way to import the whole of Racket Mode without uninstalling the version coming from my package manager (Nix)?

------

[0] I've seen that `racket-xp-documentation` actually falls back to calling the `search` function from the Racket backend when it cannot find the documentation of a particular symbol, but I'd like to be able to explicitly open the search page.  My use case is as follows.  When I use Typed Racket, `racket-xp-documentation` will show me the documentation pages from Typed Racket, but I often want too see the documentation from `racket` because it gives more details.

**Comment by greghendershott** [comment]
It should be as simple as adding the git repo directory to your `load-path`.

For example if you use `use-package`, you can simply replace

    (use-package racket-mode
       :ensure t)

with

    (use-package racket-mode
      :load-path "/path/to/the/git-clone/dir")

Now, you might _also_ want to:

- `M-x package-delete` `racket-mode` so the stuff under `.emacs.d/elpa` doesn't get loaded.
- Restart Emacs, to be sure.

**Comment by scolobb** [comment]
Thank you @greghendershott ! I had trouble doing `(require 'racket-mode)` even when I added the Git checkout to my `load-path`, and I have just realized that I didn't have `pos-tip` installed :facepalm: I installed it and everything works fine now.

I really should have read `CONTRIBUTING.md` more attentively.
