### ISSUE TITLE
Broken dependencies on MELPA

### ISSUE THREAD

**Issue by cpitclaudel** [greghendershott/racket-mode#461]
The MELPA package for racket-mode no shows no dependencies and no description; this seems to be because of the lexical-binding commit, which got rid of the description string and likely broke the header parsing code used by epl:

https://github.com/greghendershott/racket-mode/blob/8f3b214a5ea06e6a2a9492e7d20b19badd0c3bdf/racket-mode.el#L1

**Comment by greghendershott** [comment]
@cpitclaudel Ugh -- sorry!

I'd set that up nearly 10 years ago and forgot the significance.

I just pushed a commit to `master` to add back a <= 36 character Brief Description.

**Comment by cpitclaudel** [comment]
No worries, thanks! We caught it because Flycheck pulls racket-mode as part of its test suite ^^
