### ISSUE TITLE
Auto-scaling large images

### ISSUE THREAD

**Issue by lihebi** [greghendershott/racket-mode#469]
When working with [pict](https://docs.racket-lang.org/pict/index.html) library, I found myself often creating large images. It is slow to render in REPL. For example:

```racket
(rectangle 10000 10000)
```
takes more than 10 seconds to render. I found that the time consuming part is converting to png bytes:

```racket
(time (void (convert (rectangle 100 100) 'png-bytes)))
(time (void (convert (rectangle 1000 1000) 'png-bytes)))
(time (void (convert (rectangle 10000 10000) 'png-bytes)))
```

```
cpu time: 2 real time: 2 gc time: 0
cpu time: 100 real time: 100 gc time: 0
cpu time: 10330 real time: 10328 gc time: 522
```

Thus I wanted to **scale the image down before converting to png-bytes**. In image.rkt:

https://github.com/greghendershott/racket-mode/blob/204845665cc4ec13edc59106b102fa251458e737/racket/image.rkt#L21-L26

I would like something like:

```racket
(define (convert-image v)
  (cond
    [(pict? v) (let* ([w (pict-width v)]
                      [h (pict-height v)]
                      [factor (min (/ 640 w) (/ 480 h) 1)])
                 (save-temporary-image (convert (scale v factor) 'png-bytes)))]
    [(and (convertible? v) (convert v 'png-bytes)) => save-temporary-image]
    [else v]))
```

However, the `v` here does not seem to be `pict?`. I tried this:

```racket
(define (convert-image v) 
   (println v)
   (println (pict? v))
   (cond [(and (convertible? v) (convert v 'png-bytes)) => save-temporary-image] 
         [else v])) 
```

And it prints:

```
#<pict>
#f
```

Any ideas?

**Comment by capfredf** [comment]
Can you post how `convert-image` was called?

**Comment by lihebi** [comment]
This function is implemented in racket-mode. It is called just before the value of an evaluated expression is displayed:

https://github.com/greghendershott/racket-mode/blob/204845665cc4ec13edc59106b102fa251458e737/racket/print.rkt#L18-L21

For example, when you `racket-eval-last-sexp` on `(rectangle 100 100)`, that function `convert-image` will be called to generate the image, and Emacs will load the image via `insert-image`.

**Comment by greghendershott** [comment]
I was just typing a similar comment. :)

Actually there are two places in `print.rkt`. In addition to being called from a print handler, i.e. a function that's a value for the `current-print` parameter, it can be called from a function that is a value for the `pretty-print-print-hook` parameter.

I don't immediately know why what you're trying, doesn't work. I might need to take a look, tomorrow. But I do understand the need/desire.

Is `scale` the one provided by `racket/pict`? (Many Racket libs provide a "scale" and I don't know the image stuff very well.)

**Comment by greghendershott** [comment]
Hmm, it looks like `pict` depends on `racket/gui` -- which is _not_ something we want Racket Mode to require.

Looking at [`file/convertible`](file:///home/greg/racket/7.6/doc/file/convertible.html) it seems it has not just `png-bytes` but also a couple of sizing flavors:

> 'png-bytes — a byte string containing a PNG image encoding
>
> 'png-bytes+bounds — a list containing a byte string and four numbers; the byte string contains a PNG document, and the four numbers are sizing information for the image: the width, height, descent (included in the height), and extra vertical top space (included in the height), in that order
>
> 'png-bytes+bounds8 — a list containing a byte string and eight numbers; like 'png-bytes+bounds, but where the image encoded that is in the byte string can be padded in each direction (to allow the drawn region to extend beyond its “bounding box”), where the extra four numbers in the list specify the amount of padding that was added to the image: left, right, top, and bottom

Can you try those?

**Comment by lihebi** [comment]
`'png-bytes+bounds` and `'png-bytes+bounds8` do not reduce the rendering time, they seem to merely output more information in addition to png-bytes. As a result, the rendering time is about 10% more.

I was talking about [this scale function in pict](https://docs.racket-lang.org/pict/Pict_Drawing_Adjusters.html?q=scale#%28def._%28%28lib._pict%2Fmain..rkt%29._scale%29%29)

**Comment by lihebi** [comment]
I think for racket picts, it maybe better to use `svg` instead of `png`. The rendering time for svg is constant no matter the scale, because it merely exports the vectors.

```racket
  (time (void (convert (rectangle 100 100) 'svg-bytes)))
  (time (void (convert (rectangle 1000 1000) 'svg-bytes)))
  (time (void (convert (rectangle 10000 10000) 'svg-bytes)))
```
gives:
```
cpu time: 1 real time: 0 gc time: 0
cpu time: 1 real time: 0 gc time: 0
cpu time: 0 real time: 0 gc time: 0
```

For a slightly more complex pict:

```racket
  (time (void (convert (desktop-machine 1 '(devil plt)) 'svg-bytes)))
  (time (void (convert (desktop-machine 100 '(devil plt)) 'svg-bytes)))
  (time (void (convert (desktop-machine 1 '(devil plt)) 'png-bytes)))
  (time (void (convert (desktop-machine 100 '(devil plt)) 'png-bytes)))
```
gives:
```
cpu time: 5 real time: 5 gc time: 0
cpu time: 5 real time: 4 gc time: 0
cpu time: 14 real time: 15 gc time: 0
cpu time: 15151 real time: 15149 gc time: 627
```
