### ISSUE TITLE
Supporting svg for pict broke supporting png for plot

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/racket-mode#475]
@timjervis [commented](https://github.com/greghendershott/racket-mode/pull/470#commitcomment-39368830) on commit 30ed764 from PR #470 for issue #469:

> This commit killed my ability to see inline plots on both Aquamacs and Emacs Mac Port. Both versions of emacs can display inline SVGs, but to restore service, first, I had to switch to (require plot/pict) rather than (require plot) in my racket files, and second, I had to comment out lines 705 and 706 in racket-repl.el. On my system, (image-type-available-p 'imagemagick) returns 't, but the result doesn't display inline in the repl for me. Removing that switch restored normal service. Apologies for the amateurish intervention, I'm not an expert at this, but I hope it either helps someone else, or prompts a better fix.

That's an unintended regression. People shouldn't need to change their Racket programs.

Probably the issue is that `file/convertible` can convert `plot` objects to `png-bytes` --- but **not** `svg-bytes`?

In that case, we should probably change things so that if `(convert _ 'svg-bytes)` returns `#f`, we try the "old" `(convert _ 'png-bytes)` as a fallback.

And also, code that looks for these image files and calls Emacs `create-image` should be prepared to deal with either format.

Probably the new `racket-imagemagick-props` customization will need to change, or, at least be documented that it is used only in the imagemagick/svg case?

/cc @lihebi

**Comment by greghendershott** [comment]
Simple example and test case:

```racket
#lang racket

(require pict)
(rectangle 100 100)

(require plot)
(plot (function (λ (x) (sin (* 4 x))) -1 1)
      #:x-min -1.5 #:x-max 1.5 #:y-min -1.5 #:y-max 1.5)
```

Expected: When `racket-run`, this should print both values as images.

Actual: It prints the latter value as `(object:2d-plot-snip% ...)` instead of as an image.

**Comment by lihebi** [comment]
Sorry, I didn't use `plot`, not aware of that regression. The fix looks good to me, your test case shows images with that fix.

> Probably the new `racket-imagemagick-props` customization will need to change, or, at least be documented that it is used only in the imagemagick/svg case?

The props of `(create-image 'imagemagick ...)` should work for both `svg` and `png`, so I think that should be fine.

**Comment by tgbugs** [comment]
I have also encountered this issue and since I opted to not compile in the svg renderer into emacs due to some nasty performance issues I have encountered I can't use the workaround to render svgs.

**Comment by greghendershott** [comment]
@lihebi Thank you for reviewing.

I don't use enough image-producing things in Racket frequently enough for me to effectively "dog-food" changes like this.

> The props of (create-image 'imagemagick ...) should work for both svg and png, so I think that should be fine.

I agree. I thought it might not be, when I wrote out the bug report. But after looking at and updating the code, I decided it should be OK. Well, we shall see. :smile:

**Comment by lihebi** [comment]
> some nasty performance issues I have encountered I can't use the workaround to render svgs

I'm not sure if `svg` is for everyone. `png` should be more compatible with the rest of the world. If there are other issues coming up, it is probably better to have `png` as default for the best compatibility, and leaves an option to use `svg` for fast rendering of large graphs.

**Comment by timjervis** [comment]
With (create-image <file> 'imagemagick nil), I get no image in the repl, and "Invalid image size (see ‘max-image-size’)" in Emacs' message buffer. With (create-image <file> 'svg nil), everything is fine. Meanwhile I can preview the images in the temp directory and they look fine. ImageMagick is also able to identify the correct type and size of the image files without error on the command line. I'm running racket 7.7 cs, and ImageMagick 7.0.10-14. Maybe it's just me, but I get the same outcome on two different mac platforms. I'll keep digging.

**Comment by tgbugs** [comment]
This is fixed at 1e48c243c01c912574c39eeab609b414f6b9953b for me.

**Comment by greghendershott** [comment]
@timjervis Just to confirm are you saying it doesn't work for you at current tip and MELPA commit 1e48c24? (Or even back at commit b8dfb41 ?)

---

My manual testing for this is Racket 7.7 BC, Emacs 25.2.2, Linux, and:

```
greg@x1c:~$ convert --version
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib
```

So I think older or at least not-newer versions vs. yours.

If it is not working for you on macOS: I can also haul out my old MacBook and try on macOS with various versions of Racket and Emacs, and whatever ImageMagick I have there.

**Comment by greghendershott** [comment]
@timjervis Also:

> (create-image 'imagemagick nil)

Did you mean `(create-image filename 'imagemagick nil)`?

And if so, what does `(create-image filename)` do for you (not specifying `TYPE` i.e. nil)?

**Comment by timjervis** [comment]
Sadly non of the current commits work for me, and apologies, I did mean (create-image filename 'imagemagick nil). If I omit the keyword 'imagemagick, everything works.

In an ielm buffer, the following shows an image (a solid red rectangle, as it happens):

> (insert-image (create-image "racket-image.svg" nil))

Meanwhile this produces a transparent box with the SVG XML source ghosted within:

> (insert-image (create-image "racket-image.svg" 'imagemagick nil))

I'm using a Mac (Catalina 10.15.4), GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.5.0, Carbon Version 158 AppKit 1671.4) of 2020-03-24, ImageMagick 7.0.10.14 from Homebrew.

**Comment by greghendershott** [comment]
> , I did mean (create-image filename 'imagemagick nil). If I omit the keyword 'imagemagick, everything works.

@timjervis OK, good. IIUC that means commit 0316910 should work for you.

That's not yet merged to `master`. If it's something you'd like to try yourself -- either using git, or, simply temporarily redefining that containing function "live" in Emacs -- then please do and let me know?  

Otherwise no worries if you're not comfortable, I'll have another look at the code, verify it works for me on macOS just like it already does on Linux, and then I'll merge it to `master` for you to try from MELPA.

**Comment by timjervis** [comment]
Commit https://github.com/greghendershott/racket-mode/commit/03169107a069e3395c5d974c0975756f0f99e3b2 works for me. In the racket-mode repl, I can see an inline SVG image, and plots, using both plot and plot/pict versions. Great, thank you!

**Comment by greghendershott** [comment]
@timjervis Great! Also I should update the doc string for the customization variable `racket-imagemagick-props` to reflect this:

```elisp
(defcustom racket-imagemagick-props nil
  "Use ImageMagick with these properties for REPL images.

When this property list is not empty -- and the variable
`racket-images-inline' is true, and Emacs is built with with
ImageMagick support -- then `create-image' is called with
\"imagemagick\" as the type and with this property list.

For example, to scale images whose width is larger than 500
pixels, supply (:max-width 500)."
  :tag "ImageMagick Props"
  :type '(plist :key-type symbol
                :value-type (choice number string))
  :options '((:max-width integer)
             (:max-height integer)
             (:background string)
             (:width integer)
             (:height integer)
             (:rotation float))
  :risky t
  :group 'racket-repl)
```

And I'll merge to `master`.

**Comment by greghendershott** [comment]
OK, done. It will take N hours for MELPA to update to show version `20200526.xxxx`.

@timjervis Again, sorry about the breakage, and, thank you for helping figure out the fix.

**Comment by Inc0ns1st3nt** [comment]
I would like to show `plot` objects as inlined images in `racket-repl` in emacs, but I am still having `(object:2d-plot-snip% ...)` instead of an image. Drawing like `rectangle` shows up as image still
I'm on racket-mode version `20200924.1506`
Emacs 27.1
ImageMagick 7.0.10-31 Q16 x86_64 2020-09-2
Linux and racket 7.8

**Comment by greghendershott** [comment]
@Inc0ns1st3nt Sorry. It looks like I broke that about a month ago in commit 87f13be to close #477.

From a quick initial look, it seems the objects `plot` returns don't seem to support [`convert`](https://docs.racket-lang.org/file/convertible.html) format `'png-bytes+bounds` -- just `'png-bytes`.

So probably I need to add a case where we try `png-bytes` as a final fallback, and, in that case the smart pretty-print width in #477 simply won't work well. Which is unfortunate, but practically maybe it's acceptable if they pretty-print only 1 per line since plots tend to be larger (?).

---

p.s. A minimal example:

```racket
#lang racket/base

(require plot
         racket/math)

(plot (function sin (- pi) pi #:label "y = sin(x)"))
```

**Comment by greghendershott** [comment]
I merged commit 2625f97. It should be available on MELPA within a couple hours.

**Comment by Inc0ns1st3nt** [comment]
Okay, works for me now, thanks for the work

**Comment by greghendershott** [comment]
Great to hear. Thank you again for reporting it.

**Comment by triangle-man** [comment]
(Copying this from the Slack channel.)

I can no longer see picts displayed in-line in Emacs using racket-mode. (I used to be able to, but I don't remember when this was.) 

The module:
```scheme
#lang racket
(require pict)
(circle 10)
```
produces, in the Emacs `*Messages*` buffer,  the error message:
```
error in process filter: image-type: Invalid image type ‘svg’
error in process filter: Invalid image type ‘svg’
```
and no image is shown. On the other hand,
```scheme
(pict->bitmap (circle 10))
```
**does** produce an image.

I am using:
- Emacs 27.1, from the homebrew cask installation (which I think is from emacsformacosx.com)
- racket-mode 20201022.1304
- Racket v7.9 [bc]

The value of `image-types` is `(png gif tiff jpeg xpm xbm pbm)`. I don't know how to extract other configuration information from Emacs, but am very happy to try.

**Comment by greghendershott** [comment]
@triangle-man This seems to be because your Emacs is built without support for either `svg` or `imagemagick`, and at the moment Racket Mode is expecting one of them.

I think this isn't so much due to the version number of Emacs, and instead that any version of Emacs can be built various ways with various options enabled or not. Possibly the homebrew build is more on the minimal side. For instance I'm often using the Ubuntu 18.04 build of Emacs, which is an older 25.2.2, and my `image-types` is `(svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)`.

Two solution paths:

1. I'm rusty on homebrew but I seem to recall it has an option to install Emacs with various feature flags on/off?  Maybe SVG support is one? Maybe you could try that?

2. I could try to change this code again (and hopefully not cause some other, new problem!).  For example: I could have Racket Mode's front-end tell the back end when SVG isn't available. Currently, it assumes that SVG is avaible and prefers it, on the grounds it potentially can take much less space on disk and in memory. Only if a certain kind of Racket image can't be converted to SVG, does the back end fall back to converting it to PNG.

I'm willing to try 2 although I might not be able to for at least a few days. I suppose in the meantime the status quo is that Racket Mode has an undocumented requirement that Emacs is built with `svg` or `imagemagick` support (or both). So if I couldn't get to doing 2, soon, maybe I should at least document this requirement more explicitly.

**Comment by greghendershott** [comment]
> I'm rusty on homebrew but I seem to recall it has an option to install Emacs with various feature flags on/off? Maybe SVG support is one? Maybe you could try that?

Maybe something like `brew install emacs --with-imagemagick --with-librsvg` -- but don't take my word for that please double-check.

**Comment by triangle-man** [comment]
Many thanks, @greghendershott, that's extremely helpful. I am sure you are correct that my Emacs is lacking both svg and Imagemagick. In particular, prior to 27.1 `--with-imagemagick` was (apparently) the default; but now it isn't. 

I will try the homebrew build options, and report if there was success.

**Comment by greghendershott** [comment]
I don't know the whole backstory wrt `imagemagick`. If you don't want to include that, possibly for the same reasons Emacs 27.1 doesn't, then I _think_ `--with-librsvg` would be sufficient for status quo Racket Mode.

**Comment by triangle-man** [comment]
Amusingly (for some sense of amusing) homebrew has reportedly removed the ability to set configuration options (https://www.reddit.com/r/emacs/comments/bhjtf9/now_that_homebrew_has_removed_build_options_how/).

I am presently trying `emacs-mac`

**Comment by triangle-man** [comment]
[emacs-mac](https://github.com/railwaycat/homebrew-emacsmacport) -- not an "official" homebrew port -- does indeed work at least on the single example above. Pictures are now inserted inline (though note that I haven't tried anything significant yet).

Thanks again!

**Comment by greghendershott** [comment]
> Amusingly (for some sense of amusing) homebrew has reportedly removed the ability to set configuration options 

Oh! Yet another backstory I don't know. :smile:

> emacs-mac -- not an "official" homebrew port -- does indeed work at least on the single example above. Pictures are now inserted inline (though note that I haven't tried anything significant yet).

I'm glad that works for you, and thank you very much for reporting back!

---

I think I will open a fresh issue for what I mentioned above:

>>  have Racket Mode's front-end tell the back end when SVG isn't available. Currently, it assumes that SVG is availible and prefers it, on the grounds it potentially can take much less space on disk and in memory. Only if a certain kind of Racket image can't be converted to SVG, does the back end fall back to converting it to PNG.

Without the pressure of doing it to fix an immediate blocker, for you, hopefully I can implement that carefully and test enough and not introduce some fresh problem(s).

**Comment by triangle-man** [comment]
> I'm glad that works for you, and thank you very much for reporting back!

You're very welcome. I really appreciate your help.
