### ISSUE TITLE
Line breaks after images

### ISSUE THREAD

**Issue by soegaard** [greghendershott/racket-mode#477]
Currently the repl printer automatically breaks lines after all images.
When printing a list of small images, it would be nice to have them 
besides each other instead.

![image](https://user-images.githubusercontent.com/461765/83910158-57d26680-a76a-11ea-8ad9-10b85c958a85.png)

**Comment by greghendershott** [comment]
I agree this would be nice to have.

In the past I tried to be _barely_ clever about this, but that backfired: #402.

That experience is not an argument against attempting this; it's just a heads-up to future-me or whoever tries to implement this.

**Comment by greghendershott** [comment]
I took some time to try to do this properly. Hopefully it will work well, for you, and not introduce any new bugs (ha!).
