### ISSUE TITLE
Keep REPL history

### ISSUE THREAD

**Issue by cwebber** [greghendershott/racket-mode#480]
One very helpful thing in many REPL'ish environments is being able to come back to history from a previous session.  SLIME, geiser, shell-mode, etc seem to be able to provide this... I assume they probably use some common emacs feature but I haven't really looked in detail.

Sometimes I kill my racket session (especially if I end up accidentally create some infinite-loop-output-nightmare) and reopen it and am sad that I have to figure out what I was doing again!

**Comment by greghendershott** [comment]
It is already supposed to persist REPL history, since commit f6cc361 closed #367 a couple months ago.

Have you tried a more-recent version of Racket Mode? Or is it not working for you for some reason that we need to figure out and fix?

**Comment by greghendershott** [comment]
It does use an Emacs `kill-buffer-hook` to save. So that _should_ be working in the scenario you describe.

(It also uses a `kill-emacs-hook` to save all REPL histories.)

p.s. You're right, Emacs has standard functionality for this -- "input ring" in `comint-mode`, which is what Racket Mode (since early April) has been using.

**Comment by greghendershott** [comment]
Pending more info, I'm going to close this.

My assumption is when you update Racket Mode, you will get this feature and it will work fine for you.

However of course feel free to comment more and/or reopen this!

**Comment by cwebber** [comment]
(BTW, yes, this should close this... sorry I didn't respond.  Thanks for this!  I updated the version of racket-mode in Guix.)
