### ISSUE TITLE
racket-xp-mode having trouble with unicode λ character

### ISSUE THREAD

**Issue by cwebber** [greghendershott/racket-mode#484]
At least in my file, when I add unicode lambda characters like:

``` racket
(lambda ()
  (λ ()
    'foo))
```

The outer `lambda` is fine, but the two parentheses after the inner `λ` give the following warning: 

```
#%app: missing procedure expression; probably originally (), which is an illegal empty operation
```

My guess is that the `λ` is not going through somehow.  Without being sure, I suspect that this was the cause of #483.

**Comment by greghendershott** [comment]
Hmm. I'm not able to reproduce this, so far.

It sounds to me like the `λ` "goes through", but is somehow not the character you expect, i.e. not some identifier bound to the `lambda` macro -- and that is why check-syntax complains about the empty parens. You'd get the same error if you'd supplied, say, `println`, a plain function (as opposed to a macro like `lambda` that parses the empty parens specially).

So it seems like either this is a character encoding issue, or, an issue where `λ` is bound to something other than `racket/base`'s `lambda` (e.g. if you overrode that definition, intentionally or not).

- How do you insert the `λ`?
  - Using <kbd>M-C-y</kbd> a.k.a. `M-x racket-insert-lambda`
  - Or by using `M-x insert-char` and choosing "GREEK SMALL LAMBDA"
  - Or some other way?

- If you move point to the `λ`...
  - and press <kbd>C-c C-.</kbd> a.k.a. `M-x racket-xp-describe`, what does it say?
  - and press <kbd>M-.</kbd> a.k.a. `M-x racket-xp-visit-definition`, where do you go?

**Comment by greghendershott** [comment]
Related to the first main bullet above:

- If you move point to the `λ` and press <kbd>C-u C-x =</kbd> what does it show?

For me it shows:

```
             position: 56 of 107 (51%), column: 3
            character: λ (displayed as λ) (codepoint 955, #o1673, #x3bb)
    preferred charset: unicode (Unicode (ISO10646))
code point in charset: 0x03BB
               script: greek
               syntax: w 	which means: word
             category: .:Base, G:2-byte Greek, L:Left-to-right (strong), c:Chinese, g:Greek, h:Korean, j:Japanese
             to input: type "C-x 8 RET 3bb" or "C-x 8 RET GREEK SMALL LETTER LAMDA"
          buffer code: #xCE #xBB
            file code: #xCE #xBB (encoded by coding system utf-8-unix)
              display: by this font (glyph code)
    xft:-DAMA-Ubuntu Mono-normal-normal-normal-*-24-*-*-*-m-0-iso10646-1 (#x3B3)

Character code properties: customize what to show
  name: GREEK SMALL LETTER LAMDA
  old-name: GREEK SMALL LETTER LAMBDA
  general-category: Ll (Letter, Lowercase)
  decomposition: (955) ('λ')

There are text properties here:
  face                 font-lock-keyword-face
  fontified            t
  racket-xp-doc        [Show]
  racket-xp-use        [Show]
  racket-xp-visit      [Show]

[back]
```

**Comment by cwebber** [comment]
I get the same as you:

```
             position: 467 of 477 (98%), column: 1
            character: λ (displayed as λ) (codepoint 955, #o1673, #x3bb)
              charset: unicode (Unicode (ISO10646))
code point in charset: 0x03BB
               script: greek
               syntax: w 	which means: word
             category: .:Base, G:2-byte Greek, L:Left-to-right (strong), c:Chinese, g:Greek, h:Korean, j:Japanese
             to input: type "C-x 8 RET 3bb" or "C-x 8 RET GREEK SMALL LETTER LAMDA"
          buffer code: #xCE #xBB
            file code: #xCE #xBB (encoded by coding system utf-8-unix)
              display: by this font (glyph code)
    xft:-PfEd-DejaVu Sans Mono-bold-normal-normal-*-13-*-*-*-m-0-iso10646-1 (#x309)

Character code properties: customize what to show
  name: GREEK SMALL LETTER LAMDA
  old-name: GREEK SMALL LETTER LAMBDA
  general-category: Ll (Letter, Lowercase)
  decomposition: (955) ('λ')

There are text properties here:
  face                 font-lock-keyword-face
  fontified            t
```

**Comment by cwebber** [comment]
Though, for whatever reason, I'm also not getting all the racket-xp-* faces at the bottom... wonder why that is

**Comment by cwebber** [comment]
As for how I insert it, I can use `M-x racket-insert-lambda` and get the same problem (though I normally insert via my own elisp snippet, but I don't think it's relevant since it's the same result).

I get nothing for C-c C-. ("Found no documentation or signature") or M-. ("Not found")

**Comment by cwebber** [comment]
BTW I'm running Guix as my operating system, have racket-mode installed through that; it's using the revision of 5eb31a284c8db5102bc71b1e2c6ce3a095ae085b which is recent.

**Comment by greghendershott** [comment]
Thanks for the additional information!

OK so it is the correct `λ` character that `racket/base` defines as an alias for `lambda`.

That seems to point to the other fork in the road -- somehow, in your file, is `λ` bound to something else in the `#lang` or `require`s (either directly by your file, or, somehow by `racket-xp-mode` in a way I can't yet imagine but can try to figure out.)

1. What's the minimal file you get the problem with?  I tried simply:

```racket
#lang racket/base
(lambda ()
  (λ ()
    'foo))
```

2. `racket-xp-mode` is reporting the expansion error, but, I would expect you to get the same error when expanding and evaluating the file through command-line `racket <your-file.rkt>`. Do you?

**Comment by greghendershott** [comment]
Another theory: The pipe from Emacs to the Racket Mode back end process is somehow not set to use utf-8.

So far, that is the only way I can force a similar symptom to happen -- by doing `(set-process-coding-system (get-process "racket-mode-back-end") 'iso-latin-1 'iso-latin-1)`.

When the error has occurred, if you <kbd>M-:</kbd> and enter `(process-coding-system (get-process "racket-mode-back-end"))`, does the echo area show something like `(utf-8-unix . utf-8-unix)`?  Or something else, e.g. `(iso-latin-1 . iso-latin-1-unix)`?

**Comment by greghendershott** [comment]
Depending on your answer to [this](https://github.com/greghendershott/racket-mode/issues/484#issuecomment-663614412) then commit 318c868 is likely to solve this and I'll merge it.

**Comment by cwebber** [comment]
That appears to be the root of the problem... I get `(undecided-unix . iso-latin-1-unix)` (and also, yes, the minimal program example you put above triggers the problem)

**Comment by cwebber** [comment]
So that seems like it should be fixing it, though I evaluated:

```
(defun racket--cmd-open ()
  (racket--cmd-close) ;never create multi processes e.g. "racket-process<1>"
  (make-process
   :name            racket--cmd-process-name
   :connection-type 'pipe
   :noquery         t
   :buffer          (get-buffer-create (concat " *" racket--cmd-process-name "*"))
   :stderr          (make-pipe-process
                     :name     (concat racket--cmd-process-name "-stderr")
                     :buffer   (concat "*" racket--cmd-process-name "-stderr*")
                     :noquery  t
                     :coding 'utf-8
                     :filter   #'racket--cmd-process-stderr-filter
                     :sentinel #'ignore)
   :command         (list racket-program
                          (funcall racket-adjust-run-rkt racket--run.rkt)
                          (setq racket--cmd-auth (format "%S" `(auth ,(random)))))
   :filter          #'racket--cmd-process-filter))
```

and then I ran `(kill-process (get-process "racket-mode-back-end"))` and restarted racket-xp-mode in the buffer but... it still seemed to have the same problem, and still reported the `(undecided-unix . iso-latin-1-unix)`... which I can't imagine why at this point.  Confusing.

But maybe that didn't actually change the way it was spawning the proces.....?????

**Comment by cwebber** [comment]
I also tried switching it to `'(utf-8-unix . utf-8-unix)`, no dice

**Comment by cwebber** [comment]
Here's a kluge that fixed it:

```
(setq default-process-coding-system '(utf-8 . utf-8))
```

But... why do I need to set that? :\

**Comment by cwebber** [comment]
Here's a goofy dynamic scope'y fix... but it does fix it for me:

```
(defun racket--cmd-open ()
  (racket--cmd-close) ;never create multi processes e.g. "racket-process<1>"
  (make-process
   :name            racket--cmd-process-name
   :connection-type 'pipe
   :noquery         t
   :buffer          (get-buffer-create (concat " *" racket--cmd-process-name "*"))
   :stderr          (let ((default-process-coding-system '(utf-8 . utf-8)))
                      (make-pipe-process
                       :name     (concat racket--cmd-process-name "-stderr")
                       :buffer   (concat "*" racket--cmd-process-name "-stderr*")
                       :noquery  t
                       :filter   #'racket--cmd-process-stderr-filter
                       :sentinel #'ignore))
   :command         (list racket-program
                          (funcall racket-adjust-run-rkt racket--run.rkt)
                          (setq racket--cmd-auth (format "%S" `(auth ,(random)))))
   :filter          #'racket--cmd-process-filter))
```

**Comment by greghendershott** [comment]
For me, `default-process-coding-system` defaults to `'(utf-8-unix . utf-8-unix)` using the standard Ubuntu 18.04 package for Emacs `GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian`. My `init.el` doesn't change this.

That's interesting that the `:coding` argument has no effect for you, but the dynamic `let` works. That's useful to know! I'll mull this over and push a commit (possibly your `let` binding) soon-ish.

**Comment by greghendershott** [comment]
Oh. This code is creating _two_ Emacs "processes". `make-process` is for stdin/stdout, and the (nested) `make-pipe-process` is for stderr.

My previous commit only added `:coding 'utf-8` for stderr. Although that's fine, that's N/A for the problem you were reporting. Instead how about commit d30f62d which also adds `:coding 'utf-8` for stdin/stdout. Does that work for you, as does the dynamic `let` binding?

**Comment by cwebber** [comment]
It looks like it fixes it, yeah!  I evaluated it in the emacs process I was running and things worked fine again.

I'm not sure why it was happening in the first place... I can't track down anything that would have done that.  It might also not be happening when I start a brand new emacs, but I'm not sure what would have affected the other running emacs process, which was running for a few weeks...

At any rate, explicit is better than implicit, and even if something weird happened to my emacs process, this should prevent problems if something weird happens to anyone else I guess.  So I say: merge it!

Thanks for your time on this.  Sorry it was so weird and gave so much trouble.
