### ISSUE TITLE
Require modules on Windows: auto-complete problem using "\" instead of "/"

### ISSUE THREAD

**Issue by jacksonbenete** [greghendershott/racket-mode#490]
Hello there,

I'm not sure if it's a bug on racket-mode or company-mode, but using Windows there is the eternal problem about / or \ for paths.
When I'm requiring a package the auto-completion only offers to complete if I'm writing with \ like `(require lang\`, but once completed, the package will not work as, let's say, `(require lang\string)`, it must be `(require lang/string)` to compile.

Let me know if you prefer the log attached as a file or right in here.

Thank you very much for your hard work. As soon as I learn more about Lisp and Racket I will try to contribute.

[log.txt](https://github.com/greghendershott/racket-mode/files/5154210/log.txt)

**Comment by greghendershott** [comment]
Thanks for the report. I have a commit which fixes this, when I try it on Windows. I'll merge that after the CI tests go all-green.

**Comment by jacksonbenete** [comment]
Thank you very much! I'm watching the repo, so I will update when you commit the fix.
But, sorry for the newbie question, when you launch it, how do I update? 
I'm new to Emacs and doesn't seems to have a `M-x package-update` or something like that.
There is also no .git on `elpa/racket-mode` so I can't update manually on the package folder either.

**Comment by greghendershott** [comment]
Wait for MELPA to refresh, for Racket Mode. That might take a couple hours from the time I type this comment.

The old, previous version is `20200830.1755`.

The new version will be something like `20200902.xxxx`.

---

See `M-x list-packages` for a UI to install and update packages.

OR, if you want to update just one package (e.g. just racket-mode), sometimes I find it easiest just to:
1. `M-x package-delete` it.
2. `M-x package-refresh-contents`.
3. `M-x package-install` it again.
