### ISSUE TITLE
Completion in racket-xp-mode freezes Emacs

### ISSUE THREAD

**Issue by goderich** [greghendershott/racket-mode#504]
Hello! I'm using Emacs 28 with the Doom config on Manjaro. Racket-mode works very well, but racket-xp-mode very quickly makes Emacs completely unresponsive. I've tried narrowing down the bug, and I believe that it happens during autocompletion.

A cursory search appears to suggest that other people are not having this issue. How can I help diagnose this further?

Edit: I also just tried it on my Arch laptop (also using Emacs 28 Doom, same config), and it also freezes completely on autocompletion.

`racket-bug-report`:

<details>
<pre>
((alist-get 'racket-mode package-alist))
((emacs-version "28.0.50")
 (system-type gnu/linux)
 (x-gtk-use-system-tooltips nil)
 (major-mode racket-mode)
 (racket--el-source-dir "/home/goderich/.emacs.d/.local/straight/build/racket-mode/")
 (racket--rkt-source-dir "/home/goderich/.emacs.d/.local/straight/build/racket-mode/racket/")
 (racket-program "racket")
 (racket-command-timeout 10)
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function nil)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\S ?\\S ?\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-images-system-viewer "display")
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-pseudo-tooltip)))
(enabled-minor-modes
 (async-bytecomp-package-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (better-jumper-local-mode)
 (better-jumper-mode)
 (column-number-mode)
 (company-mode)
 (doom-modeline-mode)
 (dtrt-indent-mode)
 (editorconfig-mode)
 (electric-indent-mode)
 (eros-mode)
 (evil-escape-mode)
 (evil-goggles-mode)
 (evil-local-mode)
 (evil-mode)
 (evil-snipe-local-mode)
 (evil-snipe-mode)
 (evil-snipe-override-local-mode)
 (evil-snipe-override-mode)
 (evil-surround-mode)
 (evil-traces-mode)
 (file-name-shadow-mode)
 (flycheck-mode)
 (flycheck-popup-tip-mode)
 (font-lock-mode)
 (gcmh-mode)
 (general-override-mode)
 (git-gutter-mode)
 (global-company-mode)
 (global-eldoc-mode)
 (global-evil-surround-mode)
 (global-flycheck-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-magit-file-mode)
 (global-so-long-mode)
 (global-undo-fu-session-mode)
 (global-visual-line-mode)
 (highlight-numbers-mode)
 (highlight-quoted-mode)
 (hl-line-mode)
 (hl-todo-mode)
 (hs-minor-mode)
 (ivy-mode)
 (ivy-rich-mode)
 (line-number-mode)
 (magit-file-mode)
 (mouse-wheel-mode)
 (org-msg-mode)
 (org-roam-mode)
 (persp-mode)
 (projectile-mode)
 (racket-smart-open-bracket-mode)
 (rainbow-delimiters-mode)
 (ranger-override-dired-mode)
 (recentf-mode)
 (save-place-mode)
 (savehist-mode)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (size-indication-mode)
 (smartparens-global-mode)
 (smartparens-mode)
 (solaire-global-mode)
 (solaire-mode)
 (transient-mark-mode)
 (undo-fu-mode)
 (undo-fu-session-mode)
 (vi-tilde-fringe-mode)
 (visual-line-mode)
 (which-key-mode)
 (whitespace-mode)
 (window-divider-mode)
 (winner-mode)
 (ws-butler-global-mode)
 (ws-butler-mode)
 (yas-minor-mode))
(disabled-minor-modes
 (+emacs-lisp-ert-mode)
 (+global-word-wrap-mode)
 (+org-pretty-mode)
 (+popup-buffer-mode)
 (+popup-mode)
 (+word-wrap-mode)
 (abbrev-mode)
 (amx-debug-mode)
 (amx-mode)
 (auto-fill-function)
 (auto-image-file-mode)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (blink-cursor-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (button-mode)
 (cl-old-struct-compat-mode)
 (company-search-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (counsel-mode)
 (cursor-intangible-mode)
 (cursor-sensor-mode)
 (defining-kbd-macro)
 (delete-selection-mode)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (dtrt-indent-global-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (evil-magit-toggle-text-minor-mode)
 (evil-org-mode)
 (flyspell-mode)
 (general-override-local-mode)
 (git-commit-mode)
 (global-auto-revert-mode)
 (global-git-gutter-mode)
 (global-hl-line-mode)
 (global-hl-todo-mode)
 (global-prettify-symbols-mode)
 (global-reveal-mode)
 (global-undo-tree-mode)
 (global-vi-tilde-fringe-mode)
 (global-whitespace-mode)
 (global-whitespace-newline-mode)
 (gnus-dead-summary-mode)
 (gnus-undo-mode)
 (horizontal-scroll-bar-mode)
 (ibuffer-auto-mode)
 (ido-everywhere)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (magit-auto-revert-mode)
 (magit-blame-mode)
 (magit-blame-read-only-mode)
 (magit-blob-mode)
 (magit-popup-help-mode)
 (magit-todos-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (magit-wip-initial-backup-mode)
 (magit-wip-mode)
 (mail-abbrevs-mode)
 (menu-bar-mode)
 (mml-mode)
 (next-error-follow-minor-mode)
 (org-capture-mode)
 (org-cdlatex-mode)
 (org-indent-mode)
 (org-list-checkbox-radio-mode)
 (org-roam-backlinks-mode)
 (org-src-mode)
 (org-table-follow-field-mode)
 (org-table-header-line-mode)
 (orgtbl-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (pcre-mode)
 (prettify-symbols-mode)
 (racket-xp-mode)
 (rectangle-mark-mode)
 (reveal-mode)
 (rxt--read-pcre-mode)
 (rxt-global-mode)
 (rxt-mode)
 (server-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (show-smartparens-global-mode)
 (show-smartparens-mode)
 (smartparens-global-strict-mode)
 (smartparens-strict-mode)
 (smerge-mode)
 (so-long-minor-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (toc-org-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-resume-mode)
 (undo-tree-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (which-function-mode)
 (whitespace-newline-mode)
 (with-editor-mode)
 (xref-etags-mode)
 (yas-global-mode))
</pre>
</details>

**Comment by greghendershott** [comment]
Between Emacs 28.0.50 pre-release and `straight.el`, I'm a _little_ concerned about chasing down something that turns out to be a temporary mistake in a bleeding-edge version of Emacs or some package, and/or is difficult for me to reproduce at all.

Having said that, let's definitely try to narrow it down!

Without any particular idea what might be going wrong, here a few things you could please try:

- What happens if you <kbd>M-x company-mode</kbd> to disable it in the `racket-mode` buffer that has `racket-xp-mode` enabled?

    - If that fixes it: What happens if you tweak company-mode so that it doesn't _auto_ complete (I think that's setting it to have a delay of zero or `nil`; please check its docs)?  In that case, does it still freeze when you ask company-mode to do completion, manually?

    - Similarly, what if you tell `racket-xp-mode` not to refresh on a timer -- by setting the customization variable `racket-xp-after-change-refresh-delay` to `nil`?

- Independently of the above: What if you try changing `racket-show-functions` from `'(racket-show-pseudo-tooltip)` to `'(racket-show-echo-area)`?

- Independently of the above: What if you try this thing mentioned in the `racket-xp-mode` doc string?

    ```elisp
      (require 'racket-xp)
      (add-hook 'racket-xp-mode-hook
                (lambda ()
                  (remove-hook 'pre-redisplay-functions
                               #'racket-xp-pre-redisplay
                               t)))
    ```

**Comment by goderich** [comment]
Thank you for not dismissing the issue and helping me find the cause!

> What happens if you M-x company-mode to disable it in the racket-mode buffer that has racket-xp-mode enabled?

Works fine.

> If that fixes it: What happens if you tweak company-mode so that it doesn't auto complete (I think that's setting it to have a delay of zero or nil; please check its docs)? In that case, does it still freeze when you ask company-mode to do completion, manually?

Works fine, manual completion does not freeze Emacs.

> Similarly, what if you tell racket-xp-mode not to refresh on a timer -- by setting the customization variable racket-xp-after-change-refresh-delay to nil?

Doesn't freeze on autocomplete.

> Independently of the above: What if you try changing racket-show-functions from '(racket-show-pseudo-tooltip) to '(racket-show-echo-area)?

Didn't seem to have an effect. Freezing still occurred on autocomplete.

> Independently of the above: What if you try this thing mentioned in the racket-xp-mode doc string?

I've actually had it on the entire time (should have mentioned that in the original post), but it did not influence the freezing issue.

**Comment by greghendershott** [comment]
Thanks for the additional info.

From your answers it seems more likely I might be able to reproduce this simply by installing a recent rolling release of company-mode. It seems less likely it's about Emacs pre-release, or something else.

There is [some code to detect whether completion might be underway, and if so, delay annotating](https://github.com/greghendershott/racket-mode/blob/master/racket-xp.el#L671-L689):

```elisp
(defun racket--xp-on-idle-timer (buffer)
  "Handle after-change-hook => idle-timer expiration.
If no longer current-buffer, don't annotate at all. Otherwise, if
we detect some completion process is underway, don't annotate
now, set timer to check again later. Why? Typically, if the user
then makes some completion choice, that will edit the buffer,
causing the after-change-hook to run again, and schedule another
idle timer. But just in case they don't, we schedule a retry."
  (when (equal buffer (current-buffer))
    (if (racket--xp-completing-p)
        (racket--xp-start-idle-timer buffer)
      (racket--xp-annotate))))

(defun racket--xp-completing-p ()
  "Is completion underway?
This is ad hoc and forensic."
  (or (get-buffer-window "*Completions*")
      (and (boundp 'company-pseudo-tooltip-overlay)
           company-pseudo-tooltip-overlay)))
```

It's possible this check isn't effective anymore; maybe company was updated in a way that this no longer works. (Having said that, IIRC the reason I added the check was that the experience of competing updates could be "janky". Not that it caused a freeze, like you're seeing. However maybe that has changed, too).

I suppose it's possible that the check itself is somehow causing the freeze, although quick glance this seems unlikely.

I don't have an immediate answer but I'll try to find a block of time to experiment and think.

**Comment by greghendershott** [comment]
What is your value for `company-frontends`?

**Comment by greghendershott** [comment]
Another theory of the bug:

We actually _are_ still detecting the completion-underway status just fine. The problem is what we do about it.

From inside an idle-timer handler, we're scheduling another idle-timer -- for the same amount of idle time, which has already elapsed. This means we'll just be called again, right away. The docs warn against this. My bad!  However it seems harmless. But maybe in Emacs 28.0.50 it's not harmless anymore.

If you're willing to test this theory, could you please try changing in `racket-xp.el` the following code?  After making the edit, you needn't save the file, but you do need to `M-x eval-defun`.

```diff
@@ -671,20 +671,19 @@ evaluation errors that won't be found merely from expansion -- or
 (defun racket--xp-on-idle-timer (buffer)
   "Handle after-change-hook => idle-timer expiration.
 If no longer current-buffer, don't annotate at all. Otherwise, if
 we detect some completion process is underway, don't annotate
 now, set timer to check again later. Why? Typically, if the user
 then makes some completion choice, that will edit the buffer,
 causing the after-change-hook to run again, and schedule another
 idle timer. But just in case they don't, we schedule a retry."
   (when (equal buffer (current-buffer))
-    (if (racket--xp-completing-p)
-        (racket--xp-start-idle-timer buffer)
+    (unless (racket--xp-completing-p)
       (racket--xp-annotate))))
```

Or maybe the diff makes it look confusing. Also deleting the doc string, the end result of the change is simply this:

```elisp
(defun racket--xp-on-idle-timer (buffer)
   (when (equal buffer (current-buffer))
    (unless (racket--xp-completing-p)
      (racket--xp-annotate))))
```

---

If you're not comfortable tweaking Emacs Lisp like this, no worries, just let me know.

I ask only because I don't have an Emacs 28.0.50 snapshot yet, it probably takes half an hour (?) to build on Linux, and if you were comfortable this might take you a few seconds.

But if you don't want to try, I'll get around to installing Emacs 28.0.50 before too long.

**Comment by goderich** [comment]
> What is your value for company-frontends?

Value

`(company-pseudo-tooltip-frontend company-echo-metadata-frontend)`

I believe this is set somewhere in Doom.

Original Value, for reference:

`(company-pseudo-tooltip-unless-just-one-frontend company-preview-if-just-one-frontend company-echo-metadata-frontend)`

**Comment by goderich** [comment]
Thank you again for bearing with me, I really appreciate it! I just tried the change in `racket--xp-on-idle-timer`, and it's working! Fantastic!

I'm not entirely sure what was happening between the two idle timers (did they go into a loop?), but that diff appears to have fixed the issue completely!

**Comment by greghendershott** [comment]
It took me a few days but I just merged a commit for this.

As a result you shouldn't need the local hack to your copy of `racket-xp.el` anymore.

(I don't mean that you need to undo it. You can leave it if you want. I just mean that someday if/when you upgrade Racket Mode from MELPA, you'll still be good.)

**Comment by goderich** [comment]
That's great! Thank you very much for the help and the quick fix! :)
