### ISSUE TITLE
Tooltip becomes a part of content

### ISSUE THREAD

**Issue by sorawee** [greghendershott/racket-mode#514]
<img width="472" alt="Screen Shot 2021-01-06 at 10 05 17 PM" src="https://user-images.githubusercontent.com/9099577/103857451-61f37500-506b-11eb-9b1a-00d27c72530b.png">

Very rarely (but I experienced it more than 10 times already during past 3 months), tooltip becomes a part of content.

When this occurs, there's no way to remove the tooltip. Even select all and delete will leave the tooltip intact. I guess this is because it's read only?

Reverting the buffer also doesn't solve the problem, though this might have to do with Doom Emacs which tries to save a bunch of states in a buffer (I don't know how to use vanilla Emacs, so I can't confirm whether reverting works). My workaround is to make a copy of this file, delete the file, and rename the new file back to the original name. 

<details><pre>
Please copy all of the following lines and paste them into your bug report
at <https://github.com/greghendershott/racket-mode/issues/>.

Please copy all of the following lines and paste them into your bug report
at <https://github.com/greghendershott/racket-mode/issues/>.

<details>
<pre>
((alist-get 'racket-mode package-alist))
((emacs-version "27.1")
 (system-type darwin)
 (x-gtk-use-system-tooltips UNDEFINED)
 (major-mode racket-mode)
 (racket--el-source-dir "/Users/sorawee/.emacs.d/.local/straight/build-27.1/racket-mode/")
 (racket--rkt-source-dir "/Users/sorawee/.emacs.d/.local/straight/build-27.1/racket-mode/racket/")
 (racket-program "racket")
 (racket-command-timeout 10)
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function nil)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "open")
 (racket-images-system-viewer "open")
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-pseudo-tooltip)))
(enabled-minor-modes
 (+popup-mode)
 (anzu-mode)
 (async-bytecomp-package-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (better-jumper-local-mode)
 (better-jumper-mode)
 (centaur-tabs-mode)
 (column-number-mode)
 (company-mode)
 (delete-selection-mode)
 (diff-hl-margin-mode)
 (display-fill-column-indicator-mode)
 (display-line-numbers-mode)
 (doom-modeline-mode)
 (dtrt-indent-mode)
 (editorconfig-mode)
 (electric-indent-mode)
 (evil-escape-mode)
 (evil-goggles-mode)
 (evil-local-mode)
 (evil-mc-mode)
 (evil-mode)
 (evil-snipe-override-local-mode)
 (evil-snipe-override-mode)
 (evil-surround-mode)
 (file-name-shadow-mode)
 (flycheck-mode)
 (flycheck-popup-tip-mode)
 (font-lock-mode)
 (gcmh-mode)
 (general-override-mode)
 (global-anzu-mode)
 (global-company-mode)
 (global-eldoc-mode)
 (global-evil-mc-mode)
 (global-evil-surround-mode)
 (global-flycheck-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-hl-line-mode)
 (global-so-long-mode)
 (global-undo-fu-session-mode)
 (global-visual-line-mode)
 (highlight-indent-guides-mode)
 (highlight-numbers-mode)
 (highlight-quoted-mode)
 (hl-line-mode)
 (hl-todo-mode)
 (hs-minor-mode)
 (ivy-mode)
 (ivy-rich-mode)
 (line-number-mode)
 (lispy-mode)
 (lispyville-mode)
 (mouse-wheel-mode)
 (ns-auto-titlebar-mode)
 (persp-mode)
 (projectile-mode)
 (racket-xp-mode)
 (rainbow-delimiters-mode)
 (ranger-override-dired-mode)
 (recentf-mode)
 (save-place-mode)
 (savehist-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (show-smartparens-global-mode)
 (show-smartparens-mode)
 (size-indication-mode)
 (smartparens-global-mode)
 (smartparens-mode)
 (solaire-global-mode)
 (solaire-mode)
 (transient-mark-mode)
 (undo-fu-mode)
 (undo-fu-session-mode)
 (vi-tilde-fringe-mode)
 (visual-line-mode)
 (which-key-mode)
 (whitespace-mode)
 (window-divider-mode)
 (winner-mode)
 (ws-butler-global-mode)
 (ws-butler-mode)
 (yas-minor-mode))
(disabled-minor-modes
 (+emacs-lisp-ert-mode)
 (+javascript-gulp-mode)
 (+javascript-npm-mode)
 (+lsp-optimization-mode)
 (+org-pretty-mode)
 (+popup-buffer-mode)
 (+web-angularjs-mode)
 (+web-django-mode)
 (+web-jekyll-mode)
 (+web-phaser-mode)
 (+web-react-mode)
 (+web-wordpress-mode)
 (abbrev-mode)
 (amx-debug-mode)
 (amx-mode)
 (auto-fill-function)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (avy-linum-mode)
 (blink-cursor-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (bug-reference-mode)
 (bug-reference-prog-mode)
 (centaur-tabs-local-mode)
 (cl-old-struct-compat-mode)
 (company-search-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (counsel-mode)
 (counsel-projectile-mode)
 (cua-mode)
 (cursor-intangible-mode)
 (cursor-sensor-mode)
 (dash-fontify-mode)
 (defining-kbd-macro)
 (diff-auto-refine-mode)
 (diff-hl-dir-mode)
 (diff-hl-dired-mode)
 (diff-hl-margin-minor-mode)
 (diff-hl-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (dtrt-indent-global-mode)
 (edebug-mode)
 (edit-indirect--overlay)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (evil-collection-magit-toggle-text-minor-mode)
 (evil-markdown-mode)
 (evil-snipe-local-mode)
 (evil-snipe-mode)
 (evil-visualstar-mode)
 (flyspell-mode)
 (general-override-local-mode)
 (git-commit-mode)
 (git-gutter-mode)
 (global-auto-revert-mode)
 (global-dash-fontify-mode)
 (global-diff-hl-mode)
 (global-display-fill-column-indicator-mode)
 (global-display-line-numbers-mode)
 (global-evil-visualstar-mode)
 (global-git-gutter-mode)
 (global-hide-mode-line-mode)
 (global-hl-todo-mode)
 (global-prettify-symbols-mode)
 (global-reveal-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-vi-tilde-fringe-mode)
 (global-whitespace-mode)
 (global-whitespace-newline-mode)
 (goto-address-mode)
 (goto-address-prog-mode)
 (hide-mode-line-mode)
 (horizontal-scroll-bar-mode)
 (ibuffer-auto-mode)
 (ido-everywhere)
 (iedit-mode)
 (irony-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (lispy-goto-mode)
 (lispy-other-mode)
 (macrostep-mode)
 (magit-auto-revert-mode)
 (magit-blame-mode)
 (magit-blame-read-only-mode)
 (magit-blob-mode)
 (magit-gitflow-mode)
 (magit-popup-help-mode)
 (magit-todos-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (magit-wip-initial-backup-mode)
 (magit-wip-mode)
 (mail-abbrevs-mode)
 (markdown-live-preview-mode)
 (mc-hide-unmatched-lines-mode)
 (menu-bar-mode)
 (mml-mode)
 (multiple-cursors-mode)
 (next-error-follow-minor-mode)
 (org-capture-mode)
 (org-cdlatex-mode)
 (org-list-checkbox-radio-mode)
 (org-src-mode)
 (org-table-follow-field-mode)
 (org-table-header-line-mode)
 (orgtbl-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (pcre-mode)
 (prettify-symbols-mode)
 (racket-smart-open-bracket-mode)
 (rectangle-mark-mode)
 (reveal-mode)
 (rxt--read-pcre-mode)
 (rxt-global-mode)
 (rxt-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (server-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (smartparens-global-strict-mode)
 (smartparens-strict-mode)
 (smerge-mode)
 (so-long-minor-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (thai-word-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-resume-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-parent-buffer)
 (view-mode)
 (visible-mode)
 (which-function-mode)
 (whitespace-newline-mode)
 (with-editor-mode)
 (xref-etags-mode)
 (yas-global-mode))
</pre>
</details>

**Comment by greghendershott** [comment]
Wow!

If a buffer gets into this state, and you save it, the pseudo tooltip text should **not** be in the file (if e.g. you view it using `cat` or `less`).

That should be impossible because pseudo tooltips are drawn using Emacs _overlays_. Any new text is only **displayed as** replacing and/or after -- via overlay properties `'display` and/or `'after-string` -- the actual text in the buffer.

The tooltip text is never actually part of the buffer text.

> Reverting the buffer also doesn't solve the problem, though this might have to do with Doom Emacs which tries to save a bunch of states in a buffer (I don't know how to use vanilla Emacs, so I can't confirm whether reverting works). My workaround is to make a copy of this file, delete the file, and rename the new file back to the original name.
 
That seems probable. In that case, the next time this happens could you please try this:

- Do the `describe-variable` command, and at the prompt enter `racket--pseudo-tooltip-overlays`, and paste the results here. If the value is `nil`, then the next step probably won't work:
    - Do the `eval-expression` command, and at the prompt enter `(racket-show nil)`. Does the tooltip go away? If not, do `describe-variable` again, what is the value now?

---

I'd be grateful if you try that, first, so I can get some more information. However after that, an easier work-around than copying/deleting/renaming the file might be this:

- Do the `kill-buffer` command, then visit the file again. I would guess completely killing the buffer would mean there is no state for Doom Emacs to preserve or interfere with?

**Comment by sorawee** [comment]
It just happens again!

`describe-variable` on `racket--pseudo-tooltip-overlays` results in `nil`:

```
racket--pseudo-tooltip-overlays is a variable defined in ‘racket-show.el’.
Its value is nil
Local in buffer setup-core.rkt; global value is the same.
```

As you suspected, `(racket-show nil)` doesn't do anything.

`kill-buffer` doesn't work by the way. I think Doom Emacs's caching is really aggressive (I can still undo/redo after reopening a killed buffer. The history is not reset).

**Comment by greghendershott** [comment]
Thanks for following up!

I could put the overlays in the buffer using some property like `'name 'racket-pseudo-tooltip`, and delete them using `(remove-overlays nil nil 'name 'racket-pseudo-tooltip)`. But that entails examining all overlays in the entire buffer, and I was concerned that would be too slow. These tooltips get created/destroyed as point moves around the buffer; keep that fast is important. That's why I decided to keep these overlays in a list in a local variable, and just delete them directly. I'd really like to continue doing that.

It didn't occur to me that something would come along and bash a buffer-local variable with my own `racket--x` name prefix. That seems... obnoxious. If in fact that's what's happening --- but your experiment seems to suggest that.

I suppose it's unclear if doom-emacs is doing that, directly. Maybe it's doing something that causes racket-mode to nil that var. I'll ponder that possibility....

---

> `kill-buffer` doesn't work by the way. I think Doom Emacs's caching is really aggressive (I can still undo/redo after reopening a killed buffer. The history is not reset).

I'll try to find time to learn more about what it's doing.

I visited their repo yesterday and noticed [the issue tracker is locked](https://github.com/hlissner/doom-emacs/issues/4510). :cry:

Apparently b/c they're going to use Discourse somehow instead... but maybe still :cry:.

**Comment by greghendershott** [comment]
Although I still haven't been able to reproduce this, I did fix a couple problems that might (?) be "adjacent" in commits I recently merged:

- commit 6118144
- commit 05874d5

So if you have time to try it again, it's possible that this may have been fixed -- or, at least, if you're still seeing bad behavior, _maybe_ it will change in a way that is useful to help diagnose this.

**Comment by sorawee** [comment]
After upgrading, I haven't experienced the bug so far, so I think it's probably fixed and therefore I will close the issue. However, if it turns out the issue still persists, I will reopen.

**Comment by greghendershott** [comment]
Glad to hear that! Definitely don't hesitate to let me know if you see this happen again.
