### ISSUE TITLE
indent wrongly when writing Redex's define-judgment-form

### ISSUE THREAD

**Issue by juniorxxue** [greghendershott/racket-mode#521]
It's a easy-to-produce bug and work well in DrRacket

demo code is from [racket/redex/examples](https://github.com/racket/redex/blob/master/redex-examples/redex/examples/lazy.rkt#L34)

```
(define-judgment-form L
  #:mode (⇓ I I O O)
  #:contract (⇓ Γ e Δ v)
  
  
  [----------- Value
               (⇓ Γ v Γ v)] ;; <------- if square open with ------- (axiom), it will indent wrongly
  
  
  [(⇓ Γ e Δ (λ (y) e_*))
   (⇓ Δ (subst e_* y x) Θ v)
   ------------------------- Application
   (⇓ Γ (e x) Θ v)] ;; <------ if square open with parens () (inference rules), it will indent correctly
```

**Comment by juniorxxue** [comment]
<details>
<pre>
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
                 (20210221 1647)
                 "Racket editing, REPL, and more"
                 ((emacs
                   (25 1))
                  (faceup
                   (0 0 2))
                  (pos-tip
                   (20191127 1028)))
                 nil nil "/Users/xuxue/.emacs.d/elpa/racket-mode-20210221.1647"
                 ((:url . "https://www.racket-mode.com/")
                  (:maintainer "Greg Hendershott")
                  (:authors
                   ("Greg Hendershott"))
                  (:commit . "e3f916f6b22a97555a226a4139815e1af32c8029"))
                 nil))
((emacs-version "27.1")
 (system-type darwin)
 (x-gtk-use-system-tooltips UNDEFINED)
 (major-mode racket-mode)
 (racket--el-source-dir "/Users/xuxue/.emacs.d/elpa/racket-mode-20210221.1647/")
 (racket--rkt-source-dir "/Users/xuxue/.emacs.d/elpa/racket-mode-20210221.1647/racket/")
 (racket-program "/usr/local/bin/racket")
 (racket-command-timeout 10)
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function nil)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "open")
 (racket-images-system-viewer "open")
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-pseudo-tooltip)))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (blink-cursor-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (hs-minor-mode)
 (line-number-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (save-place-mode)
 (savehist-mode)
 (semantic-minor-modes-format)
 (show-paren-mode)
 (tooltip-mode)
 (transient-mark-mode))
(disabled-minor-modes
 (abbrev-mode)
 (auto-fill-function)
 (auto-save-visited-mode)
 (buffer-read-only)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (defining-kbd-macro)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (global-prettify-symbols-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (horizontal-scroll-bar-mode)
 (ido-everywhere)
 (isearch-mode)
 (jit-lock-debug-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-smart-open-bracket-mode)
 (racket-xp-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (sh-electric-here-document-mode)
 (size-indication-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (tool-bar-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode)
 (xref-etags-mode))
</pre>
</details>

**Comment by greghendershott** [comment]
I see the same.

In:

```racket
  [----------- Value
               (⇓ Γ v Γ v)]
```

As far as Racket Mode knows, `-----------` is a function or macro name and `Value` is its first "argument". `-----------` is not a macro with custom indentation defined. Therefore it indents the form like a function call, with the second "argument" ` (⇓ Γ v Γ v)` indented to align with the first "argument" `Values`, as usual.

I'm not sure how/why this indents as desired in Dr Racket. Your complete example uses `#lang racket` -- so can't be using a lang-supplied custom indenter (not that Racket Mode currently can use those, anyway).

In general Racket provides no way for non-`#lang` macros to communicate special indentation rules. Someday/maybe it will -- this would be an excellent example to "stress" that design! Especially if the indent is supposed to be a property of `define-judgement-form` and handle the "any number of `-`" sub-forms as a special case!

Meanwhile the only work-around I can offer is to start the `--------` on its own line. That is, this will indent better:

```racket
  
  [
   ----------- Value
   (⇓ Γ v Γ v)]
```

I realize that's not ideal. I will try to find time to look at how/why the example works better in DrRacket. But I can't promise how quickly -- I have some other things I think are higher priority to work on first.

**Comment by sorawee** [comment]
`framework` specifically handles identifiers with all hyphens. See https://github.com/racket/gui/blob/master/gui-lib/framework/private/racket.rkt#L715

**Comment by greghendershott** [comment]
@sorawee Thank you for finding and sharing where the magic happens.

I suppose I'll add similar magic to Racket Mode, following the precedent for `for/fold`, to close this specific issue.

**Comment by greghendershott** [comment]
I merged a commit for this. It may take a couple hours for this to become available via MELPA, then you can [update](https://www.racket-mode.com/#Update).
