### ISSUE TITLE
Scheme Implementation Details

### ISSUE THREAD

**Issue by BuddhiLW** [greghendershott/racket-mode#528]
![pic-window-210405-1440-20](https://user-images.githubusercontent.com/59554283/113605379-f0e93c80-961c-11eb-862e-da27a899f960.png)

I'm unable to give a satisfactory Scheme Implementation input to emacs prompt. How can I derive this information from?

Both GNU Guile 2.2.6, Standard ML of New Jersey (64-bit) v110.99 are installed in my system

**Comment by greghendershott** [comment]
Hi.

I don't know how to answer your question.

I think maybe you opened this issue on the wrong repo?

This is the repo for [Racket Mode](https://racket-mode.com), which is for working with the [Racket language](https://racket-lang.org/).

I'm going to go ahead and close this. However, if you have installed Racket, and if you're trying to make Racket Mode work with it, and if the [Install](https://www.racket-mode.com/#Install) and [Configure](https://www.racket-mode.com/#Configure) information isn't enough to help you --- please feel free to reopen it.

**Comment by BuddhiLW** [comment]
I'm trying to use Racket Mode. But, Emacs asks me for a Scheme Implementation.


https://user-images.githubusercontent.com/59554283/113610422-7a9c0880-9623-11eb-939a-7a5e39421bf9.mp4

**Comment by greghendershott** [comment]
I wonder, do you also have Geiser installed? If so, try:

- `M-x package-delete` and enter `geiser`.
- Exit and restart Emacs.
- [Install Racket Mode](https://www.racket-mode.com/#Install) if you haven't already.
- Try opening a file ending in `.rkt`.  (Not `.sml`).
- What happens?
- Also if `M-x racket-bug-report` works for you, please paste the result in a comment here.

---

p.s. Later, you could re-install Geiser, and configure it not to try to open `.rkt` files. But I'm suggesting taking it one step at a time, and simplifying the situation for now.

**Comment by BuddhiLW** [comment]
You are right, It's Geiser. But, if I don't have it, my buffer won't even recognize the file as racket-mode.
![pic-selected-210409-1054-59](https://user-images.githubusercontent.com/59554283/114191102-6e18f800-9922-11eb-823d-3917a8d59fc4.png)

**Comment by greghendershott** [comment]
- If you're willing to do [all of these steps I'd asked](https://github.com/greghendershott/racket-mode/issues/528#issuecomment-813574153), I'm happy help you make `.rkt` files open using Racket Mode.

- Otherwise, it sounds like you're trying to do something with `auto-mode-list` and `.sml` files. For that you'll probably need to get help elsewhere, for example <https://emacs.stackexchange.com/>.

**Comment by BuddhiLW** [comment]
Sorry.

Ok

"I wonder, do you also have Geiser installed? If so, try:

M-x package-delete and enter geiser.
Exit and restart Emacs.
Install Racket Mode if you haven't already.
Try opening a file ending in .rkt. (Not .sml).
What happens?
Also if M-x racket-bug-report works for you, please paste the result in a comment here."

1)
![pic-full-210409-1333-38](https://user-images.githubusercontent.com/59554283/114212877-b17e6100-9938-11eb-91cb-08e4dc11f482.png)
![pic-selected-210409-1333-48](https://user-images.githubusercontent.com/59554283/114212901-b80cd880-9938-11eb-8d7f-4a8bf2fffe8d.png)

2-4) Already installed racket-mode.
![pic-window-210409-1335-14](https://user-images.githubusercontent.com/59554283/114212959-cb1fa880-9938-11eb-8356-1e8aad355525.png)

5)That's what happens when I open .rkt
![pic-window-210409-1335-46](https://user-images.githubusercontent.com/59554283/114213009-da9ef180-9938-11eb-98e4-833db1387426.png)

6) The debug log

```
Please copy all of the following lines and paste them into your bug report
at <https://github.com/greghendershott/racket-mode/issues/>.

<details>
<pre>
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
		 (20210328 2038)
		 "Racket editing, REPL, and more"
		 ((emacs
		   (25 1))
		  (faceup
		   (0 0 2))
		  (pos-tip
		   (20191127 1028)))
		 nil nil "/home/buddhilw/.emacs.d/elpa/racket-mode-20210328.2038"
		 ((:url . "https://www.racket-mode.com/")
		  (:maintainer "Greg Hendershott")
		  (:authors
		   ("Greg Hendershott"))
		  (:commit . "045a871d61e930c2eea8647822df39b8319018e1"))
		 nil))
((emacs-version "27.2")
 (system-type gnu/linux)
 (x-gtk-use-system-tooltips t)
 (major-mode scribble-mode)
 (racket--el-source-dir "/home/buddhilw/.emacs.d/elpa/racket-mode-20210328.2038/")
 (racket--rkt-source-dir "/home/buddhilw/.emacs.d/elpa/racket-mode-20210328.2038/racket/")
 (racket-program "racket")
 (racket-command-timeout 10)
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function nil)
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-images-system-viewer "display")
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-pseudo-tooltip)))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (blink-cursor-mode)
 (column-number-mode)
 (company-tng-mode)
 (counsel-mode)
 (display-line-numbers-mode)
 (doom-modeline-mode)
 (electric-indent-mode)
 (emojify-mode)
 (evil-collection-unimpaired-mode)
 (evil-local-mode)
 (evil-mode)
 (evil-surround-mode)
 (file-name-shadow-mode)
 (fira-code-mode)
 (font-lock-mode)
 (global-display-line-numbers-mode)
 (global-eldoc-mode)
 (global-emojify-mode)
 (global-evil-collection-unimpaired-mode)
 (global-evil-surround-mode)
 (global-font-lock-mode)
 (ivy-mode)
 (ivy-prescient-mode)
 (ivy-rich-mode)
 (line-number-mode)
 (mouse-wheel-mode)
 (override-global-mode)
 (paredit-mode)
 (prescient-persist-mode)
 (prettify-symbols-mode)
 (rainbow-delimiters-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (transient-mark-mode)
 (which-key-mode))
(disabled-minor-modes
 (abbrev-mode)
 (archive-subfile-mode)
 (auto-complete-mode)
 (auto-fill-function)
 (auto-package-update-minor-mode)
 (auto-save-visited-mode)
 (avy-linum-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (cl-old-struct-compat-mode)
 (company-mode)
 (company-search-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (dash-fontify-mode)
 (defining-kbd-macro)
 (delete-selection-mode)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (emojify-debug-mode)
 (emojify-mode-line-mode)
 (evil-smartparens-mode)
 (flyspell-mode)
 (general-override-local-mode)
 (general-override-mode)
 (global-auto-complete-mode)
 (global-company-mode)
 (global-dash-fontify-mode)
 (global-emojify-mode-line-mode)
 (global-fira-code-mode)
 (global-ligature-mode)
 (global-prettify-symbols-mode)
 (global-reveal-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (horizontal-scroll-bar-mode)
 (hs-minor-mode)
 (ido-everywhere)
 (image-minor-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (ivy-rich-project-root-cache-mode)
 (jit-lock-debug-mode)
 (ligature-mode)
 (menu-bar-mode)
 (next-error-follow-minor-mode)
 (org-cdlatex-mode)
 (org-list-checkbox-radio-mode)
 (org-src-mode)
 (org-table-follow-field-mode)
 (org-table-header-line-mode)
 (orgtbl-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (racket-smart-open-bracket-mode)
 (racket-xp-mode)
 (rectangle-mark-mode)
 (reveal-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (sh-electric-here-document-mode)
 (show-smartparens-global-mode)
 (show-smartparens-mode)
 (size-indication-mode)
 (slime-edit-value-mode)
 (slime-editing-mode)
 (slime-macroexpansion-minor-mode)
 (slime-mode)
 (slime-popup-buffer-mode)
 (smartparens-global-mode)
 (smartparens-global-strict-mode)
 (smartparens-mode)
 (smartparens-strict-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (tar-subfile-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-parent-buffer)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode)
 (xref-etags-mode))
</pre>
</details>

```

**Comment by BuddhiLW** [comment]
After deleting quack, also: 
![pic-window-210409-1342-36](https://user-images.githubusercontent.com/59554283/114213584-85171480-9939-11eb-81e7-0a5245c2880c.png)

(note: M-x racket-mode RET does't do anything to the major mode (appearing as scribble))

**Comment by BuddhiLW** [comment]
And, just because you may want to know, I have racket installed in my system:

![pic-full-210409-1344-32](https://user-images.githubusercontent.com/59554283/114213716-babbfd80-9939-11eb-9b27-b1b59ba5dd9d.png)

**Comment by capfredf** [comment]
what is your output of `(assoc "\\.rkt" auto-mode-alist)`?

**Comment by BuddhiLW** [comment]
That's my full config related to racket, at the moment

![pic-full-210409-1744-11](https://user-images.githubusercontent.com/59554283/114238573-37ab9f00-995b-11eb-98ea-660d095a59a8.png)

**Comment by capfredf** [comment]
What is your config for scribble?

**Comment by BuddhiLW** [comment]
Well, I deleted it. It was a hook on racket-mode.

Now, racket-mode is working fine!
![pic-full-210409-2002-51](https://user-images.githubusercontent.com/59554283/114248646-90d0fe00-996e-11eb-8da7-4179498463a5.png)

**Comment by BuddhiLW** [comment]
I thought scribble would function as a minor mode. Well, thank you for the time and help.

![pic-selected-210409-2005-08](https://user-images.githubusercontent.com/59554283/114248759-eb6a5a00-996e-11eb-8dcd-618984e8a38c.png)

**Comment by greghendershott** [comment]
@capfredf Thanks for helping!

@BuddhiLW Glad to hear it's working now!
