### ISSUE TITLE
Some GUI runtime contract errors are not shown

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/racket-mode#543]
As reported on Racket Slack.

Given:

```racket
#lang racket/gui

(define download-list '("file1" "file2"))
(define download-panel%
  (class horizontal-panel%
    (inherit popup-menu)
    (define/override (on-subwindow-event receiver evt)
      (cond
        [(send evt button-down?)
         (eprintf "dl = ~a~n" download-list)
         (let ([menu (new popup-menu%
                          [title "Download List"]
                          [popdown-callback
                           (lambda (pm ce) void)])])
           (for ([dl (in-list download-list)])
             (new menu-item%
                  [parent menu]
                  [label 999] ; if I change to [label 999] I don't see a contract error message
                  [callback (lambda (x y) (eprintf "cancelling ~a~n" dl))]))
           (popup-menu menu 0 0))
         #t]
        [else
         (super on-subwindow-event receiver evt)]))
    (super-new)))
(define frame (new frame%
                   [label "test"]
                   [height 512]
                   [width 512]))
(define download-status
  (new download-panel%
       (parent frame)
       (border 2)
       (stretchable-width #f)
       (stretchable-height #f)))
(define download-button
  (new button%
       (parent download-status)
       (label "Downloads")
       (stretchable-width #f)))
(send frame show #t)
```

If you run the program using command-line Racket or in Dr Racket, and click the Download button, it shows an error about `[label 999]` like:

```
initialization for menu-item%: contract violation
  expected: label-string?
  given: 999
  context...:
   /home/greg/racket/8.0.0.12/share/pkgs/gui-lib/mred/private/mrmenu.rkt:354:0: check-shortcut-args
   /home/greg/racket/8.0.0.12/share/pkgs/gui-lib/mred/private/mrmenu.rkt:365:2
   /home/greg/racket/8.0.0.12/collects/racket/private/class-internal.rkt:3590:0: continue-make-object
   /home/greg/racket/8.0.0.12/collects/racket/private/class-internal.rkt:3565:0: do-make-object/real-class
   /var/tmp/gui.rkt:7:4: on-subwindow-event method in download-panel%
   /home/greg/racket/8.0.0.12/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /home/greg/racket/8.0.0.12/collects/ffi/unsafe/atomic.rkt:73:13
   /home/greg/racket/8.0.0.12/share/pkgs/gui-lib/mred/private/wx/gtk/window.rkt:833:4: call-pre-on-event method in window%
   /home/greg/racket/8.0.0.12/share/pkgs/gui-lib/mred/private/wx/gtk/window.rkt:823:4: dispatch-on-event method in window%
   /home/greg/racket/8.0.0.12/share/pkgs/gui-lib/mred/private/wx/gtk/window.rkt:537:36
   /home/greg/racket/8.0.0.12/collects/ffi/unsafe/try-atomic.rkt:105:19
   /home/greg/racket/8.0.0.12/share/pkgs/gui-lib/mred/private/wx/gtk/queue.rkt:222:31
   /home/greg/racket/8.0.0.12/collects/ffi/unsafe/try-atomic.rkt:45:6
   /home/greg/racket/8.0.0.12/collects/ffi/unsafe/try-atomic.rkt:30:0: call-as-nonatomic-retry-point
   /home/greg/racket/8.0.0.12/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:435:6
   /home/greg/racket/8.0.0.12/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:486:32
   ...
```

However if you run the program using Racket Mode, and click the button, no error is displayed at all.

---

Notes:

- The value of `racket-error-context` does not matter.

- An "immediate" error such as a non-string value for `label` in the frame that is created, _will_ be displayed.

- It _seems_ as if the Racket Mode `error-display-handler` is not even called (but confirm this). EDIT: Actually it's NOT being called; see below.

**Comment by alex-hhh** [comment]
This is just a guess, but the main difference between the example above and something like:

```racket
#lang racket/gui
(define frame (new frame%
                   [label 9999999999999]
                   [height 512]
                   [width 512]))
```

... is that the contract error in the original example is raised in the GUI thread, while in the example above it is raised in the main thread.

Perhaps the exception from the GUI thread is  not captured to be sent back to the REPL buffer for display and instead goes to the (possibly non existent) STDERR or the racket process itself?

**Comment by jjsimpso** [comment]
The eprintf's in the problematic code do print to the REPL buffer, so I think that STDERR exists in the GUI thread.

**Comment by greghendershott** [comment]
I've been looking at this for a couple hours and I'm still stumped.

When I change this line of the example program

```racket
         (eprintf "dl = ~a\n" download-list)
```

to

```racket
         (eprintf "dl = ~a\n" download-list)
         (eprintf "uncaught-exception-handler: ~v\n" (uncaught-exception-handler))
         (eprintf "error-display-handlder: ~v\n" (error-display-handler))
```

it prints

```
dl = (file1 file2)
uncaught-exception-handler: #<procedure:default-uncaught-exception-handler>
error-display-handlder: #<procedure:our-error-display-handler>
```

That looks like the default `uncaught-exception-handler`, which calls `error-display-handler`, and that in turn looks like the one installed by Racket Mode. (Maybe I should rename it from `our-` to `racket-mode-`.)

In the Racket Mode error display handler, I add a logger output when it is called. And in this case... it is not called. Which... makes no sense to me. Yet.

---

I also experimented with forcing `racket/gui/base` to be strictly required by the Racket Mode back end process (as opposed to the lazy, on-demand dance it does).  This made no difference for this problem (although that might be a good change to make for other reasons, that would be a separate issue/discussion).

**Comment by greghendershott** [comment]
I also looked through the `mrmenu.rkt` source, which uses a `check-label-string` helper in `check.rkt`. In the end it seems to call the boring `raise-argument-error` function. Nothing exotic. Not even a Racket contract, per se. Just manual checking with a manually raised error message.

**Comment by greghendershott** [comment]
Incidentally, if the Racket Mode back end process gets something written to stderr, that comes through to Emacs. And for quite awhile (at least a year, I think), I've had that be displayed in Emacs `message` in the echo area.

Normally you'd never see this unless there were some error e.g. trying to start the process. You wouldn't see it from an error from a user program being run. But even if user program error somehow "leaked" out to the process stderr, you would see it in the echo area and the `*Messages*` buffer. Which none of us is seeing.

**Comment by greghendershott** [comment]
@alex-hhh That's a good point about the different threads. And different threads can have differing values for parameters -- including `uncaught-exception-handler` and `error-display-handler`. Alas, in my comment above, I showed code which _seems_ to rule that out, for those. But, maybe it is some other parameter(s). So I think you have a good initial "theory of the bug".

**Comment by alex-hhh** [comment]
I think this has to do with **when** the error display handler is installed.  For example, if I install an error display handler, than create a new eventspace for the GUI, exceptions in the GUI thread are handled by the event handler:

<details><summary>example code</summary>
<p>

```racket
#lang racket/gui

(error-display-handler
 (lambda (a b)
   (printf "got an error")))

(define download-list '("file1" "file2"))
(define download-panel%
  (class horizontal-panel%
    (inherit popup-menu)
    (define/override (on-subwindow-event receiver evt)
      (cond
        [(send evt button-down?)
         (eprintf "dl = ~a~n" download-list)
         (let ([menu (new popup-menu%
                          [title "Download List"]
                          [popdown-callback
                           (lambda (pm ce) void)])])
           (for ([dl (in-list download-list)])
             (new menu-item%
                  [parent menu]
                  [label 999] ; if I change to [label 999] I don't see a contract error message
                  [callback (lambda (x y) (eprintf "cancelling ~a~n" dl))]))
           (popup-menu menu 0 0))
         #t]
        [else
         (super on-subwindow-event receiver evt)]))
    (super-new)))

(parameterize ([current-eventspace (make-eventspace)])
  (define frame (new frame%
                     [label "test"]
                     [height 512]
                     [width 512]))
  (define download-status
    (new download-panel%
         (parent frame)
         (border 2)
         (stretchable-width #f)
         (stretchable-height #f)))
  (define download-button
    (new button%
         (parent download-status)
         (label "Downloads")
         (stretchable-width #f)))
  (send frame show #t))
```

</p>
</details>

However, if I install the error handler after the eventspace is created, it will not be used for errors in the GUI handler thread:

<details><summary>example code</summary>
<p>

```racket
#lang racket/gui

(define download-list '("file1" "file2"))
(define download-panel%
  (class horizontal-panel%
    (inherit popup-menu)
    (define/override (on-subwindow-event receiver evt)
      (cond
        [(send evt button-down?)
         (eprintf "dl = ~a~n" download-list)
         (let ([menu (new popup-menu%
                          [title "Download List"]
                          [popdown-callback
                           (lambda (pm ce) void)])])
           (for ([dl (in-list download-list)])
             (new menu-item%
                  [parent menu]
                  [label 999] ; if I change to [label 999] I don't see a contract error message
                  [callback (lambda (x y) (eprintf "cancelling ~a~n" dl))]))
           (popup-menu menu 0 0))
         #t]
        [else
         (super on-subwindow-event receiver evt)]))
    (super-new)))

(parameterize ([current-eventspace (make-eventspace)])
  (define frame (new frame%
                     [label "test"]
                     [height 512]
                     [width 512]))
  (define download-status
    (new download-panel%
         (parent frame)
         (border 2)
         (stretchable-width #f)
         (stretchable-height #f)))
  (define download-button
    (new button%
         (parent download-status)
         (label "Downloads")
         (stretchable-width #f)))
  (send frame show #t))

(error-display-handler
 (lambda (a b)
   (printf "got an error")))
```

</p>
</details>

Also, if the items are created in a fresh event space (as opposed by the one created by racket-mode), the errors are reported by racket mode as well:

 <details><summary>example code</summary>
<p>

```racket
#lang racket/gui

(define download-list '("file1" "file2"))
(define download-panel%
  (class horizontal-panel%
    (inherit popup-menu)
    (define/override (on-subwindow-event receiver evt)
      (cond
        [(send evt button-down?)
         (eprintf "dl = ~a~n" download-list)
         (let ([menu (new popup-menu%
                          [title "Download List"]
                          [popdown-callback
                           (lambda (pm ce) void)])])
           (for ([dl (in-list download-list)])
             (new menu-item%
                  [parent menu]
                  [label 999] ; if I change to [label 999] I don't see a contract error message
                  [callback (lambda (x y) (eprintf "cancelling ~a~n" dl))]))
           (popup-menu menu 0 0))
         #t]
        [else
         (super on-subwindow-event receiver evt)]))
    (super-new)))

(parameterize ([current-eventspace (make-eventspace)])
  (define frame (new frame%
                     [label "test"]
                     [height 512]
                     [width 512]))
  (define download-status
    (new download-panel%
         (parent frame)
         (border 2)
         (stretchable-width #f)
         (stretchable-height #f)))
  (define download-button
    (new button%
         (parent download-status)
         (label "Downloads")
         (stretchable-width #f)))
  (send frame show #481 
```
</p>
</details>

Unfortunately, this is how far I got with the investigation, and simple modifications to the racket mode code did not identify where the problem is, but hopefully this is helpful to make some progress on this issue.

**Comment by greghendershott** [comment]
Thanks! I'll digest your examples.

I had already been carefully reviewing the parameterization of `error-display-handler`, to make sure it was in effect for the eventspace thread. But I'll review again.

---

Maybe another piece of the puzzle is the button handler runs within [`call-as-atomic`](https://docs.racket-lang.org/foreign/Atomic_Execution.html#(def._((lib._ffi%2Funsafe%2Fatomic..rkt)._call-as-atomic))) -- the second line in this context:

```
  context...:
   /home/greg/src/racket-lang/racket/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /home/greg/src/racket-lang/racket/collects/ffi/unsafe/atomic.rkt:73:13
   /home/greg/src/racket-lang/racket/share/pkgs/gui-lib/mred/private/wx/gtk/window.rkt:833:4: call-pre-on-event method in window%
   /home/greg/src/racket-lang/racket/share/pkgs/gui-lib/mred/private/wx/gtk/window.rkt:823:4: dispatch-on-event method in window%
   /home/greg/src/racket-lang/racket/share/pkgs/gui-lib/mred/private/wx/gtk/window.rkt:537:36
   /home/greg/src/racket-lang/racket/collects/ffi/unsafe/try-atomic.rkt:105:19
   /home/greg/src/racket-lang/racket/share/pkgs/gui-lib/mred/private/wx/gtk/queue.rkt:222:31
   /home/greg/src/racket-lang/racket/collects/ffi/unsafe/try-atomic.rkt:45:6
   /home/greg/src/racket-lang/racket/collects/ffi/unsafe/try-atomic.rkt:30:0: call-as-nonatomic-retry-point
   /home/greg/src/racket-lang/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:435:6
   /home/greg/src/racket-lang/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:486:32
   /home/greg/src/racket-lang/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:634:3
```

Part of its docs say:

> If _thunk_ raises an exception, the exception is caught and re-raised after exiting atomic mode. Any call to the current error value conversion handler is effectively wrapped with `call-as-nonatomic`.

Something about how the exception is re-raised, might bypass a non-default `uncaught-exception-handler` and/or `error-display-handler`. Somehow? Maybe?

**Comment by greghendershott** [comment]
For the record I've been working with a slightly different program than the original example. It exhibits the same problem (no error message appearing) but simply calls `error`. Also, it prints the value of several parameters in effect at the time of the error:

```racket
#lang racket/gui

(define download-panel%
  (class horizontal-panel%
    (inherit popup-menu)
    (define/override (on-subwindow-event receiver evt)
      (cond
        [(send evt button-down?)
         (eprintf "uncaught-exception-handler: ~v\n" (uncaught-exception-handler))
         (eprintf "error-display-handler: ~v\n" (error-display-handler))
         (eprintf "current-error-port: ~v\n" (current-error-port))
         (error 'foo "bar")]
        [else
         (super on-subwindow-event receiver evt)]))
    (super-new)))
(define frame (new frame%
                   [label "test"]
                   [height 512]
                   [width 512]))
(define download-status
  (new download-panel%
       (parent frame)
       (border 2)
       (stretchable-width #f)
       (stretchable-height #f)))
(define download-button
  (new button%
       (parent download-status)
       (label "Downloads")
       (stretchable-width #f)))
(send frame show #t)
```

This highlights the most confusing aspect for me: The values of `uncaught-exception-handler` and `error-display-handler` are as expected. That is, when pressing the `Downloads` button the REPL will show:

```
uncaught-exception-handler: #<procedure:racket-mode-uncaught-exception-handler>
error-display-handler: #<procedure:racket-mode-error-display-handler>
current-error-port: #<output-port:tcp-accepted>
```

But:

- No error message is displayed.
- When I instrument both handlers to say they are called, they are _not_ called.

Note: `racket-mode-uncaught-exception-handler` simply prints that it was called, then calls the original default. I added that only to investigate this issue.

---

In addition to trying to "whittle down" the full Racket Mode code until it stops exhibiting the problem (without success), I've also been trying the opposite: Trying to "build up" a simple equivalent of what Racket Mode does, until it _starts_ exhibiting the problem. So far I have this:

```racket
#lang racket/base

(require racket/gui/base)

(define original-uncaught-exception-handler (uncaught-exception-handler))
(uncaught-exception-handler
 (λ (e)
   (displayln "calling original uncaught exception handler")
   (original-uncaught-exception-handler e)))

(define (our-error-display-handler str v)
  (displayln "!!!"))

(define (run)
  (define chan (make-channel))
  (define repl-cust (make-custodian))
  (define repl-thd
    (parameterize* ([current-custodian repl-cust]
                    [compile-enforce-module-constants #f]
                    [compile-context-preservation-enabled #t]
                    [current-namespace (make-gui-empty-namespace)]
                    [error-display-handler our-error-display-handler]
                    [current-eventspace (make-eventspace)])
      (queue-callback
       (λ ()
         (with-handlers ([exn? (λ (e)
                                 (our-error-display-handler (exn-message e) e))])
           (namespace-require "gui.rkt")
           (current-namespace (module->namespace "gui.rkt")))
         (read-eval-print-loop)))
      (eventspace-handler-thread (current-eventspace))))
  (call-with-exception-handler
   (λ (e) (println e) e)
   (λ () (sync chan))))

(void (thread run))
(sync never-evt)
```

But it does _not_ exhibit the problem. I haven't yet discovered an element to add.

(There is a whole aspect to this where the back end is a TCP server, REPL sessions are created by establishing TCP connections, the I/O is over TCP ports, etc. Maybe _somehow_ that introduces an element where `call-as-atomic` exception handling is altered? Maybe??? But I'm really grasping at straws.)

**Comment by greghendershott** [comment]
I've been looking at this for much of two days, going on three.

This bug is really kicking my `cdr`. :sob: 

---

Update: The value of `error-display-handler` is N/A.

The Racket Mode one does some special work on the contents and formatting. (Such as prefixing lines with a `;` to make them look like comments, trying to make all paths absolute so easier to visit error sites, digging for more srclocs and context, etc.) But in the end, it simply writes stuff to `current-error-port`. Just like the default handler. If you use the default handler, the error message _contents_ aren't as "nice", but this has no bearing on whether they _appear_ or not.

The bug still happens, or not, in the same conditions regardless of the value of `error-display-handler`.

---

Another idea: IIUC in certain conditions related to atomic mode, Racket's [`error-display-handler` can be ignored and instead an "emergency" uncaught exception handler is used](https://github.com/racket/racket/blob/448b77a6629c68659e1360fbe9f9e1ecea078f9c/racket/src/cs/rumble/error.ss#L497-L499). The emergency handler [logs the error message](https://github.com/racket/racket/blob/448b77a6629c68659e1360fbe9f9e1ecea078f9c/racket/src/cs/rumble/error.ss#L776-L777).

On Linux IIUC this defaults to nothing, and (using Linux) I see nothing.

But on Windows and Mac this may get written to the system log by default, IIUC. So I wonder if @alex-hhh you could check that? Do you see a log entry with the Racket button error message text?? @jjsimpso I don't recall what you're using, but if not Linux could you check, too?

**Comment by greghendershott** [comment]
I was able to start the Racket Mode back end outside Emacs, using `PLTSYSLOG="error" racket main.rkt --auth 1 --no-use-svg`, then in another console, use `nc` to start a REPL connection. Issuing a command like `(3 "repl-session-1623514054920.9143-0" run ("/var/tmp/gui.rkt") nil 2048 t 90 14 medium nil nil)` to run the GUI program, I clicked the "Downloads" button. No error message. Checked system log. No message there. :disappointed: (Did a manual `(log-error "hi")`, saw _that_ in system log.)

So, no joy on the "emergency error display handler" theory.

You're still welcome to try (the easy way) on Windows or Mac, if you want, but I think there's probably no point.

**Comment by greghendershott** [comment]
And finally... it looks like this boiled down to a use of `with-handlers` instead of `call-with-exception-handler` in the code to use `current-get-interaction-input-port` to do a `current-read-interaction`.

In other words, this is part of the REPL loop, which runs on the GUI eventspace thread (`racket/gui` arranges for `current-get-interaction-input-port` to be a port that calls `yield`).

As a result the `with-handlers` was inadvertently causing the exception to be discarded.

**Comment by jjsimpso** [comment]
Wonderful! Glad you figured it out. I will update racket-mode once this gets released.

**Comment by greghendershott** [comment]
I merged. It may take a few hours for it to flow through to MELPA. Keep in mind the [usual advice about updating](https://www.racket-mode.com/#Update).

Thanks again for reporting this!
