### ISSUE TITLE
A Weird Tooltip behavior on Emacs 28

### ISSUE THREAD

**Issue by capfredf** [greghendershott/racket-mode#544]
A tooltip overplays a portion of text at one line it is supposed to do, but pushes the rest of that text to the left:

![no-ime](https://user-images.githubusercontent.com/512906/122496801-58771d00-cfba-11eb-91c4-b2afde42ca96.gif)

Ideally (or on Emacs 27), the tooltip should cover `r "ret used with dty wi` and it should be be immediately followed by `thout dbound")]`.

<details>
<pre>
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
                 (20210604 1431)
                 "Racket editing, REPL, and more"
                 ((emacs
                   (25 1))
                  (faceup
                   (0 0 2))
                  (pos-tip
                   (20191127 1028)))
                 nil nil "/Users/capfredf/.emacs.d/elpa/racket-mode-20210604.1431"
                 ((:url . "https://www.racket-mode.com/")
                  (:maintainer "Greg Hendershott")
                  (:authors
                   ("Greg Hendershott"))
                  (:commit . "4b46a818c08820e04d25df7fe830e80ea82e1126"))
                 nil))
((emacs-version "28.0.50")
 (system-type darwin)
 (x-gtk-use-system-tooltips UNDEFINED)
 (major-mode racket-mode)
 (racket--el-source-dir "/Users/capfredf/.emacs.d/elpa/racket-mode-20210604.1431/")
 (racket--rkt-source-dir "/Users/capfredf/.emacs.d/elpa/racket-mode-20210604.1431/racket/")
 (racket-program "/Users/capfredf/.racket/bin/racket")
 (racket-command-timeout 10)
 (racket-path-from-emacs-to-racket-function identity)
 (racket-path-from-racket-to-emacs-function identity)
 (racket-browse-url-function racket-browse-url-using-temporary-file)
 (racket-documentation-search-location "https://docs.racket-lang.org/search/index.html?q=%s")
 (racket-xp-after-change-refresh-delay nil)
 (racket-xp-mode-lighter
  (:eval
   (racket--xp-mode-lighter)))
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function nil)
 (racket-submodules-to-run
  ((test)
   (main)))
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-repl-history-directory "~/.emacs.d/racket-mode/")
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-imagemagick-props nil)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "open")
 (racket-pretty-print t)
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-pseudo-tooltip)))
(enabled-minor-modes
 (abbrev-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-revert-mode)
 (auto-save-mode)
 (blink-cursor-mode)
 (column-number-mode)
 (delete-selection-mode)
 (desktop-save-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-hl-line-mode)
 (highlight-parentheses-mode)
 (hs-minor-mode)
 (icomplete-mode)
 (line-number-mode)
 (magit-auto-revert-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (org-roam-mode)
 (override-global-mode)
 (paredit-mode)
 (projectile-mode)
 (racket-xp-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (tab-bar-mode)
 (tooltip-mode)
 (transient-mark-mode)
 (which-key-mode)
 (winner-mode)
 (yas-minor-mode))
(disabled-minor-modes
 (ace-window-display-mode)
 (ace-window-mode)
 (auto-fill-function)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (avy-linum-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (bug-reference-mode)
 (bug-reference-prog-mode)
 (button-mode)
 (cl-old-struct-compat-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (dash-fontify-mode)
 (defining-kbd-macro)
 (diff-auto-refine-mode)
 (diff-hl-dir-mode)
 (diff-hl-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (dired-isearch-filenames-mode)
 (doc-view-minor-mode)
 (doc-view-presentation-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (fido-mode)
 (flycheck-mode)
 (git-commit-mode)
 (global-auto-revert-mode)
 (global-dash-fontify-mode)
 (global-diff-hl-mode)
 (global-flycheck-mode)
 (global-goto-address-mode)
 (global-highlight-parentheses-mode)
 (global-prettify-symbols-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (gnus-dead-summary-mode)
 (gnus-undo-mode)
 (goto-address-mode)
 (goto-address-prog-mode)
 (hl-line-mode)
 (horizontal-scroll-bar-mode)
 (ibuffer-auto-mode)
 (icomplete-vertical-mode)
 (ido-everywhere)
 (image-minor-mode)
 (isearch-mode)
 (jit-lock-debug-mode)
 (magit-blame-mode)
 (magit-blame-read-only-mode)
 (magit-blob-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (magit-wip-initial-backup-mode)
 (magit-wip-mode)
 (mail-abbrevs-mode)
 (markdown-live-preview-mode)
 (mc-hide-unmatched-lines-mode)
 (mml-mode)
 (multiple-cursors-mode)
 (next-error-follow-minor-mode)
 (olivetti-mode)
 (org-bullets-mode)
 (org-capture-mode)
 (org-cdlatex-mode)
 (org-indent-mode)
 (org-list-checkbox-radio-mode)
 (org-roam-backlinks-mode)
 (org-src-mode)
 (org-table-follow-field-mode)
 (org-table-header-line-mode)
 (orgtbl-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-smart-open-bracket-mode)
 (rectangle-mark-mode)
 (reftex-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (server-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (size-indication-mode)
 (smerge-mode)
 (tab-bar-history-mode)
 (table-fixed-width-mode)
 (table-mode-indicator)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (transient-resume-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-parent-buffer)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (which-function-mode)
 (window-divider-mode)
 (with-editor-mode)
 (xref-etags-mode)
 (yas-global-mode))
</pre>
</details>

**Comment by greghendershott** [comment]
I can reproduce this after fetching and building Emacs snapshot today.

It looks like `window-text-pixel-size` in Emacs 28.0.50 always returns zero after adding an overlay with a `'display` property -- that is, it claims the width of the text is zero -- unlike earlier versions.

`racket-show-pseudo-tooltip` [uses this to do "anti jiggle"](https://github.com/greghendershott/racket-mode/blob/master/racket-show.el#L128-L166).

A change like this:

```diff
@@ -149,11 +149,11 @@ left-justify everything and do not draw any border."
             (let* ((end  (min next-eol (+ beg text-len)))
                    (ov   (make-overlay beg end))
                    (old  (text-pixel-width beg end))
                    (_    (overlay-put ov 'display text))
                    (new  (text-pixel-width beg end))
-                   (diff (- new old)))
+                   (diff (if (zerop new) 0 (- new old))))
               (cons
                ov
                (when (and (not (zerop diff))
                           (< end next-eol))
```
fixes the problem for me. However, there is some "jiggle".  That's not "pixel perfect" but it may be an acceptable mitigation, at least for now.

**Comment by greghendershott** [comment]
I merged a commit that fixes this for me using latest emacs snapshot. If it doesn't fix it for you, please feel free to re-open this issue. Thanks again for reporting!

**Comment by capfredf** [comment]
[I was wondering why Racket-mode had to calculate the window size, "shouldn't the tooltip component provided by Emacs itself". Then I saw *pseudo*`-tooltip`]

**Comment by greghendershott** [comment]
Oh by the way you can customize [`racket-show-functions`](https://www.racket-mode.com/#Showing-information) to use `racket-show-pos-tip` to use real operating system tooltips instead, if you prefer. I find those slightly annoying which is why I added the pseudo tooltips. Admittedly that has been a bit of a rabbit hole, including me wanting to make the alignment "pixel perfect", which is the story behind this particular issue.

**Comment by capfredf** [comment]
I was about to ask the problems with `x-show-tip` in this case. 
I am thinking if we could tweak the frame parameters for `x-show-tip` to make the alignment almost "pixel perfect"

**Comment by greghendershott** [comment]
It's not that the OS tooltips have a _problem_ it's just what's at that link I shared:

> `racket-show-pseudo-tooltip`
>
> Show using an overlay that resembles a tooltip.
>
> This is nicer than racket-show-pos-tip because it:
>
> - Doesn’t flicker while navigating.
> - Doesn’t disappear after a timeout.
> - Performs well when x-gtk-use-system-tooltips is nil. 
>
> On the other hand, this does not look as nice when displaying text that spans multiple lines. In that case, we simply left-justify everything and do not draw any border.

---

The "pixel perfect" thing wasn't about the system tooltips, it was about a corner case with the pseudo tooltips where the tooltip text is a slightly different width than the text it's temporarily replacing. That makes the subsequent text on the line shift, or "jiggle". I figured out I could add a space that's a specific number of pixels wide, to make it align just so and not jiggle. Emacs 28 changed something about the method I was using.

**Comment by greghendershott** [comment]
p.s. Is there some way the system tooltip positioning could be improved?  I'm not sure if my comment "misled" you, or, you actually know about a problem I don't. If the latter, happy to look at that, too.

**Comment by capfredf** [comment]
after tweaking tooltips with `pos-tip` and `x-show-tip`, I believe `racket-show-pseudo-tooltip` gives me more consistent and satisfying results.
