### ISSUE TITLE
Indentation of `do`

### ISSUE THREAD

**Issue by goderich** [greghendershott/racket-mode#545]
Thank you for `racket-mode`, it's a pleasure to use.

I've recently come across a small indentation quirk, and I'm not sure what the best way to resolve it would be.

I sometimes use parser combinators from the `megaparsack` library, and with those I also use [do](https://docs.racket-lang.org/functional/interfaces.html?q=do#%28form._%28%28lib._data%2Fmonad..rkt%29._do%29%29). I don't like the way racket-mode indents it, but the problem is there is already a rule for a different [do](https://docs.racket-lang.org/reference/for.html?q=do#%28form._%28%28lib._racket%2Fprivate%2Fmore-scheme..rkt%29._do%29%29). Currently, `do` has an indent spec of 2 on line 430 in [racket-indent.el](https://github.com/greghendershott/racket-mode/blob/master/racket-indent.el#L430).

It's probably too hard or even impossible to distinguish the two do's and give them different indentation. I also don't want to insist on changing it for everyone, obviously. Is there a way to customize the indentation of a particular keyword locally?

**Comment by sorawee** [comment]
Yes, use `racket-indent-function`. See the documentation at https://www.racket-mode.com/#racket_002dindent_002dline.

**Comment by goderich** [comment]
Oh! Well that was easy. Thank you @sorawee !
