### ISSUE TITLE
The exit command in racket-repl doesn't really exit.

### ISSUE THREAD

**Issue by PLu55** [greghendershott/racket-mode#559]
I have issues with the exit command in racket-repl, it doesn't really exit, the racket process is still running. 

My problem is that the custodians are not shutdown, a UDP port is lurking around and stopping me from restarting the session. I have to kill the process manually. It must have been different in version 7 as the same problem didn't occur.

I would be very happy if the exit command really kills the racket process or at least shutdown the custodians.

Racket 8.2
Kubuntu 21.04

**Comment by greghendershott** [comment]
Racket Mode uses one back end Racket process to support a variety of commands (without even any REPLs running). Also it supports multiple simultaneous REPLs.

As a result, exiting a REPL doesn't (shouldn't) stop the entire back end process. (It _will_ shutdown the custodian associated with the REPL. In fact every `M-x racket-run` will shut down the custodian used for the previous run of your program.)

---

If you really do want to stop the entire back end, see `M-x racket-stop-back-end`.

Also, `M-x racket-start-back-end` will stop first if already running, then start. So effectively it is a (re)start.

**Comment by greghendershott** [comment]
p.s. Maybe I addressed your literal request -- how to kill the back end process -- but not the actual problem you're experiencing.

When say "a UDP port is lurking around and stopping me from restarting the session", what happens --- do you get an error message and if so what is it exactly?

Is it possible you're using `udp-bind!` with the `reuse?` parameter set to `#f` (the default if you don't specify it)?  Even if you call `udp-close` or if the custodian is shutdown, the OS might prevent the socket from being reused for awhile. At least that's the case with TCP; maybe I'm mistaken about UDP.

**Comment by greghendershott** [comment]
I re-tagged this as a question. Although I'm happy to follow up, if you don't want to I'll close this after a few more days (in which case of course feel free to re-open if you want).
