### ISSUE TITLE
Edit wxme format racket files

### ISSUE THREAD

**Issue by bon** [greghendershott/racket-mode#56]
This might be a big ask but what would be needed to extend racket-mode to parse and write DrRacket files in [WXME](http://docs.racket-lang.org/gui/editor-overview.html?q=wxme#%28part._editorfileformat%29) format? It would be a huge win to be able to edit racket files which contain images in emacs.

**Comment by greghendershott** [comment]
I'm weeding open issues. Realistically I doubt I'm ever going to do this, so I'm going to close it.
