### ISSUE TITLE
Multi-lines in racket repl?

### ISSUE THREAD

**Issue by chienguo** [greghendershott/racket-mode#560]
Hey guys! How can I input a multi-lines s-exp in racket repl, every time I type enter key to break a new line, it just eval it which still a
unfinished s-exp. Is there anyway to do that?

**Comment by greghendershott** [comment]
You can probably use <kbd>C-j</kbd>.

---

The "R" in REPL is [`read`](https://docs.racket-lang.org/reference/Reading.html#%28def._%28%28quote._~23~25kernel%29._read%29%29). Until that returns -- until it can read a complete s-expression -- it won't get to the E (eval).

So for example if you type `(+ 1` with no closing `)` you can type <kbd>ENTER</kbd> forever; it won't eval until you supply the `)`.

However probably your `racket-repl-mode` buffer is using a minor mode that automatically adds `)` after point -- like `paredit`, `smart-parens`, or `electric-pair-mode`.  Then to break the line before the closing `)` you'll probably need <kbd>C-j</kbd>.

By default <kbd>C-j</kbd> is bound to `newline-and-indent`. It could be different. I use `paredit` which binds it to the similar `paredit-newline`.  I don't know what you're using.

**Comment by chienguo** [comment]
I'm using smart-parens, but C-j also works for me. Thanks for your reply!
