### ISSUE TITLE
Format code in line with the fmt library

### ISSUE THREAD

**Issue by fakedrake** [greghendershott/racket-mode#561]
It would be nice if we could have [fmt](https://docs.racket-lang.org/fmt/index.html) format our code. It would be nice if we could `racket-fmt-buffer` or `racket-fmt-defun`. My guess is that the implementation would likely be very similar to but simpler than the `racket-tidy-requires` code.

**Comment by greghendershott** [comment]
What UX do you have in mind? Should it reformat the file on disk and `revert-buffer`, or, only reformat the buffer?

IIUC `raco fmt` has options for both: `--out -self` and `--out -`. So it's just a question of how to wrap it in Emacs and/or the Racket Mode back end.

**Comment by sorawee** [comment]
My vote is to only reformat the buffer, so that if it happens to screw up, users can undo it easily.

Let me know if any interface works best for you or if you require any change from my part.

**Comment by fakedrake** [comment]
I am having a very pleasant experience with [floskell](https://github.com/ennocramer/floskell#emacs) and [clang-format](https://github.com/sonatard/clang-format). They work exactly like `fill-paragraph` only the paragraph is the range between `beginning-of-defun` and `end-of-defun` and the fill is code formatting. `undo` works automatically (ie the packages don't have any special lisp code for it). 

Like @sorawee sais it would be better if we didn't touch the files and anyway it would be much more work to do so if we wanted to (assuming that `fmt` works through the racket server). Automatic code formatting is very important to my work in other languages but think I have never formatted anything but the "current defun" or a specific region.

**Comment by sorawee** [comment]
It's at https://github.com/sorawee/fmt. Usually, you can click the title of the documentation ("fmt: an extensible code formatter for Racket") and it will show the documentation source ("Document source https://github.com/sorawee/fmt/tree/master/scribblings/fmt.scrbl"), which lets you know the code repository.

Formatting a specific region can be done with hack. Simply cut the region and send the region to `fmt` (either through `raco fmt` or its API --- the latter is in principle better, but its interface is right now super unstable, so I recommend the former for now) then paste the output back with each subsequent line of the output indented by the current column position. I can even add a support to indent the subsequent lines to `fmt` if that's going to be easier ([`pprint-compact`](https://docs.racket-lang.org/pprint-compact/) already supports this feature, so it's just a matter of threading options through it).

**Comment by fakedrake** [comment]
To me a more important feature that can't be done at the front end would be for fmt to negotiate the new cursor position after the formatting.
Indentation is probably fairly easy to do at the front end with some arithmetic to derive the width and then replacing the newlines with newlines+some space.

**Comment by fakedrake** [comment]
The other thing that we need to think about a little bit is how we can tell fmt about the project specific formatter map. A nice case would be for fmt to read a sequence of racket files each of which `provide`s a single function. This function accepts a name and returns either the formatter or `#f`. If it returns `#f` the job of finding a formatter is delegated to the next file. When the end of the sequence is reached fmt defaults to `standard-formatter-map`. These files would ideally be provided to fmt via a `--formatter-files=...` option that lets the front end (emacs) do the work of figuring out what formatters should be used by looking at the `deps` or whatever. 

I am not sure how easy or efficient that is. What do you think?

**Comment by sorawee** [comment]
That's better discussed in the fmt repository, probably in https://github.com/sorawee/fmt/issues/5. There's already an undocumented feature where `fmt` will look up `.fmt.rkt` in the directory it's run on. But the feature definitely needs to be refined.

**Comment by greghendershott** [comment]
> I am having a very pleasant experience with [floskell](https://github.com/ennocramer/floskell#emacs) and [clang-format](https://github.com/sonatard/clang-format). They work exactly like `fill-paragraph` only the paragraph is the range between `beginning-of-defun` and `end-of-defun` and the fill is code formatting. `undo` works automatically (ie the packages don't have any special lisp code for it).

A super quick thought after a super shallow glance at the Emacs Lisp source for both of those:

There could be a generic Emacs package doing all the boilerplate both of those packages do -- and that would be needed for  `raco fmt`.

- Emacs commands for various flavors of scope -- definition, region, entire-buffer.
  - Including the first two flavors preserving the context's indentation.

- Doing `call-process-region` for X reformat executable taking Y command line flags.

And then the end user and/or something like Racket Mode could simply `setq-local` X and Y to appropriate values.

---

Needs more thought. But something along those lines is probably "The Emacs Way"?

**Comment by greghendershott** [comment]
> There could be a generic Emacs package doing all the boilerplate both of those packages do -- and that would be needed for `raco fmt`.

So using my DuckDuckGo superpowers I found [format-all-the-code](https://github.com/lassik/emacs-format-all-the-code). Its README also mentions [unibeautify](https://github.com/Unibeautify/unibeautify).

Alas `format-all-the-code` seems to provide only the one flavor, entire buffer. :(  But maybe you could double check that @fakedrake?

Regardless/meanwhile, `format-all-the-code` and `unibeautify` might be things you and/or @sorawee you want to submit `raco fmt` to?

**Comment by fakedrake** [comment]
I didn't know about either of those @greghendershott , I took a quick look into format-all-the-code and it looks like it doesn't format functions but it looks like it can format regions (`format-all-region`). The `clang-format` package I mentioned also only supports formatting regions  so I have a wrapper for that:

``` elisp
(defun in-comment-p (&optional pos)
  "Test if character at POS is comment.  If POS is nil, character at `(point)' is tested"
  (interactive)
  (unless pos (setq pos (point)))
  (let* ((fontfaces (get-text-property pos 'face)))
    (when (not (listp fontfaces))
      (setf fontfaces (list fontfaces)))
    (delq nil
          (mapcar #'(lambda (f)
                      ;; learn this trick from flyspell
                      (or (eq f 'font-lock-comment-face)
                          (eq f 'font-lock-comment-delimiter-face)))
                  fontfaces))))

(defun clang-format-fill-paragraph (&optional justify region)
  (interactive)
  (if (in-comment-p)
      (call-interactively 'fill-paragraph justify region)
    (if region
        (let ((beg (car region))
              (end (cdr region)))
          (clang-format-region beg end))
      (let ((beg (save-excursion (c-beginning-of-defun) (point)))
            (end (save-excursion (c-end-of-defun) (point))))
        (clang-format-region beg end)))))
``` 

I am pretty sure I stole this code because I don't usually use `#'` to annotate lambdas but I don't remember from where. In any case the above code checks if we are in a comment in which case it runs `fill-paragraph` and runs `clang-format-region` 
between `c-beginning-of-defun` and `c-end-of-defun` otherwise.

My humble opinion is that this process is so easy enough to implement and different enough between tools that it's hardly a problem for each major mode to implement its own...

**Comment by greghendershott** [comment]
> My humble opinion is that this process is so easy enough to implement and different enough between tools that it's hardly a problem for each major mode to implement its own...

I had a similar reaction glancing at the [`clang-format` source](https://github.com/sonatard/clang-format/blob/master/clang-format.el). Seemed easy enough for a major mode or even a determined user's init file.

But [`floskell.el`](https://github.com/ennocramer/floskell/blob/master/contrib/floskell.el) seemed longer enough to make me wonder. At a quick glance; if/when I have time I'll look again.

---

As for finding the region of a function: There is `beginning-of-defun` and it does optionally use a variable `beginning-of-defun-function` which a major mode can override. Likewise `end-of-defun` and `end-of-defun-function`.

**Comment by fakedrake** [comment]
`floskell.el` is also simple but it has some more complex logic finding out what you mean when you say "format the current thing" because it doesn't want to use `beginning-of-defun` (it wants to cover some edge cases that are specific to haskell).

**Comment by fakedrake** [comment]
I wanted to follow up on this, is there anything new?

**Comment by fakedrake** [comment]
Excellent thank you!
________________________________

**Comment by greghendershott** [comment]
I noticed this issue is still open. It occurs to me one action I could take is to point out this option in the README. I pushed commit e7efbb5 to a topic branch. Before I merge, @sorawee I'm open to changing the description?

**Comment by sorawee** [comment]
Yes, that looks good to me! (if the package has any additional noteworthy features to mention in the future, I will submit a PR to improve the description)

**Comment by greghendershott** [comment]
Thank you for the feedback; merged.
