### ISSUE TITLE
[FR] Add apropos

### ISSUE THREAD

**Issue by NightMachinery** [greghendershott/racket-mode#572]
apropos is a very useful feature in helping one find functions/variables. 

There is already an implementation in [xrepl-lib](https://docs.racket-lang.org/xrepl/index.html#%28xrepl._apropos%29), but I don’t know how difficult adapting it for racket-mode would be.

**Comment by greghendershott** [comment]
Have you tried `racket-documentation-search`, or, since a few weeks ago (since commit 46df4d9), `racket-describe-search`?
