### ISSUE TITLE
Strengths compared to other options

### ISSUE THREAD

**Issue by spdegabrielle** [greghendershott/racket-mode#579]
I feel the guide doesn't give new users a clear picture of the strengths of each option 

https://docs.racket-lang.org/guide/Emacs.html

I'm drafting a PR to fix that.

**Comment by spdegabrielle** [comment]
Draft

https://github.com/racket/racket/compare/master...spdegabrielle:patch-4

**Comment by greghendershott** [comment]
I'm not sure how to answer this.

I haven't used all of these -- much less used them _enough_ -- to be able to speak to their strengths and weaknesses.

And that's even just for myself -- much less for other people who may have varying needs/priorities/opinions.

I suppose you could add a link to https://www.racket-mode.com/ and mention that it's been developed for about 10 years now.  The fact it has many features could be a strength to some people... but other people might think "oh that sounds too 'heavy'".

---

Maybe there could be a Discourse topic where people can ask about tooling, and people can discuss what they prefer, and why. Maybe it would be best for the manual to link to that?

**Comment by spdegabrielle** [comment]
That's fair. 

In the meantime, can we expand on 

> Racket mode provides thorough syntax highlighting and DrRacket-style REPL and buffer execution support for Emacs.

perhaps

> [Racket Mode](https://www.racket-mode.com/) has been developed for 10 years and provides extensive Racket support in Emacs including: 
- thorough syntax highlighting, 
- DrRacket-style REPL, 
- buffer execution support, 
- enhanced sexp navigation, 
- documentation integration both within Emacs, and by launching browser documentation.

**Comment by greghendershott** [comment]
I'm doing some spring cleaning on open issues and would like to close this.
