### ISSUE TITLE
Back end server?

### ISSUE THREAD

**Issue by spdegabrielle** [greghendershott/racket-mode#580]
Is the back end server the racket LSP server ?

Relationship to racket LSP server?

**Comment by spdegabrielle** [comment]
Additional related question

Relationship with Debug Adapter Protocol

> The Debug Adapter Protocol (DAP) defines the abstract protocol used between a development tool (e.g. IDE or editor) and a debugger.


https://microsoft.github.io/debug-adapter-protocol/

https://emacs-lsp.github.io/dap-mode/

**Comment by greghendershott** [comment]
> Is the back end server the racket LSP server ?

No.

The source is within this repo: [here](https://github.com/greghendershott/racket-mode/tree/master/racket).

> Relationship to racket LSP server?

None.

> Relationship with Debug Adapter Protocol

None.
