### ISSUE TITLE
`exn->string` does not capture string output in REPL buffers

### ISSUE THREAD

**Issue by zyrolasting** [greghendershott/racket-mode#585]
This shell session works as expected.

```
$ racket -e '(require racket/exn) (exn->string (exn "!" (current-continuation-marks)))'
"!\n  context...:\n   body of top-level\n"
```

In a REPL buffer, `exn->string` fails to redirect output, such that the return value is always an empty string. The output is sent to the screen instead. I have provided two separate outputs of `racket-bug-report` to establish something of a timeline.

```
try.rkt> (require racket/exn) (exn->string (exn "!" (current-continuation-marks)))
; !
; Context (plain; to see better errortrace context, re-run with C-u prefix):
;   /home/sage/.emacs.d/elpa/racket-mode-20211021.1215/racket/stack-checkpoint.rkt:15:0 call-with-stack-checkpoint
;   /home/sage/.racket/collects/racket/repl.rkt:11:26
;   /home/sage/.racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:435:6
;   /home/sage/.racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:486:32
;   /home/sage/.racket/collects/racket/private/more-scheme.rkt:148:2 call-with-break-parameterization
;   /home/sage/.racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:370:11 eventspace-handler-thread-proc
""
```

### `20220109.1535`

<details>
<pre>
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
		 (20220109 1535)
		 "Racket editing, REPL, and more"
		 ((emacs
		   (25 1)))
		 nil nil "/home/sage/.emacs.d/elpa/racket-mode-20220109.1535"
		 ((:url . "https://www.racket-mode.com/")
		  (:maintainer "Greg Hendershott")
		  (:authors
		   ("Greg Hendershott"))
		  (:commit . "a2b428ff12b4c5a1e935dc6f9b551c8c312f55a1"))
		 nil))
((emacs-version "27.1")
 (system-type gnu/linux)
 (x-gtk-use-system-tooltips t)
 (major-mode racket-mode)
 (racket--el-source-dir "/home/sage/.emacs.d/elpa/racket-mode-20220109.1535/")
 (racket--rkt-source-dir "/home/sage/.emacs.d/elpa/racket-mode-20220109.1535/racket/")
 (racket-program "racket")
 (racket-command-timeout 10)
 (racket-path-from-emacs-to-racket-function identity)
 (racket-path-from-racket-to-emacs-function identity)
 (racket-browse-url-function racket-browse-url-using-temporary-file)
 (racket-documentation-search-location "https://docs.racket-lang.org/search/index.html?q=%s")
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-mode-lighter
  (:eval
   (racket--xp-mode-lighter)))
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function nil)
 (racket-submodules-to-run
  ((test)
   (main)))
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-repl-history-directory "~/.emacs.d/racket-mode/")
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-imagemagick-props nil)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-pseudo-tooltip)))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (blink-cursor-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (hs-minor-mode)
 (line-number-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (semantic-minor-modes-format)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-mark-mode))
(disabled-minor-modes
 (abbrev-mode)
 (auto-fill-function)
 (auto-save-visited-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (defining-kbd-macro)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (global-prettify-symbols-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (horizontal-scroll-bar-mode)
 (isearch-mode)
 (jit-lock-debug-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-smart-open-bracket-mode)
 (racket-xp-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (sh-electric-here-document-mode)
 (size-indication-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode)
 (xref-etags-mode))
</pre>
</details>

### `20211021.1215`

<details>
<pre>
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
		 (20211021 1215)
		 "Racket editing, REPL, and more"
		 ((emacs
		   (25 1)))
		 nil nil "/home/sage/.emacs.d/elpa/racket-mode-20211021.1215"
		 ((:url . "https://www.racket-mode.com/")
		  (:maintainer "Greg Hendershott")
		  (:authors
		   ("Greg Hendershott"))
		  (:commit . "6da1b8e42c17461260e1f2b6227c30542a85089c"))
		 nil))
((emacs-version "27.1")
 (system-type gnu/linux)
 (x-gtk-use-system-tooltips t)
 (major-mode racket-mode)
 (racket--el-source-dir "/home/sage/.emacs.d/elpa/racket-mode-20211021.1215/")
 (racket--rkt-source-dir "/home/sage/.emacs.d/elpa/racket-mode-20211021.1215/racket/")
 (racket-program "racket")
 (racket-command-timeout 10)
 (racket-path-from-emacs-to-racket-function identity)
 (racket-path-from-racket-to-emacs-function identity)
 (racket-browse-url-function racket-browse-url-using-temporary-file)
 (racket-documentation-search-location "https://docs.racket-lang.org/search/index.html?q=%s")
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-mode-lighter
  (:eval
   (racket--xp-mode-lighter)))
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function nil)
 (racket-submodules-to-run
  ((test)
   (main)))
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-repl-history-directory "~/.emacs.d/racket-mode/")
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-imagemagick-props nil)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-pseudo-tooltip)))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (blink-cursor-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (hs-minor-mode)
 (line-number-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-mark-mode))
(disabled-minor-modes
 (abbrev-mode)
 (auto-fill-function)
 (auto-save-visited-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (defining-kbd-macro)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (dired-isearch-filenames-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (global-prettify-symbols-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (horizontal-scroll-bar-mode)
 (isearch-mode)
 (jit-lock-debug-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-smart-open-bracket-mode)
 (racket-xp-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (sh-electric-here-document-mode)
 (size-indication-mode)
 (smerge-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-parent-buffer)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode)
 (xref-etags-mode))
</pre>
</details>

**Comment by zyrolasting** [comment]
Related parameterizations [1](https://github.com/racket/racket/blob/448b77a6629c68659e1360fbe9f9e1ecea078f9c/racket/collects/racket/exn.rkt#L7) [2](https://github.com/greghendershott/racket-mode/blob/184c2c8be4d9eff00477995a99153889fea46305/racket/repl.rkt#L184)

I have no idea how these could contradict expected behavior at first glance.

**Comment by zyrolasting** [comment]
The root cause appears to be a failure to preserve the default value for `(error-display-handler)`. In `racket-mode`.

Only the latter parameterization reproduces the bug.

```
#lang racket/base

(parameterize ([current-error-port (open-output-string)])
  (displayln 1 (current-error-port))
  (get-output-string (current-error-port)))

(parameterize ([current-error-port (open-output-string)])
  ((error-display-handler) "1" #f)
  (get-output-string (current-error-port)))
```

**Comment by greghendershott** [comment]
I think the most basic issue here is that both the output and error ports are the same, TCP output port:

```
baz.rkt> (current-output-port)
#<output-port:tcp-accepted>
baz.rkt> (current-error-port)
#<output-port:tcp-accepted>
baz.rkt> (equal? (current-output-port) (current-error-port))
#t
```

Racket Mode supports multiple simultaneous REPLs. The I/O for each is a TCP connection. Normally it is fine in the REPL to combine both as they both end up in the Emacs buffer.

---

The `error-display-handler` is parameterized in the Racket Mode REPL to support a number of features. For example one feature is restoring complete path names in error messages -- some things use `srcloc->string` which munges nice complete paths to e.g. a `<pkgs>/*` prefix :cry: -- so that Emacs can actually visit them. There are also things going on.

**Comment by greghendershott** [comment]
Having said all that it's late and I might be overlooking something. I'll take a closer look tomorrow.

**Comment by zyrolasting** [comment]
You're right about the ports being the same on the `racket-mode` side, but I would characterize the issue as two parameters having no logical relationship. See https://github.com/racket/racket/issues/4131

`exn->string` calls `error-display-handler` assuming it will only ever print to `current-error-port`. If `racket-repl` preempts my code, then I'm not sure if I could even access the original `error-display-handler` and prepare that pre-condition.

**Comment by greghendershott** [comment]
I agree. Even though Racket Mode needs to parameterize ("by default") both the output and error ports to the same TCP output port, its `error-display-handler` should always display errors to whatever the _current_ value of `current-error-port` happens to be.

Instead the problem is that I had been writing errors to `current-output-port`, on the (wrong) assumption it doesn't matter it's the same `current-error-port` (not necessarily, as in this bug report), and also because using just one port simplifies deciding whether a newline is needed or not (the "fresh line" business to ensure e.g. a newline before a prompt even if the output didn't have one).

So I think the fix is as simple as writing to `current-error-port` (and potentially as non-simple as figuring out the "fresh line" business considering the two separate ports... but I'll look at that).

---

Incidentally, recent issue #577 is related to this. Although my fix for that bug didn't "cause" this bug, if I had fixed that bug differently I might have fixed this bug, too.

**Comment by greghendershott** [comment]
If you install from MELPA, it may take a few hours for that to refresh. It will be some version newer than the current there, `20220109.1535`; should be something like `20220118.xxxx`.

**Comment by zyrolasting** [comment]
@greghendershott You're the best. Thank you for remaining active on this project.
