### ISSUE TITLE
check-declare somehow finding elpa installed racket mode?

### ISSUE THREAD

**Issue by tgbugs** [greghendershott/racket-mode#599]
Running `make-compile` at 2f7b12cfebbde9f2436959387d4348cc5869a6bb somehow finds `../../.emacs.d/elpa/racket-mode-*` during `check-declares` if racket-mode was installed via elpa instead of validating against git. I have no idea how this is happening, but the old version caused compile failures due to an old version from elpa. Is this expected?

**Comment by greghendershott** [comment]
I didn't expect that. Had not seen that; on my machine and on CI there isn't any N/A `.emacs.d/elpa/racket-mode-*` directory like that.

I'm guessing that directory is in `load-path` and that's why this happens.

What if you change `Makefile` to add the current directory to the start of `load-path`, e.g.:

```diff
modified   Makefile
@@ -37,6 +37,7 @@ compile: check-declares $(elc-files)
 check-declares:
 	$(batch-emacs) \
       -l check-declare \
+      --eval '(add-to-list (quote load-path) "$(PWD)")' \
       --eval '(unless (eq system-type (quote windows-nt)) (when (check-declare-directory default-directory) (kill-emacs 1)))'
```

**Comment by greghendershott** [comment]
I think my suggestion above is N/A because it's redundant: The `Makefile` already supplies `-L .` and that means the same thing:

> ‘-L DIR’
> ‘--directory=DIR’
>      Prepend directory DIR to the variable ‘load-path’.  If you specify
>      multiple ‘-L’ options, Emacs preserves the relative order; i.e.,
>      using ‘-L /foo -L /bar’ results in a ‘load-path’ of the form
>      ‘("/foo" "/bar" ...)’.  If DIR begins with ‘:’, Emacs removes the
>      ‘:’ and appends (rather than prepends) the remainder to
>      ‘load-path’.  (On MS Windows, use ‘;’ instead of ‘:’; i.e., use the
>      value of ‘path-separator’.)

**Comment by greghendershott** [comment]
So I think I'm not sure what was going on with this? I'm happy to keep investigating if you have any ideas. Or if it's no longer relevant for you and you'd like to close it, I'm also fine with that.
