### ISSUE TITLE
Output file descriptor of racket-back-end-/ is closed

### ISSUE THREAD

**Issue by TDiazT** [greghendershott/racket-mode#601]
I was trying to setup emacs with `racket-mode` but I am getting an `Output file descriptor of racket-back-end-/ is closed` message. I am getting this message when I'm running `racket-repl` and `racket-run-module-at-point` (haven't tried others). I'm not sure whether I am missing a setup step?

I'm working on a Mac OS X (Big Sur), with Emacs 27 and Racket 8.4. 

I downloaded the whole racket distribution, and not just went with the "minimal racket" option (as mentioned in the docs). I added racket to the path as well (and it's accessible from within emacs - using `exec-path-from-shell`).

I know there's an option to configure the backend, but I'm guessing that's if you want to tweak/play with different options, etc. (considering it's so far down in the doc and not mentioned in the installation/configuration steps 😆 )

I went with the simplest setup: `(use-package racket-mode)`.

**Comment by TDiazT** [comment]
Ok, so actually `exec-path-from-shell` was not working as I thought it was (I might be missing some setup there), so the `racket` binary was actually not in scope. I had to set `racket-program` to the full path as mentioned in the docs, and then it worked ok.

The error message was a bit misleading though haha, but at least it works now.

**Comment by greghendershott** [comment]
Thank you for pointing this out.

Yes, unless you want to create special back ends (more than one, and possibly remote) you shouldn't need to deal with this; it should "just work". And so I agree that error message is too cryptic, when the Racket executable can't be found.

The (optional) multi back ends feature is relatively new; that message may have become too cryptic as a result. I'll take a look at how to improve it.

**Comment by greghendershott** [comment]
With the commit closing this issue, the error message is now something like:

```
user-error: Cannot find Racket executable
racket-program: "/path/to/file/that/does/not/exist"
exec-path: ("/home/greg/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/snap/bin" "/home/greg/src/racket-lang/racket/bin/" "/home/greg/.cargo/bin" "/usr/lib/emacs/25.2/x86_64-linux-gnu")
```

Maybe that is trying to be too helpful and provide too much information. But the message you reported was so horrible, I think it's probably OK even if this over-corrects. :smile:

Thank you again for pointing this out, and I'm sorry you had to be the one to experience it.
