### ISSUE TITLE
Indent doesn't handle well the programs inside  #| ... |#.

### ISSUE THREAD

**Issue by chansey97** [greghendershott/racket-mode#603]
The current unexpected behavior is:

```
#|

(define (foo x)
  1)

(define (bar x)
  2)

|#
```

after indent

```
#|

(define (foo x)
1)

(define (bar x)
2)

|#
```

This is no ideal... 

The expected behavior is that any programs inside `#| ... |#` can be indented correctly or don't indent it.

Thanks.

<details>
<pre>
((alist-get 'racket-mode package-alist))
((emacs-version "27.2")
 (system-type windows-nt)
 (x-gtk-use-system-tooltips UNDEFINED)
 (major-mode racket-mode)
 (racket--el-source-dir "c:/Users/Chansey/AppData/Roaming/.emacs.d/site-lisp/racket-mode-20220216.1917/")
 (racket--rkt-source-dir "c:/Users/Chansey/AppData/Roaming/.emacs.d/site-lisp/racket-mode-20220216.1917/racket/")
 (racket-program "C:\\Program Files\\Racket\\Racket.exe")
 (racket-command-timeout 10)
 (racket-path-from-emacs-to-racket-function UNDEFINED)
 (racket-path-from-racket-to-emacs-function UNDEFINED)
 (racket-browse-url-function racket-browse-url-using-temporary-file)
 (racket-documentation-search-location "https://docs.racket-lang.org/search/index.html?q=%s")
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-mode-lighter
  (:eval
   (racket--xp-mode-lighter)))
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function nil)
 (racket-submodules-to-run
  ((test)
   (main)))
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-repl-history-directory "~/.emacs.d/racket-mode/")
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-imagemagick-props nil)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-pseudo-tooltip)))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (back-button-mode)
 (blink-cursor-mode)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (company-mode)
 (company-quickhelp-local-mode)
 (company-quickhelp-mode)
 (cua-mode)
 (delete-selection-mode)
 (desktop-save-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-auto-revert-mode)
 (global-company-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (global-hl-line-mode)
 (global-linum-mode)
 (global-page-break-lines-mode)
 (global-symbol-overlay-mode)
 (global-undo-tree-mode)
 (goto-address-prog-mode)
 (hs-minor-mode)
 (ivy-mode)
 (line-number-mode)
 (linum-mode)
 (menu-bar-mode)
 (mode-icons-mode)
 (mouse-wheel-mode)
 (paredit-mode)
 (popwin-mode)
 (projectile-mode)
 (racket-xp-mode)
 (recentf-mode)
 (save-place-mode)
 (savehist-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (symbol-overlay-mode)
 (tabbar-mode)
 (tabbar-mwheel-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-mark-mode)
 (treemacs-filewatch-mode)
 (treemacs-fringe-indicator-mode)
 (undo-tree-mode)
 (yas-global-mode)
 (yas-minor-mode))
(disabled-minor-modes
 (abbrev-mode)
 (ace-window-display-mode)
 (ace-window-mode)
 (auto-fill-function)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (avy-linum-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (company-search-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (counsel-mode)
 (defining-kbd-macro)
 (dired-hide-details-mode)
 (drag-stuff-global-mode)
 (drag-stuff-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (flymake-mode)
 (global-prettify-symbols-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (goto-address-mode)
 (haskell-indentation-mode)
 (hl-line-mode)
 (horizontal-scroll-bar-mode)
 (ibuffer-auto-mode)
 (isearch-mode)
 (jit-lock-debug-mode)
 (next-error-follow-minor-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (page-break-lines-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-smart-open-bracket-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (sh-electric-here-document-mode)
 (show-smartparens-global-mode)
 (show-smartparens-mode)
 (size-indication-mode)
 (smartparens-global-mode)
 (smartparens-global-strict-mode)
 (smartparens-mode)
 (smartparens-strict-mode)
 (sql-upcase-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (tabbar-local-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (treemacs-follow-mode)
 (treemacs-git-mode)
 (treemacs-tag-follow-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode)
 (xref-etags-mode))
</pre>
</details>

**Comment by chansey97** [comment]
More discussion https://racket.slack.com/archives/C09L257PY/p1647274722287779

**Comment by chansey97** [comment]
> I don't think I agree with the expected behavior?

Actually there are two expected behaviors I mentioned in the main thread. One is "indented correctly", the other is "don't indent it". Now I think the later should be a good option, i.e. Don't touch any text inside `#| ... |#`.

My current usage scenario is that I have a .rkt file which contains a lot of programs, but some of them I don't want to execute. Imagine that you have a file with a lot of tests code but some of them you don't want to run. I think using `#| ... |#` to comment them is a good idea. But the current racket-mode will compress the text inside #| ... |# ...

For example,

```
#|
(define (fib n)
  (if (<= n 2)
      1
      (+ (fib (- n 1))
         (fib (- n 2)))))
|#
```

After indent, it will be compressed to 

```
#|
(define (fib n)
(if (<= n 2)
1
(+ (fib (- n 1))
(fib (- n 2)))))
|#
```

It's ugly... (anyway I admit that it might be not a big problem, because we can uncomment it and indent again.) 

P.s. I am currently using `;;` instead of `#|...|#` to comment. The drawback is that I no longer select a sexp by just clicking the parentheses (also for expand-region).

**Comment by greghendershott** [comment]
> Actually there are two expected behaviors I mentioned in the main thread. One is "indented correctly", the other is "don't indent it". Now I think the later should be a good option, i.e. Don't touch any text inside #| ... |#.

I didn't read that thread because the link didn't work for me. (Racket Slack, for me, is at `app.slack.com/client/blahblahblah`.)

I'm probably being dense, but, I'm curious how/when the comment gets re-indented?

I mean, if you select the comment region and do `M-x indent-region`, it will re-indented. But probably you're not doing that, manually, since you don't want it to happen. So instead...

Do you manually select the entire file and `M-x indent-region`, and that's how/when it happens?

Or maybe do you use some special minor-mode that automatically does `indent-region` automatically, somehow?

Or something else?

**Comment by chansey97** [comment]
> Do you manually select the entire file and M-x indent-region, and that's how/when it happens?

Yes. I select the entire buffer and M-x indent-region.

> Or maybe do you use some special minor-mode that automatically does indent-region automatically, somehow?

No. I did not use any special minor-mode. I just tried a clean environment in my VMWare.

**Comment by greghendershott** [comment]
I think `indent-region` means indent everything. So it's working as intended. Just not as you want.

But this is Emacs. It's entirely reasonable to want something else. And you can have it. :smile: So:

You could define your own command that indents all lines in the buffer _except_ those with comment syntax. To a first approximation (I only did a quick test), it would be:

```elisp
(defun chansey97/indent-buffer-except-comments ()
  "Indent the entire buffer, except for comment lines."
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (let ((end (point-max)))
      (while (< (point) end)
        (unless (elt (syntax-ppss) 4) ;comment
          (indent-according-to-mode))
        (forward-line 1)))))
```

You could choose this with `M-x chansey97/indent-buffer-except-comments`.

You could also re-bind <kbd>C-M-\\</kbd> from `indent-region` to this.  You could change that in the global key map, or, you could change it just in `racket-mode-map` (and maybe `racket-repl-mode-map`).

Note that I made this indent the entire buffer so you needn't select it as the region beforehand.

**Comment by chansey97** [comment]
It works very well. Thanks!

Also, I have learned new knowledge from you. `(elt (syntax-ppss) 4)` can check a pos in a comment! Thanks again.
