### ISSUE TITLE
Error message path in REPL buffer can not be clicked when current path is too long

### ISSUE THREAD

**Issue by chansey97** [greghendershott/racket-mode#604]
I have two .rkt files in my working directory:

```
E:\work-pl\racket\code\racket-mode-tests\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\test-long-path.rkt
E:\work-pl\racket\code\racket-mode-tests\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\main.rkt
```

The two files' contain:

test-long-path.rkt
```
#lang racket
(provide (all-defined-out))

(define (foo)
  (bar))
```

main.rkt
```
#lang racket
(require "./test-long-path.rkt")

(foo)
```

Obviously, executing `main.rkt` will report an error, because `bar` in `test-long-path.rkt` is unbound.

So in `main.rkt`, executing `M-x (racket-run)`, Racket REPL buffer will report:

```
; 
; Welcome to Racket v8.0 [bc].
; 
> 
; ...de-tests\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\test-long-path.rkt:5:3: bar: unbound identifier
;   in: bar
> 
```

That is nice. However, as you see the error message path is not complete:

```
; ...de-tests\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\test-long-path.rkt:5:3: bar: 
```

instead of 

```
E:\work-pl\racket\code\racket-mode-tests\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\test-long-path.rkt
```

So when I click that link my Emacs cannot successfully open the file. Currently `projectile` will open a dialogue and I have to select a file manually.

Note that if the path is not too long, for example, if my working directory is `E:\work-pl\racket\code\racket-mode-tests`, then no problem.

<details>
<pre>
((alist-get 'racket-mode package-alist))
((emacs-version "27.2")
 (system-type windows-nt)
 (x-gtk-use-system-tooltips UNDEFINED)
 (major-mode racket-mode)
 (racket--el-source-dir "c:/Users/Chansey/AppData/Roaming/.emacs.d/site-lisp/racket-mode-20220216.1917/")
 (racket--rkt-source-dir "c:/Users/Chansey/AppData/Roaming/.emacs.d/site-lisp/racket-mode-20220216.1917/racket/")
 (racket-program "C:\\Program Files\\Racket\\Racket.exe")
 (racket-command-timeout 10)
 (racket-path-from-emacs-to-racket-function UNDEFINED)
 (racket-path-from-racket-to-emacs-function UNDEFINED)
 (racket-browse-url-function racket-browse-url-using-temporary-file)
 (racket-documentation-search-location "https://docs.racket-lang.org/search/index.html?q=%s")
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-mode-lighter
  (:eval
   (racket--xp-mode-lighter)))
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function nil)
 (racket-submodules-to-run
  ((test)
   (main)))
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-repl-history-directory "~/.emacs.d/racket-mode/")
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-imagemagick-props nil)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-pseudo-tooltip)))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (back-button-mode)
 (blink-cursor-mode)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (company-mode)
 (company-quickhelp-local-mode)
 (company-quickhelp-mode)
 (cua-mode)
 (delete-selection-mode)
 (desktop-save-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-auto-revert-mode)
 (global-company-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (global-hl-line-mode)
 (global-linum-mode)
 (global-page-break-lines-mode)
 (global-symbol-overlay-mode)
 (global-undo-tree-mode)
 (goto-address-prog-mode)
 (hs-minor-mode)
 (ivy-mode)
 (line-number-mode)
 (linum-mode)
 (menu-bar-mode)
 (mode-icons-mode)
 (mouse-wheel-mode)
 (paredit-mode)
 (popwin-mode)
 (projectile-mode)
 (racket-xp-mode)
 (recentf-mode)
 (save-place-mode)
 (savehist-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (symbol-overlay-mode)
 (tabbar-mode)
 (tabbar-mwheel-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-mark-mode)
 (treemacs-filewatch-mode)
 (treemacs-fringe-indicator-mode)
 (undo-tree-mode)
 (yas-global-mode)
 (yas-minor-mode))
(disabled-minor-modes
 (abbrev-mode)
 (ace-window-display-mode)
 (ace-window-mode)
 (auto-fill-function)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (avy-linum-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (company-search-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (counsel-mode)
 (defining-kbd-macro)
 (dired-hide-details-mode)
 (drag-stuff-global-mode)
 (drag-stuff-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (flymake-mode)
 (global-prettify-symbols-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (goto-address-mode)
 (haskell-indentation-mode)
 (hl-line-mode)
 (horizontal-scroll-bar-mode)
 (ibuffer-auto-mode)
 (isearch-mode)
 (jit-lock-debug-mode)
 (next-error-follow-minor-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (page-break-lines-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-smart-open-bracket-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (sh-electric-here-document-mode)
 (show-smartparens-global-mode)
 (show-smartparens-mode)
 (size-indication-mode)
 (smartparens-global-mode)
 (smartparens-global-strict-mode)
 (smartparens-mode)
 (smartparens-strict-mode)
 (sql-upcase-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (tabbar-local-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (treemacs-follow-mode)
 (treemacs-git-mode)
 (treemacs-tag-follow-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode)
 (xref-etags-mode))
</pre>
</details>

**Comment by greghendershott** [comment]
What if you use command-line Racket:

```
> racket.exe E:\work-pl\racket\code\racket-mode-tests\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\xxxxxxxxxxxxx\main.rkt
```

Do you see the same truncated path in the error message?

Racket Mode already tries pretty hard to avoid "lossy" paths in error messages, for example trying to "undo" things like `<pkgs>/path/to/file.rkt`, trying to change relative paths into absolute/complete paths, and so on. There a few tactics like this in [error.rkt](https://github.com/greghendershott/racket-mode/blob/master/racket/error.rkt). 

But the paths starting with `...` I think are elided in a way where it's probably impossible to recover the information?

**Comment by greghendershott** [comment]
> But if I run the main.rkt in the DrRacket, it can correctly open test-long-path.rkt, although in DrRacket's REPL there is neither complete path nor truncated path, it is just a test-long-path.rkt:5:3.

That's interesting. I was leaning toward believing it's not possible for Racket Mode to handle this. But if DrR can do it, I accept the challenge to figure out how. :smile:

**Comment by chansey97** [comment]
I have another Racket (v8.2 cs) installed in my VMWare. I just tried it and it is no problem. I may have to upgrade Racket to v8.4 bc.

**Comment by chansey97** [comment]
The test results:

1. Racket v8.4 cs has no problem.
2, Racket v8.4 bc has still the same problem.

**Comment by greghendershott** [comment]
I merged this to the main branch.
