### ISSUE TITLE
How is "racket-debug-run-to-here" supposed to work

### ISSUE THREAD

**Issue by fberlakovich** [greghendershott/racket-mode#613]
This could also be a bug, but since I am not sure I just assume I am using it wrong. Consider the following example
```
(define (debugging-test)
  (define a "a")
  (define b "b")
  (define c "c")
  a)
```

When I instrument the function and call `debugging-test` in the REPL, the debugger stops in the function as expected. Then I move the cursor to `(define c "c")` and press <kbd>h</kbd>. I would expect the debugger to stop at this line, showing me the then already defined values `a` and `b`. However, the debugger simply continues running to the end of the function. Is this an issue or am I using it wrong?

**Comment by greghendershott** [comment]
- The UX is: Use <kbd>n</kbd> and <kbd>p</kbd> to move among "break-able positions", and at one of those, press <kbd>h</kbd> to "run to here".
- If that still doesn't work, and you're using Windows, try using a more-recent version of Racket Mode that handles the issue in #597.
- If that still doesn't work, I'll need some `M-x racket-bug-report` details pasted into here, and we can investigate.

**Comment by fberlakovich** [comment]
> * If that still doesn't work, and you're using Windows, try using a more-recent version of Racket Mode that handles the issue in [The `racket-debug-run-to-here` doesn't work #597](https://github.com/greghendershott/racket-mode/issues/597).

I do not use Windows (not directly at least, emacs runs in WSL with only WSL internal paths), but #597 seems to have fixed it. Before updating, <kbd>n</kbd> and <kbd>p</kbd> would not jump to all breakable positions and in the example I posted, there seemed to be no position at all. 

Anyway, it works now, thanks a lot for the hint!
