### ISSUE TITLE
Allow user to set multiple, persistent breakpoints

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/racket-mode#614]
To a first approximation this generalizes `racket-debug-run-to-here`, which lets the user set a temporary one-time breakpoint.

Let the user toggle breakable positions to be breakpoints, or not. When execution reaches any, break.

`racket-debug-run-to-here` remains as a command; effectively it temporarily changes the list of breakpoints to that single location, for the next resume.

This arises from the discussion on #612.

**Comment by fberlakovich** [comment]
I couldn't test for very long but so far it works like a charm!

**Comment by greghendershott** [comment]
Thanks for the feedback; that's good to know.

I just pushed another commit which should work the same for you. However, if you wish, with a <kbd>C-u</kbd> prefix, you get prompted for a _condition_ and a list of _actions_. The default values of `#t` and `(break)` are equivalent to the plain old breakpoints of the previous commit. See the doc string for `racket-debug-toggle-breakpoint` for more information.

I'm not 100% confident about this UX or implementation. I just wanted to explore adding conditional breakpoints, as well as so-called "watchpoints", which I've seen from other debuggers, because it seems like these can all be done as flavors of the same basic mechanism we already have in place.

**Comment by greghendershott** [comment]
Oh, one "TODO" with the latest commit is that the `log` action should probably use some dedicated logger topic (not the `racket-mode` one I use mostly for development and diagnosing of Racket Mode itself). e.g. It should be some new topic like `racket-mode-debugger`, and, that should probably be added to the list of topics/levels enabled by default for `racket-logger-mode`.

**Comment by greghendershott** [comment]
Update: Over the last few days I pushed some more commits, revising the implementation and UX of multiple persistent breakpoints (which you'd asked for) with configurable conditions and actions (which you didn't ask for, but I think is probably useful for some debugging scenarios).

I just squashed these down to one commit, which I _think_ is probably ready to merge to the main branch.

I'll probably hold off merging while I dogfood this a bit more. But I'm inclined to merge soon unless I notice any serious problems.

**Comment by fberlakovich** [comment]
> Update: Over the last few days I pushed some more commits, revising the implementation and UX of multiple persistent breakpoints (which you'd asked for) with configurable conditions and actions (which you didn't ask for, but I think is probably useful for some debugging scenarios).

Absolutely awesome, I love those new features ❤️! In my typical debugging workflow in other IDEs I use conditional breakpoints and logging a lot, but it didn't occurr to me that it would be possible in racket-mode too.
