### ISSUE TITLE
Error reporting not as comprehensive as DrRacket

### ISSUE THREAD

**Issue by sinistersnare** [greghendershott/racket-mode#618]
Hi, I was wondering if there was a way to further improve racket-mode's error reporting. When I type a program such as:

```
#lang racket
(define x '(1 2 3))
(map x x)
```

Into a racket-mode buffer, and then run it in the Racket REPL, I get the following error
```
; map: contract violation
;   expected: procedure?
;   given: '(1 2 3)
; Context (plain; to see better errortrace context, re-run with C-u prefix):
;   /usr/share/racket/collects/racket/private/map.rkt:257:2 gen-map
```

Of course in this small example the error is obvious. In a more complex program, it may be hard to track down, especially since the offending line is not omitted completely in the REPL error message.

In DrRacket, the location that produced the error is highlighted in the text-buffer. Is there some way to report that information in the racket-mode REPL? I would love to help contribute such a solution if it exists.

Thank you for your time, Racket mode has been wonderful.

Details asked for:

<details>
<pre>
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
                 (20220222 1947)
                 "Racket editing, REPL, and more"
                 ((emacs
                   (25 1)))
                 nil nil "/home/dasilver/.emacs.d/elpa/27.1/develop/racket-mode-20220222.1947"
                 ((:url . "https://www.racket-mode.com/")
                  (:maintainer "Greg Hendershott")
                  (:authors
                   ("Greg Hendershott"))
                  (:commit . "30b5dfdd3a11a513b1c21e448fc8cb1ecc8a71bd"))
                 nil))
((emacs-version "27.1")
 (system-type gnu/linux)
 (x-gtk-use-system-tooltips t)
 (major-mode racket-repl-mode)
 (racket--el-source-dir "/home/dasilver/.emacs.d/elpa/27.1/develop/racket-mode-20220222.1947/")
 (racket--rkt-source-dir "/home/dasilver/.emacs.d/elpa/27.1/develop/racket-mode-20220222.1947/racket/")
 (racket-program "racket")
 (racket-command-timeout 10)
 (racket-path-from-emacs-to-racket-function UNDEFINED)
 (racket-path-from-racket-to-emacs-function UNDEFINED)
 (racket-browse-url-function racket-browse-url-using-temporary-file)
 (racket-documentation-search-location "https://docs.racket-lang.org/search/index.html?q=%s")
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-mode-lighter
  (:eval
   (racket--xp-mode-lighter)))
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function nil)
 (racket-submodules-to-run
  ((test)
   (main)))
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-repl-history-directory "~/.emacs.d/racket-mode/")
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-imagemagick-props nil)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-pseudo-tooltip)))
(enabled-minor-modes
 (anzu-mode)
 (async-bytecomp-package-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (clean-aindent-mode)
 (column-number-mode)
 (editorconfig-mode)
 (electric-indent-mode)
 (evil-escape-mode)
 (evil-local-mode)
 (evil-mode)
 (evil-surround-mode)
 (eyebrowse-mode)
 (file-name-shadow-mode)
 (flycheck-pos-tip-mode)
 (font-lock-mode)
 (global-anzu-mode)
 (global-auto-revert-mode)
 (global-display-line-numbers-mode)
 (global-eldoc-mode)
 (global-evil-surround-mode)
 (global-flycheck-mode)
 (global-font-lock-mode)
 (global-hl-line-mode)
 (global-hl-todo-mode)
 (global-page-break-lines-mode)
 (global-spacemacs-leader-override-mode)
 (global-spacemacs-whitespace-cleanup-mode)
 (global-undo-tree-mode)
 (global-vi-tilde-fringe-mode)
 (helm--remap-mouse-mode)
 (helm-descbinds-mode)
 (helm-flx-mode)
 (helm-minibuffer-history-mode)
 (helm-mode)
 (ido-vertical-mode)
 (line-number-mode)
 (mouse-wheel-mode)
 (override-global-mode)
 (persp-mode)
 (projectile-mode)
 (pupo-mode)
 (purpose-mode)
 (recentf-mode)
 (save-place-mode)
 (savehist-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (show-smartparens-global-mode)
 (show-smartparens-mode)
 (smartparens-mode)
 (smartparens-strict-mode)
 (spaceline-helm-mode)
 (spaceline-info-mode)
 (spacemacs-leader-override-mode)
 (spacemacs-whitespace-cleanup-mode)
 (transient-mark-mode)
 (undo-tree-mode)
 (vi-tilde-fringe-mode)
 (volatile-highlights-mode)
 (which-key-mode)
 (winner-mode)
 (winum-mode)
 (ws-butler-global-mode)
 (ws-butler-mode)
 (xterm-mouse-mode)
 (yas-global-mode)
 (yas-minor-mode))
(disabled-minor-modes
 (abbrev-mode)
 (auto-fill-function)
 (auto-highlight-symbol-mode)
 (auto-image-file-mode)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (blink-cursor-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (bug-reference-mode)
 (bug-reference-prog-mode)
 (cl-old-struct-compat-mode)
 (column-enforce-mode)
 (company-mode)
 (company-search-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (cua-mode)
 (dash-fontify-mode)
 (defining-kbd-macro)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (display-line-numbers-mode)
 (drag-stuff-global-mode)
 (drag-stuff-mode)
 (edebug-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (evil-mc-mode)
 (flycheck-mode)
 (flyspell-mode)
 (global-auto-highlight-symbol-mode)
 (global-column-enforce-mode)
 (global-company-mode)
 (global-dash-fontify-mode)
 (global-evil-mc-mode)
 (global-highlight-parentheses-mode)
 (global-prettify-symbols-mode)
 (global-reveal-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (goto-address-mode)
 (goto-address-prog-mode)
 (helm--minor-mode)
 (helm-adaptive-mode)
 (helm-autoresize-mode)
 (helm-display-line-numbers-mode)
 (helm-ff--delete-async-modeline-mode)
 (helm-ff-icon-mode)
 (helm-migemo-mode)
 (helm-popup-tip-mode)
 (hidden-mode-line-mode)
 (highlight-numbers-mode)
 (highlight-parentheses-mode)
 (hl-line-mode)
 (hl-todo-mode)
 (horizontal-scroll-bar-mode)
 (hs-minor-mode)
 (html-autoview-mode)
 (hybrid-mode)
 (ibuffer-auto-mode)
 (ido-everywhere)
 (image-dired-minor-mode)
 (image-minor-mode)
 (imenu-list-minor-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (menu-bar-mode)
 (next-error-follow-minor-mode)
 (org-cdlatex-mode)
 (org-src-mode)
 (org-table-follow-field-mode)
 (orgtbl-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (page-break-lines-mode)
 (paragraph-indent-minor-mode)
 (popwin-mode)
 (prettify-symbols-mode)
 (racket-smart-open-bracket-mode)
 (racket-xp-mode)
 (rainbow-delimiters-mode)
 (rectangle-mark-mode)
 (reveal-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (sgml-electric-tag-pair-mode)
 (sh-electric-here-document-mode)
 (size-indication-mode)
 (smartparens-global-mode)
 (smartparens-global-strict-mode)
 (string-edit-mode)
 (symbol-overlay-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode)
 (xref-etags-mode))
</pre>
</details>

**Comment by sinistersnare** [comment]
Ah, I see this is fixed by using a more comprehensive error-trace, as described in the docs. Using spacemacs, these things are a bit obscured, I didn't know how to activate it with the '`C-u` prefix'

**Comment by bestlem** [comment]
There is the function `racket-run-with-errortrace` which just runs racket-run with the C-u prefix

**Comment by sinistersnare** [comment]
Is there a function like `racket-run-with-errortrace-and-switch-to-repl`? I looked around the code and couldnt figure out how to add that to the current `run-and-switch-to-repl` functionality.

**Comment by greghendershott** [comment]
> There is the function racket-run-with-errortrace which just runs racket-run with the C-u prefix
> 
> Unfortunately there is not a similar function for test

@bestlem The plain `racket-test` command is equivalent to moving point somewhere within a `test` submodule and using <kbd>C-c C-c</kbd> to `racket-run-module-at-point`.  That is, it's nothing more special than running any module, it just happens to be the `test` submodule.  So you could move point somewhere within a `test` submodule and do <kbd>C-u C-c C-c</kbd>.

But I realize that's not as convenient, having to move point first like that.

> Is there a function like racket-run-with-errortrace-and-switch-to-repl? I looked around the code and couldnt figure out how to add that to the current run-and-switch-to-repl functionality.

@sinistersnare No, but `racket-run-and-switch-to-repl` does accept the same prefix arguments, including a single <kbd>C-u</kbd> prefix.

I don't use `evil-mode` or spacemacs so I'm not sure how you'd handle <kbd>C-u</kbd> generally?

If you really need it to be its own, distinct command, I guess you could define your own such command. Probably something (not tested) like this:

```elisp
(defun sinistersnare/racket-run-with-errortrace-and-switch-to-reply ()
  "Do `racket-run-and-switch-to-repl as if with single C-u prefix arg."
  (interactive)
  (racket-run-and-switch-to-repl '(4)))
```

---

Maybe we now have enough options for run-related commands, that there needs to be some better way to compose them all?

I'm not immediately sure what are the reasonable Emacs UX possibilites for this.

Defining a command for every permutation seems like it's maybe not the best idea... but maybe practically speaking it's the least-worst idea? I don't know....

**Comment by greghendershott** [comment]
@sinistersnare It looks like [spacemacs binds <kbd>SPC u</kbd> to universal argument](https://www.spacemacs.org/doc/DOCUMENTATION.html#universal-argument)?

So I think you could press <kbd>SPC u</kbd> followed by whatever key you have bound to `racket-run-and-switch-to-repl` -- does that work for you?

**Comment by sinistersnare** [comment]
That seems to work, nice! Im still a relatively new Emacs user, I am only now learning about the universal argument.

Regarding permutations for run-options, Im not sure. I think with how Spacemacs setup there could be good ways to do it, by nesting the parameters, but Im no editor designer. 

Regardless, racket-mode has been great, thanks so much!

**Comment by greghendershott** [comment]
Great!

In Emacs, it's not unusual for a command to vary how it behaves, if you supply a "universal argument" prefix. (Sometimes it will even accept multiple prefixes, for more variations. For example `racket-run` with one prefix means "run with extra error context", and with two prefixes means "run instrumented for step debugging".)

By default this prefix comes from pressing <kbd>C-u</kbd> one or more times, before invoking the command.  But that's configurable. Since `evil-mode` (IIUC) uses <kbd>C-u</kbd> to mean "page up" like in Vim, and since spacemacs using `evil-mode`, spacemacs sets it to <kbd>SPC u</kbd>.

At least that's my understanding. Although maybe I've used Emacs longer than you have, definitely you've used evil-mode and spacemacs more than I have! :smile:
