### ISSUE TITLE
Quotes affect REPL highlighting

### ISSUE THREAD

**Issue by zyrolasting** [greghendershott/racket-mode#633]
I don't think this is the same as #463.

![image](https://user-images.githubusercontent.com/1312121/179866799-c36e8f18-9c5a-49a9-82d9-1bfd39ad17cd.png)

I'm not sure if this is better called a bug or a feature request, because I don't know if `racket-mode` tries to organize buffer text into regions.

**Comment by greghendershott** [comment]
Currently it treats the entire `racket-repl-mode` buffer as something to font-lock using mostly the same rules as a `racket-mode` edit buffer.

Is this good or bad?

A REPL buffer is kind of a hopeless mix of:

- prompts
- input expressions, possibly invalid with mismatched characters
- output values from the `print` in `read-eval-print-loop`
- other output from `print`s and `write`s in your end user program
- arbitrary output from your program, e.g. `(display "I am not a Racket expression")`.

Given this, you could argue that it's a mistake to font-lock the buffer, at all. Eventually it will produce a surprising or bad result. It can also be slow when the program prints many, large values.

You could argue it should be disabled by default, and advise users they can use `racket-repl-mode-hook` to enable `font-lock-mode` if they want it.

On the other hand, in my own years of using it I've found the font-lock to be useful enough -- it helps me visually parse things -- to like it despite the occasional glitches.

So the status quo is it's enabled by default, and you can use `racket-repl-mode-hook` disable `font-lock-mode`.

---

So my personal opinion is that it's not really a bug, except maybe a documentation bug?  But I'm open to discussion.

---

I think there's a potential feature, which you hinted at: Have the back end somehow distinguish which parts of `current-output-port` come from `print` vs. `display` so the front end can font-lock those or not, as appropriate. And maybe more "region distinctions" in the front end as necessary.

This feels like a lot of work (plus the risk of breaking things) for a not-huge benefit. At least that's my initial feeling.

It might make more sense to undertake this as part of the work to support a lang lexer mode (and I'll tag this issue with that, for now).
