### ISSUE TITLE
No REPL session available

### ISSUE THREAD

**Issue by honza** [greghendershott/racket-mode#636]
1. Open a racket file
2. Enter a simple form, like `(+ 1 2)`
3. Run `racket-eval-last-sexp`

`No REPL session available`

It's my understanding that the connection to the REPL should be seamless, and automatic. 

<details>
<pre>
((alist-get 'racket-mode package-alist))
((emacs-version "28.1")
 (system-type gnu/linux)
 (x-gtk-use-system-tooltips nil)
 (major-mode racket-mode)
 (racket--el-source-dir "/home/honza/.emacs.d/.local/straight/build-28.1/racket-mode/")
 (racket--rkt-source-dir "/home/honza/.emacs.d/.local/straight/build-28.1/racket-mode/racket/")
 (racket-program "racket")
 (racket-command-timeout 10)
 (racket-path-from-emacs-to-racket-function UNDEFINED)
 (racket-path-from-racket-to-emacs-function UNDEFINED)
 (racket-browse-url-function racket-browse-url-using-temporary-file)
 (racket-documentation-search-location "https://docs.racket-lang.org/search/index.html?q=%s")
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-mode-lighter
  (:eval
   (racket--xp-mode-lighter)))
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function nil)
 (racket-submodules-to-run
  ((test)
   (main)))
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-repl-history-directory "~/.emacs.d/.local/cache/racket-mode/")
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-imagemagick-props nil)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "display")
 (racket-pretty-print t)
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-pseudo-tooltip)))
(enabled-minor-modes
 (+popup-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (better-jumper-local-mode)
 (better-jumper-mode)
 (column-number-mode)
 (company-mode)
 (display-line-numbers-mode)
 (doom-modeline-mode)
 (dtrt-indent-mode)
 (electric-indent-mode)
 (evil-escape-mode)
 (evil-goggles-mode)
 (evil-local-mode)
 (evil-mode)
 (evil-snipe-local-mode)
 (evil-snipe-mode)
 (evil-snipe-override-local-mode)
 (evil-snipe-override-mode)
 (evil-surround-mode)
 (file-name-shadow-mode)
 (flycheck-mode)
 (flycheck-popup-tip-mode)
 (font-lock-mode)
 (format-all-mode)
 (gcmh-mode)
 (general-override-mode)
 (global-company-mode)
 (global-eldoc-mode)
 (global-evil-surround-mode)
 (global-flycheck-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-hl-line-mode)
 (global-so-long-mode)
 (highlight-numbers-mode)
 (highlight-quoted-mode)
 (hl-line-mode)
 (hl-todo-mode)
 (hs-minor-mode)
 (ivy-mode)
 (ivy-prescient-mode)
 (ivy-rich-mode)
 (ivy-rich-project-root-cache-mode)
 (line-number-mode)
 (mouse-wheel-mode)
 (org-roam-db-autosync-mode)
 (parinfer-rust-mode)
 (prescient-persist-mode)
 (projectile-mode)
 (rainbow-delimiters-mode)
 (recentf-mode)
 (save-place-mode)
 (savehist-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (size-indication-mode)
 (smartparens-global-mode)
 (smartparens-mode)
 (solaire-global-mode)
 (transient-mark-mode)
 (vi-tilde-fringe-mode)
 (which-key-mode)
 (whitespace-mode)
 (windmove-mode)
 (window-divider-mode)
 (winner-mode)
 (ws-butler-global-mode)
 (ws-butler-mode)
 (yas-global-mode)
 (yas-minor-mode))
(disabled-minor-modes
 (+ansible-yaml-mode)
 (+emacs-lisp-ert-mode)
 (+javascript-gulp-mode)
 (+javascript-npm-mode)
 (+lsp-optimization-mode)
 (+popup-buffer-mode)
 (+web-angularjs-mode)
 (+web-django-mode)
 (+web-jekyll-mode)
 (+web-phaser-mode)
 (+web-react-mode)
 (+web-wordpress-mode)
 (abbrev-mode)
 (amx-debug-mode)
 (amx-mode)
 (auto-fill-function)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (avy-linum-mode)
 (blink-cursor-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (button-mode)
 (cl-old-struct-compat-mode)
 (company-search-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (context-menu-mode)
 (counsel-mode)
 (counsel-projectile-mode)
 (cursor-intangible-mode)
 (cursor-sensor-mode)
 (dash-fontify-mode)
 (defining-kbd-macro)
 (delete-selection-mode)
 (desktop-save-mode)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (doom-docs-mode)
 (dtrt-indent-global-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (evil-collection-magit-toggle-text-minor-mode)
 (flyspell-mode)
 (general-override-local-mode)
 (git-commit-mode)
 (global-auto-revert-mode)
 (global-dash-fontify-mode)
 (global-display-line-numbers-mode)
 (global-hl-todo-mode)
 (global-prettify-symbols-mode)
 (global-reveal-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-vi-tilde-fringe-mode)
 (global-visual-line-mode)
 (global-whitespace-mode)
 (global-whitespace-newline-mode)
 (horizontal-scroll-bar-mode)
 (ibuffer-auto-mode)
 (indent-tabs-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (lock-file-mode)
 (magit-auto-revert-mode)
 (magit-blame-mode)
 (magit-blame-read-only-mode)
 (magit-blob-mode)
 (magit-popup-help-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (magit-wip-initial-backup-mode)
 (magit-wip-mode)
 (mail-abbrevs-mode)
 (menu-bar-mode)
 (mml-mode)
 (next-error-follow-minor-mode)
 (org-capture-mode)
 (org-cdlatex-mode)
 (org-list-checkbox-radio-mode)
 (org-src-mode)
 (org-table-follow-field-mode)
 (org-table-header-line-mode)
 (orgtbl-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-smart-open-bracket-mode)
 (racket-xp-mode)
 (rectangle-mark-mode)
 (reveal-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (server-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (show-smartparens-global-mode)
 (show-smartparens-mode)
 (smartparens-global-strict-mode)
 (smartparens-strict-mode)
 (smerge-mode)
 (so-long-minor-mode)
 (solaire-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-resume-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (which-function-mode)
 (whitespace-newline-mode)
 (with-editor-mode)
 (xref-etags-mode))
</pre>
</details>

**Comment by greghendershott** [comment]
Probably you want to be using `racket-send-last-sexp` instead, for day to day use. If necessary it will automatically run the file and start a REPL, first. It's bound to <kbd>C-x C-e</kbd> like the similar commands in e.g. `emacs-lisp-mode` and `scheme-mode`.

The original motivation for `racket-eval-last-sexp` was, IIRC, for another package (lispy maybe?) that needed something like this for one of its commands. It's not bound to any keys by default.

---

Of course keep in mind that both of these are pretty limited in a language like Racket -- the meaning of even `(+ 1 2)` isn't necessarily clear until you know the lexical context and/or `#lang`. Needing at least some `#lang` is partly why you need a live REPL session for some file.

---

Do you think any of the above should be added to the doc strings for either or both of these commands? Probably that's how I would want to close this issue?

**Comment by greghendershott** [comment]
> Probably you want to be using `racket-send-last-sexp` instead, for day to day use. If necessary it will automatically run the file and start a REPL, first.

That was my recollection, but I realized that I hardly ever use this unless I've already run the file. So to be sure I tried just now. With no live REPL, it does **not** automatically run first, instead it gives an error:

```
Debugger entered--Lisp error: (wrong-type-argument processp nil)
  process-mark(nil)
  (goto-char (process-mark proc))
  (save-excursion (goto-char (process-mark proc)) (insert 10) (if echo-p (progn (insert (save-current-buffer (set-buffer source-buffer) (buffer-substring start end))) (insert "\n;; =>\n"))) (set-marker (process-mark proc) (point)))
  (closure ((proc) (source-buffer . #<buffer issue-636.rkt>) (echo-p) (end . 27) (start . 20) t) nil (save-excursion (goto-char (process-mark proc)) (insert 10) (if echo-p (progn (insert (save-current-buffer (set-buffer source-buffer) (buffer-substring start end))) (insert "\n;; =>\n"))) (set-marker (process-mark proc) (point))))()
  funcall((closure ((proc) (source-buffer . #<buffer issue-636.rkt>) (echo-p) (end . 27) (start . 20) t) nil (save-excursion (goto-char (process-mark proc)) (insert 10) (if echo-p (progn (insert (save-current-buffer (set-buffer source-buffer) (buffer-substring start end))) (insert "\n;; =>\n"))) (set-marker (process-mark proc) (point)))))
  (save-current-buffer (set-buffer buf) (funcall thunk))
  (let ((buf val)) (save-current-buffer (set-buffer buf) (funcall thunk)))
  (if (bufferp val) (let ((buf val)) (save-current-buffer (set-buffer buf) (funcall thunk))) nil)
  (let* ((val (get-buffer name))) (if (bufferp val) (let ((buf val)) (save-current-buffer (set-buffer buf) (funcall thunk))) nil))
  (let ((name val)) (let* ((val (get-buffer name))) (if (bufferp val) (let ((buf val)) (save-current-buffer (set-buffer buf) (funcall thunk))) nil)))
  (if (stringp val) (let ((name val)) (let* ((val (get-buffer name))) (if (bufferp val) (let ((buf val)) (save-current-buffer (set-buffer buf) (funcall thunk))) nil))) (let ((v val)) (error "bad racket-repl-buffer-name: %s" v)))
  (let* ((val (if (eq major-mode (quote racket-repl-mode)) (buffer-name) racket-repl-buffer-name))) (if (stringp val) (let ((name val)) (let* ((val (get-buffer name))) (if (bufferp val) (let ((buf val)) (save-current-buffer (set-buffer buf) (funcall thunk))) nil))) (let ((v val)) (error "bad racket-repl-buffer-name: %s" v))))
  racket--call-with-repl-buffer((closure ((proc) (source-buffer . #<buffer issue-636.rkt>) (echo-p) (end . 27) (start . 20) t) nil (save-excursion (goto-char (process-mark proc)) (insert 10) (if echo-p (progn (insert (save-current-buffer (set-buffer source-buffer) (buffer-substring start end))) (insert "\n;; =>\n"))) (set-marker (process-mark proc) (point)))))
  (let ((proc (get-buffer-process racket-repl-buffer-name))) (racket--call-with-repl-buffer (function (lambda nil (save-excursion (goto-char (process-mark proc)) (insert 10) (if echo-p (progn (insert ...) (insert "\n;; =>\n"))) (set-marker (process-mark proc) (point)))))) (save-current-buffer (set-buffer source-buffer) (comint-send-region proc start end) (comint-send-string proc "\n")))
  (let ((source-buffer (current-buffer))) (racket-repl t) (racket--repl-forget-errors) (let ((proc (get-buffer-process racket-repl-buffer-name))) (racket--call-with-repl-buffer (function (lambda nil (save-excursion (goto-char (process-mark proc)) (insert 10) (if echo-p (progn ... ...)) (set-marker (process-mark proc) (point)))))) (save-current-buffer (set-buffer source-buffer) (comint-send-region proc start end) (comint-send-string proc "\n"))) (display-buffer racket-repl-buffer-name))
  racket--send-region-to-repl(20 27 nil)
  racket-send-last-sexp(nil)
  funcall-interactively(racket-send-last-sexp nil)
  #<subr call-interactively>(racket-send-last-sexp nil nil)
  apply(#<subr call-interactively> racket-send-last-sexp (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> racket-send-last-sexp nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (racket-send-last-sexp nil nil))
  call-interactively(racket-send-last-sexp nil nil)
  command-execute(racket-send-last-sexp)
```

At the very least, this could/should give a better error message, such as "Please run the file first."

Maybe it should even do the thing I mis-remembered it doing, and automatically run it for you.

**Comment by greghendershott** [comment]
I gave this some more thought.

When a REPL doesn't already exist, it could indeed be handy to automatically run the file and thereby create the REPL. However:

- A given program might take an indeterminate amount of time to run and get to a REPL prompt (a dumb example is `(sleep 10)`). Sure, we _could_ handle this "asynchronously" so that Emacs isn't blocked; Racket Mode already does so for some other things. But this seems a bit over-engineered compared to asking the user to run it themselves.

- Racket Mode has different "flavors" of what it means to "run", including `racket-run`, `racket-run-and-switch-to-repl`, `racket-run-module-at-point`, `racket-test`, etc. Many of these even have "sub-flavors" using one or more `C-u` command prefixes. Sure, we _could_ add even more customization variables for users to be able to say which one to use here. But (again) this seems a bit over-engineered compared to reminding the user to run it themselves, as they prefer.

So I think reminding the user to run, is really probably the best (or anyway, "least-worst") way to approach this.

I do have a commit that improves the error messages and doc strings, in this vein. My plan is to merge that.
