### ISSUE TITLE
scribble support?

### ISSUE THREAD

**Issue by dented42** [greghendershott/racket-mode#64]
racket-mode doesn't seem to understand scribble files very well. It would be nice to have Emacs commands for rendering the current buffer to an plain-text, markdown, html, latex, or pdf document. This would also require being able to parse at-exprs correctly, which would mean racket mode would by default be able to parse '#lang at-exp racket' and friends.

I think having racket-mode be able to theoretically support any reader extension is most likely overkill, but support for common ones such as at-expressions, the typed racket annotations (#{a : B} and friends), and scribble would be nice.

**Comment by cena** [comment]
Little late to this, and hopefully not too off-topic, but is there a list somewhere of every #lang?  I'm attempting to use Emacs to go through HTDP, and after an hour+ of fruitless searching, finally tweeted to #racketlang about how to use the beginning student language in emacs.  ( #lang htdp/bsl ) 

Knowing what's definable in #lang seems helpful (if not completely within racket-mode's wheelhouse).

**Comment by greghendershott** [comment]
> is there a list somewhere of every #lang?

This is a great question. It might be good to raise on StackOverflow and/or [racket-users](https://groups.google.com/forum/#!forum/racket-users).

I think the answer is to navigate all installed collections, and see which ones provide a `lang/reader`.

> how to use the beginning student language in emacs. ( #lang htdp/bsl ) 

I'm not familiar at all with the various students languages.

I did just try doing the following in racket-mode and it worked:

```
#lang htdp/bsl
(+ 1 1)
```

But if you have any problems feel free to log a fresh issue for each one, here.
