### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by vojta-horanek** [greghendershott/racket-mode#644]
I've found a typo in the documentation, more exactly [here](https://www.racket-mode.com/#Configure-Emacs-to-use-MELPA). 
Instead of
```
(package-initialze)
```
you probably meant to say
```
(package-initialize)
```

**Comment by greghendershott** [comment]
Thanks! Just fixed it in commit 3b92a5b.

**Comment by greghendershott** [comment]
p.s. Also I refreshed the web site and invalidated the Amazon CloudWatch CDN.

If you still have that page open in your browser, you might need to refresh to see the change.
