### ISSUE TITLE
collection not found

### ISSUE THREAD

**Issue by WIZARDELF** [greghendershott/racket-mode#652]
I repeatedly got this error when running commands like `racket-run`:

<details>
<pre>
{racket-back-end-/-stderr} /Users/lisp/.emacs.d/elpa/racket-mode-20230124.2016/racket/elisp.rkt:83:11: collection not found
  for module path: rackunit
  collection: "rackunit"
  in collection directories:
   /Users/lisp/Library/Racket/8.7/collects
   /usr/local/Cellar/minimal-racket/8.7/share/racket/collects/
   /usr/local/opt/minimal-racket/share/racket/pkgs/base
   /usr/local/opt/minimal-racket/share/racket/pkgs/racket-lib
  location...:
   /Users/lisp/.emacs.d/elpa/racket-mode-20230124.2016/racket/elisp.rkt:83:11
</pre>
</details>

I'd set the `racket-program` var: `(setq racket-program "/usr/local/bin/racket")`

My box info:

<details>
<pre>
((alist-get 'racket-mode package-alist)
 #s(package-desc racket-mode
								 (20230124 2016)
								 "Racket editing, REPL, and more"
								 ((emacs
									 (25 1)))
								 nil nil "/Users/lisp/.emacs.d/elpa/racket-mode-20230124.2016"
								 ((:url . "https://www.racket-mode.com/")
									(:maintainer "Greg Hendershott")
									(:authors
									 ("Greg Hendershott" . "racket-mode-author@greghendershott.com"))
									(:commit . "eda9fc2c7c475bb98259464d88c6912cee73e0b0"))
								 nil))
((emacs-version "28.2")
 (system-type darwin)
 (x-gtk-use-system-tooltips UNDEFINED)
 (major-mode racket-mode)
 (racket--el-source-dir "/Users/lisp/.emacs.d/elpa/racket-mode-20230124.2016/")
 (racket--rkt-source-dir "/Users/lisp/.emacs.d/elpa/racket-mode-20230124.2016/racket/")
 (racket-program "/usr/local/Cellar/minimal-racket/8.7/bin/racket")
 (racket-command-timeout 10)
 (racket-path-from-emacs-to-racket-function UNDEFINED)
 (racket-path-from-racket-to-emacs-function UNDEFINED)
 (racket-browse-url-function racket-browse-url-using-temporary-file)
 (racket-documentation-search-location "https://docs.racket-lang.org/search/index.html?q=%s")
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-mode-lighter
	(:eval
	 (racket--xp-mode-lighter)))
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function nil)
 (racket-submodules-to-run
	((test)
	 (main)))
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-repl-history-directory "~/.emacs.d/racket-mode/")
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-imagemagick-props nil)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "open")
 (racket-pretty-print t)
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
	((cm-accomplice . warning)
	 (GC . info)
	 (module-prefetch . warning)
	 (optimizer . info)
	 (racket/contract . error)
	 (racket-mode-debugger . info)
	 (sequence-specialization . info)
	 (* . fatal)))
 (racket-show-functions
	(racket-show-pseudo-tooltip)))
(enabled-minor-modes
 (ace-pinyin-global-mode)
 (ace-pinyin-mode)
 (async-bytecomp-package-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (blink-cursor-mode)
 (column-number-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (geiser-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (global-prettify-symbols-mode)
 (global-undo-tree-mode)
 (global-visual-line-mode)
 (hs-minor-mode)
 (line-number-mode)
 (mouse-wheel-mode)
 (override-global-mode)
 (pyvenv-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (smartparens-global-mode)
 (smartparens-mode)
 (tooltip-mode)
 (transient-mark-mode)
 (undo-tree-mode)
 (visual-line-mode)
 (yas-minor-mode))
(disabled-minor-modes
 (abbrev-mode)
 (archive-subfile-mode)
 (auto-fill-function)
 (auto-save-visited-mode)
 (avy-linum-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (button-mode)
 (cider--debug-mode)
 (cider-auto-test-mode)
 (cider-enlighten-mode)
 (cider-mode)
 (cider-popup-buffer-mode)
 (cl-old-struct-compat-mode)
 (clj-refactor-mode)
 (company-mode)
 (company-search-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (context-menu-mode)
 (dash-fontify-mode)
 (defining-kbd-macro)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (doc-view-minor-mode)
 (doc-view-presentation-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (elpy-django)
 (elpy-mode)
 (eshell-arg-mode)
 (eshell-command-mode)
 (eshell-proc-mode)
 (flymake-mode)
 (geiser-autodoc-mode)
 (geiser-smart-tab-mode)
 (global-company-mode)
 (global-dash-fontify-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-subword-mode)
 (global-superword-mode)
 (gnus-dead-summary-mode)
 (gnus-undo-mode)
 (helm--minor-mode)
 (helm--remap-mouse-mode)
 (helm-autoresize-mode)
 (helm-display-line-numbers-mode)
 (helm-migemo-mode)
 (helm-popup-tip-mode)
 (highlight-indentation-current-column-mode)
 (highlight-indentation-mode)
 (horizontal-scroll-bar-mode)
 (html-autoview-mode)
 (ido-everywhere)
 (image-minor-mode)
 (indent-tabs-mode)
 (isearch-mode)
 (jit-lock-debug-mode)
 (lock-file-mode)
 (mail-abbrevs-mode)
 (mc-hide-unmatched-lines-mode)
 (menu-bar-mode)
 (mml-mode)
 (multiple-cursors-mode)
 (next-error-follow-minor-mode)
 (org-cdlatex-mode)
 (org-list-checkbox-radio-mode)
 (org-src-mode)
 (org-table-follow-field-mode)
 (org-table-header-line-mode)
 (orgtbl-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (paredit-mode)
 (prettify-symbols-mode)
 (pyvenv-tracking-mode)
 (racket-debug-mode)
 (racket-smart-open-bracket-mode)
 (racket-xp-mode)
 (rainbow-delimiters-mode)
 (rectangle-mark-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (server-mode)
 (sgml-electric-tag-pair-mode)
 (sh-electric-here-document-mode)
 (show-smartparens-global-mode)
 (show-smartparens-mode)
 (size-indication-mode)
 (smartparens-global-strict-mode)
 (smartparens-strict-mode)
 (subword-mode)
 (superword-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (undo-tree-visualizer-selection-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-parent-buffer)
 (view-mode)
 (visible-mode)
 (window-divider-mode)
 (winner-mode)
 (xref-etags-mode)
 (yas-global-mode))
</pre>
</details>

**Comment by greghendershott** [comment]
I think the short answer is probably you'll need to `raco pkg install rackunit`.

Are you using "minimal Racket", e.g. from homebrew on mac?

- If so: Did you follow [these instructions](https://www.racket-mode.com/#Minimal-Racket)?

    - If not, please do that.

    - If yes, you did that already, then maybe I need to update those instructions, and explicitly add `rackunit` to the lists. Let me know and I'll investigate.

**Comment by WIZARDELF** [comment]
Thank you very much, @greghendershott 💯 Your instruction worked, and my *racket-mode* works well now.

I really did `raco pkg install --auto drracket` as is described in the document. Probably, the document needs to add `raco pkg install rackunit`.
