### ISSUE TITLE
hash-lang: error during indentation

### ISSUE THREAD

**Issue by Bogdanp** [greghendershott/racket-mode#668]
Hi Greg,

I don't know if this is supposed to be fully baked yet or not, but I just added an indentation function to `#lang lua` that fails with 

```
let: send: no such method
  method name: begin-edit-sequence
  class name: our-hash-lang%
```

on the `hash-lang` branch, but works fine in DrRacket. The implementation in `#lang lua` is [here](https://github.com/Bogdanp/racket-lua/blob/918346d352af2d8835eec011e0047df9ac1e7e53/lua-lib/lang/tool.rkt#L33-L88). I think this _should_ work, since the first argument is supposed to be a `text%`, which implements `editor<%>` and should have a `begin-edit-sequence` method.

<details>
<pre>
((alist-get 'racket-mode package-alist))
((emacs-version "29.1")
 (system-type darwin)
 (x-gtk-use-system-tooltips UNDEFINED)
 (major-mode help-mode)
 (racket--el-source-dir "/Users/bogdan/.emacs.d/vendor/racket-mode/")
 (racket--rkt-source-dir "/Users/bogdan/.emacs.d/vendor/racket-mode/racket/")
 (racket-program "racket")
 (racket-command-timeout 10)
 (racket-path-from-emacs-to-racket-function UNDEFINED)
 (racket-path-from-racket-to-emacs-function UNDEFINED)
 (racket-browse-url-function racket-browse-url-using-temporary-file)
 (racket-documentation-search-location "https://docs.racket-lang.org/search/index.html?q=%s")
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-mode-lighter
  (:eval
   (racket--xp-mode-lighter)))
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function racket-repl-buffer-name-project)
 (racket-submodules-to-run
  ((test)
   (main)))
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-repl-history-directory "~/.emacs.d/racket-mode/")
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-imagemagick-props nil)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "open")
 (racket-pretty-print t)
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (racket-mode-debugger . info)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-echo-area)))
(enabled-minor-modes
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (buffer-read-only)
 (column-number-mode)
 (dumb-jump-mode)
 (electric-indent-mode)
 (evil-local-mode)
 (evil-mode)
 (evil-surround-mode)
 (file-name-shadow-mode)
 (flx-ido-mode)
 (font-lock-mode)
 (global-auto-revert-mode)
 (global-eldoc-mode)
 (global-evil-surround-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-hl-line-mode)
 (ido-everywhere)
 (ido-ubiquitous-mode)
 (ido-vertical-mode)
 (isearch-fold-quotes-mode)
 (line-number-mode)
 (mac-mouse-wheel-mode)
 (menu-bar-mode)
 (override-global-mode)
 (projectile-mode)
 (recentf-mode)
 (save-place-mode)
 (savehist-mode)
 (semantic-minor-modes-format)
 (server-mode)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (transient-mark-mode)
 (windmove-mode))
(disabled-minor-modes
 (abbrev-mode)
 (auto-fill-function)
 (auto-image-file-mode)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (blink-cursor-mode)
 (buffer-face-mode)
 (button-mode)
 (cl-old-struct-compat-mode)
 (comint-fontify-input-mode)
 (company-mode)
 (company-search-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (context-menu-mode)
 (cursor-face-highlight-mode)
 (dash-fontify-mode)
 (defining-kbd-macro)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (dired-isearch-filenames-mode)
 (dired-omit-mode)
 (diredp-breadcrumbs-in-header-line-mode)
 (display-line-numbers-mode)
 (edit-indirect--overlay)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (eshell-arg-mode)
 (eshell-command-mode)
 (eshell-proc-mode)
 (flycheck-mode)
 (flymake-mode)
 (flyspell-mode)
 (git-commit-mode)
 (global-company-mode)
 (global-dash-fontify-mode)
 (global-dired-hide-details-mode)
 (global-display-line-numbers-mode)
 (global-flycheck-mode)
 (global-prettify-symbols-mode)
 (global-reveal-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (gnus-dead-summary-mode)
 (gnus-undo-mode)
 (header-line-indent-mode)
 (hl-line-mode)
 (horizontal-scroll-bar-mode)
 (hs-minor-mode)
 (ibuffer-auto-mode)
 (ido-cr+-debug-mode)
 (image-minor-mode)
 (indent-tabs-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (lock-file-mode)
 (lost-selection-mode)
 (mac-auto-ascii-mode)
 (mac-auto-operator-composition-mode)
 (mac-font-panel-mode)
 (magit-auto-revert-mode)
 (magit-blame-mode)
 (magit-blame-read-only-mode)
 (magit-blob-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (magit-wip-initial-backup-mode)
 (magit-wip-mode)
 (mail-abbrevs-mode)
 (minibuffer-electric-default-mode)
 (mml-mode)
 (mouse-wheel-mode)
 (mu4e-context-minor-mode)
 (mu4e-search-minor-mode)
 (mu4e-update-minor-mode)
 (next-error-follow-minor-mode)
 (org-cdlatex-mode)
 (org-list-checkbox-radio-mode)
 (org-src-mode)
 (org-table-follow-field-mode)
 (org-table-header-line-mode)
 (orgtbl-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (paredit-mode)
 (prettify-symbols-mode)
 (pyvenv-mode)
 (pyvenv-tracking-mode)
 (racket-smart-open-bracket-mode)
 (racket-xp-mode)
 (rainbow-delimiters-mode)
 (read-extended-command-mode)
 (rectangle-mark-mode)
 (reveal-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (shell-highlight-undef-mode)
 (size-indication-mode)
 (smerge-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-resume-mode)
 (treesit-explore-mode)
 (treesit-inspect-mode)
 (undelete-frame-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-dir-git-mode)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (which-function-mode)
 (window-divider-mode)
 (with-editor-mode)
 (xref-etags-mode))
</pre>
</details>

**Comment by greghendershott** [comment]
Thank you for trying this!! I'm really pushing to merge this branch. On the one hand I don't want to merge something too flaky. On the other hand merging it will get more people using it so I can find/fix more problems.

---

Maybe some Racket "make a lang" documentation needs to be updated -- and if you already know where, please tell me and I'll make a PR -- but:

Since [expeditor](https://docs.racket-lang.org/expeditor/index.html) it should preferably be not a full `text%` but instead a [`color-textoid%`](https://docs.racket-lang.org/syntax-color/color-textoid.html).

If you're willing and able to do that, then it should work with expeditor in command-line racket, as well as non-GUI-drracket tools like the back end for Racket Mode's `racket-hash-lang-mode`. (Or at least, we can progress to more nuanced bugs. :wink:)

Is that practical for you with `#lang lua`??

**Comment by greghendershott** [comment]
p.s. If there's some issue like, you really need a method like `begin-edit-sequence` for it to work in DrRacket, then we can figure that out in a couple ways.

Maybe `color-textoid%`s should add such a method, as a dummy no-op? Unless that's a breaking change to the interface.

Or, maybe you could add some sort of `is-a` conditional -- if that's not too fugly?

We could discuss with Matthew.

**Comment by Bogdanp** [comment]
I was able to implement the indenter using the more limited interface, though I don't love the approach I had to take. It's surprising to me that there's no way to get the line being indented and the line before using this interface, but maybe I'm just missing some trick so I'll try to look into it again later. Either way, indentation for `#lang lua` now works in emacs so I'll go ahead and close this. Thanks again for the pointer!

I did find one issue with racket-mode's `color-textoid<%>` implementation. The following code

```racket
(send editor get-text 0 'eof)
```

raises a contract error complaining about the `'eof` value. Easy to work around by using the `last-position` method, though. Let me know if you want me to open a separate issue for this.

**Comment by greghendershott** [comment]
Thanks!

- I'm sorry it was harder to use the more limited interface. What you describe sounds like something every indenter would do, so there _ought_ to be some documented trick even if the interface is baked and can't add a method (?). (I haven't tried to write an indenter using it so I don't have any good advice. I guess I'd look at the implementations for some other langs.)

- Thanks for pointing out that omission with `get-text`; I just pushed a commit to add that.

**Comment by Bogdanp** [comment]
> I'm sorry it was harder to use the more limited interface. What you describe sounds like something every indenter would do, so there ought to be some documented trick even if the interface is baked and can't add a method (?). (I haven't tried to write an indenter using it so I don't have any good advice. I guess I'd look at the implementations for some other langs.)

Ah, no worries! It turns out I was missing something after all: the "paragraph" methods actually referred to newline-delimited _lines_ in the buffer (as opposed to lines that may be soft-wrapped, for example). So, getting the previous and current line is actually straightforward given that context!

**Comment by greghendershott** [comment]
Oh good. Yeah the "paragraph" terminology still trips me.

To be fair, if I worked with text% long-term, I'm sure I'd get used to it. Like, I seem OK now with Emacs "frames" that are windows and "windows" that are panes. :)
