### ISSUE TITLE
`racket-hash-lang-mode` turns off `electric-pair-mode` globally

### ISSUE THREAD

**Issue by usaoc** [greghendershott/racket-mode#680]
It seems that `racket-hash-lang-mode` toggles `electric-pair-mode` as opposed to `electric-pair-local-mode`, therefore turning off the minor mode globally.  Is there any problem with using the latter?

**Comment by greghendershott** [comment]
Ouch. I intended `electric-pair-local-mode` there. Good catch.

Will merge commit as soon as it runs through CI...
