### ISSUE TITLE
racket-repl-mode ansi escape code coloring 

### ISSUE THREAD

**Issue by tgbugs** [greghendershott/racket-mode#688]
Before the changes to repl-mode in 25224889d20b37bfd0d315a656542bb4fe8c2076 ansi escape codes were processed correctly. After the changes they are no longer processed correctly. Is there some way to get this working again?

Steps to reproduce:
In the repl run
```racket
(system "echo $(tput setaf 4)should be blue$(tput sgr0)")
```
The output should be blue as it was in the comint version of the repl and as it would be if running racket from the command line.

The actual result in some cases contains raw escape charachters, possibly when logging to stderr instead of stdout?
```
[32m[2023-12-08 12:58:41,141][0m - [33m WARNING[0m -        sparcur - [34mfetch_metadata_files.py:45  [0m - No paths to fetch, did you pull the file system metadata?[0m
```

<details>
<h2>Package</h2>
<dl>
<dt>metadata</dt><dd><pre>nil</pre></dd>
<dt>package-archives</dt><dd><pre>(("gnu" . "https://elpa.gnu.org/packages/")
 ("nongnu" . "https://elpa.nongnu.org/nongnu/")
 ("melpa" . "https://melpa.org/packages/"))
</pre></dd>
<dt>racket--el-source-dir</dt><dd><pre>"/home/tom/.emacs.d/lisp/racket-mode/"</pre></dd>
<dt>racket--rkt-source-dir</dt><dd><pre>"/home/tom/.emacs.d/lisp/racket-mode/racket/"</pre></dd>
</dl>
<h2>System values</h2>
<dl>
<dt>emacs-version</dt><dd><pre>"29.1"</pre></dd>
<dt>major-mode</dt><dd><pre>help-mode</pre></dd>
<dt>system-type</dt><dd><pre>gnu/linux</pre></dd>
<dt>x-gtk-use-system-tooltips</dt><dd><pre>t</pre></dd>
<dt>display-graphic-p</dt><dd><pre>t</pre></dd>
</dl>
<h2>Buffer values</h2>
<dl>
<dt>after-change-functions</dt><dd><pre>nil</pre></dd>
<dt>before-change-functions</dt><dd><pre>nil</pre></dd>
<dt>completion-at-point-functions</dt><dd><pre>(tags-completion-at-point-function)
</pre></dd>
<dt>eldoc-documentation-function</dt><dd><pre>eldoc-documentation-default</pre></dd>
<dt>font-lock-defaults</dt><dd><pre>nil</pre></dd>
<dt>pre-command-hook</dt><dd><pre>(evil--jump-hook t)
</pre></dd>
<dt>post-command-hook</dt><dd><pre>(evil--jump-handle-buffer-crossing t)
</pre></dd>
<dt>post-self-insert-hook</dt><dd><pre>(electric-pair-post-self-insert-function electric-pair-open-newline-between-pairs-psif electric-indent-post-self-insert-function blink-paren-post-self-insert-function)
</pre></dd>
<dt>xref-backend-functions</dt><dd><pre>(etags--xref-backend)
</pre></dd>
</dl>
<h2>Racket Mode values</h2>
<dl>
<dt>racket--cmd-open-p</dt><dd><pre>t</pre></dd>
<dt>racket-after-run-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-back-end-configurations</dt><dd><pre>((:directory "/" :racket-program nil :remote-source-dir nil :restart-watch-directories nil :windows nil))
</pre></dd>
<dt>racket-before-run-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-browse-url-function</dt><dd><pre>racket-browse-url-using-temporary-file</pre></dd>
<dt>racket-command-timeout</dt><dd><pre>10</pre></dd>
<dt>racket-documentation-search-location</dt><dd><pre>"https://docs.racket-lang.org/search/index.html?q=%s"</pre></dd>
<dt>racket-error-context</dt><dd><pre>medium</pre></dd>
<dt>racket-hash-lang-mode-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-hash-lang-module-language-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-hash-lang-token-face-alist</dt><dd><pre>((constant . font-lock-constant-face)
 (error . error)
 (other . font-lock-doc-face)
 (keyword . font-lock-keyword-face)
 (hash-colon-keyword . racket-keyword-argument-face)
 (at . font-lock-doc-face))
</pre></dd>
<dt>racket-history-filter-regexp</dt><dd><pre>"\\`\\s *\\'"</pre></dd>
<dt>racket-imagemagick-props</dt><dd><pre>nil</pre></dd>
<dt>racket-images-inline</dt><dd><pre>t</pre></dd>
<dt>racket-images-keep-last</dt><dd><pre>100</pre></dd>
<dt>racket-images-system-viewer</dt><dd><pre>"display"</pre></dd>
<dt>racket-indent-curly-as-sequence</dt><dd><pre>t</pre></dd>
<dt>racket-indent-sequence-depth</dt><dd><pre>0</pre></dd>
<dt>racket-logger-config</dt><dd><pre>((cm-accomplice . warning)
 (GC . info)
 (module-prefetch . warning)
 (optimizer . info)
 (racket/contract . error)
 (racket-mode-debugger . info)
 (sequence-specialization . info)
 (* . fatal))
</pre></dd>
<dt>racket-memory-limit</dt><dd><pre>2048</pre></dd>
<dt>racket-mode-hook</dt><dd><pre>(rainbow-delimiters-mode tgbugs-racket-hs racket-xp-mode rcc goto-address-mode tgbugs-buffer-local-tab-complete tgbugs-racket-outline-helper electric-indent-local-mode)
</pre></dd>
<dt>racket-module-forms</dt><dd><pre>"\\s(\\(?:module[*+]?\\|library\\)"</pre></dd>
<dt>racket-pretty-lambda</dt><dd><pre>nil</pre></dd>
<dt>racket-pretty-print</dt><dd><pre>t</pre></dd>
<dt>racket-program</dt><dd><pre>"racket"</pre></dd>
<dt>racket-repl-buffer-name-function</dt><dd><pre>nil</pre></dd>
<dt>racket-repl-history-directory</dt><dd><pre>"~/.emacs.d/racket-mode/"</pre></dd>
<dt>racket-repl-mode-hook</dt><dd><pre>(rainbow-delimiters-mode tgbugs-buffer-local-tab-complete)
</pre></dd>
<dt>racket-sexp-comment-fade</dt><dd><pre>0.5</pre></dd>
<dt>racket-shell-or-terminal-function</dt><dd><pre>racket-shell</pre></dd>
<dt>racket-show-functions</dt><dd><pre>(racket-show-echo-area)
</pre></dd>
<dt>racket-smart-open-bracket-enable</dt><dd><pre>nil</pre></dd>
<dt>racket-submodules-to-run</dt><dd><pre>((test)
 (main))
</pre></dd>
<dt>racket-use-repl-submit-predicate</dt><dd><pre>nil</pre></dd>
<dt>racket-xp-add-binding-faces</dt><dd><pre>nil</pre></dd>
<dt>racket-xp-after-change-refresh-delay</dt><dd><pre>1</pre></dd>
<dt>racket-xp-highlight-unused-regexp</dt><dd><pre>"^[^_]"</pre></dd>
<dt>racket-xp-mode-lighter</dt><dd><pre>(:eval
 (racket--xp-mode-lighter))
</pre></dd>
</dl>
<h2>Minor modes</h2>
<dl>
<dt>enabled</dt><dd><pre>((async-bytecomp-package-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (buffer-read-only)
 (column-number-mode)
 (csv-field-index-mode)
 (display-line-numbers-mode)
 (electric-pair-mode)
 (evil-collection-unimpaired-mode)
 (evil-local-mode)
 (evil-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-display-line-numbers-mode)
 (global-eldoc-mode)
 (global-evil-collection-unimpaired-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-undo-tree-mode)
 (isearch-fold-quotes-mode)
 (line-number-mode)
 (magit-auto-revert-mode)
 (mouse-wheel-mode)
 (override-global-mode)
 (savehist-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (tooltip-mode)
 (transient-mark-mode)
 (treemacs-filewatch-mode)
 (treemacs-follow-mode)
 (treemacs-fringe-indicator-mode)
 (treemacs-git-mode)
 (undo-tree-mode)
 (url-handler-mode)
 (which-function-mode))
</pre></dd>
<details><summary>Disabled minor modes</summary>
<dt>disabled</dt><dd><pre>((abbrev-mode)
 (archive-subfile-mode)
 (auto-complete-mode)
 (auto-fill-function)
 (auto-fill-mode)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-mode)
 (auto-save-visited-mode)
 (avy-linum-mode)
 (bibtex-completion-notes-global-mode)
 (bibtex-completion-notes-mode)
 (blink-cursor-mode)
 (buffer-face-mode)
 (bug-reference-mode)
 (bug-reference-prog-mode)
 (button-mode)
 (cider--debug-mode)
 (cider-auto-test-mode)
 (cider-enlighten-mode)
 (cider-mode)
 (cider-popup-buffer-mode)
 (cl-old-struct-compat-mode)
 (comint-fontify-input-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (context-menu-mode)
 (crdt-mode)
 (crdt-org-sync-overlay-mode)
 (crdt-visualize-author-mode)
 (csv-align-mode)
 (cursor-face-highlight-mode)
 (cursor-intangible-mode)
 (cursor-sensor-mode)
 (dap-auto-configure-mode)
 (dap-mode)
 (dash-fontify-mode)
 (defining-kbd-macro)
 (delete-selection-mode)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (dired-isearch-filenames-mode)
 (edebug-backtrace-mode)
 (edebug-mode)
 (edit-indirect--overlay)
 (eldoc-mode)
 (electric-indent-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (elpy-django)
 (elpy-mode)
 (eshell-arg-mode)
 (eshell-command-mode)
 (eshell-proc-mode)
 (eshell-var-mode)
 (ess-elisp-trace-mode)
 (eval-sexp-fu-flash-mode)
 (evil-cleverparens-mode)
 (evil-collection-magit-toggle-text-minor-mode)
 (evil-leader-mode)
 (evil-org-mode)
 (evil-paredit-mode)
 (evil-surround-mode)
 (flycheck-mode)
 (flymake-mode)
 (flyspell-mode)
 (gcmh-mode)
 (geiser-autodoc-mode)
 (geiser-mode)
 (geiser-repl-autoeval-mode)
 (geiser-smart-tab-mode)
 (git-commit-mode)
 (global-auto-complete-mode)
 (global-auto-revert-mode)
 (global-dash-fontify-mode)
 (global-evil-leader-mode)
 (global-evil-surround-mode)
 (global-flycheck-mode)
 (global-goto-address-mode)
 (global-hl-line-mode)
 (global-hl-todo-mode)
 (global-linum-mode)
 (global-prettify-symbols-mode)
 (global-reveal-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-tree-sitter-mode)
 (global-visual-line-mode)
 (gnus-dead-summary-mode)
 (gnus-undo-mode)
 (goto-address-mode)
 (goto-address-prog-mode)
 (haskell-indentation-mode)
 (header-line-indent-mode)
 (helm--minor-mode)
 (helm--remap-mouse-mode)
 (helm-autoresize-mode)
 (helm-display-line-numbers-mode)
 (helm-migemo-mode)
 (helm-popup-tip-mode)
 (highlight-numbers-mode)
 (hl-line-mode)
 (hl-todo-mode)
 (horizontal-scroll-bar-mode)
 (hs-minor-mode)
 (ido-everywhere)
 (indent-tabs-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (julia-repl-mode)
 (jupyter-org-interaction-mode)
 (jupyter-repl-interaction-mode)
 (jupyter-repl-persistent-mode)
 (linum-mode)
 (lispy-goto-mode)
 (lispy-mode)
 (lispy-other-mode)
 (lock-file-mode)
 (lost-selection-mode)
 (lsp-inlay-hints-mode)
 (lsp-installation-buffer-mode)
 (lsp-java-lens-mode)
 (lsp-managed-mode)
 (lsp-mode)
 (lsp-signature-mode)
 (lsp-treemacs-deps-list-mode)
 (lsp-treemacs-error-list-mode)
 (lsp-treemacs-generic-mode)
 (lsp-treemacs-sync-mode)
 (macrostep-mode)
 (magit-blame-mode)
 (magit-blame-read-only-mode)
 (magit-blob-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (magit-wip-initial-backup-mode)
 (magit-wip-mode)
 (mail-abbrevs-mode)
 (markdown-live-preview-mode)
 (menu-bar-mode)
 (mml-mode)
 (next-error-follow-minor-mode)
 (org-capture-mode)
 (org-cdlatex-mode)
 (org-list-checkbox-radio-mode)
 (org-make-toc-mode)
 (org-src-mode)
 (org-table-follow-field-mode)
 (org-table-header-line-mode)
 (orgstrap-edit-mode)
 (orgtbl-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (paredit-mode)
 (polymode-minor-mode)
 (prettify-symbols-mode)
 (pycoverage-mode)
 (pyvenv-mode)
 (pyvenv-tracking-mode)
 (racket-hash-lang-repl-mode)
 (racket-smart-open-bracket-mode)
 (racket-xp-mode)
 (rainbow-delimiters-mode)
 (rainbow-delimiters-org-mode)
 (read-extended-command-mode)
 (rectangle-mark-mode)
 (reveal-mode)
 (rst-minor-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (server-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (shell-highlight-undef-mode)
 (show-paren-mode)
 (show-smartparens-global-mode)
 (show-smartparens-mode)
 (size-indication-mode)
 (slime-autodoc-mode)
 (slime-edit-value-mode)
 (slime-editing-mode)
 (slime-fuzzy-target-buffer-completions-mode)
 (slime-macroexpansion-minor-mode)
 (slime-mode)
 (slime-popup-buffer-mode)
 (slime-repl-map-mode)
 (slime-repl-read-mode)
 (slime-trace-dialog-autofollow-mode)
 (slime-trace-dialog-hide-details-mode)
 (slime-trace-dialog-minor-mode)
 (smartparens-global-mode)
 (smartparens-global-strict-mode)
 (smartparens-mode)
 (smartparens-strict-mode)
 (smerge-mode)
 (symex-editing-mode)
 (symex-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (table-fixed-width-mode)
 (table-mode-indicator)
 (tablist-edit-column-minor-mode)
 (tablist-minor-mode)
 (tar-subfile-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (transient-resume-mode)
 (tree-sitter-hl-mode)
 (tree-sitter-mode)
 (treemacs-hide-gitignored-files-mode)
 (treemacs-indent-guide-mode)
 (treemacs-indicate-top-scroll-mode)
 (treesit-explore-mode)
 (treesit-inspect-mode)
 (undelete-frame-mode)
 (undo-tree-visualizer-selection-mode)
 (use-hard-newlines)
 (vc-dir-git-mode)
 (vc-parent-buffer)
 (vdiff-3way-mode)
 (vdiff-mode)
 (vdiff-scroll-lock-mode)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (vterm-copy-mode)
 (window-divider-mode)
 (with-editor-mode)
 (xref-etags-mode)
 (yas-global-mode)
 (yas-minor-mode))
</pre></dd>
</details>
</dl>
</details>

**Comment by greghendershott** [comment]
Thanks for the report. I wrongly assumed that was one of the many `comint` things that were for use by things like `M-x shell`. I didn't realize people would do that from Racket output.

`comint` did this by calling `ansi-color-process-output` on all output before inserting into the buffer.

I could pretty simply revive that same indiscriminate behavior, where an escape affects _everything_ in the buffer.

But:

A main motivation for the new REPL is to use structured output. (Typically, many kinds of output get dumped into the same text stream; then you (try to) recover them via regexps. Whereas with the new REPL, the back end preserves the output structure for the front end REPL.)

And so what I'd want to do is revive this more smartly -- to have the escapes affect only portions of the REPL that are stdout or stderr.  For example a "blue" escape should affect the color subsequent stdout/sterr output regions in the buffer -- but not other regions, like error messages, prompts, values, file locations, etc.

Doing this would be more work, but not terribly difficult, from a quick glance at `ansi-color-apply-on-region`. (I _think_ I can use its `ansi-color-context-region` state variable to preserve the codes state, but change the position marker to be the next stdout/stderr region. Or something like that.)

I'll take a look.

**Comment by greghendershott** [comment]
From a quick experiment, that seems to work well.

Something like:

```
> (display "\033[30;47mblah blah blah")
blah blah blah
> (display "foo")
foo
```

Causes the "blah blah blah" and "foo" regions to be colored -- but _not_ the following prompt and new input. Just as I want and would expect, in the new REPL.

Whereas with `M-x shell` and running `racket` there, _everything_ is colored, even the prompt and input. Which I don't want.

Also I reset any escape code start upon the next `racket-run`, which IIUC is correct.

So, after sleeping on it and reviewing, I might have a commit to merge tomorrow.

---

But one thing that confuses me:

Your example using `system` and `tput` works for me running Racket in Gnome terminal, outside Emacs.

But it does not give me any blue color in Emacs. Not in `M-x shell`. Not in my just-updated Racket REPL. 

I don't see blue and I don't see any raw codes. 

It seems like maybe `tput` isn't emitting the escape codes for me running something via Emacs?

I am pretty ignorant about escape codes and terminals. Is this because when the emacs process is running racket, `tput` doesn't see it as a certain kind of terminal??  (For me. But presumably you have it configured differently?)

**Comment by greghendershott** [comment]
Oh maybe it's because `TERM` env var for me is `xterm-256color` in Gnome terminal but `dumb` in Emacs?

Presumably if someone like you has set `TERM` as you want for Emacs, then when I launch the `racket` process from Emacs it will inherit that, and doing `(system " ... tput ... ")` will do what you want?

**Comment by greghendershott** [comment]
In an `M-x shell` buffer, `tput` `setaf` works when I use `-T xterm-256color` ("don't look at TERM, just produce SGR escapes"):

```
$ echo $(tput -T xterm-256color setaf 4)should be blue$(tput -T xterm-256color setaf 0)
should be blue
$ racket
Welcome to Racket v8.10.0.3 [cs].
> (require racket/system)
> (system "echo $(tput -T xterm-256color setaf 4)should be blue$(tput -T xterm-256color setaf 0)")
should be blue
#t
```

**Comment by greghendershott** [comment]
I just pushed a commit (not yet merged to the main branch) that handles SGR escapes to colorize.  By default; it can also be configured to show them raw or filter them with no colorizing.

---

p.s. Although I don't understand exactly how/when `tput` emits SGR escapes or not, in Emacs generally, I _think_ that's a general Emacs configuration question.

If you have any tips in this regard I'd be happy to add them to the docs for `racket-repl-mode` (but AFAICT it's not something `racket-repl-mode` can or should solve?).

**Comment by greghendershott** [comment]
I went ahead and merged this. I think the TL;DR is, if you have things configured in such a way that `tput` emits SGR escapes when run from Emacs, and you see colors in e.g. `shell-mode` (which uses `comint-mode`)... then you should now see colors in `racket-repl-mode`.

If not, or if you have any other questions or comments of course please let me know.
