### ISSUE TITLE
Racket mode is just not working. Can someone please help me?

### ISSUE THREAD

**Issue by okirpane** [greghendershott/racket-mode#698]
I have installed and reinstalled `racket-mode` as outlined in the [manual](https://www.racket-mode.com/#Install).

When I start up emacs after installing `racket-mode`, I keep getting the following error:

`{racket-back-end-/} exited abnormally with code 1`

I'm lost on what I can do to fix this. Can someone help me?

**Comment by soegaard** [comment]
Try visting the Racket Discord: https://discord.com/invite/6Zq8sH5

**Comment by greghendershott** [comment]
@okirpane The error message might be longer than `{racket-back-end-/} exited abnormally with code 1`, but Emacs might not show it in the echo area at the bottom.

If you switch to the Emacs `*Messages*` buffer, is there more text, and if so can you share it with me?

**Comment by greghendershott** [comment]
p.s.

1. You wrote that it errors when you start up emacs. Did you mean that literally -- before even trying to open a .rkt file or do `M-x racket-mode`, just starting emacs, you get that error about the back end?  If so, could you please share some of your emacs init file where you configure this, if any?

2. What happens if you try to `M-x find-file` and open some `.rkt` file?

3. Can you please do `M-x racket-bug-report` and paste the results here?  (It's best if you can do this from a buffer in which `racket-mode` is the major mode. But if for some reason you can't, it would still be helpful from _any_ buffer. It would give me some idea of your system and versions of things.)

**Comment by greghendershott** [comment]
Closing because no reply; nothing for me to do.

If someday you do return, I'd be glad to reopen, and spend more time to figure it out with you.

**Comment by okirpane** [comment]
Hey @greghendershott, 
Sorry for the late response. In case it's still helpful or you have the bandwidth to help, here's what I see when I run `M-x racket-bug-report`.

### Bug Report

<details>
<h2>Package</h2>
<dl>
<dt>metadata</dt><dd><pre>(#s(package-desc racket-mode (1 0 20251106 215641)
		 "Racket editing, REPL, and more"
		 ((emacs (25 1)) (compat (30 0 2 0))) nil nil
		 "/home/ojas/.emacs.d/elpa/racket-mode-1.0.20251106.215641"
		 ((:url . "https://www.racket-mode.com/")
		  (:authors
		   ("Greg Hendershott"
		    . "racket-mode-author@greghendershott.com"))
		  (:commit . "HEAD"))
		 t))
</pre></dd>
<dt>package-archives</dt><dd><pre>(("gnu" . "https://elpa.gnu.org/packages/")
 ("nongnu" . "https://elpa.nongnu.org/nongnu/"))
</pre></dd>
<dt>racket--el-source-dir</dt><dd><pre>"/home/ojas/.emacs.d/elpa/racket-mode-1.0.20251106.215641/"
</pre></dd>
<dt>racket--rkt-source-dir</dt><dd><pre>"/home/ojas/.emacs.d/elpa/racket-mode-1.0.20251106.215641/racket/"
</pre></dd>
</dl>
<h2>System values</h2>
<dl>
<dt>emacs-version</dt><dd><pre>"30.2"
</pre></dd>
<dt>major-mode</dt><dd><pre>racket-mode
</pre></dd>
<dt>system-type</dt><dd><pre>gnu/linux
</pre></dd>
<dt>x-gtk-use-system-tooltips</dt><dd><pre>t
</pre></dd>
<dt>display-graphic-p</dt><dd><pre>t
</pre></dd>
</dl>
<h2>Buffer values</h2>
<dl>
<dt>after-change-functions</dt><dd><pre>(jit-lock-after-change t)
</pre></dd>
<dt>before-change-functions</dt><dd><pre>(t syntax-ppss-flush-cache)
</pre></dd>
<dt>completion-at-point-functions</dt><dd><pre>(racket-complete-at-point)
</pre></dd>
<dt>eldoc-documentation-function</dt><dd><pre>eldoc-documentation-default
</pre></dd>
<dt>eldoc-documentation-strategy</dt><dd><pre>eldoc-documentation-default
</pre></dd>
<dt>eldoc-documentation-functions</dt><dd><pre>nil
</pre></dd>
<dt>font-lock-defaults</dt><dd><pre>((racket-font-lock-keywords-level-0 racket-font-lock-keywords-level-1
				    racket-font-lock-keywords-level-2
				    racket-font-lock-keywords-level-3)
 nil nil nil nil (font-lock-mark-block-function . mark-defun)
 (parse-sexp-lookup-properties . t) (font-lock-multiline . t)
 (font-lock-syntactic-face-function
  . racket-font-lock-syntactic-face-function)
 (font-lock-extend-region-functions font-lock-extend-region-wholelines
				    font-lock-extend-region-multiline))
</pre></dd>
<dt>pre-command-hook</dt><dd><pre>(tooltip-hide)
</pre></dd>
<dt>post-command-hook</dt><dd><pre>(jit-lock--antiblink-post-command t)
</pre></dd>
<dt>post-self-insert-hook</dt><dd><pre>(electric-indent-post-self-insert-function
 blink-paren-post-self-insert-function)
</pre></dd>
<dt>xref-backend-functions</dt><dd><pre>(racket-mode-xref-backend-function t)
</pre></dd>
</dl>
<h2>Racket Mode values</h2>
<dl>
<dt>racket--cmd-open-p</dt><dd><pre>nil
</pre></dd>
<dt>racket-after-run-hook</dt><dd><pre>nil
</pre></dd>
<dt>racket-back-end-configurations</dt><dd><pre>((:directory "/" :racket-program nil :remote-source-dir nil
	     :restart-watch-directories nil :windows nil))
</pre></dd>
<dt>racket-before-run-hook</dt><dd><pre>(racket-ansi-color-context-reset)
</pre></dd>
<dt>racket-browse-url-function</dt><dd><pre>browse-url-default-browser
</pre></dd>
<dt>racket-command-timeout</dt><dd><pre>10
</pre></dd>
<dt>racket-debug-break-expression-string</dt><dd><pre>"●"
</pre></dd>
<dt>racket-debuggable-files</dt><dd><pre>racket-same-directory-files
</pre></dd>
<dt>racket-doc-index-directory</dt><dd><pre>"~/.emacs.d/racket-mode/"
</pre></dd>
<dt>racket-doc-index-predicate-function</dt><dd><pre>always
</pre></dd>
<dt>racket-documentation-search-location</dt><dd><pre>"https://docs.racket-lang.org/search/index.html?q=%s"
</pre></dd>
<dt>racket-error-context</dt><dd><pre>medium
</pre></dd>
<dt>racket-expand-hiding</dt><dd><pre>standard
</pre></dd>
<dt>racket-hash-lang-mode-hook</dt><dd><pre>nil
</pre></dd>
<dt>racket-hash-lang-module-language-hook</dt><dd><pre>nil
</pre></dd>
<dt>racket-hash-lang-token-face-alist</dt><dd><pre>((builtin . font-lock-builtin-face)
 (constant . font-lock-constant-face) (error . error)
 (operator . font-lock-operator-face) (other . font-lock-doc-face)
 (keyword . font-lock-keyword-face)
 (hash-colon-keyword . racket-keyword-argument-face)
 (at . font-lock-doc-face))
</pre></dd>
<dt>racket-history-filter-regexp</dt><dd><pre>"\\`\\s *\\'"
</pre></dd>
<dt>racket-imagemagick-props</dt><dd><pre>nil
</pre></dd>
<dt>racket-images-do-not-use-svg</dt><dd><pre>nil
</pre></dd>
<dt>racket-images-inline</dt><dd><pre>t
</pre></dd>
<dt>racket-images-keep-last</dt><dd><pre>100
</pre></dd>
<dt>racket-images-system-viewer</dt><dd><pre>"display"
</pre></dd>
<dt>racket-indent-curly-as-sequence</dt><dd><pre>t
</pre></dd>
<dt>racket-indent-sequence-depth</dt><dd><pre>0
</pre></dd>
<dt>racket-input-prefix</dt><dd><pre>"\\"
</pre></dd>
<dt>racket-input-translations</dt><dd><pre>(("All" "∀") ("Union" "U") ("Intersection" "∩")
 ("test-->>E" "test-->>∃") ("vdash" "⊢") ("gg" "≫") ("succ" "≻")
 ("times" "×") ("Uparrow" "⇑") ("Downarrow" "⇓") ("Leftarrow" "⇐")
 ("Rightarrow" "⇒") ("leftarrow" "←") ("rightarrow" "→")
 ("nwarrow" "↖") ("nearrow" "↗") ("uparrow" "↑") ("downarrow" "↓")
 ("searrow" "↘") ("swarrow" "↙") ("leftrightarrow" "↔")
 ("updownarrow" "⇕") ("aleph" "א") ("emptyset" "∅") ("nabla" "∇")
 ("surd" "√") ("negation" "¬") ("infinity" "∞") ("prod" "∏")
 ("coprod" "∐") ("integrate" "∫") ("oint" "∮") ("vee" "∨")
 ("wedge" "∧") ("follows" "∘") ("setin" "∈") ("ni" "∋") ("notin" "∉")
 ("sqsubset" "⊏") ("sqsupset" "⊐") ("sqsubseteq" "⊑")
 ("sqsupseteq" "⊒") ("subset" "⊂") ("superset" "⊃") ("subseteq" "⊆")
 ("supseteq" "⊇") ("approx" "≈") ("cong" "≌") ("neq" "≠")
 ("sqcap" "⊓") ("sqcup" "⊔") ("models" "⊧") ("alpha" "α")
 ("Alpha" "Α") ("beta" "β") ("Beta" "Β") ("gamma" "γ") ("Gamma" "Γ")
 ("delta" "δ") ("Delta" "Δ") ("epsilon" "ε") ("Epsilon" "Ε")
 ("zeta" "ζ") ("Zeta" "Ζ") ("eta" "η") ("Eta" "Η") ("theta" "θ")
 ("Theta" "Θ") ("iota" "ι") ("Iota" "Ι") ("kappa" "κ") ("Kappa" "Κ")
 ("lambda" "λ") ("Lambda" "Λ") ("lamda" "λ") ("Lamda" "Λ") ("mu" "μ")
 ("Mu" "Μ") ("nu" "ν") ("Nu" "Ν") ("xi" "ξ") ("Xi" "Ξ")
 ("omicron" "ο") ("Omicron" "Ο") ("pi" "π") ("Pi" "Π") ("rho" "ρ")
 ("Rho" "Ρ") ("sigma" "σ") ("Sigma" "Σ") ("tau" "τ") ("Tau" "Τ")
 ("upsilon" "υ") ("Upsilon" "Υ") ("phi" "φ") ("Phi" "Φ") ("chi" "χ")
 ("Chi" "Χ") ("psi" "ψ") ("Psi" "Ψ") ("omega" "ω") ("Omega" "Ω")
 ("digamma" "ϝ") ("Digamma" "Ϝ") ("san" "ϻ") ("San" "Ϻ") ("qoppa" "ϙ")
 ("Qoppa" "Ϙ") ("sampi" "ϡ") ("Sampi" "Ϡ") ("stigma" "ϛ")
 ("Stigma" "Ϛ") ("heta" "ͱ") ("Heta" "Ͱ") ("sho" "ϸ") ("Sho" "Ϸ")
 ("|A|" "𝔸") ("|B|" "𝔹") ("|C|" "ℂ") ("|D|" "𝔻") ("|E|" "𝔼")
 ("|F|" "𝔽") ("|G|" "𝔾") ("|H|" "ℍ") ("|I|" "𝕀") ("|J|" "𝕁")
 ("|K|" "𝕂") ("|L|" "𝕃") ("|M|" "𝕄") ("|N|" "ℕ") ("|O|" "𝕆")
 ("|P|" "ℙ") ("|Q|" "ℚ") ("|R|" "ℝ") ("|S|" "𝕊") ("|T|" "𝕋")
 ("|U|" "𝕌") ("|V|" "𝕍") ("|W|" "𝕎") ("|X|" "𝕏") ("|Y|" "𝕐")
 ("|Z|" "ℤ") ("|gamma|" "ℽ") ("|Gamma|" "ℾ") ("|pi|" "ℼ") ("|Pi|" "ℿ")
 ("forall" "∀") ("exists" "∃") ("_0" "₀") ("_1" "₁") ("_2" "₂")
 ("_3" "₃") ("_4" "₄") ("_5" "₅") ("_6" "₆") ("_7" "₇") ("_8" "₈")
 ("_9" "₉") ("^0" "⁰") ("^1" "¹") ("^2" "²") ("^3" "³") ("^4" "⁴")
 ("^5" "⁵") ("^6" "⁶") ("^7" "⁷") ("^8" "⁸") ("^9" "⁹"))
</pre></dd>
<dt>racket-logger-config</dt><dd><pre>((cm-accomplice . warning) (GC . info) (module-prefetch . warning)
 (optimizer . info) (racket/contract . error)
 (racket-mode-debugger . info) (sequence-specialization . info)
 (* . fatal))
</pre></dd>
<dt>racket-memory-limit</dt><dd><pre>2048
</pre></dd>
<dt>racket-mode-hook</dt><dd><pre>nil
</pre></dd>
<dt>racket-module-forms</dt><dd><pre>"\\s(\\(?:module[*+]?\\|library\\)"
</pre></dd>
<dt>racket-pretty-lambda</dt><dd><pre>nil
</pre></dd>
<dt>racket-pretty-print</dt><dd><pre>t
</pre></dd>
<dt>racket-program</dt><dd><pre>"racket"
</pre></dd>
<dt>racket-repl-buffer-name-function</dt><dd><pre>nil
</pre></dd>
<dt>racket-repl-command-file</dt><dd><pre>"/home/ojas/.emacs.d/racket-mode/repl.rkt"
</pre></dd>
<dt>racket-repl-echo-sent-expressions</dt><dd><pre>t
</pre></dd>
<dt>racket-repl-history-directory</dt><dd><pre>"~/.emacs.d/racket-mode/"
</pre></dd>
<dt>racket-repl-mode-hook</dt><dd><pre>nil
</pre></dd>
<dt>racket-sexp-comment-fade</dt><dd><pre>0.5
</pre></dd>
<dt>racket-shell-or-terminal-function</dt><dd><pre>racket-shell
</pre></dd>
<dt>racket-show-functions</dt><dd><pre>(racket-show-pseudo-tooltip)
</pre></dd>
<dt>racket-smart-open-bracket-enable</dt><dd><pre>nil
</pre></dd>
<dt>racket-submodules-to-run</dt><dd><pre>((test) (main))
</pre></dd>
<dt>racket-use-repl-submit-predicate</dt><dd><pre>nil
</pre></dd>
<dt>racket-xp-add-binding-faces</dt><dd><pre>nil
</pre></dd>
<dt>racket-xp-after-change-refresh-delay</dt><dd><pre>1
</pre></dd>
<dt>racket-xp-eldoc-level</dt><dd><pre>summary
</pre></dd>
<dt>racket-xp-highlight-unused-regexp</dt><dd><pre>"^[^_]"
</pre></dd>
<dt>racket-xp-mode-lighter</dt><dd><pre>(:eval (racket--xp-mode-lighter))
</pre></dd>
</dl>
<h2>Minor modes</h2>
<dl>
<dt>enabled</dt><dd><pre>((auto-composition-mode) (auto-compression-mode)
 (auto-encryption-mode) (blink-cursor-mode) (electric-indent-mode)
 (file-name-shadow-mode) (font-lock-mode) (global-eldoc-mode)
 (global-font-lock-mode) (line-number-mode) (menu-bar-mode)
 (minibuffer-regexp-mode) (mouse-wheel-mode)
 (semantic-minor-modes-format) (show-paren-mode) (tool-bar-mode)
 (tooltip-mode) (transient-mark-mode))
</pre></dd>
<details><summary>Disabled minor modes</summary>
<dt>disabled</dt><dd><pre>((abbrev-mode) (auto-fill-function) (auto-fill-mode) (auto-save-mode)
 (auto-save-visited-mode) (buffer-face-mode) (buffer-read-only)
 (button-mode) (cl-old-struct-compat-mode) (column-number-mode)
 (comint-fontify-input-mode) (compilation-minor-mode)
 (compilation-shell-minor-mode) (completion-in-region-mode)
 (context-menu-mode) (cursor-face-highlight-mode) (defining-kbd-macro)
 (eldoc-mode) (electric-layout-mode) (electric-pair-mode)
 (electric-quote-mode) (global-prettify-symbols-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode) (global-visual-line-mode)
 (horizontal-scroll-bar-mode) (hs-minor-mode) (indent-tabs-mode)
 (isearch-fold-quotes-mode) (isearch-mode) (jit-lock-debug-mode)
 (lock-file-mode) (lost-selection-mode) (modifier-bar-mode)
 (next-error-follow-minor-mode) (overwrite-mode)
 (paragraph-indent-minor-mode) (prettify-symbols-mode)
 (racket-debug-mode) (racket-hash-lang-repl-mode) (racket-input-mode)
 (racket-smart-open-bracket-mode) (racket-xp-mode)
 (read-extended-command-mode) (read-passwd-mode)
 (semantic-highlight-edits-mode) (semantic-highlight-func-mode)
 (semantic-mode) (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode) (semantic-stickyfunc-mode)
 (sh-electric-here-document-mode) (shell-dirtrack-mode)
 (shell-highlight-undef-mode) (size-indication-mode)
 (tab-bar-history-mode) (tab-bar-mode) (temp-buffer-resize-mode)
 (text-scale-mode) (treesit-explore-mode) (treesit-inspect-mode)
 (undelete-frame-mode) (url-handler-mode) (use-hard-newlines)
 (view-mode) (visible-mode) (visual-line-mode) (window-divider-mode)
 (xref-etags-mode))
</pre></dd>
</details>
</dl>
</details>

### Steps to reproduce: 
Run `raco pkg install --auto drracket`
Run `M-x package-install RET racket-mode RET`
Run `racket-mode` on a `.rkt` file
After typing in some racket-mode compile using `C-c C-c` to see `{racket-back-end-/} exited abnormally with code 1`
If you run `M-x racket-bug-report` on the file, you will see the bug report above.

**Comment by g-gundam** [comment]
## My experience
- I just experienced this error while running racket-mode-20260303.1556.
- I happened to have the snap version of racket installed.
- The following was what was in my `*Warnings*` buffer when I tried to open any racket source file.

```
⛔ Warning (racket-mode): {racket-back-end-/-stderr} open-input-file: cannot open module file
  module path: #<path:/home/gg/.config/prot/elpa/racket-mode-20260303.1556/racket/main.rkt>
  path: /home/gg/.config/prot/elpa/racket-mode-20260303.1556/racket/main.rkt
  system error: Permission denied; errno=13
```

I could not figure out what file it was trying to open.

## My workaround
- I uninstalled the snap version and installed racket via [Ubuntu PPA](https://launchpad.net/~plt/+archive/ubuntu/racket) instead.
- Then, racket-mode worked fine.
- I didn't have to do anything further on the Emacs side.

**Comment by greghendershott** [comment]
Although I don't know if it's what @okirpane was experiencing, it might be? -- so thank you for sharing this experience @g-gundam .

> I could not figure out what file it was trying to open.

It's trying to open the file in the error message: `/home/gg/.config/prot/elpa/racket-mode-20260303.1556/racket/main.rkt`.

When the Racket Mode back end starts, that means doing `racket /path/to/racket-mode/main.rkt`.

When `racket` isn't "normal", but instead is sand-boxed like a Snap, then it might lack permissions for `/path/to/racket-mode/main.rkt`. Therefore the error.

See pinned issue #666 for more details.

---

Idea: I could look at making the error message more helpful, in the case where it's a permission error for loading that `main.rkt` file -- have it specifically suggest the Snap version of Racket might be to blame, and link to #666.

Of course, I can't do so _in_ that `main.rkt` file, or any other `.rkt` file I supply as part of Racket Mode. Instead, I'd need to parse the text error message on the Emacs end, which would be less reliable... but potentially still helpful.

**Comment by greghendershott** [comment]
I just pushed the change I described in my previous comment.
