### ISSUE TITLE
Identifiers with @ in racket-xp-mode

### ISSUE THREAD

**Issue by soegaard** [greghendershott/racket-mode#699]
I just noticed, that when I am in `racket-xp-mode` and uses `option-.` to jump to the definition
of the identifier `pt@d` it jumps to the definition of `pt` instead.

This might be in order to make `option-.` work in with Scribble and files that use `at-mode`|
if so, just stick to the current behaviour.

<details>
<h2>Package</h2>
<dl>
<dt>metadata</dt><dd><pre>(#s(package-desc racket-mode
                 (20240130 2013)
                 "Racket editing, REPL, and more"
                 ((emacs
                   (25 1)))
                 nil nil "/Users/soegaard/.emacs.d/elpa/racket-mode-20240130.2013"
                 ((:url . "https://www.racket-mode.com/")
                  (:maintainer "Greg Hendershott")
                  (:maintainers
                   ("Greg Hendershott"))
                  (:authors
                   ("Greg Hendershott" . "racket-mode-author@greghendershott.com"))
                  (:commit . "d3ab936af10909874443cadb2e6c952faf2f536f"))
                 nil))
</pre></dd>
<dt>package-archives</dt><dd><pre>(("gnu" . "https://elpa.gnu.org/packages/")
 ("melpa" . "https://melpa.org/packages/"))
</pre></dd>
<dt>racket--el-source-dir</dt><dd><pre>"/Users/soegaard/.emacs.d/elpa/racket-mode-20240130.2013/"</pre></dd>
<dt>racket--rkt-source-dir</dt><dd><pre>"/Users/soegaard/.emacs.d/elpa/racket-mode-20240130.2013/racket/"</pre></dd>
</dl>
<h2>System values</h2>
<dl>
<dt>emacs-version</dt><dd><pre>"27.2"</pre></dd>
<dt>major-mode</dt><dd><pre>racket-mode</pre></dd>
<dt>system-type</dt><dd><pre>darwin</pre></dd>
<dt>display-graphic-p</dt><dd><pre>t</pre></dd>
</dl>
<h2>Buffer values</h2>
<dl>
<dt>after-change-functions</dt><dd><pre>(jit-lock-after-change t racket--xp-after-change-hook)
</pre></dd>
<dt>before-change-functions</dt><dd><pre>(t syntax-ppss-flush-cache)
</pre></dd>
<dt>completion-at-point-functions</dt><dd><pre>(racket-xp-complete-at-point)
</pre></dd>
<dt>eldoc-documentation-function</dt><dd><pre>nil</pre></dd>
<dt>font-lock-defaults</dt><dd><pre>((racket-font-lock-keywords-level-0 racket-font-lock-keywords-level-1 racket-font-lock-keywords-level-2 racket-font-lock-keywords-level-3)
 nil nil nil nil
 (font-lock-mark-block-function . mark-defun)
 (parse-sexp-lookup-properties . t)
 (font-lock-multiline . t)
 (font-lock-syntactic-face-function . racket-font-lock-syntactic-face-function)
 (font-lock-extend-region-functions font-lock-extend-region-wholelines font-lock-extend-region-multiline))
</pre></dd>
<dt>pre-command-hook</dt><dd><pre>(delete-selection-pre-hook)
</pre></dd>
<dt>post-command-hook</dt><dd><pre>(jit-lock--antiblink-post-command t)
</pre></dd>
<dt>post-self-insert-hook</dt><dd><pre>(electric-indent-post-self-insert-function blink-paren-post-self-insert-function)
</pre></dd>
<dt>xref-backend-functions</dt><dd><pre>(racket-xp-xref-backend-function racket-mode-xref-backend-function t)
</pre></dd>
</dl>
<h2>Racket Mode values</h2>
<dl>
<dt>racket--cmd-open-p</dt><dd><pre>t</pre></dd>
<dt>racket-after-run-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-back-end-configurations</dt><dd><pre>((:directory "/" :racket-program nil :remote-source-dir nil :restart-watch-directories nil :windows nil))
</pre></dd>
<dt>racket-before-run-hook</dt><dd><pre>(racket-ansi-color-context-reset)
</pre></dd>
<dt>racket-browse-url-function</dt><dd><pre>racket-browse-url-using-temporary-file</pre></dd>
<dt>racket-command-timeout</dt><dd><pre>10</pre></dd>
<dt>racket-documentation-search-location</dt><dd><pre>"https://docs.racket-lang.org/search/index.html?q=%s"</pre></dd>
<dt>racket-error-context</dt><dd><pre>medium</pre></dd>
<dt>racket-expand-hiding</dt><dd><pre>standard</pre></dd>
<dt>racket-hash-lang-mode-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-hash-lang-module-language-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-hash-lang-token-face-alist</dt><dd><pre>((constant . font-lock-constant-face)
 (error . error)
 (other . font-lock-doc-face)
 (keyword . font-lock-keyword-face)
 (hash-colon-keyword . racket-keyword-argument-face)
 (at . font-lock-doc-face))
</pre></dd>
<dt>racket-history-filter-regexp</dt><dd><pre>"\\`\\s *\\'"</pre></dd>
<dt>racket-imagemagick-props</dt><dd><pre>nil</pre></dd>
<dt>racket-images-inline</dt><dd><pre>t</pre></dd>
<dt>racket-images-keep-last</dt><dd><pre>100</pre></dd>
<dt>racket-images-system-viewer</dt><dd><pre>"open"</pre></dd>
<dt>racket-indent-curly-as-sequence</dt><dd><pre>t</pre></dd>
<dt>racket-indent-sequence-depth</dt><dd><pre>0</pre></dd>
<dt>racket-logger-config</dt><dd><pre>((cm-accomplice . warning)
 (GC . info)
 (module-prefetch . warning)
 (optimizer . info)
 (racket/contract . error)
 (racket-mode-debugger . info)
 (sequence-specialization . info)
 (* . fatal))
</pre></dd>
<dt>racket-memory-limit</dt><dd><pre>2048</pre></dd>
<dt>racket-mode-hook</dt><dd><pre>(racket-unicode-input-method-enable
 (lambda nil
   (define-key racket-mode-map
     (kbd "M-<left>")
     #'backward-sexp)
   (define-key racket-mode-map
     (kbd "M-<right>")
     #'forward-sexp)
   (define-key racket-mode-map
     (kbd "s-r")
     #'my-racket-run-from-editor)
   (define-key racket-mode-map
     (kbd "s-e")
     #'racket-run-and-switch-to-repl)
   (define-key racket-mode-map
     (kbd "s-d")
     #'my-racket-switch-from-editor-to-repl)
   (define-key racket-mode-map
     (kbd "s-i")
     #'my-racket-indent-whole-buffer)
   (define-key racket-mode-map
     (kbd "s-<left>")
     #'move-beginning-of-line)
   (define-key racket-mode-map
     (kbd "s-<right>")
     #'move-end-of-line)
   (define-key racket-mode-map
     (kbd "s-<down>")
     #'scroll-up-command)
   (show-paren-mode)))
</pre></dd>
<dt>racket-module-forms</dt><dd><pre>"\\s(\\(?:module[*+]?\\|library\\)"</pre></dd>
<dt>racket-pretty-lambda</dt><dd><pre>nil</pre></dd>
<dt>racket-pretty-print</dt><dd><pre>t</pre></dd>
<dt>racket-program</dt><dd><pre>"/Applications/Racket v8.12/bin/racket"</pre></dd>
<dt>racket-repl-buffer-name-function</dt><dd><pre>nil</pre></dd>
<dt>racket-repl-command-file</dt><dd><pre>"/Users/soegaard/.emacs.d/racket-mode/repl.rkt"</pre></dd>
<dt>racket-repl-history-directory</dt><dd><pre>"~/.emacs.d/racket-mode/"</pre></dd>
<dt>racket-repl-mode-hook</dt><dd><pre>(racket-unicode-input-method-enable
 (lambda nil
   (define-key racket-repl-mode-map
     (kbd "s-e")
     #'my-racket-switch-from-repl-to-editor)
   (define-key racket-repl-mode-map
     (kbd "s-d")
     #'delete-other-windows)))
</pre></dd>
<dt>racket-sexp-comment-fade</dt><dd><pre>0.5</pre></dd>
<dt>racket-shell-or-terminal-function</dt><dd><pre>racket-shell</pre></dd>
<dt>racket-show-functions</dt><dd><pre>(racket-show-pseudo-tooltip)
</pre></dd>
<dt>racket-smart-open-bracket-enable</dt><dd><pre>nil</pre></dd>
<dt>racket-submodules-to-run</dt><dd><pre>((test)
 (main))
</pre></dd>
<dt>racket-use-repl-submit-predicate</dt><dd><pre>nil</pre></dd>
<dt>racket-xp-add-binding-faces</dt><dd><pre>nil</pre></dd>
<dt>racket-xp-after-change-refresh-delay</dt><dd><pre>1</pre></dd>
<dt>racket-xp-highlight-unused-regexp</dt><dd><pre>"^[^_]"</pre></dd>
<dt>racket-xp-mode-lighter</dt><dd><pre>(:eval
 (racket--xp-mode-lighter))
</pre></dd>
</dl>
<h2>Minor modes</h2>
<dl>
<dt>enabled</dt><dd><pre>((auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (column-number-mode)
 (delete-selection-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (racket-xp-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (transient-mark-mode))
</pre></dd>
<details><summary>Disabled minor modes</summary>
<dt>disabled</dt><dd><pre>((abbrev-mode)
 (auto-fill-function)
 (auto-fill-mode)
 (auto-save-mode)
 (auto-save-visited-mode)
 (blink-cursor-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (cl-old-struct-compat-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (defining-kbd-macro)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-pair-mode)
 (electric-quote-mode)
 (global-prettify-symbols-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (horizontal-scroll-bar-mode)
 (hs-minor-mode)
 (isearch-mode)
 (jit-lock-debug-mode)
 (line-number-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-hash-lang-repl-mode)
 (racket-smart-open-bracket-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (sh-electric-here-document-mode)
 (size-indication-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode)
 (xref-etags-mode))
</pre></dd>
</details>
</dl>
</details>

**Comment by greghendershott** [comment]
Thanks for the report! Alas, I can't seem to reproduce this, yet.

Given `issue-699.rkt`:

```
#lang racket/base
(define pt 12)
(define pt@x 13)
pt
pt@x
(require "issue-699-2.rkt")
pt@y
```

and `issue-699-2.rkt`:

```
#lang racket/base
(define pt@y 14)
(provide pt@y)
```

In `issue-699.rkt`:

1. When I put point at the start of the use of `pt@x` on line 5, and do <kbd>M-.</kbd>, it goes to the definition of `pt@x` on line 3. (This works because there's a `racket-xp-use` text property pointing there.)

2. When I put point at the start of the use of `pt@y` on line 7, and do <kbd>M-.</kbd>, it goes to the definition of `pt@y` on line 2 of the other file, `issue-699-2.rkt`. (This works because there's a `racket-xp-visit` text property pointing there.)

Both seem correct, and unlike what you report.

- What results do you get with my example?
- Do you have some other small example where you see the problem?

p.s. I don't love how the coloring of `pt@x` is different for `pt` and `@x`, and will look at that, but I _think_ that's a distinct thing.

**Comment by greghendershott** [comment]
Trying to think of ways this could go wrong (maybe you encountered):

If you do <kbd>C-u M-.</kbd>, the <kbd>C-u</kbd> prefix meaning "prompt me for the symbol", it will propose a default that is just `pt` -- not `pt@x`. But you can still type `pt@x`, and it will find it (although this pass is potentially less reliable).

Although maybe not a huge defect, I think I see how I could improve that.

**Comment by soegaard** [comment]
I played with your example:

```
#lang racket/base
(define pt 12)
(define pt@x 13)
pt
pt@x
(require "issue-699-2.rkt")
pt@y
```

First, I run the file.

If I now use `cmd-.` on `pt@y` I am sent to as expected to "issue-699-2.rkt".

Now, if I insert a space, to change `pt@y` to `pt @y` and then use `cmd-.` on `pt`,
then I am still sent to "issue-699-2.rkt" and not to the definition of `pt`.

So, I think, that what happened originally. I made a change and used `cmd-.` without running the file first.

**Comment by greghendershott** [comment]
Ah that scenario makes sense.

Not that you wouldn't need to `racket-run` the file again, just give `racket-xp-mode` time to re-annotate it.

However in this example, since ` @y` is likely an error, `racket-xp-mode` will show the error. Upon an error it retains many properties, with the justification they might be handy when you edit to fix an error -- even if some might be misleading, as in this case. So it's a trade-off.

FWIW I did find a simple change for the other scenario I thought of -- where if you <kbd>C-u M-.</kbd> it prompts with the wrong default. Although not a huge defect, it's safe and simple to improve this, I think. So I'll probably close this issue by merging that commit (even if a bit OT from your original report).
