### ISSUE TITLE
Out of range error in narrowed buffer during redisplay using `racket-xp-mode`

### ISSUE THREAD

**Issue by nverno** [greghendershott/racket-mode#703]
During redisplay there are `args-out-of-range` errors when the source buffer is narrowed.

Steps to reproduce:

Using the following source with `racket-xp-mode` enabled, call `narrow-to-defun`  in `foo`.
```
#lang racket

(define/contract (foo x)
  (-> string? string?)
  x)
```
Then, trigger redisplay, eg. modify and save the buffer.

At this point, I get a message 

> Error running timer: (args-out-of-range 1 53)

Or a backtrace with `debug-on-error`.

<details>
<h2>Package</h2>
<dl>
<dt>metadata</dt><dd><pre>(#s(package-desc racket-mode (20240301 1714) "Racket editing, REPL, and more"
                 ((emacs (25 1))) nil nil
                 "/home/noah/.emacs.d/elpa/racket-mode-20240301.1714"
                 ((:url . "https://www.racket-mode.com/")
                  (:maintainer "Greg Hendershott")
                  (:maintainers ("Greg Hendershott"))
                  (:authors
                   ("Greg Hendershott" .
                    "racket-mode-author@greghendershott.com"))
                  (:commit . "f803fa1ce5309ae074c12f1294bbbad8baf5a340"))
                 nil))
</pre></dd>
<dt>package-archives</dt><dd><pre>(("melpa" . "https://melpa.org/packages/")
 ("gnu" . "https://elpa.gnu.org/packages/")
 ("nongnu" . "https://elpa.nongnu.org/nongnu/"))
</pre></dd>
<dt>racket--el-source-dir</dt><dd><pre>"/home/noah/.emacs.d/elpa/racket-mode-20240301.1714/"
</pre></dd>
<dt>racket--rkt-source-dir</dt><dd><pre>"/home/noah/.emacs.d/elpa/racket-mode-20240301.1714/racket/"
</pre></dd>
</dl>
<h2>System values</h2>
<dl>
<dt>emacs-version</dt><dd><pre>"30.0.50"
</pre></dd>
<dt>major-mode</dt><dd><pre>help-mode
</pre></dd>
<dt>system-type</dt><dd><pre>gnu/linux
</pre></dd>
<dt>x-gtk-use-system-tooltips</dt><dd><pre>t
</pre></dd>
<dt>display-graphic-p</dt><dd><pre>t
</pre></dd>
</dl>
<h2>Buffer values</h2>
<dl>
<dt>after-change-functions</dt><dd><pre>nil
</pre></dd>
<dt>before-change-functions</dt><dd><pre>nil
</pre></dd>
<dt>completion-at-point-functions</dt><dd><pre>(tags-completion-at-point-function)
</pre></dd>
<dt>eldoc-documentation-function</dt><dd><pre>eldoc-documentation-default
</pre></dd>
<dt>font-lock-defaults</dt><dd><pre>nil
</pre></dd>
<dt>pre-command-hook</dt><dd><pre>(company-pre-command t)
</pre></dd>
<dt>post-command-hook</dt><dd><pre>(company-post-command t)
</pre></dd>
<dt>post-self-insert-hook</dt><dd><pre>(electric-indent-post-self-insert-function blink-paren-post-self-insert-function)
</pre></dd>
<dt>xref-backend-functions</dt><dd><pre>(etags--xref-backend)
</pre></dd>
</dl>
<h2>Racket Mode values</h2>
<dl>
<dt>racket--cmd-open-p</dt><dd><pre>t
</pre></dd>
<dt>racket-after-run-hook</dt><dd><pre>nil
</pre></dd>
<dt>racket-back-end-configurations</dt><dd><pre>((:directory "/" :racket-program nil :remote-source-dir nil
             :restart-watch-directories nil :windows nil))
</pre></dd>
<dt>racket-before-run-hook</dt><dd><pre>(racket-ansi-color-context-reset)
</pre></dd>
<dt>racket-browse-url-function</dt><dd><pre>browse-url
</pre></dd>
<dt>racket-command-timeout</dt><dd><pre>10
</pre></dd>
<dt>racket-documentation-search-location</dt><dd><pre>"https://docs.racket-lang.org/search/index.html?q=%s"
</pre></dd>
<dt>racket-error-context</dt><dd><pre>medium
</pre></dd>
<dt>racket-expand-hiding</dt><dd><pre>standard
</pre></dd>
<dt>racket-hash-lang-mode-hook</dt><dd><pre>nil
</pre></dd>
<dt>racket-hash-lang-module-language-hook</dt><dd><pre>nil
</pre></dd>
<dt>racket-hash-lang-token-face-alist</dt><dd><pre>((constant . font-lock-constant-face) (error . error)
 (other . font-lock-doc-face) (keyword . font-lock-keyword-face)
 (hash-colon-keyword . racket-keyword-argument-face) (at . font-lock-doc-face))
</pre></dd>
<dt>racket-history-filter-regexp</dt><dd><pre>"\\`\\s *\\'"
</pre></dd>
<dt>racket-imagemagick-props</dt><dd><pre>nil
</pre></dd>
<dt>racket-images-inline</dt><dd><pre>t
</pre></dd>
<dt>racket-images-keep-last</dt><dd><pre>100
</pre></dd>
<dt>racket-images-system-viewer</dt><dd><pre>"display"
</pre></dd>
<dt>racket-indent-curly-as-sequence</dt><dd><pre>t
</pre></dd>
<dt>racket-indent-sequence-depth</dt><dd><pre>0
</pre></dd>
<dt>racket-logger-config</dt><dd><pre>((cm-accomplice . warning) (GC . info) (module-prefetch . warning)
 (optimizer . info) (racket/contract . error) (racket-mode-debugger . info)
 (sequence-specialization . info) (* . fatal))
</pre></dd>
<dt>racket-memory-limit</dt><dd><pre>2048
</pre></dd>
<dt>racket-mode-hook</dt><dd><pre>(nvp-racket-hook)
</pre></dd>
<dt>racket-module-forms</dt><dd><pre>"\\s(\\(?:module[*+]?\\|library\\)"
</pre></dd>
<dt>racket-pretty-lambda</dt><dd><pre>nil
</pre></dd>
<dt>racket-pretty-print</dt><dd><pre>t
</pre></dd>
<dt>racket-program</dt><dd><pre>"racket"
</pre></dd>
<dt>racket-repl-buffer-name-function</dt><dd><pre>nil
</pre></dd>
<dt>racket-repl-command-file</dt><dd><pre>"/home/noah/.emacs.d/racket-mode/repl.rkt"
</pre></dd>
<dt>racket-repl-history-directory</dt><dd><pre>"/home/noah/.emacs.d/cache/"
</pre></dd>
<dt>racket-repl-mode-hook</dt><dd><pre>(nvp-racket-repl-hook)
</pre></dd>
<dt>racket-sexp-comment-fade</dt><dd><pre>0.5
</pre></dd>
<dt>racket-shell-or-terminal-function</dt><dd><pre>racket-shell
</pre></dd>
<dt>racket-show-functions</dt><dd><pre>(racket-show-pseudo-tooltip)
</pre></dd>
<dt>racket-smart-open-bracket-enable</dt><dd><pre>nil
</pre></dd>
<dt>racket-submodules-to-run</dt><dd><pre>((test) (main))
</pre></dd>
<dt>racket-use-repl-submit-predicate</dt><dd><pre>nil
</pre></dd>
<dt>racket-xp-add-binding-faces</dt><dd><pre>nil
</pre></dd>
<dt>racket-xp-after-change-refresh-delay</dt><dd><pre>1
</pre></dd>
<dt>racket-xp-highlight-unused-regexp</dt><dd><pre>"^[^_]"
</pre></dd>
<dt>racket-xp-mode-lighter</dt><dd><pre>(:eval (racket--xp-mode-lighter))
</pre></dd>
</dl>
<h2>Minor modes</h2>
<dl>
<dt>enabled</dt><dd><pre>((abbrev-mode) (auto-composition-mode) (auto-compression-mode)
 (auto-encryption-mode) (buffer-read-only) (column-number-mode) (company-mode)
 (company-quickhelp-local-mode) (company-quickhelp-mode)
 (company-statistics-mode) (delete-selection-mode) (electric-indent-mode)
 (file-name-shadow-mode) (font-lock-mode) (global-auto-revert-mode)
 (global-company-mode) (global-eldoc-mode) (global-font-lock-mode)
 (global-prettify-symbols-mode) (global-subword-mode) (isearch-fold-quotes-mode)
 (line-number-mode) (menu-bar-mode) (minibuffer-regexp-mode) (mouse-wheel-mode)
 (nvp-treesit-mode) (recentf-mode) (repeat-mode) (save-place-mode)
 (savehist-mode) (semantic-minor-modes-format) (server-mode) (show-paren-mode)
 (smartparens-global-mode) (smooth-scrolling-mode) (subword-mode)
 (transient-mark-mode) (treesit-inspect-mode) (vertico-mode) (windmove-mode)
 (winner-mode))
</pre></dd>
<details><summary>Disabled minor modes</summary>
<dt>disabled</dt><dd><pre>((2C-mode) (ace-window-display-mode) (ace-window-mode) (anaconda-eldoc-mode)
 (anaconda-mode) (auto-compile-mode) (auto-compile-on-load-mode)
 (auto-compile-on-save-mode) (auto-fill-function) (auto-fill-mode)
 (auto-revert-mode) (auto-revert-tail-mode) (auto-save-mode)
 (auto-save-visited-mode) (avy-linum-mode) (blink-cursor-mode)
 (buffer-face-mode) (button-mode) (ccls-code-lens-mode)
 (cl-old-struct-compat-mode) (comint-fontify-input-mode) (company-search-mode)
 (compilation-minor-mode) (compilation-shell-minor-mode)
 (completion-in-region-mode) (consult-preview-at-point-mode) (context-menu-mode)
 (cursor-face-highlight-mode) (cursor-intangible-mode) (cursor-sensor-mode)
 (dash-fontify-mode) (defining-kbd-macro) (diff-auto-refine-mode)
 (diff-minor-mode) (dired-click-to-select-mode) (dired-hide-details-mode)
 (dired-isearch-filenames-mode) (display-line-numbers-mode) (display-time-mode)
 (doc-view-minor-mode) (doc-view-presentation-mode) (edebug-backtrace-mode)
 (edebug-mode) (eldoc-mode) (electric-layout-mode) (electric-pair-mode)
 (electric-quote-mode) (flycheck-mode) (flymake-mode) (geiser-autodoc-mode)
 (geiser-repl-autoeval-mode) (geiser-repl-superparen-mode)
 (geiser-smart-tab-mode) (global-dash-fontify-mode)
 (global-display-line-numbers-mode) (global-flycheck-mode) (global-hl-line-mode)
 (global-robe-mode) (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode) (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode) (global-semantic-stickyfunc-mode)
 (global-superword-mode) (global-visual-line-mode) (gnus-dead-summary-mode)
 (gnus-undo-mode) (gorepl-minor-mode) (header-line-indent-mode)
 (highlight-quoted-mode) (hl-line-mode) (horizontal-scroll-bar-mode)
 (hs-minor-mode) (html-autoview-mode) (iedit-mode) (image-minor-mode)
 (indent-tabs-mode) (inf-ruby-minor-mode) (isearch-mode) (jit-lock-debug-mode)
 (leetcode--loading-mode) (leetcode-solution-mode) (lock-file-mode)
 (lost-selection-mode) (lsp-completion-mode) (lsp-diagnostics-mode)
 (lsp-headerline-breadcrumb-mode) (lsp-inlay-hints-mode)
 (lsp-installation-buffer-mode) (lsp-kotlin-lens-mode) (lsp-lens-mode)
 (lsp-managed-mode) (lsp-mode) (lsp-modeline-code-actions-mode)
 (lsp-modeline-diagnostics-mode) (lsp-modeline-workspace-status-mode)
 (lsp-semantic-tokens-mode) (lsp-signature-mode) (lsp-terraform-modules-mode)
 (macrostep-mode) (mail-abbrevs-mode) (markdown-live-preview-mode)
 (mc-hide-unmatched-lines-mode) (mml-mode) (modern-c++-font-lock-global-mode)
 (modern-c++-font-lock-mode) (modifier-bar-mode) (multiple-cursors-mode)
 (next-error-follow-minor-mode) (nvp-imenu-completion-mode)
 (nvp-leet-indirect-minor-mode) (nvp-leet-minor-mode) (nvp-leet-result-mode)
 (nvp-override-mode) (nvp-repl-minor-mode) (nvp-repl-source-minor-mode)
 (nvp-scratch-minor-mode) (nvp-trace-minor-mode) (nvp-treesit-minor-mode)
 (org-bullets-mode) (org-cdlatex-mode) (org-indent-mode)
 (org-list-checkbox-radio-mode) (org-noter-doc-mode) (org-noter-notes-mode)
 (org-src-mode) (org-table-follow-field-mode) (org-table-header-line-mode)
 (orgtbl-mode) (outline-minor-mode) (overwrite-mode)
 (paragraph-indent-minor-mode) (paredit-mode) (pdf-cache-prefetch-minor-mode)
 (pdf-misc-context-menu-minor-mode) (pdf-misc-menu-bar-minor-mode)
 (pdf-misc-minor-mode) (pdf-misc-size-indication-minor-mode)
 (pdf-view-auto-slice-minor-mode) (pdf-view-dark-minor-mode)
 (pdf-view-midnight-minor-mode) (pdf-view-printer-minor-mode)
 (pdf-view-themed-minor-mode) (prettify-symbols-mode)
 (racket-hash-lang-repl-mode) (racket-smart-open-bracket-mode) (racket-xp-mode)
 (read-extended-command-mode) (read-passwd-mode) (rectangle-mark-mode)
 (rectangular-region-mode) (robe-mode) (rspec-dired-mode) (rspec-mode)
 (rspec-verifiable-mode) (rustic-doc-mode) (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode) (semantic-mode)
 (semantic-show-parser-state-mode) (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode) (sgml-electric-tag-pair-mode)
 (sh-electric-here-document-mode) (shell-dirtrack-mode)
 (shell-highlight-undef-mode) (show-smartparens-global-mode)
 (show-smartparens-mode) (size-indication-mode) (smartparens-global-strict-mode)
 (smartparens-mode) (smartparens-strict-mode) (superword-mode)
 (tab-bar-history-mode) (tab-bar-mode) (tablist-edit-column-minor-mode)
 (tablist-minor-mode) (temp-buffer-resize-mode) (text-scale-mode)
 (tool-bar-mode) (tooltip-mode) (transient-resume-mode) (treesit-explore-mode)
 (undelete-frame-mode) (url-handler-mode) (use-hard-newlines) (vc-dir-git-mode)
 (view-mode) (visible-mode) (visual-line-mode) (window-divider-mode)
 (xref-etags-mode) (yard-mode) (yas-global-mode) (yas-minor-mode))
</pre></dd>
</details>
</dl>
</details>

**Comment by greghendershott** [comment]
Thanks for the report. It looks like there are a few issues related to narrowing.

1. The one you reported. Fix: Temporarily widen before applying text properties.

2. Even if that's fixed, the narrowed text is a program fragment that check-syntax will complain isn't valid Racket, e.g. say there's an `#%app is undefined` error. Fix: Always give check-syntax the full buffer, i.e. ignore any narrowing.

3. What if you have narrowed to `foo`, have point on `bar` in the program below and press <kbd>M-.</kbd> a.k.a. `M-x xref-find-definitions`. Status quo that's another range error. Fix?? Instead should it `widen` -- discard your narrowing, so it can actually go to and show you `bar`? I _think_ so, but I don't use use narrowing enough to know what's expected or best practice, so I'm curious what you think?

```racket
#lang racket

(define/contract (foo x)
  (-> string? string?)
  (bar x)) ;;;;;;;;;; <==== point on `bar` here

(define (bar x)
  x)
```

**Comment by greghendershott** [comment]
Hmm I saw it error in Emacs 28.2 (daily driver). Maybe this improved in 30. I can try build from source.

In any case, maybe it's fair to classify that as "not my problem to fix", instead that's up to xref, and it may in fact have improved this sometime after 28.2?

**Comment by nverno** [comment]
Oh you're right it does error on emacs 30 as well.  I thought you were asking about how to handle the widening more generally.  The following patch seems to fix the xref problem, letting `xref` decide whether to allow it or not depending on `widen-automatically`

```
=diff --git a/racket-xp.el b/racket-xp.el
index fc4c43b..9f32778 100644
--- a/racket-xp.el
+++ b/racket-xp.el
@@ -1084,9 +1084,11 @@ around at the first and last errors."
    (pcase (get-text-property 0 'racket-xp-use str)
      (`(,beg ,end)
       (list
-       (xref-make (buffer-substring beg end)
-                  (xref-make-buffer-location (current-buffer)
-                                             (marker-position beg))))))
+       (save-restriction
+         (widen)
+         (xref-make (buffer-substring beg end)
+                    (xref-make-buffer-location (current-buffer)
+                                               (marker-position beg)))))))
    ;; Annotated by dr/cs as imported module; visit the module
    (pcase (get-text-property 0 'racket-xp-def str)
      (`(import ,id . ,_)
>
```

**Comment by greghendershott** [comment]
Thanks for the idea for  xref!

Commit 483a1e7 seems to cover all the bases -- but just in my quick testing; so if it's convenient for you to try it, please let me know?

Otherwise I'll sleep on it, try to test a bit more myself, and merge within a few days.

**Comment by nverno** [comment]
It's working perfectly!

**Comment by greghendershott** [comment]
Merged; thanks for confirming, as well as for the xref idea!
