### ISSUE TITLE
view/run command history?

### ISSUE THREAD

**Issue by sausageandbiscuits** [greghendershott/racket-mode#708]
Is there any way to view / run previously run expressions in the REPL? Similar to how in a terminal you can use the up arrow key to see the previously run statements and re-execute them.

**Comment by greghendershott** [comment]
Yes. Try <kbd>M-p</kbd> and <kbd>M-n</kbd> for the previous and next items. And press <kbd>RET</kbd> to execute.

If you're new to Emacs, you'll find these are the keys typically used for history -- like in the minibuffer, `*shell*` buffers, other language REPLs, and so on.

**Comment by sausageandbiscuits** [comment]
Thank you thank you!
