### ISSUE TITLE
Bitmaps not render in the REPL with the HTDP

### ISSUE THREAD

**Issue by akaml** [greghendershott/racket-mode#709]
Hi. I have a problem with displaying bitmap images in repl when using #lang htdp/bsl.
One of the reproduction options is to  load an image from a file(via the bitmap function) or to call already defined bitmap image in the repl
If you create images using the functions of forming simple shapes (rect, circle, etc.), then the shapes are displayed correctly, the problem arises with bitmap.
I checked the image cache and found an svg file with a bitmap embedded via base64. It seems that there is a problem with the display itself in emacs.
I tried different versions of racket - the problem remains
The code for reproduction:
[issue.txt](https://github.com/greghendershott/racket-mode/files/15300235/issue.txt)
<img width="298" alt="drracket" src="https://github.com/greghendershott/racket-mode/assets/6190380/f881c8cd-da11-457b-a401-10b14cd0f53a">
<img width="259" alt="emacs" src="https://github.com/greghendershott/racket-mode/assets/6190380/1410a651-3368-41eb-a521-4c1f95bc1da4">

<details>
<h2>Package</h2>
<dl>
<dt>metadata</dt><dd><pre>(#s(package-desc racket-mode
                 (20240418 1446)
                 "Racket editing, REPL, and more"
                 ((emacs
                   (25 1)))
                 nil nil "c:/Users/admin/AppData/Roaming/.emacs.d/elpa/racket-mode-20240418.1446"
                 ((:url . "https://www.racket-mode.com/")
                  (:maintainer "Greg Hendershott")
                  (:maintainers
                   ("Greg Hendershott"))
                  (:authors
                   ("Greg Hendershott" . "racket-mode-author@greghendershott.com"))
                  (:commit . "d5f4007fd2c2604673125035f4852dce1b639b33"))
                 nil))
</pre></dd>
<dt>package-archives</dt><dd><pre>(("melpa" . "https://melpa.org/packages/")
 ("gnu" . "https://elpa.gnu.org/packages/")
 ("nongnu" . "https://elpa.nongnu.org/nongnu/"))
</pre></dd>
<dt>racket--el-source-dir</dt><dd><pre>"c:/Users/admin/AppData/Roaming/.emacs.d/elpa/racket-mode-20240418.1446/"</pre></dd>
<dt>racket--rkt-source-dir</dt><dd><pre>"c:/Users/admin/AppData/Roaming/.emacs.d/elpa/racket-mode-20240418.1446/racket/"</pre></dd>
</dl>
<h2>System values</h2>
<dl>
<dt>emacs-version</dt><dd><pre>"29.3"</pre></dd>
<dt>major-mode</dt><dd><pre>help-mode</pre></dd>
<dt>system-type</dt><dd><pre>windows-nt</pre></dd>
<dt>display-graphic-p</dt><dd><pre>t</pre></dd>
</dl>
<h2>Buffer values</h2>
<dl>
<dt>after-change-functions</dt><dd><pre>nil</pre></dd>
<dt>before-change-functions</dt><dd><pre>nil</pre></dd>
<dt>completion-at-point-functions</dt><dd><pre>(tags-completion-at-point-function)
</pre></dd>
<dt>eldoc-documentation-function</dt><dd><pre>eldoc-documentation-default</pre></dd>
<dt>font-lock-defaults</dt><dd><pre>nil</pre></dd>
<dt>pre-command-hook</dt><dd><pre>(tooltip-hide)
</pre></dd>
<dt>post-command-hook</dt><dd><pre>(global-font-lock-mode-check-buffers global-eldoc-mode-check-buffers global-display-line-numbers-mode-check-buffers mode-local-post-major-mode-change)
</pre></dd>
<dt>post-self-insert-hook</dt><dd><pre>(electric-indent-post-self-insert-function blink-paren-post-self-insert-function)
</pre></dd>
<dt>xref-backend-functions</dt><dd><pre>(etags--xref-backend)
</pre></dd>
</dl>
<h2>Racket Mode values</h2>
<dl>
<dt>racket--cmd-open-p</dt><dd><pre>t</pre></dd>
<dt>racket-after-run-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-back-end-configurations</dt><dd><pre>((:directory "/" :racket-program nil :remote-source-dir nil :restart-watch-directories nil :windows t))
</pre></dd>
<dt>racket-before-run-hook</dt><dd><pre>(racket-ansi-color-context-reset)
</pre></dd>
<dt>racket-browse-url-function</dt><dd><pre>browse-url</pre></dd>
<dt>racket-command-timeout</dt><dd><pre>10</pre></dd>
<dt>racket-documentation-search-location</dt><dd><pre>"https://docs.racket-lang.org/search/index.html?q=%s"</pre></dd>
<dt>racket-error-context</dt><dd><pre>medium</pre></dd>
<dt>racket-expand-hiding</dt><dd><pre>standard</pre></dd>
<dt>racket-hash-lang-mode-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-hash-lang-module-language-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-hash-lang-token-face-alist</dt><dd><pre>((constant . font-lock-constant-face)
 (error . error)
 (other . font-lock-doc-face)
 (keyword . font-lock-keyword-face)
 (hash-colon-keyword . racket-keyword-argument-face)
 (at . font-lock-doc-face))
</pre></dd>
<dt>racket-history-filter-regexp</dt><dd><pre>"\\`\\s *\\'"</pre></dd>
<dt>racket-imagemagick-props</dt><dd><pre>nil</pre></dd>
<dt>racket-images-inline</dt><dd><pre>t</pre></dd>
<dt>racket-images-keep-last</dt><dd><pre>100</pre></dd>
<dt>racket-images-system-viewer</dt><dd><pre>"display"</pre></dd>
<dt>racket-indent-curly-as-sequence</dt><dd><pre>t</pre></dd>
<dt>racket-indent-sequence-depth</dt><dd><pre>0</pre></dd>
<dt>racket-logger-config</dt><dd><pre>((cm-accomplice . warning)
 (GC . info)
 (module-prefetch . warning)
 (optimizer . info)
 (racket/contract . error)
 (racket-mode-debugger . info)
 (sequence-specialization . info)
 (* . fatal))
</pre></dd>
<dt>racket-memory-limit</dt><dd><pre>2048</pre></dd>
<dt>racket-mode-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-module-forms</dt><dd><pre>"\\s(\\(?:module[*+]?\\|library\\)"</pre></dd>
<dt>racket-pretty-lambda</dt><dd><pre>nil</pre></dd>
<dt>racket-pretty-print</dt><dd><pre>t</pre></dd>
<dt>racket-program</dt><dd><pre>"Racket.exe"</pre></dd>
<dt>racket-repl-buffer-name-function</dt><dd><pre>nil</pre></dd>
<dt>racket-repl-command-file</dt><dd><pre>"c:/Users/admin/AppData/Roaming/.emacs.d/racket-mode/repl.rkt"</pre></dd>
<dt>racket-repl-history-directory</dt><dd><pre>"~/.emacs.d/racket-mode/"</pre></dd>
<dt>racket-repl-mode-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-sexp-comment-fade</dt><dd><pre>0.5</pre></dd>
<dt>racket-shell-or-terminal-function</dt><dd><pre>racket-shell</pre></dd>
<dt>racket-show-functions</dt><dd><pre>(racket-show-pseudo-tooltip)
</pre></dd>
<dt>racket-smart-open-bracket-enable</dt><dd><pre>nil</pre></dd>
<dt>racket-submodules-to-run</dt><dd><pre>((test)
 (main))
</pre></dd>
<dt>racket-use-repl-submit-predicate</dt><dd><pre>nil</pre></dd>
<dt>racket-xp-add-binding-faces</dt><dd><pre>nil</pre></dd>
<dt>racket-xp-after-change-refresh-delay</dt><dd><pre>1</pre></dd>
<dt>racket-xp-highlight-unused-regexp</dt><dd><pre>"^[^_]"</pre></dd>
<dt>racket-xp-mode-lighter</dt><dd><pre>(:eval
 (racket--xp-mode-lighter))
</pre></dd>
</dl>
<h2>Minor modes</h2>
<dl>
<dt>enabled</dt><dd><pre>((auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (blink-cursor-mode)
 (buffer-read-only)
 (display-line-numbers-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-display-line-numbers-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (isearch-fold-quotes-mode)
 (line-number-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (tooltip-mode)
 (transient-mark-mode))
</pre></dd>
<details><summary>Disabled minor modes</summary>
<dt>disabled</dt><dd><pre>((abbrev-mode)
 (auto-fill-function)
 (auto-fill-mode)
 (auto-save-mode)
 (auto-save-visited-mode)
 (buffer-face-mode)
 (button-mode)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (comint-fontify-input-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (context-menu-mode)
 (cursor-face-highlight-mode)
 (defining-kbd-macro)
 (display-fill-column-indicator-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-pair-mode)
 (electric-quote-mode)
 (ggtags-mode)
 (ggtags-navigation-mode)
 (global-display-fill-column-indicator-mode)
 (global-prettify-symbols-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (header-line-indent-mode)
 (horizontal-scroll-bar-mode)
 (hs-minor-mode)
 (indent-tabs-mode)
 (isearch-mode)
 (jit-lock-debug-mode)
 (lock-file-mode)
 (lost-selection-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-hash-lang-repl-mode)
 (racket-smart-open-bracket-mode)
 (racket-xp-mode)
 (read-extended-command-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (sh-electric-here-document-mode)
 (shell-highlight-undef-mode)
 (size-indication-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (treesit-explore-mode)
 (treesit-inspect-mode)
 (undelete-frame-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode)
 (xref-etags-mode))
</pre></dd>
</details>
</dl>
</details>

**Comment by greghendershott** [comment]
Thanks for the excellent, clear report!

> One of the reproduction options is to load an image from a file(via the bitmap function) or to call already defined bitmap image in the repl.
> If you create images using the functions of forming simple shapes (rect, circle, etc.), then the shapes are displayed correctly, the problem arises with bitmap.

> I checked the image cache and found an svg file with a bitmap embedded via base64. It seems that there is a problem with the display itself in emacs.

Interesting! Thank you for narrowing that down.

Although I can't reproduce this (I do see the image) on Emacs 28.2 on Linux, you're using Windows.

I'll try Windows, later; assuming I can reproduce it there: This seems specific to the Windows version of Emacs -- it has some problem handling SVGs with embedded bitmaps?

If so, this might need to get fixed, properly, in Emacs for Windows. But maybe there is some work-around I can supply for you meanwhile??

---

Quick background about the image handling:

Currently the Racket Mode back end uses Racket's [`file/convertible`](https://docs.racket-lang.org/file/convertible.html) to convert image objects. It asks for SVG when the Emacs front end reports `'svg` in both the `image-types` and `image-types-available-p` lists. Otherwise it asks for PNG. (The preference for SVG is because it can be much smaller/faster for vector graphics. See e.g. #470. And with no downside for bitmap graphics... usually.)

There's no option to prefer PNG exposed, for you to try here. I could add something like that. However, even if it helps work around this shortcoming in Emacs for Windows, it would be at the cost of bloating graphics handling generally. So... I'm not immediately sure what's best to do...

**Comment by akaml** [comment]
Thanks for the answer! Apparently, the problem is with the emacs build.
I used vanilla versions of emacs from the gnu website (tested on versions 28 and 29), but after installing via msys2, the problem went away
At first I thought that the problem was in imagemagick, but it turned out that the msys2 version was built without its support.
Support for image types:
image-types =>
emacs 28.2(vanila): (svg png gif tiff jpeg xpm xbm ppm)
emacs 29.3(msys2): (bmp svg webgl png gif tiff jpeg xpm xbm ppm)
Of the interesting differences, I can only notice the lack of bmp support in the vanilla version
I also had a problem opening images embedded in svg outside of racket-mode on vanilla versions

**Comment by akaml** [comment]
@greghendershott 
FYI: I ran the code from the issue-709 branch - the problem on the vanilla version is fixed when (setq racket-images-do-not-use-svg). Thanks!

**Comment by greghendershott** [comment]
> Support for image types:
> image-types =>
> emacs 28.2(vanila): (svg png gif tiff jpeg xpm xbm ppm)
> emacs 29.3(msys2): (bmp svg webgl png gif tiff jpeg xpm xbm ppm)

Interesting; so the problematic version advertises itself as supporting `svg` -- and does generally for vector ops -- but apparently  there's a hole in the implementation where it doesn't support embedded bitmaps.
