### ISSUE TITLE
Install package from racket-mode?

### ISSUE THREAD

**Issue by julian-hoch** [greghendershott/racket-mode#710]
Is it possible to install packages from racket-mode? I didn't find any related functions or documentation.
Or do you need to use DrRacket to install packages?

**Comment by greghendershott** [comment]
Although you may use DrRacket to install Racket packages, you may also use the command line: [`raco pkg install`](https://docs.racket-lang.org/pkg/getting-started.html#%28part._installing-packages%29) (from your OS terminal or an Emacs shell buffer).

FWIW my impression is that most Racket Mode users install Racket packages from the command line, but either way is fine.
