### ISSUE TITLE
Values are printed without newlines when `racket-pretty-print` is `nil`

### ISSUE THREAD

**Issue by usaoc** [greghendershott/racket-mode#711]
To reproduce this, run any module with more than one module-level expressions, say

```racket
#lang racket/base
1
2
```

with `racket-pretty-print` set to `nil`.  The reason is that in

<https://github.com/greghendershott/racket-mode/blob/d2cff2b7f210846108875c7eccb1b5ab98bceb74/racket/print.rkt#L17-L36>

the non-pretty mode uses `print`, which doesn’t add a newline.

**Comment by greghendershott** [comment]
Thanks for the report!

Just merged a fix.
