### ISSUE TITLE
`racket-hash-lang-mode`: Allow text tokens to use a different face

### ISSUE THREAD

**Issue by usaoc** [greghendershott/racket-mode#712]
Currently, in `racket-hash-lang-mode`, text tokens such as Scribble text use the face `default`.  With a spell-checker such as [Jinx](https://github.com/minad/jinx), this is annoying, because it needs to include/exclude spell-checking based on faces.  Can text tokens be allowed to use a different face, preferably based on user customization?

**Comment by greghendershott** [comment]
I see.

The `jinx` README mentions using arbitrary predicates:

> Jinx can flexibly ignore misspellings via faces (jinx-exclude-faces and jinx-include-faces), regular expressions (jinx-exclude-regexps), and programmable predicates.

One could look for `racket-token` properties with a value of `text`.

Unfortunately [glancing at its source](https://github.com/minad/jinx/blob/main/jinx.el#L270), `jinx--predicates` follows the naming convention for internal/private variables -- it doesn't seem intended as a customization after all.

---

So:

I can give text tokens a distinct new face, `racket-hash-lang-text` (which inherits from the `default` face, so it will look the same;  but a user can customize any face's appearance).

**Comment by greghendershott** [comment]
Before I merge it, does commit 4cdbc1d seem like it will work and meet your needs?

**Comment by usaoc** [comment]
> Before I merge it, does commit [4cdbc1d](https://github.com/greghendershott/racket-mode/commit/4cdbc1deb30c1625fadde762e55eb78c3acede53) seem like it will work and meet your needs?

From a quick testing, yes.

**Comment by greghendershott** [comment]
OK; merged.
