### ISSUE TITLE
Show some documentation when hovering

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/racket-mode#716]
@greghendershott Hello, it's been 8 years I know but because I use Racket and Emacs, so here's a few things. I agree with you that `eldoc` on the echo just to see the structure of the s-expression doesn't really have much. But, one can do much more with `eldoc`. Below is a screenshot of a Rust source file where I can get information about anything (keyword or expression) just by hovering it:

![pic-selected-240827-0346-37](https://github.com/user-attachments/assets/6bbdb9ef-d735-4d82-a839-62958190f166)

This is done through `eldoc` which is getting the necessary stuff from `rust-analyzer` which is being managed through `eglot` and then put into a nice hovering box using [`eldoc-box`](https://github.com/casouri/eldoc-box). I think _this_ can be put to good use alongside the excellent documentation that Racket already holds. Moreover, this also works for one's own local definitions:

![pic-selected-240827-0351-26](https://github.com/user-attachments/assets/8224e2eb-2730-412b-ba74-b0fb6e20c976)

This works similarly with Haskell using `haskell-mode` as well. I am not really sure how one might integrate this with `racket-mode`, but if you can share your thoughts on this and maybe guide a bit on how to make `eldoc` talk to Racket documentation I could try for implementing this.

_Originally posted by @divyaranjan1905 in https://github.com/greghendershott/racket-mode/issues/199#issuecomment-2311517636_

**Comment by greghendershott** [comment]
Note: Already you can `(setq-local eldoc-documentation-function #'racket-xp-eldoc-function)` to show "blueboxes". Have you tried this? Does it work OK for you with `eldoc-box`?

**Comment by greghendershott** [comment]
I'm getting up to speed on the latest `eldoc`. (The last I looked at it was when I was using Emacs 25.)

I see now it:

- supports zero or more functions -- `eldoc-documentation-functions`, plural
- allows the user to pick a strategy to use some or all of those -- `eldoc-documentation-strategy`
- allows slower sources to return a result asynchronously, via a callback

This all sounds great. Especially the last point, because, although getting the "bluebox" signature summaries is fairly fast, it can be slower to fetch full documentation and massage the HTML to render well in an Emacs buffer.

So what I'm exploring right now:

- Supply a couple flavors of functions.
- Default `eldoc-documentation-functions` to just the short bluebox summaries -- but of course a user (like you) could configure for full docs.

So far this seems to be working well with the vanilla Emacs UX. I plan to try `eldoc-box` soon, too.

**Comment by divyaranjan1905** [comment]
> Note: Already you can `(setq-local eldoc-documentation-function #'racket-xp-eldoc-function)` to show "blueboxes". Have you tried this? Does it work OK for you with `eldoc-box`?

The setting you prescribed, doesn't seem to do anything for me, I don't see any blue box.

**Comment by divyaranjan1905** [comment]
>     * Default `eldoc-documentation-functions` to just the short bluebox summaries -- but of course a user (like you) could configure for full docs.
> 
> So far this seems to be working well with the vanilla Emacs UX. I plan to try `eldoc-box` soon, too. 

@greghendershott Sounds great, anything you need help with? I've done a thing or two with `eldoc` and did mess around with `eldoc-box` as well. Since I've been pleased with this package and planning to start contributing, this will be a good opportunity.

**Comment by divyaranjan1905** [comment]
> Much of the documentation is too large to fit even in an eldoc-box frame, and that frame doesn't support scrolling with e.g. the mousewheel.

Actually @greghendershott , it does. I can scroll through the buffer using whatever keybindings I have (`C-n`, `C-p`) or us the mouse.

**Comment by greghendershott** [comment]
Hmm. For me with `eldoc-box-hover-at-point-mode`, the keybindings and mousewheel control the buffer, not the child frame.

**Comment by greghendershott** [comment]
In any case I think that commit 085736b on the `issue-716` branch might be good enough to merge.

If you're willing/able to try that, and give me feedback, *before* I merge -- I'd be grateful.

However if it's not convenient for you, no worries, just let me know; I could go ahead and merge, and get your feedback, later.

**Comment by divyaranjan1905** [comment]
> Hmm. For me with `eldoc-box-hover-at-point-mode`, the keybindings and mousewheel control the edit buffer, not the child frame.

@greghendershott First click into the child frame while it's open, and then try the mousewheel and keybindings.

**Comment by divyaranjan1905** [comment]
@greghendershott I did a checkout of branch `issue-716` and I don't think what's implemented is exactly what I was meaning to add. Here's what I see when I hover with `eldoc-box-hover-at-point-mode` toggled on:

![screenshot_2024-09-13_10 37 14](https://github.com/user-attachments/assets/e232d894-aa3d-447f-9356-a37dc4570c02)

That doesn't really provide any documentation help, it only provides the syntax information regarding how the particular procedure or s-expression is syntactically structured. What I intended with this issue, is to channel the documentation generated by `racket-xp-describe` to show up, containing the relevant examples and description. To reiterate again, how this works with `rust-analyzer` in rust files:

![screenshot_2024-09-13_10 40 58](https://github.com/user-attachments/assets/c0ad49c9-2cde-4c3d-b553-1ed89bd5e1fc)

I can click into this child frame, and if needed scroll easily and get the relevant information without having another window open up on the side. The documentation `rust-analyzer` gets is also using the CLI, similar to `raco doc`.

I understand there's issues of latency, I did notice that at times `racket-xp-describe` also gets hung up, but that could also be because of the HTML rendering. From what seems like it the `eldoc` buffer of `rust` files seems to be markdown with syntax highlighting.

**Comment by greghendershott** [comment]
I had a function to do this, but I deleted it before committing. I felt the performance was just too slow. Some doc files like "require.html" can take seconds. Although that's acceptable-ish when using `racket-describe`, it's pretty awful when just navigating around an edit buffer with eldoc. IMHO. But I can add it back in, just not enabled by default, for now. You can try, and maybe we'll have some ideas?

One second...

**Comment by greghendershott** [comment]
OK I pushed commit f6d68fb to the `issue-716` branch. See the commit message for details how to enable. Please let me know what you think?

**Comment by greghendershott** [comment]
What it looks like on my system (not configured quite as nicely as yours):

![image](https://github.com/user-attachments/assets/d0758169-e91a-474f-80b0-e09c45c18bd2)

**Comment by greghendershott** [comment]
I will also explore some optimizations that occur to me with a fresh brain fueled by coffee.

For example, the "adjusting" step is slowest (where we massage to render better in Emacs). But we need not adjust the entire DOM (as we do when rendering full pages in racket-describe) before extracting one section of interest. We can adjust only that (smaller) section. That should help significantly (?).

After that obvious big optimization, I can also look at micro-optimizing the "adjusting" itself...

**Comment by greghendershott** [comment]
> For example, the "adjusting" step is slowest (where we massage to render better in Emacs). But we need not adjust the entire DOM (as we do when rendering full pages in racket-describe) before extracting one section of interest. We can adjust only that (smaller) section. That should help significantly (?).

Wow. That made a **HUGE** difference.

Maybe enough to have this enabled by default.

I'll push a new commit, I just want to take a quick break, and come back to verify a few things.

**Comment by greghendershott** [comment]
Pushed commit 32f7305.

I _think_ this is close to being ready to merge?

Would love your feedback, again, when you have a chance -- thanks!

**Comment by greghendershott** [comment]
Ready to merge.

Here are screenshots for different permutations of `racket-xp-eldoc-level` and `eldoc-documentation-strategy` (using `eldoc-box-hover-at-point-mode`).

# `racket-xp-eldoc-level`: `'summary`

Just the bluebox signature.

## `eldoc-documentation-strategy`: `#'eldoc-documentation-default`

Info about point *or* sexp app.

![image](https://github.com/user-attachments/assets/e07218e3-4d84-4f5c-a0fa-be28a1c9fa47)

## `eldoc-documentation-strategy`: `#'eldoc-documentation-compose`

Info about point *and* sexp app.

![image](https://github.com/user-attachments/assets/fd1de5b8-7b5e-49b0-872b-ffcb5355d291)

# `racket-xp-eldoc-level`: `'complete`

Full documentation.

## `eldoc-documentation-strategy`: `#'eldoc-documentation-default`

Info about point *or* sexp app.

![image](https://github.com/user-attachments/assets/0f556c51-0f79-4676-8941-83cfb590ecf7)

## `eldoc-documentation-strategy`: `#'eldoc-documentation-compose`

Info about point *and* sexp app.

![image](https://github.com/user-attachments/assets/36d3bef8-36c0-4b69-8da8-b4e2d948661a)

**Comment by greghendershott** [comment]
I've continued to make some more commits, to improve this for full documentation and with `eldoc-box`.

If anyone tried this over the last week, before today, and found it too slow, or the display being not ideal (e.g. some doc lines looking "double spaced")?  Then you may want to update both packages (racket-mode and eldoc-box), and try again.

I think you'll find it in good shape. But if you still have problems, feel free to comment here or (even better) open a new issue.
