### ISSUE TITLE
Occasional hangs and eldoc errors

### ISSUE THREAD

**Issue by samth** [greghendershott/racket-mode#726]
I get the following error message regularly, along with occasional long hangs where I can't do anything in the buffer. This seems to happen mostly in `rhombus` files.

```
eldoc error: (user-error Cannot move backward)
```

<details>
<h2>Package</h2>
<dl>
<dt>metadata</dt><dd><pre>nil</pre></dd>
<dt>package-archives</dt><dd><pre>(("elpa" . "https://elpa.gnu.org/packages/")
 ("melpa" . "https://melpa.org/packages/"))
</pre></dd>
<dt>racket--el-source-dir</dt><dd><pre>"/home/samth/sw/racket-mode/"</pre></dd>
<dt>racket--rkt-source-dir</dt><dd><pre>"/home/samth/sw/racket-mode/racket/"</pre></dd>
</dl>
<h2>System values</h2>
<dl>
<dt>emacs-version</dt><dd><pre>"29.3"</pre></dd>
<dt>major-mode</dt><dd><pre>racket-hash-lang-mode</pre></dd>
<dt>system-type</dt><dd><pre>gnu/linux</pre></dd>
<dt>x-gtk-use-system-tooltips</dt><dd><pre>t</pre></dd>
<dt>display-graphic-p</dt><dd><pre>t</pre></dd>
</dl>
<h2>Buffer values</h2>
<dl>
<dt>after-change-functions</dt><dd><pre>(jit-lock-after-change t racket--xp-after-change-hook racket--hash-lang-after-change-hook)
</pre></dd>
<dt>before-change-functions</dt><dd><pre>(t syntax-ppss-flush-cache)
</pre></dd>
<dt>completion-at-point-functions</dt><dd><pre>(racket-xp-complete-at-point)
</pre></dd>
<dt>eldoc-documentation-function</dt><dd><pre>eldoc-documentation-default</pre></dd>
<dt>eldoc-documentation-strategy</dt><dd><pre>eldoc-documentation-default</pre></dd>
<dt>eldoc-documentation-functions</dt><dd><pre>(racket-xp-eldoc-point racket-xp-eldoc-sexp-app t)
</pre></dd>
<dt>font-lock-defaults</dt><dd><pre>(nil t)
</pre></dd>
<dt>pre-command-hook</dt><dd><pre>(eldoc-pre-command-refresh-echo-area t)
</pre></dd>
<dt>post-command-hook</dt><dd><pre>(eldoc-schedule-timer t)
</pre></dd>
<dt>post-self-insert-hook</dt><dd><pre>(racket-hash-lang-post-self-insert t)
</pre></dd>
<dt>xref-backend-functions</dt><dd><pre>(racket-xp-xref-backend-function t)
</pre></dd>
</dl>
<h2>Racket Mode values</h2>
<dl>
<dt>racket--cmd-open-p</dt><dd><pre>t</pre></dd>
<dt>racket-after-run-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-back-end-configurations</dt><dd><pre>((:directory "/" :racket-program nil :remote-source-dir nil :restart-watch-directories nil :windows nil))
</pre></dd>
<dt>racket-before-run-hook</dt><dd><pre>(racket-ansi-color-context-reset)
</pre></dd>
<dt>racket-browse-url-function</dt><dd><pre>browse-url</pre></dd>
<dt>racket-command-timeout</dt><dd><pre>10</pre></dd>
<dt>racket-documentation-search-location</dt><dd><pre>"https://docs.racket-lang.org/search/index.html?q=%s"</pre></dd>
<dt>racket-error-context</dt><dd><pre>medium</pre></dd>
<dt>racket-expand-hiding</dt><dd><pre>standard</pre></dd>
<dt>racket-hash-lang-mode-hook</dt><dd><pre>(racket-xp-mode)
</pre></dd>
<dt>racket-hash-lang-module-language-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-hash-lang-token-face-alist</dt><dd><pre>((constant . font-lock-constant-face)
 (error . error)
 (other . font-lock-doc-face)
 (keyword . font-lock-keyword-face)
 (hash-colon-keyword . racket-keyword-argument-face)
 (at . font-lock-doc-face))
</pre></dd>
<dt>racket-history-filter-regexp</dt><dd><pre>"\\`\\s *\\'"</pre></dd>
<dt>racket-imagemagick-props</dt><dd><pre>nil</pre></dd>
<dt>racket-images-do-not-use-svg</dt><dd><pre>nil</pre></dd>
<dt>racket-images-inline</dt><dd><pre>t</pre></dd>
<dt>racket-images-keep-last</dt><dd><pre>100</pre></dd>
<dt>racket-images-system-viewer</dt><dd><pre>"display"</pre></dd>
<dt>racket-indent-curly-as-sequence</dt><dd><pre>t</pre></dd>
<dt>racket-indent-sequence-depth</dt><dd><pre>0</pre></dd>
<dt>racket-input-prefix</dt><dd><pre>"\\"</pre></dd>
<dt>racket-input-translations</dt><dd><pre>(("All" "∀")
 ("Union" "U")
 ("Intersection" "∩")
 ("test-->>E" "test-->>∃")
 ("vdash" "⊢")
 ("gg" "≫")
 ("succ" "≻")
 ("times" "×")
 ("Uparrow" "⇑")
 ("Downarrow" "⇓")
 ("Leftarrow" "⇐")
 ("Rightarrow" "⇒")
 ("leftarrow" "←")
 ("rightarrow" "→")
 ("nwarrow" "↖")
 ("nearrow" "↗")
 ("uparrow" "↑")
 ("downarrow" "↓")
 ("searrow" "↘")
 ("swarrow" "↙")
 ("leftrightarrow" "↔")
 ("updownarrow" "⇕")
 ("aleph" "א")
 ("emptyset" "∅")
 ("nabla" "∇")
 ("surd" "√")
 ("negation" "¬")
 ("infinity" "∞")
 ("prod" "∏")
 ("coprod" "∐")
 ("integrate" "∫")
 ("oint" "∮")
 ("vee" "∨")
 ("wedge" "∧")
 ("follows" "∘")
 ("setin" "∈")
 ("ni" "∋")
 ("notin" "∉")
 ("sqsubset" "⊏")
 ("sqsupset" "⊐")
 ("sqsubseteq" "⊑")
 ("sqsupseteq" "⊒")
 ("subset" "⊂")
 ("superset" "⊃")
 ("subseteq" "⊆")
 ("supseteq" "⊇")
 ("approx" "≈")
 ("cong" "≌")
 ("neq" "≠")
 ("sqcap" "⊓")
 ("sqcup" "⊔")
 ("models" "⊧")
 ("alpha" "α")
 ("Alpha" "Α")
 ("beta" "β")
 ("Beta" "Β")
 ("gamma" "γ")
 ("Gamma" "Γ")
 ("delta" "δ")
 ("Delta" "Δ")
 ("epsilon" "ε")
 ("Epsilon" "Ε")
 ("zeta" "ζ")
 ("Zeta" "Ζ")
 ("eta" "η")
 ("Eta" "Η")
 ("theta" "θ")
 ("Theta" "Θ")
 ("iota" "ι")
 ("Iota" "Ι")
 ("kappa" "κ")
 ("Kappa" "Κ")
 ("lambda" "λ")
 ("Lambda" "Λ")
 ("lamda" "λ")
 ("Lamda" "Λ")
 ("mu" "μ")
 ("Mu" "Μ")
 ("nu" "ν")
 ("Nu" "Ν")
 ("xi" "ξ")
 ("Xi" "Ξ")
 ("omicron" "ο")
 ("Omicron" "Ο")
 ("pi" "π")
 ("Pi" "Π")
 ("rho" "ρ")
 ("Rho" "Ρ")
 ("sigma" "σ")
 ("Sigma" "Σ")
 ("tau" "τ")
 ("Tau" "Τ")
 ("upsilon" "υ")
 ("Upsilon" "Υ")
 ("phi" "φ")
 ("Phi" "Φ")
 ("chi" "χ")
 ("Chi" "Χ")
 ("psi" "ψ")
 ("Psi" "Ψ")
 ("omega" "ω")
 ("Omega" "Ω")
 ("digamma" "ϝ")
 ("Digamma" "Ϝ")
 ("san" "ϻ")
 ("San" "Ϻ")
 ("qoppa" "ϙ")
 ("Qoppa" "Ϙ")
 ("sampi" "ϡ")
 ("Sampi" "Ϡ")
 ("stigma" "ϛ")
 ("Stigma" "Ϛ")
 ("heta" "ͱ")
 ("Heta" "Ͱ")
 ("sho" "ϸ")
 ("Sho" "Ϸ")
 ("|A|" "𝔸")
 ("|B|" "𝔹")
 ("|C|" "ℂ")
 ("|D|" "𝔻")
 ("|E|" "𝔼")
 ("|F|" "𝔽")
 ("|G|" "𝔾")
 ("|H|" "ℍ")
 ("|I|" "𝕀")
 ("|J|" "𝕁")
 ("|K|" "𝕂")
 ("|L|" "𝕃")
 ("|M|" "𝕄")
 ("|N|" "ℕ")
 ("|O|" "𝕆")
 ("|P|" "ℙ")
 ("|Q|" "ℚ")
 ("|R|" "ℝ")
 ("|S|" "𝕊")
 ("|T|" "𝕋")
 ("|U|" "𝕌")
 ("|V|" "𝕍")
 ("|W|" "𝕎")
 ("|X|" "𝕏")
 ("|Y|" "𝕐")
 ("|Z|" "ℤ")
 ("|gamma|" "ℽ")
 ("|Gamma|" "ℾ")
 ("|pi|" "ℼ")
 ("|Pi|" "ℿ")
 ("forall" "∀")
 ("exists" "∃")
 ("_0" "₀")
 ("_1" "₁")
 ("_2" "₂")
 ("_3" "₃")
 ("_4" "₄")
 ("_5" "₅")
 ("_6" "₆")
 ("_7" "₇")
 ("_8" "₈")
 ("_9" "₉")
 ("^0" "⁰")
 ("^1" "¹")
 ("^2" "²")
 ("^3" "³")
 ("^4" "⁴")
 ("^5" "⁵")
 ("^6" "⁶")
 ("^7" "⁷")
 ("^8" "⁸")
 ("^9" "⁹"))
</pre></dd>
<dt>racket-logger-config</dt><dd><pre>((racket-hash-lang-mode . debug)
 (racket-mode . debug)
 (cm-accomplice . warning)
 (GC . info)
 (module-prefetch . warning)
 (optimizer . info)
 (racket/contract . error)
 (racket-mode-debugger . info)
 (sequence-specialization . info)
 (* . fatal))
</pre></dd>
<dt>racket-memory-limit</dt><dd><pre>2048</pre></dd>
<dt>racket-mode-hook</dt><dd><pre>(racket-xp-mode)
</pre></dd>
<dt>racket-module-forms</dt><dd><pre>"\\s(\\(?:module[*+]?\\|library\\)"</pre></dd>
<dt>racket-pretty-lambda</dt><dd><pre>nil</pre></dd>
<dt>racket-pretty-print</dt><dd><pre>t</pre></dd>
<dt>racket-program</dt><dd><pre>"~/bin/racket"</pre></dd>
<dt>racket-repl-buffer-name-function</dt><dd><pre>nil</pre></dd>
<dt>racket-repl-command-file</dt><dd><pre>"/home/samth/.emacs.d/racket-mode/repl.rkt"</pre></dd>
<dt>racket-repl-history-directory</dt><dd><pre>"~/.emacs.d/racket-mode/"</pre></dd>
<dt>racket-repl-mode-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-sexp-comment-fade</dt><dd><pre>0.5</pre></dd>
<dt>racket-shell-or-terminal-function</dt><dd><pre>racket-shell</pre></dd>
<dt>racket-show-functions</dt><dd><pre>(racket-show-pseudo-tooltip)
</pre></dd>
<dt>racket-smart-open-bracket-enable</dt><dd><pre>nil</pre></dd>
<dt>racket-submodules-to-run</dt><dd><pre>((test)
 (main))
</pre></dd>
<dt>racket-use-repl-submit-predicate</dt><dd><pre>nil</pre></dd>
<dt>racket-xp-add-binding-faces</dt><dd><pre>t</pre></dd>
<dt>racket-xp-after-change-refresh-delay</dt><dd><pre>1</pre></dd>
<dt>racket-xp-highlight-unused-regexp</dt><dd><pre>"^[^_]"</pre></dd>
<dt>racket-xp-mode-lighter</dt><dd><pre>(:eval
 (racket--xp-mode-lighter))
</pre></dd>
</dl>
<h2>Minor modes</h2>
<dl>
<dt>enabled</dt><dd><pre>((auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (blink-cursor-mode)
 (eldoc-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (global-paren-face-mode)
 (indent-tabs-mode)
 (line-number-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (override-global-mode)
 (racket-xp-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (tooltip-mode)
 (transient-mark-mode))
</pre></dd>
<details><summary>Disabled minor modes</summary>
<dt>disabled</dt><dd><pre>((abbrev-mode)
 (auto-fill-function)
 (auto-fill-mode)
 (auto-save-mode)
 (auto-save-visited-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (button-mode)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (comint-fontify-input-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (context-menu-mode)
 (cursor-face-highlight-mode)
 (defining-kbd-macro)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (electric-indent-mode)
 (electric-layout-mode)
 (electric-pair-mode)
 (electric-quote-mode)
 (global-prettify-symbols-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (horizontal-scroll-bar-mode)
 (hs-minor-mode)
 (isearch-fold-quotes-mode)
 (isearch-mode)
 (jit-lock-debug-mode)
 (lock-file-mode)
 (lost-selection-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (paren-face-mode)
 (prettify-symbols-mode)
 (racket-hash-lang-repl-mode)
 (racket-input-mode)
 (racket-smart-open-bracket-mode)
 (read-extended-command-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (sh-electric-here-document-mode)
 (shell-highlight-undef-mode)
 (size-indication-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (treesit-explore-mode)
 (treesit-inspect-mode)
 (undelete-frame-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-dir-git-mode)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode)
 (xref-etags-mode))
</pre></dd>
</details>
</dl>
</details>

**Comment by greghendershott** [comment]
I can reproduce the "user-error" -- and I have a fix that, instead `signal`-ing a `scan-error`.

But I haven't been able to reproduce any hangs/delays, so far.

I might go ahead and merge that change to "close" this... but in that case of course feel free to comment or re-open it if you're still seeing hangs.

**Comment by samth** [comment]
I get the hangs particularly when the lexer errors. See https://github.com/racket/rhombus/issues/573 for related info.
