### ISSUE TITLE
Can't display outline shape correctly.

### ISSUE THREAD

**Issue by uyweywe** [greghendershott/racket-mode#727]
Emacs version:29.4
Racket version:8.15
OS:linux
I've tried changing the display protocol to x11, but to no avail! geiser looks to have the same problem.I have tried using vanilla Emacs with no other packages,but it didn't works.
![screenshot_20241112_110851](https://github.com/user-attachments/assets/f1a11857-d879-47aa-94af-f146a17f028b)
![screenshot_20241112_110929](https://github.com/user-attachments/assets/390ae89d-c6a6-4f6c-b485-0a6cde353e39)
This is actual image file.
![racket-image-17313799731731379973840](https://github.com/user-attachments/assets/85beb7d5-71b9-40f6-b734-a5d87b7a9178)

**Comment by greghendershott** [comment]
Thanks for reporting!

I can reproduce this.

Fortunately it looks like there are newer [file/convertible](https://docs.racket-lang.org/file/convertible.html) formats -- `'png-bytes+bounds8` and `'svg-bytes+bounds8` -- which fix this for me. I'll merge after CI tests finish.
