### ISSUE TITLE
racket-sexp-comment-fade not working

### ISSUE THREAD

**Issue by mateidragony** [greghendershott/racket-mode#729]
<details>
<h2>Package</h2>
<dl>
<dt>metadata</dt><dd><pre>(#s(package-desc racket-mode
		 (20241116 1700)
		 "Racket editing, REPL, and more."
		 ((emacs
		   (25 1)))
		 nil nil "/home/mateidragony/.emacs.d/elpa/racket-mode-20241116.1700"
		 ((:authors
		   ("Greg Hendershott" . "racket-mode-author@greghendershott.com"))
		  (:revdesc . "c5bee6895b2d")
		  (:commit . "c5bee6895b2d028820a75356abacc19a5ed11918")
		  (:url . "https://github.com/greghendershott/racket-mode"))
		 nil))
</pre></dd>
<dt>package-archives</dt><dd><pre>(("gnu-devel" . "https://elpa.gnu.org/devel/")
 ("melpa-stable" . "https://stable.melpa.org/packages/")
 ("gnu" . "https://elpa.gnu.org/packages/")
 ("nongnu" . "https://elpa.nongnu.org/nongnu/")
 ("melpa" . "https://melpa.org/packages/"))
</pre></dd>
<dt>racket--el-source-dir</dt><dd><pre>"/home/mateidragony/.emacs.d/elpa/racket-mode-20241116.1700/"</pre></dd>
<dt>racket--rkt-source-dir</dt><dd><pre>"/home/mateidragony/.emacs.d/elpa/racket-mode-20241116.1700/racket/"</pre></dd>
</dl>
<h2>System values</h2>
<dl>
<dt>emacs-version</dt><dd><pre>"29.4"</pre></dd>
<dt>major-mode</dt><dd><pre>racket-mode</pre></dd>
<dt>system-type</dt><dd><pre>gnu/linux</pre></dd>
<dt>x-gtk-use-system-tooltips</dt><dd><pre>t</pre></dd>
<dt>display-graphic-p</dt><dd><pre>nil</pre></dd>
</dl>
<h2>Buffer values</h2>
<dl>
<dt>after-change-functions</dt><dd><pre>(jit-lock-after-change t)
</pre></dd>
<dt>before-change-functions</dt><dd><pre>(t syntax-ppss-flush-cache)
</pre></dd>
<dt>completion-at-point-functions</dt><dd><pre>(racket-complete-at-point)
</pre></dd>
<dt>eldoc-documentation-function</dt><dd><pre>eldoc-documentation-default</pre></dd>
<dt>eldoc-documentation-strategy</dt><dd><pre>eldoc-documentation-default</pre></dd>
<dt>eldoc-documentation-functions</dt><dd><pre>nil</pre></dd>
<dt>font-lock-defaults</dt><dd><pre>((racket-font-lock-keywords-level-0 racket-font-lock-keywords-level-1 racket-font-lock-keywords-level-2 racket-font-lock-keywords-level-3)
 nil nil nil nil
 (font-lock-mark-block-function . mark-defun)
 (parse-sexp-lookup-properties . t)
 (font-lock-multiline . t)
 (font-lock-syntactic-face-function . racket-font-lock-syntactic-face-function)
 (font-lock-extend-region-functions font-lock-extend-region-wholelines font-lock-extend-region-multiline))
</pre></dd>
<dt>pre-command-hook</dt><dd><pre>(tooltip-hide)
</pre></dd>
<dt>post-command-hook</dt><dd><pre>(jit-lock--antiblink-post-command t)
</pre></dd>
<dt>post-self-insert-hook</dt><dd><pre>(electric-pair-post-self-insert-function electric-pair-open-newline-between-pairs-psif electric-indent-post-self-insert-function blink-paren-post-self-insert-function)
</pre></dd>
<dt>xref-backend-functions</dt><dd><pre>(racket-mode-xref-backend-function t)
</pre></dd>
</dl>
<h2>Racket Mode values</h2>
<dl>
<dt>racket--cmd-open-p</dt><dd><pre>t</pre></dd>
<dt>racket-after-run-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-back-end-configurations</dt><dd><pre>((:directory "/" :racket-program nil :remote-source-dir nil :restart-watch-directories nil :windows nil))
</pre></dd>
<dt>racket-before-run-hook</dt><dd><pre>(racket-ansi-color-context-reset)
</pre></dd>
<dt>racket-browse-url-function</dt><dd><pre>browse-url-default-browser</pre></dd>
<dt>racket-command-timeout</dt><dd><pre>10</pre></dd>
<dt>racket-doc-index-directory</dt><dd><pre>"~/.emacs.d/racket-mode/"</pre></dd>
<dt>racket-doc-index-predicate-function</dt><dd><pre>always</pre></dd>
<dt>racket-documentation-search-location</dt><dd><pre>"https://docs.racket-lang.org/search/index.html?q=%s"</pre></dd>
<dt>racket-error-context</dt><dd><pre>medium</pre></dd>
<dt>racket-expand-hiding</dt><dd><pre>standard</pre></dd>
<dt>racket-hash-lang-token-face-alist</dt><dd><pre>((constant . font-lock-constant-face)
 (error . error)
 (other . font-lock-doc-face)
 (keyword . font-lock-keyword-face)
 (hash-colon-keyword . racket-keyword-argument-face)
 (at . font-lock-doc-face))
</pre></dd>
<dt>racket-history-filter-regexp</dt><dd><pre>"\\`\\s *\\'"</pre></dd>
<dt>racket-imagemagick-props</dt><dd><pre>nil</pre></dd>
<dt>racket-images-do-not-use-svg</dt><dd><pre>nil</pre></dd>
<dt>racket-images-inline</dt><dd><pre>t</pre></dd>
<dt>racket-images-keep-last</dt><dd><pre>100</pre></dd>
<dt>racket-images-system-viewer</dt><dd><pre>"display"</pre></dd>
<dt>racket-indent-curly-as-sequence</dt><dd><pre>t</pre></dd>
<dt>racket-indent-sequence-depth</dt><dd><pre>0</pre></dd>
<dt>racket-input-prefix</dt><dd><pre>"\\"</pre></dd>
<dt>racket-input-translations</dt><dd><pre>(("All" "∀")
 ("Union" "U")
 ("Intersection" "∩")
 ("test-->>E" "test-->>∃")
 ("vdash" "⊢")
 ("gg" "≫")
 ("succ" "≻")
 ("times" "×")
 ("Uparrow" "⇑")
 ("Downarrow" "⇓")
 ("Leftarrow" "⇐")
 ("Rightarrow" "⇒")
 ("leftarrow" "←")
 ("rightarrow" "→")
 ("nwarrow" "↖")
 ("nearrow" "↗")
 ("uparrow" "↑")
 ("downarrow" "↓")
 ("searrow" "↘")
 ("swarrow" "↙")
 ("leftrightarrow" "↔")
 ("updownarrow" "⇕")
 ("aleph" "א")
 ("emptyset" "∅")
 ("nabla" "∇")
 ("surd" "√")
 ("negation" "¬")
 ("infinity" "∞")
 ("prod" "∏")
 ("coprod" "∐")
 ("integrate" "∫")
 ("oint" "∮")
 ("vee" "∨")
 ("wedge" "∧")
 ("follows" "∘")
 ("setin" "∈")
 ("ni" "∋")
 ("notin" "∉")
 ("sqsubset" "⊏")
 ("sqsupset" "⊐")
 ("sqsubseteq" "⊑")
 ("sqsupseteq" "⊒")
 ("subset" "⊂")
 ("superset" "⊃")
 ("subseteq" "⊆")
 ("supseteq" "⊇")
 ("approx" "≈")
 ("cong" "≌")
 ("neq" "≠")
 ("sqcap" "⊓")
 ("sqcup" "⊔")
 ("models" "⊧")
 ("alpha" "α")
 ("Alpha" "Α")
 ("beta" "β")
 ("Beta" "Β")
 ("gamma" "γ")
 ("Gamma" "Γ")
 ("delta" "δ")
 ("Delta" "Δ")
 ("epsilon" "ε")
 ("Epsilon" "Ε")
 ("zeta" "ζ")
 ("Zeta" "Ζ")
 ("eta" "η")
 ("Eta" "Η")
 ("theta" "θ")
 ("Theta" "Θ")
 ("iota" "ι")
 ("Iota" "Ι")
 ("kappa" "κ")
 ("Kappa" "Κ")
 ("lambda" "λ")
 ("Lambda" "Λ")
 ("lamda" "λ")
 ("Lamda" "Λ")
 ("mu" "μ")
 ("Mu" "Μ")
 ("nu" "ν")
 ("Nu" "Ν")
 ("xi" "ξ")
 ("Xi" "Ξ")
 ("omicron" "ο")
 ("Omicron" "Ο")
 ("pi" "π")
 ("Pi" "Π")
 ("rho" "ρ")
 ("Rho" "Ρ")
 ("sigma" "σ")
 ("Sigma" "Σ")
 ("tau" "τ")
 ("Tau" "Τ")
 ("upsilon" "υ")
 ("Upsilon" "Υ")
 ("phi" "φ")
 ("Phi" "Φ")
 ("chi" "χ")
 ("Chi" "Χ")
 ("psi" "ψ")
 ("Psi" "Ψ")
 ("omega" "ω")
 ("Omega" "Ω")
 ("digamma" "ϝ")
 ("Digamma" "Ϝ")
 ("san" "ϻ")
 ("San" "Ϻ")
 ("qoppa" "ϙ")
 ("Qoppa" "Ϙ")
 ("sampi" "ϡ")
 ("Sampi" "Ϡ")
 ("stigma" "ϛ")
 ("Stigma" "Ϛ")
 ("heta" "ͱ")
 ("Heta" "Ͱ")
 ("sho" "ϸ")
 ("Sho" "Ϸ")
 ("|A|" "𝔸")
 ("|B|" "𝔹")
 ("|C|" "ℂ")
 ("|D|" "𝔻")
 ("|E|" "𝔼")
 ("|F|" "𝔽")
 ("|G|" "𝔾")
 ("|H|" "ℍ")
 ("|I|" "𝕀")
 ("|J|" "𝕁")
 ("|K|" "𝕂")
 ("|L|" "𝕃")
 ("|M|" "𝕄")
 ("|N|" "ℕ")
 ("|O|" "𝕆")
 ("|P|" "ℙ")
 ("|Q|" "ℚ")
 ("|R|" "ℝ")
 ("|S|" "𝕊")
 ("|T|" "𝕋")
 ("|U|" "𝕌")
 ("|V|" "𝕍")
 ("|W|" "𝕎")
 ("|X|" "𝕏")
 ("|Y|" "𝕐")
 ("|Z|" "ℤ")
 ("|gamma|" "ℽ")
 ("|Gamma|" "ℾ")
 ("|pi|" "ℼ")
 ("|Pi|" "ℿ")
 ("forall" "∀")
 ("exists" "∃")
 ("_0" "₀")
 ("_1" "₁")
 ("_2" "₂")
 ("_3" "₃")
 ("_4" "₄")
 ("_5" "₅")
 ("_6" "₆")
 ("_7" "₇")
 ("_8" "₈")
 ("_9" "₉")
 ("^0" "⁰")
 ("^1" "¹")
 ("^2" "²")
 ("^3" "³")
 ("^4" "⁴")
 ("^5" "⁵")
 ("^6" "⁶")
 ("^7" "⁷")
 ("^8" "⁸")
 ("^9" "⁹"))
</pre></dd>
<dt>racket-logger-config</dt><dd><pre>((cm-accomplice . warning)
 (GC . info)
 (module-prefetch . warning)
 (optimizer . info)
 (racket/contract . error)
 (racket-mode-debugger . info)
 (sequence-specialization . info)
 (* . fatal))
</pre></dd>
<dt>racket-memory-limit</dt><dd><pre>2048</pre></dd>
<dt>racket-mode-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-module-forms</dt><dd><pre>"\\s(\\(?:module[*+]?\\|library\\)"</pre></dd>
<dt>racket-pretty-lambda</dt><dd><pre>nil</pre></dd>
<dt>racket-pretty-print</dt><dd><pre>t</pre></dd>
<dt>racket-program</dt><dd><pre>"racket"</pre></dd>
<dt>racket-repl-buffer-name-function</dt><dd><pre>nil</pre></dd>
<dt>racket-repl-command-file</dt><dd><pre>"/home/mateidragony/.emacs.d/racket-mode/repl.rkt"</pre></dd>
<dt>racket-repl-history-directory</dt><dd><pre>"~/.emacs.d/racket-mode/"</pre></dd>
<dt>racket-repl-mode-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-sexp-comment-fade</dt><dd><pre>0.5</pre></dd>
<dt>racket-shell-or-terminal-function</dt><dd><pre>racket-shell</pre></dd>
<dt>racket-show-functions</dt><dd><pre>(racket-show-pseudo-tooltip)
</pre></dd>
<dt>racket-smart-open-bracket-enable</dt><dd><pre>nil</pre></dd>
<dt>racket-submodules-to-run</dt><dd><pre>((test)
 (main))
</pre></dd>
<dt>racket-use-repl-submit-predicate</dt><dd><pre>nil</pre></dd>
<dt>racket-xp-add-binding-faces</dt><dd><pre>nil</pre></dd>
<dt>racket-xp-after-change-refresh-delay</dt><dd><pre>1</pre></dd>
<dt>racket-xp-eldoc-level</dt><dd><pre>summary</pre></dd>
<dt>racket-xp-highlight-unused-regexp</dt><dd><pre>"^[^_]"</pre></dd>
<dt>racket-xp-mode-lighter</dt><dd><pre>(:eval
 (racket--xp-mode-lighter))
</pre></dd>
</dl>
<h2>Minor modes</h2>
<dl>
<dt>enabled</dt><dd><pre>((auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (blink-cursor-mode)
 (display-line-numbers-mode)
 (electric-indent-mode)
 (electric-pair-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-display-line-numbers-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (line-number-mode)
 (mouse-wheel-mode)
 (override-global-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-mark-mode))
</pre></dd>
<details><summary>Disabled minor modes</summary>
<dt>disabled</dt><dd><pre>((abbrev-mode)
 (archive-subfile-mode)
 (auto-fill-function)
 (auto-fill-mode)
 (auto-save-mode)
 (auto-save-visited-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (button-mode)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (comint-fontify-input-mode)
 (company-mode)
 (company-search-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (context-menu-mode)
 (cursor-face-highlight-mode)
 (dash-fontify-mode)
 (defining-kbd-macro)
 (dired-hide-details-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-quote-mode)
 (global-company-mode)
 (global-dash-fontify-mode)
 (global-prettify-symbols-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (header-line-indent-mode)
 (horizontal-scroll-bar-mode)
 (hs-minor-mode)
 (indent-tabs-mode)
 (irony-mode)
 (isearch-fold-quotes-mode)
 (isearch-mode)
 (jit-lock-debug-mode)
 (lock-file-mode)
 (lost-selection-mode)
 (mail-abbrevs-mode)
 (menu-bar-mode)
 (mml-mode)
 (next-error-follow-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-input-mode)
 (racket-smart-open-bracket-mode)
 (racket-xp-mode)
 (rainbow-delimiters-mode)
 (read-extended-command-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (sh-electric-here-document-mode)
 (shell-highlight-undef-mode)
 (size-indication-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (tar-subfile-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (treesit-explore-mode)
 (treesit-inspect-mode)
 (undelete-frame-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode)
 (xref-etags-mode))
</pre></dd>
</details>
</dl>
</details>

Steps to reproduce: 

Type this program

```#; (+ 1 2)```

The sexp does not fade due to the comment like it used to. 

![image](https://github.com/user-attachments/assets/21414891-679f-4ae2-975f-18deffe4cde6)

**Comment by mateidragony** [comment]
For those interested, fading wasn't working due to my emacs background being clear

**Comment by greghendershott** [comment]
Oh that's an interesting case I hadn't considered.

If you `M-x describe-face` and enter `default`, what are the face properties?

If `Background` is something like `nil`, I wonder if an effective fallback plan would be to blend the colors with black, instead?

**Comment by greghendershott** [comment]
I tried to figure out a bit more, on my own.

I notice starting in Emacs 29 there's a new `alpha-background` frame parameter.

When I `M-x eval` and enter `(set-frame-parameter nil 'alpha-background 0)`, sexp comment fading still works. (Maybe because my theme still has a dark background for the `default` font, I'm not sure.)

So I'd be grateful if you have time to supply more details so I can reproduce.

**Comment by mateidragony** [comment]
Yeah, so my theme just doesn't set `default` background, so its value is `unspecified-bg`. The alpha-background thing doesn't seem to do anything to make my background clear though....
