### ISSUE TITLE
/ call, with #lang htdp/bsl set, that returns a decimal errors on attempt to write to REPL

### ISSUE THREAD

**Issue by mbatson** [greghendershott/racket-mode#732]
For example, with `#lang htdp/bsl`, calling `(/ 1 3)` prints a blank line to the Racket REPL and gives the following error message:

`{racket-back-end-/-stderr} elisp-write can't write Racket value #(struct:number-markup 1/3 never always decimal)`

This occurs whether `(/ 1 3)` is called:
- From a racket-mode buffer with `racket-run-and-switch-to-repl`.
- From a racket-mode buffer with `racket-run-module-at-point`.
- From the REPL itself.

This seems to occur with any combination of arguments to `/` that result in a decimal number being returned, e.g., `(/ 5 2)`. 

It does **not** occur (meaning the return value prints to the REPL as expected with no error message) if `/` returns an integer, e.g., `(/ 10 2)`.

It does not occur if the return value of `/` is not printed to the REPL, e.g., `(exact? (/ 1 3))` returns `#true` and prints this to the REPL as expected.

I've also tested this in an `emacs -Q` session, only installing `racket-mode`: same result.

---

Here is the result of calling `racket-bug-report` (this was run while I was in an `emacs -Q` session. If you'd like me to re-run it in my normal Emacs state, just let me know):

<details>
<h2>Package</h2>
<dl>
<dt>metadata</dt><dd><pre>(#s(package-desc racket-mode
		 (1 0 20241129 85359)
		 "Racket editing, REPL, and more"
		 ((emacs
		   (25 1)))
		 nil nil "c:/Users/mbats/.emacs.d/elpa/racket-mode-1.0.20241129.85359"
		 ((:url . "https://www.racket-mode.com/")
		  (:authors
		   ("Greg Hendershott" . "racket-mode-author@greghendershott.com"))
		  (:commit . "HEAD"))
		 nil))
</pre></dd>
<dt>package-archives</dt><dd><pre>(("gnu" . "https://elpa.gnu.org/packages/")
 ("nongnu" . "https://elpa.nongnu.org/nongnu/"))
</pre></dd>
<dt>racket--el-source-dir</dt><dd><pre>"c:/Users/mbats/.emacs.d/elpa/racket-mode-1.0.20241129.85359/"</pre></dd>
<dt>racket--rkt-source-dir</dt><dd><pre>"c:/Users/mbats/.emacs.d/elpa/racket-mode-1.0.20241129.85359/racket/"</pre></dd>
</dl>
<h2>System values</h2>
<dl>
<dt>emacs-version</dt><dd><pre>"29.4"</pre></dd>
<dt>major-mode</dt><dd><pre>racket-mode</pre></dd>
<dt>system-type</dt><dd><pre>windows-nt</pre></dd>
<dt>display-graphic-p</dt><dd><pre>t</pre></dd>
</dl>
<h2>Buffer values</h2>
<dl>
<dt>after-change-functions</dt><dd><pre>(jit-lock-after-change t racket--xp-after-change-hook)
</pre></dd>
<dt>before-change-functions</dt><dd><pre>(t syntax-ppss-flush-cache)
</pre></dd>
<dt>completion-at-point-functions</dt><dd><pre>(racket-xp-complete-at-point)
</pre></dd>
<dt>eldoc-documentation-function</dt><dd><pre>eldoc-documentation-default</pre></dd>
<dt>eldoc-documentation-strategy</dt><dd><pre>eldoc-documentation-default</pre></dd>
<dt>eldoc-documentation-functions</dt><dd><pre>(racket-xp-eldoc-point racket-xp-eldoc-sexp-app t)
</pre></dd>
<dt>font-lock-defaults</dt><dd><pre>((racket-font-lock-keywords-level-0 racket-font-lock-keywords-level-1 racket-font-lock-keywords-level-2 racket-font-lock-keywords-level-3)
 nil nil nil nil
 (font-lock-mark-block-function . mark-defun)
 (parse-sexp-lookup-properties . t)
 (font-lock-multiline . t)
 (font-lock-syntactic-face-function . racket-font-lock-syntactic-face-function)
 (font-lock-extend-region-functions font-lock-extend-region-wholelines font-lock-extend-region-multiline))
</pre></dd>
<dt>pre-command-hook</dt><dd><pre>(eldoc-pre-command-refresh-echo-area t)
</pre></dd>
<dt>post-command-hook</dt><dd><pre>(jit-lock--antiblink-post-command eldoc-schedule-timer t)
</pre></dd>
<dt>post-self-insert-hook</dt><dd><pre>(electric-indent-post-self-insert-function blink-paren-post-self-insert-function)
</pre></dd>
<dt>xref-backend-functions</dt><dd><pre>(racket-xp-xref-backend-function racket-mode-xref-backend-function t)
</pre></dd>
</dl>
<h2>Racket Mode values</h2>
<dl>
<dt>racket--cmd-open-p</dt><dd><pre>t</pre></dd>
<dt>racket-after-run-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-back-end-configurations</dt><dd><pre>((:directory "/" :racket-program nil :remote-source-dir nil :restart-watch-directories nil :windows t))
</pre></dd>
<dt>racket-before-run-hook</dt><dd><pre>(racket-ansi-color-context-reset)
</pre></dd>
<dt>racket-browse-url-function</dt><dd><pre>browse-url-default-browser</pre></dd>
<dt>racket-command-timeout</dt><dd><pre>10</pre></dd>
<dt>racket-doc-index-directory</dt><dd><pre>"~/.emacs.d/racket-mode/"</pre></dd>
<dt>racket-doc-index-predicate-function</dt><dd><pre>always</pre></dd>
<dt>racket-documentation-search-location</dt><dd><pre>"https://docs.racket-lang.org/search/index.html?q=%s"</pre></dd>
<dt>racket-error-context</dt><dd><pre>medium</pre></dd>
<dt>racket-expand-hiding</dt><dd><pre>standard</pre></dd>
<dt>racket-hash-lang-mode-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-hash-lang-module-language-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-hash-lang-token-face-alist</dt><dd><pre>((constant . font-lock-constant-face)
 (error . error)
 (other . font-lock-doc-face)
 (keyword . font-lock-keyword-face)
 (hash-colon-keyword . racket-keyword-argument-face)
 (at . font-lock-doc-face))
</pre></dd>
<dt>racket-history-filter-regexp</dt><dd><pre>"\\`\\s *\\'"</pre></dd>
<dt>racket-imagemagick-props</dt><dd><pre>nil</pre></dd>
<dt>racket-images-do-not-use-svg</dt><dd><pre>nil</pre></dd>
<dt>racket-images-inline</dt><dd><pre>t</pre></dd>
<dt>racket-images-keep-last</dt><dd><pre>100</pre></dd>
<dt>racket-images-system-viewer</dt><dd><pre>"display"</pre></dd>
<dt>racket-indent-curly-as-sequence</dt><dd><pre>t</pre></dd>
<dt>racket-indent-sequence-depth</dt><dd><pre>0</pre></dd>
<dt>racket-input-prefix</dt><dd><pre>"\\"</pre></dd>
<dt>racket-input-translations</dt><dd><pre>(("All" "∀")
 ("Union" "U")
 ("Intersection" "∩")
 ("test-->>E" "test-->>∃")
 ("vdash" "⊢")
 ("gg" "≫")
 ("succ" "≻")
 ("times" "×")
 ("Uparrow" "⇑")
 ("Downarrow" "⇓")
 ("Leftarrow" "⇐")
 ("Rightarrow" "⇒")
 ("leftarrow" "←")
 ("rightarrow" "→")
 ("nwarrow" "↖")
 ("nearrow" "↗")
 ("uparrow" "↑")
 ("downarrow" "↓")
 ("searrow" "↘")
 ("swarrow" "↙")
 ("leftrightarrow" "↔")
 ("updownarrow" "⇕")
 ("aleph" "א")
 ("emptyset" "∅")
 ("nabla" "∇")
 ("surd" "√")
 ("negation" "¬")
 ("infinity" "∞")
 ("prod" "∏")
 ("coprod" "∐")
 ("integrate" "∫")
 ("oint" "∮")
 ("vee" "∨")
 ("wedge" "∧")
 ("follows" "∘")
 ("setin" "∈")
 ("ni" "∋")
 ("notin" "∉")
 ("sqsubset" "⊏")
 ("sqsupset" "⊐")
 ("sqsubseteq" "⊑")
 ("sqsupseteq" "⊒")
 ("subset" "⊂")
 ("superset" "⊃")
 ("subseteq" "⊆")
 ("supseteq" "⊇")
 ("approx" "≈")
 ("cong" "≌")
 ("neq" "≠")
 ("sqcap" "⊓")
 ("sqcup" "⊔")
 ("models" "⊧")
 ("alpha" "α")
 ("Alpha" "Α")
 ("beta" "β")
 ("Beta" "Β")
 ("gamma" "γ")
 ("Gamma" "Γ")
 ("delta" "δ")
 ("Delta" "Δ")
 ("epsilon" "ε")
 ("Epsilon" "Ε")
 ("zeta" "ζ")
 ("Zeta" "Ζ")
 ("eta" "η")
 ("Eta" "Η")
 ("theta" "θ")
 ("Theta" "Θ")
 ("iota" "ι")
 ("Iota" "Ι")
 ("kappa" "κ")
 ("Kappa" "Κ")
 ("lambda" "λ")
 ("Lambda" "Λ")
 ("lamda" "λ")
 ("Lamda" "Λ")
 ("mu" "μ")
 ("Mu" "Μ")
 ("nu" "ν")
 ("Nu" "Ν")
 ("xi" "ξ")
 ("Xi" "Ξ")
 ("omicron" "ο")
 ("Omicron" "Ο")
 ("pi" "π")
 ("Pi" "Π")
 ("rho" "ρ")
 ("Rho" "Ρ")
 ("sigma" "σ")
 ("Sigma" "Σ")
 ("tau" "τ")
 ("Tau" "Τ")
 ("upsilon" "υ")
 ("Upsilon" "Υ")
 ("phi" "φ")
 ("Phi" "Φ")
 ("chi" "χ")
 ("Chi" "Χ")
 ("psi" "ψ")
 ("Psi" "Ψ")
 ("omega" "ω")
 ("Omega" "Ω")
 ("digamma" "ϝ")
 ("Digamma" "Ϝ")
 ("san" "ϻ")
 ("San" "Ϻ")
 ("qoppa" "ϙ")
 ("Qoppa" "Ϙ")
 ("sampi" "ϡ")
 ("Sampi" "Ϡ")
 ("stigma" "ϛ")
 ("Stigma" "Ϛ")
 ("heta" "ͱ")
 ("Heta" "Ͱ")
 ("sho" "ϸ")
 ("Sho" "Ϸ")
 ("|A|" "𝔸")
 ("|B|" "𝔹")
 ("|C|" "ℂ")
 ("|D|" "𝔻")
 ("|E|" "𝔼")
 ("|F|" "𝔽")
 ("|G|" "𝔾")
 ("|H|" "ℍ")
 ("|I|" "𝕀")
 ("|J|" "𝕁")
 ("|K|" "𝕂")
 ("|L|" "𝕃")
 ("|M|" "𝕄")
 ("|N|" "ℕ")
 ("|O|" "𝕆")
 ("|P|" "ℙ")
 ("|Q|" "ℚ")
 ("|R|" "ℝ")
 ("|S|" "𝕊")
 ("|T|" "𝕋")
 ("|U|" "𝕌")
 ("|V|" "𝕍")
 ("|W|" "𝕎")
 ("|X|" "𝕏")
 ("|Y|" "𝕐")
 ("|Z|" "ℤ")
 ("|gamma|" "ℽ")
 ("|Gamma|" "ℾ")
 ("|pi|" "ℼ")
 ("|Pi|" "ℿ")
 ("forall" "∀")
 ("exists" "∃")
 ("_0" "₀")
 ("_1" "₁")
 ("_2" "₂")
 ("_3" "₃")
 ("_4" "₄")
 ("_5" "₅")
 ("_6" "₆")
 ("_7" "₇")
 ("_8" "₈")
 ("_9" "₉")
 ("^0" "⁰")
 ("^1" "¹")
 ("^2" "²")
 ("^3" "³")
 ("^4" "⁴")
 ("^5" "⁵")
 ("^6" "⁶")
 ("^7" "⁷")
 ("^8" "⁸")
 ("^9" "⁹"))
</pre></dd>
<dt>racket-logger-config</dt><dd><pre>((cm-accomplice . warning)
 (GC . info)
 (module-prefetch . warning)
 (optimizer . info)
 (racket/contract . error)
 (racket-mode-debugger . info)
 (sequence-specialization . info)
 (* . fatal))
</pre></dd>
<dt>racket-memory-limit</dt><dd><pre>2048</pre></dd>
<dt>racket-mode-hook</dt><dd><pre>(racket-xp-mode)
</pre></dd>
<dt>racket-module-forms</dt><dd><pre>"\\s(\\(?:module[*+]?\\|library\\)"</pre></dd>
<dt>racket-pretty-lambda</dt><dd><pre>nil</pre></dd>
<dt>racket-pretty-print</dt><dd><pre>t</pre></dd>
<dt>racket-program</dt><dd><pre>"Racket.exe"</pre></dd>
<dt>racket-repl-buffer-name-function</dt><dd><pre>nil</pre></dd>
<dt>racket-repl-command-file</dt><dd><pre>"c:/Users/mbats/.emacs.d/racket-mode/repl.rkt"</pre></dd>
<dt>racket-repl-history-directory</dt><dd><pre>"~/.emacs.d/racket-mode/"</pre></dd>
<dt>racket-repl-mode-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-sexp-comment-fade</dt><dd><pre>0.5</pre></dd>
<dt>racket-shell-or-terminal-function</dt><dd><pre>racket-shell</pre></dd>
<dt>racket-show-functions</dt><dd><pre>(racket-show-pseudo-tooltip)
</pre></dd>
<dt>racket-smart-open-bracket-enable</dt><dd><pre>nil</pre></dd>
<dt>racket-submodules-to-run</dt><dd><pre>((test)
 (main))
</pre></dd>
<dt>racket-use-repl-submit-predicate</dt><dd><pre>nil</pre></dd>
<dt>racket-xp-add-binding-faces</dt><dd><pre>nil</pre></dd>
<dt>racket-xp-after-change-refresh-delay</dt><dd><pre>1</pre></dd>
<dt>racket-xp-eldoc-level</dt><dd><pre>summary</pre></dd>
<dt>racket-xp-highlight-unused-regexp</dt><dd><pre>"^[^_]"</pre></dd>
<dt>racket-xp-mode-lighter</dt><dd><pre>(:eval
 (racket--xp-mode-lighter))
</pre></dd>
</dl>
<h2>Minor modes</h2>
<dl>
<dt>enabled</dt><dd><pre>((auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (blink-cursor-mode)
 (eldoc-mode)
 (electric-indent-mode)
 (file-name-shadow-mode)
 (font-lock-mode)
 (global-eldoc-mode)
 (global-font-lock-mode)
 (line-number-mode)
 (menu-bar-mode)
 (mouse-wheel-mode)
 (racket-xp-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-mark-mode))
</pre></dd>
<details><summary>Disabled minor modes</summary>
<dt>disabled</dt><dd><pre>((2C-mode)
 (abbrev-mode)
 (auto-fill-function)
 (auto-fill-mode)
 (auto-save-mode)
 (auto-save-visited-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (button-mode)
 (cl-old-struct-compat-mode)
 (column-number-mode)
 (comint-fontify-input-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (context-menu-mode)
 (cursor-face-highlight-mode)
 (defining-kbd-macro)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (display-line-numbers-mode)
 (electric-layout-mode)
 (electric-pair-mode)
 (electric-quote-mode)
 (global-display-line-numbers-mode)
 (global-prettify-symbols-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (header-line-indent-mode)
 (horizontal-scroll-bar-mode)
 (hs-minor-mode)
 (indent-tabs-mode)
 (isearch-fold-quotes-mode)
 (isearch-mode)
 (jit-lock-debug-mode)
 (lock-file-mode)
 (lost-selection-mode)
 (next-error-follow-minor-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (racket-hash-lang-repl-mode)
 (racket-input-mode)
 (racket-smart-open-bracket-mode)
 (read-extended-command-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (sh-electric-here-document-mode)
 (shell-highlight-undef-mode)
 (size-indication-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (treesit-explore-mode)
 (treesit-inspect-mode)
 (undelete-frame-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-dir-git-mode)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (window-divider-mode)
 (xref-etags-mode))
</pre></dd>
</details>
</dl>
</details>

**Comment by mbatson** [comment]
I've done a little bit more playing around with this, and thought this could be helpful information, so adding it on here:

I'm also getting the same error from calls like:
`(* 3 4.2)` errors with `{racket-back-end-/-stderr} elisp-write can't write Racket value #(struct:number-markup 63/5 never always decimal)`
and
`4.2` errors with `{racket-back-end-/-stderr} elisp-write can't write Racket value #(struct:number-markup 21/5 never always decimal)`

So it seems that possibly there is something going on with decimal fractions being passed as simple fractions to `elisp-write`? I could be totally wrong though as I am completely new to Racket and have no familiarity with how racket-mode works internally with the Racket back-end.

I also forgot to mention that DrRacket prints the return value of all these function calls to the REPL as decimal fractions. And that I don't experience any of these errors in racket-mode calling the same functions using `#lang racket`.

**Comment by greghendershott** [comment]
I can reproduce this.

I think it's because `htdp/bsl` is installing a pretty-print handler that assumes -- too broadly, I think -- that if the output port is capable of `port-writes-specials?`, then it must running under DrRacket.

Therefore it writes these `number-markup` structs instead of printing a string representation like `"1/3"` as would happen with plain printing or a non-specials port:

https://github.com/racket/htdp/blob/aef9ae1c8e4c1e256edde5ab842d20d558202ee2/htdp-lib/htdp/bsl/runtime.rkt#L112-L155

That turns out OK in DrRacket.

But Racket Mode's back end has no idea how to marshal these `number-markup` structs to an Emacs Lisp value, so it barfs.

---

Quick braindump:

- I think one work-around you could do, might be to change the Emacs customization variable `racket-pretty` from `t` to `nil`. (But you might prefer pretty printing, so this isn't a great work-around.)

- I think the ultimate fix would need to come in `htdp/bsl` itself?

- Meanwhile I could try to hack around this by giving it a port for which `port-writes-specials?` returns false. I need such a port to write specials for printing images, but maybe I can do some dance to hide that... ???

- Or maybe I can do what a `snip%` does with these, provided (which seems unlikely) I wouldn't need to depend on `racket/gui`.

**Comment by mbatson** [comment]
Ah I see, thanks for the quick response!

Unfortunately, setting `racket-pretty-print` to `nil` seems to have no effect on this issue on my end.

**Comment by greghendershott** [comment]
Dang. Maybe `htdp/bsl` is unconditionally pretty-printing.

- As a quick hack, it looks like I can make it print `#(struct:number-markup 2/3 never always decimal)` in the Racket Mode REPL. Not ideal, but it reflects the reality of what's happening, and prints _something_ with "2/3" in it. Probably I'll push a commit to do that, until/unless it can be fixed, truly.

- If you're brand new to programming, or teaching people like that, then `htdp/bsl` can be a good choice for "first programmimg language, ever". Otherwise consider using `#lang racket`.

- AFAICT `htdp/bsl` is designed assuming Dr Racket. This makes sense in a classroom with the expectation everyone will use DrR. However over the years I've gotten [various issues](https://github.com/greghendershott/racket-mode/issues?q=label%3Ahtdp%2Fbsl+) using it in Emacs with Racket Mode. Eventually I've been able to resolve most, but not quickly -- many reach into pretty deep assumptions.

**Comment by greghendershott** [comment]
I merged a commit that will print "2/3". Although I still think this is something best changed in `htdp/bsl` itself, I see how to accommodate it, at least in more recent versions of Racket that include the `simple-tree-text-markup` package in `main-dist`. (And in older versions, it will fall back to printing `#(struct:number-markup 2/3 never always decimal)`. But in any case it won't do the originally reported thing of printing a blank line and showing an error message.)

**Comment by mbatson** [comment]
It does make a certain sense that `htdp/bsl` is assuming use of DrRacket, as I imagine the intersection of people using BSL who already have a favoured editor such as Emacs is a very small group. In my own case, I've intermediate experience with programming but lack a formal education, so decided to work through HtDP in order to benefit from its instruction in the area of methodical program design. With that in mind, I'll see how it goes following along with `htdp/bsl` (just so there's less friction between the book's exercises and my solutions), but if I keep running into further issues outside of DrRacket, I'll either just switch to running the code there, or just jump into racket lang itself for completing the book exercises.

Thanks very much for your help and time on this!

**Comment by greghendershott** [comment]
You're welcome!

If you do notice more problems using `htdp/bsl` with Racket Mode, don't hesitate to report them, too.
