### ISSUE TITLE
paredit: Symbol's function definition is void: t

### ISSUE THREAD

**Issue by Bogdanp** [greghendershott/racket-mode#736]
<details>
<h2>Package</h2>
<dl>
<dt>metadata</dt><dd><pre>nil</pre></dd>
<dt>package-archives</dt><dd><pre>(("gnu" . "https://elpa.gnu.org/packages/")
 ("nongnu" . "https://elpa.nongnu.org/nongnu/"))
</pre></dd>
<dt>racket--el-source-dir</dt><dd><pre>"/Users/bogdan/.emacs.d/vendor/racket-mode/"</pre></dd>
<dt>racket--rkt-source-dir</dt><dd><pre>"/Users/bogdan/.emacs.d/vendor/racket-mode/racket/"</pre></dd>
</dl>
<h2>System values</h2>
<dl>
<dt>emacs-version</dt><dd><pre>"29.1"</pre></dd>
<dt>major-mode</dt><dd><pre>racket-mode</pre></dd>
<dt>system-type</dt><dd><pre>darwin</pre></dd>
<dt>display-graphic-p</dt><dd><pre>t</pre></dd>
</dl>
<h2>Buffer values</h2>
<dl>
<dt>after-change-functions</dt><dd><pre>(evil-track-last-insertion jit-lock-after-change flycheck-handle-change t racket--xp-after-change-hook)
</pre></dd>
<dt>before-change-functions</dt><dd><pre>(t syntax-ppss-flush-cache)
</pre></dd>
<dt>completion-at-point-functions</dt><dd><pre>(racket-xp-complete-at-point)
</pre></dd>
<dt>eldoc-documentation-function</dt><dd><pre>eldoc-documentation-default</pre></dd>
<dt>eldoc-documentation-strategy</dt><dd><pre>eldoc-documentation-default</pre></dd>
<dt>eldoc-documentation-functions</dt><dd><pre>(racket-xp-eldoc-point racket-xp-eldoc-sexp-app t)
</pre></dd>
<dt>font-lock-defaults</dt><dd><pre>((racket-font-lock-keywords-level-0 racket-font-lock-keywords-level-1 racket-font-lock-keywords-level-2 racket-font-lock-keywords-level-3)
 nil nil nil nil
 (font-lock-mark-block-function . mark-defun)
 (parse-sexp-lookup-properties . t)
 (font-lock-multiline . t)
 (font-lock-syntactic-face-function . racket-font-lock-syntactic-face-function)
 (font-lock-extend-region-functions font-lock-extend-region-wholelines font-lock-extend-region-multiline))
</pre></dd>
<dt>pre-command-hook</dt><dd><pre>(evil--jump-hook company-pre-command t)
</pre></dd>
<dt>post-command-hook</dt><dd><pre>(jit-lock--antiblink-post-command evil--jump-handle-buffer-crossing company-post-command flycheck-perform-deferred-syntax-check flycheck-error-list-update-source flycheck-error-list-highlight-errors flycheck-display-error-at-point-soon flycheck-hide-error-buffer t)
</pre></dd>
<dt>post-self-insert-hook</dt><dd><pre>(electric-indent-post-self-insert-function blink-paren-post-self-insert-function)
</pre></dd>
<dt>xref-backend-functions</dt><dd><pre>(racket-xp-xref-backend-function racket-mode-xref-backend-function t)
</pre></dd>
</dl>
<h2>Racket Mode values</h2>
<dl>
<dt>racket--cmd-open-p</dt><dd><pre>t</pre></dd>
<dt>racket-after-run-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-back-end-configurations</dt><dd><pre>((:directory "/Users/bogdan/work/Podcatcher/podcatcher-test/" :racket-program "/Users/bogdan/work/Podcatcher/bin/pbracket" :remote-source-dir nil :restart-watch-directories nil :windows nil)
 (:directory "/Users/bogdan/work/Podcatcher/podcatcher-core/" :racket-program "/Users/bogdan/work/Podcatcher/bin/pbracket" :remote-source-dir nil :restart-watch-directories nil :windows nil)
 (:directory "/" :racket-program nil :remote-source-dir nil :restart-watch-directories
             ("/Users/bogdan/sandbox/racket-gui-extra/gui-extra-lib/")
             :windows nil))
</pre></dd>
<dt>racket-before-run-hook</dt><dd><pre>(racket-ansi-color-context-reset)
</pre></dd>
<dt>racket-browse-url-function</dt><dd><pre>racket-browse-url-using-temporary-file</pre></dd>
<dt>racket-command-timeout</dt><dd><pre>10</pre></dd>
<dt>racket-doc-index-directory</dt><dd><pre>"~/.emacs.d/racket-mode/"</pre></dd>
<dt>racket-doc-index-predicate-function</dt><dd><pre>always</pre></dd>
<dt>racket-documentation-search-location</dt><dd><pre>"https://docs.racket-lang.org/search/index.html?q=%s"</pre></dd>
<dt>racket-error-context</dt><dd><pre>medium</pre></dd>
<dt>racket-expand-hiding</dt><dd><pre>standard</pre></dd>
<dt>racket-hash-lang-mode-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-hash-lang-module-language-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-hash-lang-token-face-alist</dt><dd><pre>((constant . font-lock-constant-face)
 (error . error)
 (other . font-lock-doc-face)
 (keyword . font-lock-keyword-face)
 (hash-colon-keyword . racket-keyword-argument-face)
 (at . font-lock-doc-face))
</pre></dd>
<dt>racket-history-filter-regexp</dt><dd><pre>"\\`\\s *\\'"</pre></dd>
<dt>racket-imagemagick-props</dt><dd><pre>nil</pre></dd>
<dt>racket-images-do-not-use-svg</dt><dd><pre>nil</pre></dd>
<dt>racket-images-inline</dt><dd><pre>t</pre></dd>
<dt>racket-images-keep-last</dt><dd><pre>100</pre></dd>
<dt>racket-images-system-viewer</dt><dd><pre>"open"</pre></dd>
<dt>racket-indent-curly-as-sequence</dt><dd><pre>t</pre></dd>
<dt>racket-indent-sequence-depth</dt><dd><pre>0</pre></dd>
<dt>racket-input-prefix</dt><dd><pre>"\\"</pre></dd>
<dt>racket-input-translations</dt><dd><pre>(("All" "∀")
 ("Union" "U")
 ("Intersection" "∩")
 ("test-->>E" "test-->>∃")
 ("vdash" "⊢")
 ("gg" "≫")
 ("succ" "≻")
 ("times" "×")
 ("Uparrow" "⇑")
 ("Downarrow" "⇓")
 ("Leftarrow" "⇐")
 ("Rightarrow" "⇒")
 ("leftarrow" "←")
 ("rightarrow" "→")
 ("nwarrow" "↖")
 ("nearrow" "↗")
 ("uparrow" "↑")
 ("downarrow" "↓")
 ("searrow" "↘")
 ("swarrow" "↙")
 ("leftrightarrow" "↔")
 ("updownarrow" "⇕")
 ("aleph" "א")
 ("emptyset" "∅")
 ("nabla" "∇")
 ("surd" "√")
 ("negation" "¬")
 ("infinity" "∞")
 ("prod" "∏")
 ("coprod" "∐")
 ("integrate" "∫")
 ("oint" "∮")
 ("vee" "∨")
 ("wedge" "∧")
 ("follows" "∘")
 ("setin" "∈")
 ("ni" "∋")
 ("notin" "∉")
 ("sqsubset" "⊏")
 ("sqsupset" "⊐")
 ("sqsubseteq" "⊑")
 ("sqsupseteq" "⊒")
 ("subset" "⊂")
 ("superset" "⊃")
 ("subseteq" "⊆")
 ("supseteq" "⊇")
 ("approx" "≈")
 ("cong" "≌")
 ("neq" "≠")
 ("sqcap" "⊓")
 ("sqcup" "⊔")
 ("models" "⊧")
 ("alpha" "α")
 ("Alpha" "Α")
 ("beta" "β")
 ("Beta" "Β")
 ("gamma" "γ")
 ("Gamma" "Γ")
 ("delta" "δ")
 ("Delta" "Δ")
 ("epsilon" "ε")
 ("Epsilon" "Ε")
 ("zeta" "ζ")
 ("Zeta" "Ζ")
 ("eta" "η")
 ("Eta" "Η")
 ("theta" "θ")
 ("Theta" "Θ")
 ("iota" "ι")
 ("Iota" "Ι")
 ("kappa" "κ")
 ("Kappa" "Κ")
 ("lambda" "λ")
 ("Lambda" "Λ")
 ("lamda" "λ")
 ("Lamda" "Λ")
 ("mu" "μ")
 ("Mu" "Μ")
 ("nu" "ν")
 ("Nu" "Ν")
 ("xi" "ξ")
 ("Xi" "Ξ")
 ("omicron" "ο")
 ("Omicron" "Ο")
 ("pi" "π")
 ("Pi" "Π")
 ("rho" "ρ")
 ("Rho" "Ρ")
 ("sigma" "σ")
 ("Sigma" "Σ")
 ("tau" "τ")
 ("Tau" "Τ")
 ("upsilon" "υ")
 ("Upsilon" "Υ")
 ("phi" "φ")
 ("Phi" "Φ")
 ("chi" "χ")
 ("Chi" "Χ")
 ("psi" "ψ")
 ("Psi" "Ψ")
 ("omega" "ω")
 ("Omega" "Ω")
 ("digamma" "ϝ")
 ("Digamma" "Ϝ")
 ("san" "ϻ")
 ("San" "Ϻ")
 ("qoppa" "ϙ")
 ("Qoppa" "Ϙ")
 ("sampi" "ϡ")
 ("Sampi" "Ϡ")
 ("stigma" "ϛ")
 ("Stigma" "Ϛ")
 ("heta" "ͱ")
 ("Heta" "Ͱ")
 ("sho" "ϸ")
 ("Sho" "Ϸ")
 ("|A|" "𝔸")
 ("|B|" "𝔹")
 ("|C|" "ℂ")
 ("|D|" "𝔻")
 ("|E|" "𝔼")
 ("|F|" "𝔽")
 ("|G|" "𝔾")
 ("|H|" "ℍ")
 ("|I|" "𝕀")
 ("|J|" "𝕁")
 ("|K|" "𝕂")
 ("|L|" "𝕃")
 ("|M|" "𝕄")
 ("|N|" "ℕ")
 ("|O|" "𝕆")
 ("|P|" "ℙ")
 ("|Q|" "ℚ")
 ("|R|" "ℝ")
 ("|S|" "𝕊")
 ("|T|" "𝕋")
 ("|U|" "𝕌")
 ("|V|" "𝕍")
 ("|W|" "𝕎")
 ("|X|" "𝕏")
 ("|Y|" "𝕐")
 ("|Z|" "ℤ")
 ("|gamma|" "ℽ")
 ("|Gamma|" "ℾ")
 ("|pi|" "ℼ")
 ("|Pi|" "ℿ")
 ("forall" "∀")
 ("exists" "∃")
 ("_0" "₀")
 ("_1" "₁")
 ("_2" "₂")
 ("_3" "₃")
 ("_4" "₄")
 ("_5" "₅")
 ("_6" "₆")
 ("_7" "₇")
 ("_8" "₈")
 ("_9" "₉")
 ("^0" "⁰")
 ("^1" "¹")
 ("^2" "²")
 ("^3" "³")
 ("^4" "⁴")
 ("^5" "⁵")
 ("^6" "⁶")
 ("^7" "⁷")
 ("^8" "⁸")
 ("^9" "⁹"))
</pre></dd>
<dt>racket-logger-config</dt><dd><pre>((cm-accomplice . warning)
 (GC . info)
 (module-prefetch . warning)
 (optimizer . info)
 (racket/contract . error)
 (racket-mode-debugger . info)
 (sequence-specialization . info)
 (* . fatal))
</pre></dd>
<dt>racket-memory-limit</dt><dd><pre>2048</pre></dd>
<dt>racket-mode-hook</dt><dd><pre>(bp-racket-mode-hook racket-xp-mode rainbow-delimiters-mode paredit-mode)
</pre></dd>
<dt>racket-module-forms</dt><dd><pre>"\\s(\\(?:module[*+]?\\|library\\)"</pre></dd>
<dt>racket-pretty-lambda</dt><dd><pre>nil</pre></dd>
<dt>racket-pretty-print</dt><dd><pre>t</pre></dd>
<dt>racket-program</dt><dd><pre>"racket"</pre></dd>
<dt>racket-repl-buffer-name-function</dt><dd><pre>racket-repl-buffer-name-project</pre></dd>
<dt>racket-repl-command-file</dt><dd><pre>"/Users/bogdan/.emacs.d/racket-mode/repl.rkt"</pre></dd>
<dt>racket-repl-history-directory</dt><dd><pre>"~/.emacs.d/racket-mode/"</pre></dd>
<dt>racket-repl-mode-hook</dt><dd><pre>nil</pre></dd>
<dt>racket-sexp-comment-fade</dt><dd><pre>0.5</pre></dd>
<dt>racket-shell-or-terminal-function</dt><dd><pre>racket-shell</pre></dd>
<dt>racket-show-functions</dt><dd><pre>(racket-show-echo-area)
</pre></dd>
<dt>racket-smart-open-bracket-enable</dt><dd><pre>nil</pre></dd>
<dt>racket-submodules-to-run</dt><dd><pre>((test)
 (main))
</pre></dd>
<dt>racket-use-repl-submit-predicate</dt><dd><pre>nil</pre></dd>
<dt>racket-xp-add-binding-faces</dt><dd><pre>nil</pre></dd>
<dt>racket-xp-after-change-refresh-delay</dt><dd><pre>1</pre></dd>
<dt>racket-xp-eldoc-level</dt><dd><pre>summary</pre></dd>
<dt>racket-xp-highlight-unused-regexp</dt><dd><pre>"^[^_]"</pre></dd>
<dt>racket-xp-mode-lighter</dt><dd><pre>(:eval
 (racket--xp-mode-lighter))
</pre></dd>
</dl>
<h2>Minor modes</h2>
<dl>
<dt>enabled</dt><dd><pre>((auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (column-number-mode)
 (company-mode)
 (dumb-jump-mode)
 (electric-indent-mode)
 (evil-local-mode)
 (evil-mode)
 (evil-surround-mode)
 (file-name-shadow-mode)
 (flx-ido-mode)
 (flycheck-mode)
 (font-lock-mode)
 (global-auto-revert-mode)
 (global-eldoc-mode)
 (global-evil-surround-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-hl-line-mode)
 (ido-everywhere)
 (ido-ubiquitous-mode)
 (ido-vertical-mode)
 (line-number-mode)
 (mac-mouse-wheel-mode)
 (menu-bar-mode)
 (mu4e-modeline-mode)
 (override-global-mode)
 (paredit-mode)
 (projectile-mode)
 (racket-xp-mode)
 (rainbow-delimiters-mode)
 (recentf-mode)
 (save-place-mode)
 (savehist-mode)
 (semantic-minor-modes-format)
 (server-mode)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (transient-mark-mode)
 (windmove-mode))
</pre></dd>
<details><summary>Disabled minor modes</summary>
<dt>disabled</dt><dd><pre>((abbrev-mode)
 (auto-fill-function)
 (auto-fill-mode)
 (auto-image-file-mode)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-mode)
 (auto-save-visited-mode)
 (blink-cursor-mode)
 (buffer-face-mode)
 (buffer-read-only)
 (button-mode)
 (cl-old-struct-compat-mode)
 (comint-fontify-input-mode)
 (company-search-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (context-menu-mode)
 (copilot-mode)
 (cursor-face-highlight-mode)
 (cursor-intangible-mode)
 (cursor-sensor-mode)
 (dash-fontify-mode)
 (defining-kbd-macro)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (dired-isearch-filenames-mode)
 (dired-omit-mode)
 (diredp-breadcrumbs-in-header-line-mode)
 (edit-indirect--overlay)
 (editorconfig-mode)
 (eldoc-mode)
 (electric-layout-mode)
 (electric-pair-mode)
 (electric-quote-mode)
 (ert--current-run-stats)
 (eshell-arg-mode)
 (eshell-command-mode)
 (eshell-proc-mode)
 (flyspell-mode)
 (git-commit-mode)
 (global-company-mode)
 (global-copilot-mode)
 (global-dash-fontify-mode)
 (global-dired-hide-details-mode)
 (global-flycheck-mode)
 (global-prettify-symbols-mode)
 (global-reveal-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-visual-line-mode)
 (gnus-dead-summary-mode)
 (gnus-message-citation-mode)
 (gnus-undo-mode)
 (hl-line-mode)
 (horizontal-scroll-bar-mode)
 (hs-minor-mode)
 (ibuffer-auto-mode)
 (ido-cr+-debug-mode)
 (image-minor-mode)
 (indent-tabs-mode)
 (isearch-fold-quotes-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (lock-file-mode)
 (lost-selection-mode)
 (mac-auto-ascii-mode)
 (mac-auto-operator-composition-mode)
 (mac-font-panel-mode)
 (magit-auto-revert-mode)
 (magit-blame-mode)
 (magit-blame-read-only-mode)
 (magit-blob-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (magit-wip-initial-backup-mode)
 (magit-wip-mode)
 (mail-abbrevs-mode)
 (minibuffer-electric-default-mode)
 (mml-mode)
 (mouse-wheel-mode)
 (mu4e-compose-minor-mode)
 (mu4e-context-minor-mode)
 (mu4e-loading-mode)
 (mu4e-search-minor-mode)
 (mu4e-thread-mode)
 (mu4e-update-minor-mode)
 (mu4e-view-completion-minor-mode)
 (next-error-follow-minor-mode)
 (org-cdlatex-mode)
 (org-list-checkbox-radio-mode)
 (org-src-mode)
 (org-table-follow-field-mode)
 (org-table-header-line-mode)
 (orgtbl-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (prettify-symbols-mode)
 (pyvenv-mode)
 (pyvenv-tracking-mode)
 (racket-hash-lang-repl-mode)
 (racket-input-mode)
 (racket-smart-open-bracket-mode)
 (read-extended-command-mode)
 (rectangle-mark-mode)
 (reveal-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (shell-highlight-undef-mode)
 (size-indication-mode)
 (smerge-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (tooltip-mode)
 (transient-resume-mode)
 (treesit-explore-mode)
 (treesit-inspect-mode)
 (undelete-frame-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-dir-git-mode)
 (vc-parent-buffer)
 (view-mode)
 (visible-mode)
 (visual-line-mode)
 (which-function-mode)
 (window-divider-mode)
 (with-editor-mode)
 (xref-etags-mode))
</pre></dd>
</details>
</dl>
</details>

Steps to reproduce: 

```racket
(define|)
```

where `|` is the cursor. I used to be able to type an open paren immediately after an identifier and it would insert a space followed by a pair of parens, now it fails with:

```
Debugger entered--Lisp error: (void-function t)
  t(nil 40)
  funcall(t nil 40)
  (not (funcall predicate endp delimiter))
  (if (not (funcall predicate endp delimiter)) (throw 'exit nil))
  (let ((predicate (car tail))) (if (not (funcall predicate endp delimiter)) (throw 'exit nil)) (setq tail (cdr tail)))
  (while tail (let ((predicate (car tail))) (if (not (funcall predicate endp delimiter)) (throw 'exit nil)) (setq tail (cdr tail))))
  (let ((tail paredit-space-for-delimiter-predicates)) (while tail (let ((predicate (car tail))) (if (not (funcall predicate endp delimiter)) (throw 'exit nil)) (setq tail (cdr tail)))))
  (catch 'exit (let ((tail paredit-space-for-delimiter-predicates)) (while tail (let ((predicate (car tail))) (if (not (funcall predicate endp delimiter)) (throw 'exit nil)) (setq tail (cdr tail))))) t)
  (and (not (if endp (eobp) (bobp))) (memq (char-syntax (if endp (char-after) (char-before))) (list 119 95 34 (let ((matching (matching-paren delimiter))) (and matching (char-syntax matching))) (and (not endp) (eq 34 (char-syntax delimiter)) 41))) (catch 'exit (let ((tail paredit-space-for-delimiter-predicates)) (while tail (let ((predicate (car tail))) (if (not (funcall predicate endp delimiter)) (throw 'exit nil)) (setq tail (cdr tail))))) t))
  paredit-space-for-delimiter-p(nil 40)
  (let ((spacep (paredit-space-for-delimiter-p nil open))) (if spacep (insert " ")) (insert open) (save-excursion (cond (n (funcall forward (paredit-scan-sexps-hack (point) (prefix-numeric-value n)))) (regionp (funcall forward (+ end (if spacep 2 1))))) (if (and (not (paredit-in-string-p)) (paredit-in-comment-p)) (newline)) (insert close) (if (paredit-space-for-delimiter-p t close) (insert " "))))
  (let* ((regionp (and (paredit-region-active-p) (paredit-region-safe-for-insert-p))) (end (and regionp (not n) (prog1 (region-end) (goto-char (region-beginning)))))) (let ((spacep (paredit-space-for-delimiter-p nil open))) (if spacep (insert " ")) (insert open) (save-excursion (cond (n (funcall forward (paredit-scan-sexps-hack (point) (prefix-numeric-value n)))) (regionp (funcall forward (+ end (if spacep 2 1))))) (if (and (not (paredit-in-string-p)) (paredit-in-comment-p)) (newline)) (insert close) (if (paredit-space-for-delimiter-p t close) (insert " ")))))
  paredit-insert-pair(nil 40 41 goto-char)
  (cond ((or (paredit-in-string-p) (paredit-in-comment-p)) (insert 40)) ((not (paredit-in-char-p)) (paredit-insert-pair n 40 41 'goto-char) (save-excursion (backward-up-list) (indent-sexp))))
  paredit-open-round(nil)
  funcall-interactively(paredit-open-round nil)
  #<subr call-interactively>(paredit-open-round nil nil)
  apply(#<subr call-interactively> paredit-open-round (nil nil))
  (let ((ido-cr+-current-command command)) (apply orig-fun command args))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> paredit-open-round nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (paredit-open-round nil nil))
  call-interactively(paredit-open-round nil nil)
  command-execute(paredit-open-round)
```

because `paredit-space-for-delimiter-predicates` is wrong:

```
paredit-space-for-delimiter-predicates is a variable defined in ‘paredit.el’.

Its value is (racket--paredit-space-for-delimiter-predicate t)
Local in buffer test.rkt; global value is nil
```

Probably introduced in https://github.com/greghendershott/racket-mode/commit/3a9675d2e447d7d844c4a40adb91d9c59b250319 . Update: switching to `dd40f62` fixes the problem, so it was definitely that commit.

**Comment by greghendershott** [comment]
Sorry! I actually noticed this myself yesterday. But infrequently (e.g. I tend to type that space manually, so it was more limited conditions for me) and I was eyeball-deep working on something else.

**Comment by Bogdanp** [comment]
No worries! I can confirm the fix works. Thanks for the quick repair!
