### ISSUE TITLE
Navigating past oldest item in command history gets in weird state

### ISSUE THREAD

**Issue by jasonhemann** [greghendershott/racket-mode#80]
In the Racket REPL, when I `C-<up>` to the very beginning of the session, end up seeing:
≺≻ ≺≻ 

In other words, it's as if the prompt itself was part of the command history. From there, I can't `C-<down>`, or `C-<up>` back around to the most recent command executed.

My present workaround is to just press `<Ret>`, at which point it issues the obvious:

; ≺≻: undefined;
;  cannot reference undefined identifier

And gives me back the prompt. Do you see the same behavior?

**Comment by greghendershott** [comment]
Well this turned out to be simple. I pushed a fix.

**Comment by greghendershott** [comment]
Well... simple if I hadn't made a silly mistake. Pushed another commit.

**Comment by jasonhemann** [comment]
Just tried it out. Awesome. Thank you much.
