### ISSUE TITLE
racket-describe fails on Windows because Racket can't find libxml

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/racket-mode#83]
Reported via `#racket` IRC:

```
8:06 PM <cosmez> btw, if you dont have libxml installed when you ",describe" it fails. silently
8:07 PM <cosmez> so maybe add that to the readme?
8:07 PM <greghendershott> cosmez: On Linux? I didn't realize Racket xml collection depended on libxml. Interesting.
8:07 PM <cosmez> libxml2, libxml-parse-html-region
8:08 PM <cosmez> that happens on windows only.
```

**Comment by MRFaria** [comment]
You need to have built Emacs with libxml2 support, or on Windows, Emacs also supports dynamic loading of libraries, so you could install libxml2 after starting Emacs.

**Comment by greghendershott** [comment]
@MRFaria thanks for the explanation. Also, I can now confirm first-hand that `libxml2` support is present in the official GNU builds for Windows, at least as of Emacs 26.1.

As a result, I'm going to (finally!) close this issue.
