### ISSUE TITLE
feature request: C-a (move-beginning-of-line) should jump to just after prompt

### ISSUE THREAD

**Issue by rntz** [greghendershott/racket-mode#87]
Currently, C-a in a Racket-REPL buffer will jump to the beginning of the line, which is to say, before the "≺≻" prompt. It'd be handy if it jumped just after the prompt, to the beginning of the logical line of code being entered. This is what it does in most repl modes, in shell modes, etc.

**Comment by greghendershott** [comment]
Thank you for taking the time to file an issue about this!  It was bothering me, but I'd had bigger fish to fry, and then I got desensitized to how it works and forgot. So your report was a helpful nudge. I pushed a commit to fix this.
