### ISSUE TITLE
with newly upgraded racket mode, emacs warns about faceup-0.0.2, s-1.9.0

### ISSUE THREAD

**Issue by jasonhemann** [greghendershott/racket-mode#88]
Updated to newest version of racket-mode automatically via auto-package-update. After updating, emacs warns:

Warning (emacs): Unable to activate package `racket-mode'.
Required package `faceup-0.0.2' is unavailable

installing faceup manually then prompted the message: 

Warning (emacs): Unable to activate package `racket-mode'.
Required package `s-1.9.0' is unavailable
Warning (emacs): Unable to activate package `racket-mode'.
Required package `s-1.9.0' is unavailable
Warning (emacs): Unable to activate package `racket-mode'.
Required package `s-1.9.0' is unavailable

after which everything works fine. It would be nice if these dependencies were automatically handled, if that's possible.

**Comment by greghendershott** [comment]
Dang. I thought I'd set that up correctly with [`Package-Requires` in racket-mode.el](https://github.com/greghendershott/racket-mode/blob/master/racket-mode.el#L6).

Sorry about that. Thank you very much for the report.

**Comment by greghendershott** [comment]
Oh wait. It does show the packages requirements in the <kbd>M-x list-packages</kbd> detail for the package. And the error messages you get are about a missing required package (as opposed to an error about function undefined). So it seems Emacs knows it needs those exact packages... it just didn't install them. Huh.

> Updated to newest version of racket-mode automatically via auto-package-update.

Just to confirm what you mean by "auto-package-update":

1. You <kbd>M-x list-packages</kbd> and are in the `*Packages*` buffer.
2. You press <kbd>U</kbd> which runs `package-menu-mark-upgrades`. This marks various things with `D` or `I` (delete or install).
3. Then you press <kbd>X</kbd>.

Correct?

**Comment by greghendershott** [comment]
I can't seem to reproduce this. In a VM I had with an older version of racket-mode installed from MELPA, I went through the steps I listed above. I did not get the error messages you reported, either during the upgrade, or after I opened a .rkt file and tried a few basic things.

Can you let me know about the update process you used?

**Comment by jasonhemann** [comment]
I'm using the package 'auto-package-update' to automatically download and install package updates when emacs starts up. It's possible the fault likes with auto-package-update, and not racket-mode. Automatic updates have worked in the past, but these dependencies are new, yes?

Below is the version information on my installed copy of racket-mode.

racket-mode is an installed package.

     Status: Installed in `~/.emacs.d/elpa/racket-mode-20150208.1720/' (unsigned).
    Archive: n/a
    Version: 20150208.1720
   Requires: emacs-24.3, dash-2.10.0, faceup-0.0.2, s-1.9.0
    Summary: Major mode for Racket language.
   Homepage: https://github.com/greghendershott/racket-mode
    Other versions: 20150125.2029 (installed), 20150208.1720 (melpa).

Goals:
- Focus on Racket (not various Schemes).
- Fontify all Racket keywords, builtins, and so on.
- Fontify variations of define for functions and variables.
- Indent Racket forms (even `for/fold` and `for*/fold`).
- Follow DrRacket concepts where applicable.
- Compatible with Emacs 24.3+.

Details: https://github.com/greghendershott/racket-mode

**Comment by greghendershott** [comment]
@jasonhemann Ah OK. I just [asked over there](https://github.com/rranelli/auto-package-update.el/issues/14).

**Comment by rranelli** [comment]
Hi! I'm the author of `auto-package-update`.

@jasonhemann  I never had such problem.

How is your package archives configured? (i.e., whats the value of the `package-archives` variable)

Have you tried to run `package-refresh-contents` before `auto-package-update-now` ? It actually shouldn't make a difference, but who knows.

**Comment by rranelli** [comment]
I also was able to install `racket-mode` with no problems whatsoever. I have installed it from Melpa.

**Comment by jasonhemann** [comment]
Currently, it's set to:

(("gnu" . "http://elpa.gnu.org/packages/")
 ("marmalade" . "https://marmalade-repo.org/packages/")
 ("melpa" . "http://melpa.milkbox.net/packages/"))

@rranelli I haven't. I resolved it by manually installing those dependencies, and then upgrading the package. If I manage to reconstruct the problem, I'll give that a shot.

I can't imagine it mattering, but I'm using the emacs-mac port of emacs 24.4, installed via homebrew.

**Comment by rranelli** [comment]
Your Emacs version probably does not matter.

Maybe that has something to do with you using multiple package archives. The only archive I use in my setup is `melpa`.

If you ever encounter the problem again please let me know =)

**Comment by greghendershott** [comment]
@rranelli A (belated) thank-you for stopping by to help!

@jasonhemann Thank you for reporting this! At this point I don't think there's anything actionable, so I'm going to close it. However please do reopen it if you have this problem again.

**Comment by rranelli** [comment]
I'm happy to help, thanks =)
