### ISSUE TITLE
C-c C-d racket-doc doesn't work for all #langs

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/racket-mode#89]
Reported by @rntz on `#racket`.

For example:

```
#lang r5rs

(define x 0)
```

With point on `define`, <kbd>C-c C-d</kbd> does nothing.

The root cause is that `local-require` isn't available in r5rs, so racket-mode's `(local-require racket/help)` fails.

Using primitive `#%require` would fix this.

However a more basic issue is that, with any require, the program's namespace is getting polluted with `racket/help`.

**Comment by rntz** [comment]
:+1:
