### ISSUE TITLE
check-syntax screws with interactive search

### ISSUE THREAD

**Issue by zenspider** [greghendershott/racket-mode#97]
This one is hard to describe, but I just isolated it.

1. In a new emacs, open a racket file.
2. `C-s` to search for something that hits multiple times, eg "check-"
3. `C-s` multiple times to jump across matches. (I'm set up to highlight all matches).
4. At this point, things work normal. The current match is highlighted, the cursor is right after it, etc.
5. Run your new check-syntax feature, and quit out of it immediately.
6. Repeat at step 2. Successive `C-s`es _unhighlight_ immediately after going to the match, other matches aren't highlighted, etc.

I can probably make you a video if you want.

**Comment by greghendershott** [comment]
I can repro this. Bizarre. Either my overlays are messing it up. Or minor-mode, I'm doing wrong.

I'm actually really curious to dig in and learn what's going on with this. Thanks for the report!

**Comment by greghendershott** [comment]
p.s. Thank you for the really excellent, detailed report -- very helpful!
